force-app/main/default/objects/Promo__c/Promo__c.object-meta.xml
<CustomObject>
    <label>Promo</label>
    <nameField>
        <label>Nom</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Promos</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/PromoRemise__c/PromoRemise__c.object-meta.xml
<CustomObject>
    <label>Remise de promo</label>
    <nameField>
        <displayFormat>rem-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Remises de promo</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PromoRemise__c/fields/Promo__c.field-meta.xml
<CustomField>
    <fullName>Promo__c</fullName>
    <label>Promo</label>
    <referenceTo>Promo__c</referenceTo>
    <relationshipLabel>Remises de promo</relationshipLabel>
    <relationshipName>PromoRemises</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/SM_PromoRemise.cls
/**
 * Created by mouad on 02/02/2019.
 */

public with sharing class SM_PromoRemise {

    public static void Trig_PromoRemiseBeforeInsert(List<PromoRemise__c> promoRemises)
    {

/*            for (PromoRemise__c promoRemise : promoRemises) {

                String promoRT = [SELECT RecordType.Name FROM Promo__c WHERE Id = :promoRemise.Promo__c LIMIT 1].RecordType.Name;
                //System.debug('MBEN: Trig_PromoRemiseBeforeInsert11: ' + promoRT);
                System.debug('MBEN: Trig_PromoRemiseBeforeInsert12: ' + promoRemise.Promo__r.Id);
                System.debug('MBEN: Trig_PromoRemiseBeforeInsert13: ' + promoRemise.Promo__c);
                promoRemise.RecordTypeId = [SELECT Id FROM RecordType WHERE SobjectType='PromoRemise__c' AND Name = :promoRT LIMIT 1].Id;

                System.debug('MBEN: Trig_PromoRemiseBeforeInsert2');
            }*/


    }

}