force-app/main/default/objects/Case/fields/CommentairesInternes__c.field-meta.xml
<CustomField>
    <fullName>CommentairesInternes__c</fullName>
    <label>Commentaires internes (200 caracts max)</label>
    <length>33000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/Date_de_creation__c.field-meta.xml
<CustomField>
    <fullName>Date_de_creation__c</fullName>
    <defaultValue>now()</defaultValue>
    <label>Date de création</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case/fields/Famille__c.field-meta.xml
<CustomField>
    <fullName>Famille__c</fullName>
    <label>Famille</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0- Souscription</fullName>
            </value>
            <value>
                <fullName>1- Vie de l&#39;abonnement</fullName>
            </value>
            <value>
                <fullName>2- Club UGC / fidelite</fullName>
            </value>
            <value>
                <fullName>3- Autres Produits</fullName>
            </value>
            <value>
                <fullName>4- Reservation</fullName>
                <label>4- Réservation</label>
            </value>
            <value>
                <fullName>5- Compte client</fullName>
            </value>
            <value>
                <fullName>6- Prospection</fullName>
            </value>
            <value>
                <fullName>7- Finance</fullName>
            </value>
            <value>
                <fullName>8- Cinema</fullName>
                <label>8- Cinéma</label>
            </value>
            <value>
                <fullName>9- Divers</fullName>
            </value>
            <value>
                <fullName>0- Commentaires</fullName>
                <isActive>false</isActive>
                <label>0- Commentaires</label>
            </value>
            <value>
                <fullName>1- Demandes d info UI</fullName>
                <isActive>false</isActive>
                <label>1- Demandes d info UI</label>
            </value>
            <value>
                <fullName>1- Demandes d&#39;info UI</fullName>
                <isActive>false</isActive>
                <label>1- Demandes d&#39;info UI</label>
            </value>
            <value>
                <fullName>2- Demande d infos generales</fullName>
                <isActive>false</isActive>
                <label>2- Demande d infos generales</label>
            </value>
            <value>
                <fullName>2- Demande d&#39;infos générales</fullName>
                <isActive>false</isActive>
                <label>2- Demande d&#39;infos générales</label>
            </value>
            <value>
                <fullName>3- Autres demandes d&#39;informations</fullName>
                <isActive>false</isActive>
                <label>3- Autres demandes d&#39;informations</label>
            </value>
            <value>
                <fullName>4- Abonnement Carte UGC</fullName>
                <isActive>false</isActive>
                <label>4- Abonnement Carte UGC</label>
            </value>
            <value>
                <fullName>5- Abonnement en attente</fullName>
                <isActive>false</isActive>
                <label>5- Abonnement en attente</label>
            </value>
            <value>
                <fullName>6- GestionCompteUI</fullName>
                <isActive>false</isActive>
                <label>6- GestionCompteUI</label>
            </value>
            <value>
                <fullName>7- Réclamations UI</fullName>
                <isActive>false</isActive>
                <label>7- Réclamations UI</label>
            </value>
            <value>
                <fullName>8- Autres types de reclamations</fullName>
                <isActive>false</isActive>
                <label>8- Autres types de reclamations</label>
            </value>
            <value>
                <fullName>8- Autres types de réclamations</fullName>
                <isActive>false</isActive>
                <label>8- Autres types de réclamations</label>
            </value>
            <value>
                <fullName>9- Supports Digitaux</fullName>
                <isActive>false</isActive>
                <label>9- Supports Digitaux</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Motif__c.field-meta.xml
<CustomField>
    <fullName>Motif__c</fullName>
    <label>Motif</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Famille__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>01- Info process abo</fullName>
            </value>
            <value>
                <fullName>02- Erreur prise abo</fullName>
            </value>
            <value>
                <fullName>03- Click and collect</fullName>
            </value>
            <value>
                <fullName>05- B2B</fullName>
            </value>
            <value>
                <fullName>06- VPC</fullName>
            </value>
            <value>
                <fullName>07- Creation Abonnement</fullName>
            </value>
            <value>
                <fullName>01- Reception carte</fullName>
                <label>01- Réception carte</label>
            </value>
            <value>
                <fullName>02- Reedition payante</fullName>
            </value>
            <value>
                <fullName>03- Reedition gratuite</fullName>
            </value>
            <value>
                <fullName>04- Desabonnement</fullName>
            </value>
            <value>
                <fullName>05- Resiliation</fullName>
            </value>
            <value>
                <fullName>06- Migration UI 1/2/3</fullName>
            </value>
            <value>
                <fullName>07- Reabonnement</fullName>
            </value>
            <value>
                <fullName>08- Retention</fullName>
            </value>
            <value>
                <fullName>09- Retour Carte</fullName>
            </value>
            <value>
                <fullName>10- Retractation</fullName>
            </value>
            <value>
                <fullName>11- Avertissement</fullName>
            </value>
            <value>
                <fullName>12- Annulation Migration</fullName>
            </value>
            <value>
                <fullName>13- Annulation Contrat</fullName>
            </value>
            <value>
                <fullName>04- Dematerialise</fullName>
                <label>04- Dématérialisé</label>
            </value>
            <value>
                <fullName>01- Inscription</fullName>
            </value>
            <value>
                <fullName>02- Solde de points</fullName>
            </value>
            <value>
                <fullName>03- Echange de points</fullName>
            </value>
            <value>
                <fullName>04- Fonctionnement Club</fullName>
            </value>
            <value>
                <fullName>01- Offres UGC</fullName>
            </value>
            <value>
                <fullName>02- Formules UGC+</fullName>
            </value>
            <value>
                <fullName>03- Solo</fullName>
            </value>
            <value>
                <fullName>04- Blue</fullName>
            </value>
            <value>
                <fullName>05- VLO</fullName>
            </value>
            <value>
                <fullName>01- Modalites de reservation</fullName>
                <label>01- Modalités de réservation</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/ProvenanceDemande__c.field-meta.xml
<CustomField>
    <fullName>ProvenanceDemande__c</fullName>
    <formula>IF(ISPICKVAL(Origin,&quot;E-mail entrant&quot;),IMAGE(&quot;/resource/1227196930000/EmailEntrant?isdtp=p1&quot;,&quot;.png&quot;,22,22),
IF(ISPICKVAL(Origin,&quot;E-mail sortant&quot;),IMAGE(&quot;/resource/1227196930000/EmailEntrant?isdtp=p1&quot;,&quot;.png&quot;,22,22),
IF(ISPICKVAL(Origin,&quot;Téléphone entrant&quot;),IMAGE(&quot;/resource/1227196861000/Appelentrant?isdtp=p1&quot;,&quot;.png&quot;,22,22),
IF(ISPICKVAL(Origin,&quot;Telephone sortant&quot;),IMAGE(&quot;/resource/1227196861000/Appelentrant?isdtp=p1&quot;,&quot;.png&quot;,22,22),
IF(ISPICKVAL(Origin,&quot;Formulairedecontact&quot;),IMAGE(&quot;/resource/1227196220000/FormulaireContact?isdtp=p1&quot;,&quot;.png&quot;,22,22),
IF(ISPICKVAL(Origin,&quot;Courrier entrant&quot;),IMAGE(&quot;/resource/1227642306000/CourrierEntrant?isdtp=p1&quot;,&quot;.png&quot;,22,22),
IF(ISPICKVAL(Origin,&quot;Courrier sortant&quot;),IMAGE(&quot;/resource/1227642306000/CourrierEntrant?isdtp=p1&quot;,&quot;.png&quot;,22,22),
IF(ISPICKVAL(Origin,&quot;Salle&quot;),IMAGE(&quot;/resource/1227197419000/Iconesalle?isdtp=p1&quot;,&quot;.png&quot;,22,22),
IF(ISPICKVAL(Origin,&quot;Interne&quot;),IMAGE(&quot;/resource/1227198181000/IconeInterne?isdtp=p1&quot;,&quot;.png&quot;,22,22),
IF(ISPICKVAL(Origin,&quot;Facebook&quot;),IMAGE(&quot;/resource/1227197302200/FacebookEntrant?isdtp=p1&quot;,&quot;.png&quot;,22,22),
IF(ISPICKVAL(Origin,&quot;Twitter&quot;),IMAGE(&quot;/resource/1227197343000/TwitterEntrant?isdtp=p1&quot;,&quot;.png&quot;,22,22),
IF(ISPICKVAL(Origin,&quot;Critizr&quot;),IMAGE(&quot;/resource/1227197837000/CritizrEntrant?isdtp=p1&quot;,&quot;.png&quot;,22,22),
&quot;&quot;))))))))))))
&amp; &quot; &quot; &amp; 
IF(ISPICKVAL(Status,&quot;Fermee&quot;),IMAGE(&quot;/resource/1511537369000/Cadenasferme&quot;,&quot;.png&quot;,22,22),
IF(ISPICKVAL(Status,&quot;Fermée&quot;),IMAGE(&quot;/resource/1511537369000/Cadenasferme&quot;,&quot;.png&quot;,22,22),
IF(ISPICKVAL(Status,&quot;EnCours&quot;),IMAGE(&quot;/resource/1512578078000/Cadenasouvert2&quot;,&quot;.png&quot;,22,22),
IF(ISPICKVAL(Status,&quot;En Cours&quot;),IMAGE(&quot;/resource/1512578078000/Cadenasouvert2&quot;,&quot;.png&quot;,22,22),
IF(ISPICKVAL( Status ,&quot;EnAttenteRetourClient&quot;),IMAGE(&quot;/resource/1512578078000/Cadenasouvert2&quot;,&quot;.png&quot;,22,22),
IF(ISPICKVAL( Status ,&quot;EnAttenteRemboursement&quot;),IMAGE(&quot;/resource/1512578078000/Cadenasouvert2&quot;,&quot;.png&quot;,22,22),
IF(ISPICKVAL( Status ,&quot;EnAttenteRetourSalle&quot;),IMAGE(&quot;//resource/1512578078000/Cadenasouvert2&quot;,&quot;.png&quot;,22,22),
IF(ISPICKVAL( Status ,&quot;En attente retour interne&quot;),IMAGE(&quot;/resource/1512578078000/Cadenasouvert2&quot;,&quot;.png&quot;,22,22),
&quot;&quot;))))))))</formula>
    <label>.</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/SousMotif__c.field-meta.xml
<CustomField>
    <fullName>SousMotif__c</fullName>
    <label>Sous-motif</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Motif__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>I- Info</fullName>
            </value>
            <value>
                <fullName>R- Récla</fullName>
            </value>
            <value>
                <fullName>A- Action</fullName>
            </value>
            <value>
                <fullName>Click to Call Info</fullName>
            </value>
            <value>
                <fullName>Click to Call Recla</fullName>
            </value>
            <value>
                <fullName>AD- Action DRC</fullName>
            </value>
            <value>
                <fullName>AS- Action Stand</fullName>
            </value>
            <value>
                <fullName>AH- Action Selfcare</fullName>
            </value>
            <value>
                <fullName>R1- 1er rejet</fullName>
            </value>
            <value>
                <fullName>R2- 2nd rejet</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DisplayCases_CC.cls
public with sharing class DisplayCases_CC {
    
    @AuraEnabled
    public static CasePageWrapper getCases(Id accountId, Decimal pageNumber, Integer recordToDisplay, 
    	String sortField, Boolean isAsc, String searchField, String keyword) 
    {        
    	Id recordId = Id.valueOf(accountId); 
    	
        if(recordId.getSObjectType() == Schema.Case.SObjectType) {
        	Case cse = [SELECT accountId FROM Case WHERE id = :recordId];
        	recordId = cse.accountId;
        }
        
        Integer pageSize = recordToDisplay;
        Integer offset = ((Integer)pageNumber - 1) * pageSize;
        
        
        // create a instance of wrapper class.
        CasePageWrapper caseWrap =  new CasePageWrapper();  
        caseWrap.pageSize = pageSize;
        caseWrap.page = (Integer) pageNumber;
        
        String selectClause = 'SELECT Id, CaseNumber, Owner.Name, Date_de_creation__c , Famille__c, Motif__c, SousMotif__c, tolabel(Origin), CommentairesInternes__c, Status, ProvenanceDemande__c';
        
        String fromWhereClause = ' From Case where AccountId = :recordId';
        
        Date date1 = null;
        Date date2 = null;
        
        if(!String.isBlank(searchField)  &&  !String.isBlank(keyword) ) {
        	if(searchField == 'Date_de_creation__c') {
        		try {
	        		date1 = Date.valueOf(keyword);
	        		date2 = date1.addDays(1);
	        		fromWhereClause += ' AND Date_de_creation__c >= :date1 AND Date_de_creation__c < :date2 ';
        		} catch(System.TypeException e) {
        			
        		}
        	} else {
        		keyword = '%' + keyword + '%';
            	fromWhereClause += ' AND ' + searchField + ' like :keyword ';
        	}
        }
          
        String orderClause = ' order by ' + sortField;
        
        if (isAsc) { 
            orderClause += ' asc';
        } else {
            orderClause += ' desc';
        }
        
        orderClause += ' LIMIT :recordToDisplay OFFSET :offset';  
        
        String soql = selectClause + fromWhereClause + orderClause;   
        system.debug('## DisplayCases_CC ## query: ' + soql);   
        caseWrap.cases = Database.query(soql);      
            
        caseWrap.total = Database.countQuery('SELECT count() ' + fromWhereClause);
        caseWrap.numberPages = new List<Integer>();
        
        Integer totalPage = (Integer)Math.ceil((Double)caseWrap.total/(Double)caseWrap.pageSize);
        for(Integer i = 0;i<totalPage;i++){
            caseWrap.numberPages.add(i+1);          
        }
        // return the wrapper class instance .
        return caseWrap;
    }
    
    // create a wrapper class with @AuraEnabled Properties    
    public class CasePageWrapper {
        @AuraEnabled public Integer pageSize {get;set;}
        @AuraEnabled public Integer page {get;set;}
        @AuraEnabled public Integer total {get;set;}
        @AuraEnabled public List<Integer> numberPages {get;set;}
        @AuraEnabled public List<Case> cases {get;set;}
    }
    
    
    @AuraEnabled
    public static Map<string,string> getCaseFieldsIdLabels() {
        
        Map<string,string> retVal = new Map<string,string>();
        List<String> apiNames = new List<String>();
        apiNames.add('CaseNumber');
        apiNames.add('Origin');
        apiNames.add('Date_de_creation__c');
        apiNames.add('Famille__c');
        apiNames.add('Motif__c');
        apiNames.add('SousMotif__c');
        // apiNames.add('CommentairesInternes__c');
        Map<String, Schema.SObjectType> GlobalMap = Schema.getGlobalDescribe();
        Schema.DescribeSObjectResult obj = GlobalMap.get('Case').getDescribe();
        for(String s : apiNames){
            Schema.SObjectField field = obj.Fields.getMap().get(s);
            Schema.DescribeFieldResult describeFieldResult = field.getDescribe();
            String fieldLabel = describeFieldResult.getLabel();
            
            retVal.put(s, fieldLabel);
            
        }
        
        return retVal;
        
    }
    
    @AuraEnabled
    public static List<Task> getActivities(String caseId) {
        List<Task> activities = [SELECT Id, Type, TECH_Type__c, Subject, WhoId, Who.Name, ActivityDate, Description,
                              Commentaire__c, WhatId, What.Name, OwnerId, Owner.Name, IconeCanalOrigine__c,
                              (Select Name, Id from Attachments) FROM Task 
                              WHERE WhatId = :caseId AND origine__c != null
                              ORDER BY CreatedDate, ActivityDate];
        return activities;
    }
    
    
    @AuraEnabled
    public static Map<String, String> getOriginLabels(){
        Map<String, String> retval = new Map<String, String>();
        Schema.DescribeFieldResult fieldResult = Case.Origin.getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        for (Schema.PicklistEntry f: ple) {
        	retVal.put(f.getValue(), f.getLabel());
        }
        return retval;
    }
    
    @AuraEnabled
    public static String getCommentairesInternesLabel() {
        Map<String, Schema.SObjectType> GlobalMap = Schema.getGlobalDescribe();
        Schema.DescribeSObjectResult obj = GlobalMap.get('Case').getDescribe();
        Schema.SObjectField field = obj.Fields.getMap().get('CommentairesInternes__c');
        Schema.DescribeFieldResult describeFieldResult = field.getDescribe();
        return  describeFieldResult.getLabel();
    }
    
    public class IdsDto {
    	@AuraEnabled
    	public String accountId { get; set; }
    	
    	@AuraEnabled
    	public String contactId { get; set; }
    	 
    }
    
    @AuraEnabled
    public static IdsDto getContactIds(Id recordId) {
    	if(recordId.getSObjectType() == Schema.Case.SObjectType) {
        	Case cse = [SELECT accountId FROM Case WHERE id = :recordId];
        	recordId = cse.accountId;
        }
        
        Contact contact = [SELECT id FROM Contact WHERE accountId = :recordId];
        
        IdsDto res = new IdsDto();
        res.accountId = recordId;
        res.contactId = contact.Id;
        
        return res;
        
    }
}