force-app/main/default/objects/Case/fields/CommentairesInternes__c.field-meta.xml
<CustomField>
    <fullName>CommentairesInternes__c</fullName>
    <label>Commentaires internes (200 caracts max)</label>
    <length>33000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/Famille__c.field-meta.xml
<CustomField>
    <fullName>Famille__c</fullName>
    <label>Famille</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0- Souscription</fullName>
            </value>
            <value>
                <fullName>1- Vie de l&#39;abonnement</fullName>
            </value>
            <value>
                <fullName>2- Club UGC / fidelite</fullName>
            </value>
            <value>
                <fullName>3- Autres Produits</fullName>
            </value>
            <value>
                <fullName>4- Reservation</fullName>
                <label>4- Réservation</label>
            </value>
            <value>
                <fullName>5- Compte client</fullName>
            </value>
            <value>
                <fullName>6- Prospection</fullName>
            </value>
            <value>
                <fullName>7- Finance</fullName>
            </value>
            <value>
                <fullName>8- Cinema</fullName>
                <label>8- Cinéma</label>
            </value>
            <value>
                <fullName>9- Divers</fullName>
            </value>
            <value>
                <fullName>0- Commentaires</fullName>
                <isActive>false</isActive>
                <label>0- Commentaires</label>
            </value>
            <value>
                <fullName>1- Demandes d info UI</fullName>
                <isActive>false</isActive>
                <label>1- Demandes d info UI</label>
            </value>
            <value>
                <fullName>1- Demandes d&#39;info UI</fullName>
                <isActive>false</isActive>
                <label>1- Demandes d&#39;info UI</label>
            </value>
            <value>
                <fullName>2- Demande d infos generales</fullName>
                <isActive>false</isActive>
                <label>2- Demande d infos generales</label>
            </value>
            <value>
                <fullName>2- Demande d&#39;infos générales</fullName>
                <isActive>false</isActive>
                <label>2- Demande d&#39;infos générales</label>
            </value>
            <value>
                <fullName>3- Autres demandes d&#39;informations</fullName>
                <isActive>false</isActive>
                <label>3- Autres demandes d&#39;informations</label>
            </value>
            <value>
                <fullName>4- Abonnement Carte UGC</fullName>
                <isActive>false</isActive>
                <label>4- Abonnement Carte UGC</label>
            </value>
            <value>
                <fullName>5- Abonnement en attente</fullName>
                <isActive>false</isActive>
                <label>5- Abonnement en attente</label>
            </value>
            <value>
                <fullName>6- GestionCompteUI</fullName>
                <isActive>false</isActive>
                <label>6- GestionCompteUI</label>
            </value>
            <value>
                <fullName>7- Réclamations UI</fullName>
                <isActive>false</isActive>
                <label>7- Réclamations UI</label>
            </value>
            <value>
                <fullName>8- Autres types de reclamations</fullName>
                <isActive>false</isActive>
                <label>8- Autres types de reclamations</label>
            </value>
            <value>
                <fullName>8- Autres types de réclamations</fullName>
                <isActive>false</isActive>
                <label>8- Autres types de réclamations</label>
            </value>
            <value>
                <fullName>9- Supports Digitaux</fullName>
                <isActive>false</isActive>
                <label>9- Supports Digitaux</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Motif__c.field-meta.xml
<CustomField>
    <fullName>Motif__c</fullName>
    <label>Motif</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Famille__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>01- Info process abo</fullName>
            </value>
            <value>
                <fullName>02- Erreur prise abo</fullName>
            </value>
            <value>
                <fullName>03- Click and collect</fullName>
            </value>
            <value>
                <fullName>05- B2B</fullName>
            </value>
            <value>
                <fullName>06- VPC</fullName>
            </value>
            <value>
                <fullName>07- Creation Abonnement</fullName>
            </value>
            <value>
                <fullName>01- Reception carte</fullName>
                <label>01- Réception carte</label>
            </value>
            <value>
                <fullName>02- Reedition payante</fullName>
            </value>
            <value>
                <fullName>03- Reedition gratuite</fullName>
            </value>
            <value>
                <fullName>04- Desabonnement</fullName>
            </value>
            <value>
                <fullName>05- Resiliation</fullName>
            </value>
            <value>
                <fullName>06- Migration UI 1/2/3</fullName>
            </value>
            <value>
                <fullName>07- Reabonnement</fullName>
            </value>
            <value>
                <fullName>08- Retention</fullName>
            </value>
            <value>
                <fullName>09- Retour Carte</fullName>
            </value>
            <value>
                <fullName>10- Retractation</fullName>
            </value>
            <value>
                <fullName>11- Avertissement</fullName>
            </value>
            <value>
                <fullName>12- Annulation Migration</fullName>
            </value>
            <value>
                <fullName>13- Annulation Contrat</fullName>
            </value>
            <value>
                <fullName>04- Dematerialise</fullName>
                <label>04- Dématérialisé</label>
            </value>
            <value>
                <fullName>01- Inscription</fullName>
            </value>
            <value>
                <fullName>02- Solde de points</fullName>
            </value>
            <value>
                <fullName>03- Echange de points</fullName>
            </value>
            <value>
                <fullName>04- Fonctionnement Club</fullName>
            </value>
            <value>
                <fullName>01- Offres UGC</fullName>
            </value>
            <value>
                <fullName>02- Formules UGC+</fullName>
            </value>
            <value>
                <fullName>03- Solo</fullName>
            </value>
            <value>
                <fullName>04- Blue</fullName>
            </value>
            <value>
                <fullName>05- VLO</fullName>
            </value>
            <value>
                <fullName>01- Modalites de reservation</fullName>
                <label>01- Modalités de réservation</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/SousMotif__c.field-meta.xml
<CustomField>
    <fullName>SousMotif__c</fullName>
    <label>Sous-motif</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Motif__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>I- Info</fullName>
            </value>
            <value>
                <fullName>R- Récla</fullName>
            </value>
            <value>
                <fullName>A- Action</fullName>
            </value>
            <value>
                <fullName>Click to Call Info</fullName>
            </value>
            <value>
                <fullName>Click to Call Recla</fullName>
            </value>
            <value>
                <fullName>AD- Action DRC</fullName>
            </value>
            <value>
                <fullName>AS- Action Stand</fullName>
            </value>
            <value>
                <fullName>AH- Action Selfcare</fullName>
            </value>
            <value>
                <fullName>R1- 1er rejet</fullName>
            </value>
            <value>
                <fullName>R2- 2nd rejet</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Zuora__ZInvoice__c/Zuora__ZInvoice__c.object-meta.xml
<CustomObject>
    <description>Zuora Invoice object. Invoices are bills that you send to customers.</description>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Zuora__ZInvoice__c/fields/Tech_CodeRejet__c.field-meta.xml
<CustomField>
    <fullName>Tech_CodeRejet__c</fullName>
    <label>Tech_CodeRejet</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Zuora__ZInvoice__c/fields/Tech_DateRejet__c.field-meta.xml
<CustomField>
    <fullName>Tech_DateRejet__c</fullName>
    <label>Tech_DateRejet</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Zuora__ZInvoice__c/fields/Tech_FlagRejetPaye__c.field-meta.xml
<CustomField>
    <fullName>Tech_FlagRejetPaye__c</fullName>
    <label>Tech_FlagRejetPaye</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Zuora__ZInvoice__c/fields/Tech_TypeRejet__c.field-meta.xml
<CustomField>
    <fullName>Tech_TypeRejet__c</fullName>
    <label>Tech_TypeRejet</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SM_Invoice.cls
/**
 * Created by mouad on 02/12/2018.
 */

public with sharing class SM_Invoice {

    //public static String zEntityId = '8adce421-63ec-c07b-0163-f45782667179'; // France

    /*public static WSZ.InvoiceItemsOut getInvoiceItems(String invoiceId) {
        //String endpoint = 'https://rest.sandbox.eu.zuora.com/v1/creditmemos/' + memoId;
        String endpoint = '/v1/invoices/'+ invoiceId +'/items';
        String method = 'GET';
        String wsIn = null;
        String wsOut = '';

        // Retrieve Zuora token
        String accessToken = WS001_CallZuora.access_token;

        wsOut = WS001_CallZuora.sendRequest(accessToken, endpoint, zEntityId, method, wsIn, 'type1', null);
        //wsOut = wsOut.replace('number','numberx');
        //wsOut = wsOut.replace('currency', 'currencyx');
        return (WSZ.InvoiceItemsOut) JSON.deserializeStrict(wsOut, WSZ.InvoiceItemsOut.class);
    }*/
    
    public static void processTriggerAfter (Map<Id, Zuora__ZInvoice__c> mapOldInvoices, List<Zuora__ZInvoice__c> listNewInvoices)  { 
    	if(mapOldInvoices == null){
    		processTriggerAfterInsert(listNewInvoices);
    	}else {
    		processTriggerAfterUpdate (mapOldInvoices, listNewInvoices);
    	}
    	
    }
    
    public static void processTriggerAfterInsert (List<Zuora__ZInvoice__c> listInvoices)  { 
    	system.debug ('##MNE SM_Invoice processTriggerAfterInsert listInvoices >> ' + listInvoices); 
    	map<Id, Zuora__ZInvoice__c> mapInvoiceByIdToCreateCase = new map<Id, Zuora__ZInvoice__c>();
    	set<Id> setAccountIdToDeactivateCard = new set<Id>();
    	set<Id> setAccountIdToReactivateCard = new set<Id>();
    	
    	for(Zuora__ZInvoice__c inv : listInvoices){
    		if(inv.Tech_FlagRejetPaye__c == 'true'){
    			//activer carte
    			if(inv.Zuora__Account__c != null){
    				setAccountIdToReactivateCard.add(inv.Zuora__Account__c);
    			}
    		}
    		else if(inv.Tech_FlagRejetPaye__c == 'false' && (inv.Tech_TypeRejet__c == 'Rejet_1' || inv.Tech_TypeRejet__c == 'Rejet_2')){
    			mapInvoiceByIdToCreateCase.put(inv.Id, inv);
    			if(inv.Zuora__Account__c != null){
    				setAccountIdToDeactivateCard.add(inv.Zuora__Account__c);
    			}
    		}
    	}
    	
    	list<Case> listRejetCaseCreated;
    	if(mapInvoiceByIdToCreateCase.size() > 0){
    		listRejetCaseCreated = createRejetCase(mapInvoiceByIdToCreateCase);
    	}
    	
    	if(setAccountIdToDeactivateCard.size() > 0){
    		system.debug ('##MNE SM_Invoice processTriggerAfterInsert callout Asynchrone methode desactivation card'); 
    		SM_Carte.desactivationByListAsynchrone(setAccountIdToDeactivateCard, 'X');
    	}
    	
    	if(setAccountIdToReactivateCard.size() > 0){
    		system.debug ('##MNE SM_Invoice processTriggerAfterInsert callout Asynchrone methode resactivation card'); 
    		SM_Carte.activationByListAsynchrone(setAccountIdToReactivateCard);
    	}
    	
    	system.debug ('##MNE SM_Invoice processTriggerAfterInsert END'); 
    }
    
	public static void processTriggerAfterUpdate (Map<Id, Zuora__ZInvoice__c> mapOldInvoices, List<Zuora__ZInvoice__c> listNewInvoices)  {   
		system.debug ('##MNE SM_Invoice processTriggerAfterUpdate mapOldInvoices >> ' + mapOldInvoices); 
		system.debug ('##MNE SM_Invoice processTriggerAfterUpdate listNewInvoices >> ' + listNewInvoices); 
		map<Id, Zuora__ZInvoice__c> mapInvoiceByIdToCreateCase = new map<Id, Zuora__ZInvoice__c>();
    	set<Id> setAccountIdToDeactivateCard = new set<Id>();
    	set<Id> setAccountIdToReactivateCard = new set<Id>();
		
		for(Zuora__ZInvoice__c inv : listNewInvoices){
			Zuora__ZInvoice__c oldinv = mapOldInvoices.get(inv.Id);
			
			system.debug ('##MNE SM_Invoice processTriggerAfterUpdate inv.Tech_FlagRejetPaye__c >> ' + inv.Tech_FlagRejetPaye__c); 
			system.debug ('##MNE SM_Invoice processTriggerAfterUpdate oldinv.Tech_FlagRejetPaye__c >> ' + oldinv.Tech_FlagRejetPaye__c); 
			system.debug ('##MNE SM_Invoice processTriggerAfterUpdate inv.Tech_TypeRejet__c >> ' + inv.Tech_TypeRejet__c); 
			system.debug ('##MNE SM_Invoice processTriggerAfterUpdate oldinv.Tech_TypeRejet__c >> ' + oldinv.Tech_TypeRejet__c); 
			
			if(inv.Tech_FlagRejetPaye__c != oldinv.Tech_FlagRejetPaye__c && inv.Tech_FlagRejetPaye__c == 'true'){
				//reactiver la carte
				if(inv.Zuora__Account__c != null){
    				setAccountIdToReactivateCard.add(inv.Zuora__Account__c);
    			}
			}
			else if(inv.Tech_FlagRejetPaye__c == 'false' && inv.Tech_TypeRejet__c != oldinv.Tech_TypeRejet__c && (inv.Tech_TypeRejet__c == 'Rejet_1' || inv.Tech_TypeRejet__c == 'Rejet_2')){
				mapInvoiceByIdToCreateCase.put(inv.Id, inv);
    			if(inv.Zuora__Account__c != null){
    				setAccountIdToDeactivateCard.add(inv.Zuora__Account__c);
    			}
			}
		}
		
		list<Case> listRejetCaseCreated;
    	if(mapInvoiceByIdToCreateCase.size() > 0){
    		listRejetCaseCreated = createRejetCase(mapInvoiceByIdToCreateCase);
    	}
    	
    	if(setAccountIdToDeactivateCard.size() > 0){
    		system.debug ('##MNE SM_Invoice processTriggerAfterUpdate callout Asynchrone methode desactivation card'); 
    		SM_Carte.desactivationByListAsynchrone(setAccountIdToDeactivateCard, 'X');
    	}
    	
    	if(setAccountIdToReactivateCard.size() > 0){
    		system.debug ('##MNE SM_Invoice processTriggerAfterUpdate callout Asynchrone methode resactivation card'); 
    		SM_Carte.activationByListAsynchrone(setAccountIdToReactivateCard);
    	}
    	
    	system.debug ('##MNE SM_Invoice processTriggerAfterUpdate END'); 
    }
    
    
    public static list<Case> createRejetCase(map<Id, Zuora__ZInvoice__c> mapInvoiceByIdToCreateCase){
    	system.debug ('##MNE SM_Invoice createRejetCase mapInvoiceByIdToCreateCase >> ' + mapInvoiceByIdToCreateCase); 
    	list<Case> listCaseToInsert = new list<Case>();
        Id impayeRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Impayé').getRecordTypeId();
        
        for(Zuora__ZInvoice__c inv : mapInvoiceByIdToCreateCase.values()){
        	Case c = new Case();
	        c.RecordTypeId = impayeRecordTypeId;
	        c.AccountId = inv.Zuora__Account__c;
	        c.Famille__c = '7- Finance';
	 		c.Motif__c = '02- Impayé';
	 		c.CommentairesInternes__c = inv.Tech_CodeRejet__c+' / '+inv.Tech_DateRejet__c;
	 		c.Origin = 'Interne';
	 		
	 		if(inv.Tech_FlagRejetPaye__c == 'false' && (inv.Tech_TypeRejet__c == 'Rejet_1' || inv.Tech_TypeRejet__c == 'Rejet_2') && inv.Tech_CodeRejet__c == 'MD07'){
	 			c.SousMotif__c = 'I- Info';
    		}
    		else if(inv.Tech_FlagRejetPaye__c == 'false' && inv.Tech_TypeRejet__c == 'Rejet_1' && inv.Tech_CodeRejet__c != 'MD07'){
    			c.SousMotif__c = 'R1- 1er rejet';
    		}
    		else if(inv.Tech_FlagRejetPaye__c == 'false' && inv.Tech_TypeRejet__c == 'Rejet_2' && inv.Tech_CodeRejet__c != 'MD07'){
    			c.SousMotif__c = 'R2- 2nd rejet';
    		}
	 		listCaseToInsert.add(c);
        }
        system.debug ('##MNE SM_Invoice createRejetCase listCaseToInsert size >> ' + listCaseToInsert); 
        system.debug ('##MNE SM_Invoice createRejetCase listCaseToInsert >> ' + listCaseToInsert.size()); 
        if(listCaseToInsert.size() > 0){
        	insert listCaseToInsert;
        }
        system.debug ('##MNE SM_Invoice createRejetCase END'); 
        return listCaseToInsert;
    }


}