force-app/main/default/objects/Case/fields/DateFinContrat__c.field-meta.xml
<CustomField>
    <fullName>DateFinContrat__c</fullName>
    <label>TECH_Date de fin de contrat</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/ExecDate__c.field-meta.xml
<CustomField>
    <fullName>ExecDate__c</fullName>
    <description>Last execution date</description>
    <label>Execution Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case/fields/ExecMessage__c.field-meta.xml
<CustomField>
    <fullName>ExecMessage__c</fullName>
    <description>save issue on case process execution: desabo..etc.</description>
    <label>Execution Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/ExecStatus__c.field-meta.xml
<CustomField>
    <fullName>ExecStatus__c</fullName>
    <description>Last execution status</description>
    <label>Execution Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Erreur</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/ExecSuccessDate__c.field-meta.xml
<CustomField>
    <fullName>ExecSuccessDate__c</fullName>
    <label>Execution Success Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case/fields/Subscription__c.field-meta.xml
<CustomField>
    <fullName>Subscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Abonnement</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>$Source.AccountId</field>
            <operation>equals</operation>
            <valueField>Zuora__Subscription__c.Zuora__Account__r.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Zuora__Subscription__c</referenceTo>
    <relationshipLabel>Demandes</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Zuora__Subscription__c/Zuora__Subscription__c.object-meta.xml
<CustomObject>
    <description>A subscription is a product or service that has recurring charges, such as a monthly flat fee or charges based on usage. Subscriptions can also include one-time charges, such as activation fees.</description>
    <label>Subscription</label>
    <nameField>
        <label>Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Zuora__Subscription__c/fields/CancelCaseID__c.field-meta.xml
<CustomField>
    <fullName>CancelCaseID__c</fullName>
    <description>id synchronise de Zuora</description>
    <label>ID Demande de desabo</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Zuora__Subscription__c/fields/DateFinContrat__c.field-meta.xml
<CustomField>
    <fullName>DateFinContrat__c</fullName>
    <description>custom field for Date Fin Contrat pour les cancel sub a term</description>
    <label>Date Fin Contrat</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Zuora__Subscription__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <description>Bilendi</description>
    <label>Source</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Zuora__Subscription__c/fields/Zuora__Status__c.field-meta.xml
<CustomField>
    <fullName>Zuora__Status__c</fullName>
    <label>Status</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Zuora__Subscription__c/fields/Zuora__SubscriptionNumber__c.field-meta.xml
<CustomField>
    <fullName>Zuora__SubscriptionNumber__c</fullName>
    <externalId>true</externalId>
    <label>Subscription Number</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/Batch_SubscriptionCancel.cls
global class Batch_SubscriptionCancel implements Database.Batchable<sObject>, Database.Stateful, Database.AllowsCallouts {

    public Date dateFinContrat;
    public String subNumber;

    public Batch_SubscriptionCancel(Date dateFinContrat, String subNumber) {
        if (dateFinContrat ==  null){
            this.dateFinContrat = Date.today();
        }else {
            this.dateFinContrat = dateFinContrat;
        }        
        this.subNumber = subNumber;                        
    }

    global Database.QueryLocator start(Database.BatchableContext BC) {

        // String query = 'Select Id From Case where Subscription__r.DateFinContrat__c= :cancelDate and Id = \'5000E000009jn2WQAQ\'';
        //String query = 'Select Id, CancelCaseID__c From Zuora__Subscription__c where Zuora__Status__c=\'Active\' and DateFinContrat__c=:dateFinContrat and CancelCaseID__c = \'5000E000009jn2WQAQ\'';
        String query;
        if (subNumber == null) {
            query = 'Select Id, CancelCaseID__c, Source__c From Zuora__Subscription__c where Zuora__Status__c=\'Active\' and DateFinContrat__c=:dateFinContrat limit 1';
        }else {
            query = 'Select Id, CancelCaseID__c, Source__c From Zuora__Subscription__c where Zuora__Status__c=\'Active\' and DateFinContrat__c=:dateFinContrat and Zuora__SubscriptionNumber__c = :subNumber limit 1';            
        }
        system.debug('##MNE Batch_SubscriptionCancel start query >> '+query);
        return Database.getQueryLocator(query); 
        // List<Zuora__Subscription__c> subscriptions = [Select Id, CancelCaseID__c From Zuora__Subscription__c where Zuora__Status__c='Active' and DateFinContrat__c=:dateFinContrat and CancelCaseID__c='5000E000009jn2WQAQ'];
        //List<Case> cases = [Select Id From Case where Subscription__r.DateFinContrat__c=:cancelDate]

    }

    global void execute(Database.BatchableContext BC, List<Zuora__Subscription__c> scope) {
        // List<Case> cases = [Select Id From Case where Subscription__r.DateFinContrat__c=:cancelDate and Id='5000E000009jn2WQAQ'];
        
        Id caseId, subId, currentId;
        
        for (Zuora__Subscription__c sub: scope){
            try {

                if (sub.CancelCaseID__c != null){ // contrats avec caseID (desabonner depuis un case saleforce)
                    caseId = sub.CancelCaseID__c;
                    currentId = caseId;
                    System.debug('MBEN: Batch_SubscriptionCancel: Case: '+ caseId);
                    SM_Desabonnement.desabonner(caseId,true);
                }else if (sub.Source__c == 'Bilendi'){//contrats Bilendi
                    subId = sub.Id;
                    currentId = subId;
                    System.debug('MBEN: Batch_SubscriptionCancel: Subscription Bilendi: '+ subId);
                    SM_Desabonnement.desabonner_Bilendi(subId);
                }else {
                    throw new RTException(RTExceptionCode.ERREUR_DESABO_BATCH_CASE_ABSENT);
                }

                // trace success
                if(currentId.getSObjectType() == Schema.Case.SObjectType && currentId != null){
                    Case c = new Case();
                    Datetime dNow = Datetime.now();
                    c.Id = caseId;                    
                    c.ExecStatus__c = 'Success';
                    c.ExecDate__c =dNow;
                    c.ExecSuccessDate__c = dNow;
                    update c;
                }
            }

            catch(Exception e) {                        
                if(currentId.getSObjectType() == Schema.Case.SObjectType && currentId != null){
                    Case c = new Case();
                    Datetime dNow = Datetime.now();
                    c.Id = caseId;
                    String sDate = String.valueOf(dNow);
                    String current_ExecMessage = [Select ExecMessage__c from Case where Id=:caseId].ExecMessage__c;
                    String fullMessage = e.getMessage() + e.getStackTraceString() + e.getTypeName() + e.getCause() + e.getLineNumber();
                    c.ExecMessage__c = sDate + fullMessage + '\n' + current_ExecMessage;
                    c.ExecStatus__c = 'Erreur';
                    c.ExecDate__c = dNow;                    
                    update c;
                }else {
                    System.debug('MBEN: Batch_SubscriptionCancel: '+ String.valueOf(e)); //TODO il faut tracer dans un autre objet
                }                
            }

            finally{
                                
            } 

        } //end for
        
        System.debug('MBEN-execute: scope: ' + scope.size());
    }

    global void finish(Database.BatchableContext BC) {
            System.debug('MBEN-finish' );
    
    }

}