force-app/main/default/objects/Case/fields/Date_de_D_sabonnement__c.field-meta.xml
<CustomField>
    <fullName>Date_de_D_sabonnement__c</fullName>
    <label>Date de désabonnement</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/Date_de_R_siliation__c.field-meta.xml
<CustomField>
    <fullName>Date_de_R_siliation__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <label>Date de résiliation</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case/fields/Date_fin_engagement__c.field-meta.xml
<CustomField>
    <fullName>Date_fin_engagement__c</fullName>
    <label>TECH_Date de fin d&#39;engagement</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/DateDemande__c.field-meta.xml
<CustomField>
    <fullName>DateDemande__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Date de la demande</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/DateFinContrat__c.field-meta.xml
<CustomField>
    <fullName>DateFinContrat__c</fullName>
    <label>TECH_Date de fin de contrat</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/DemandeRemboursement2__c.field-meta.xml
<CustomField>
    <fullName>DemandeRemboursement2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Demande de remboursement 2</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Demandes d&#39;origine</relationshipLabel>
    <relationshipName>OrigineDemandes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Famille__c.field-meta.xml
<CustomField>
    <fullName>Famille__c</fullName>
    <label>Famille</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0- Souscription</fullName>
            </value>
            <value>
                <fullName>1- Vie de l&#39;abonnement</fullName>
            </value>
            <value>
                <fullName>2- Club UGC / fidelite</fullName>
            </value>
            <value>
                <fullName>3- Autres Produits</fullName>
            </value>
            <value>
                <fullName>4- Reservation</fullName>
                <label>4- Réservation</label>
            </value>
            <value>
                <fullName>5- Compte client</fullName>
            </value>
            <value>
                <fullName>6- Prospection</fullName>
            </value>
            <value>
                <fullName>7- Finance</fullName>
            </value>
            <value>
                <fullName>8- Cinema</fullName>
                <label>8- Cinéma</label>
            </value>
            <value>
                <fullName>9- Divers</fullName>
            </value>
            <value>
                <fullName>0- Commentaires</fullName>
                <isActive>false</isActive>
                <label>0- Commentaires</label>
            </value>
            <value>
                <fullName>1- Demandes d info UI</fullName>
                <isActive>false</isActive>
                <label>1- Demandes d info UI</label>
            </value>
            <value>
                <fullName>1- Demandes d&#39;info UI</fullName>
                <isActive>false</isActive>
                <label>1- Demandes d&#39;info UI</label>
            </value>
            <value>
                <fullName>2- Demande d infos generales</fullName>
                <isActive>false</isActive>
                <label>2- Demande d infos generales</label>
            </value>
            <value>
                <fullName>2- Demande d&#39;infos générales</fullName>
                <isActive>false</isActive>
                <label>2- Demande d&#39;infos générales</label>
            </value>
            <value>
                <fullName>3- Autres demandes d&#39;informations</fullName>
                <isActive>false</isActive>
                <label>3- Autres demandes d&#39;informations</label>
            </value>
            <value>
                <fullName>4- Abonnement Carte UGC</fullName>
                <isActive>false</isActive>
                <label>4- Abonnement Carte UGC</label>
            </value>
            <value>
                <fullName>5- Abonnement en attente</fullName>
                <isActive>false</isActive>
                <label>5- Abonnement en attente</label>
            </value>
            <value>
                <fullName>6- GestionCompteUI</fullName>
                <isActive>false</isActive>
                <label>6- GestionCompteUI</label>
            </value>
            <value>
                <fullName>7- Réclamations UI</fullName>
                <isActive>false</isActive>
                <label>7- Réclamations UI</label>
            </value>
            <value>
                <fullName>8- Autres types de reclamations</fullName>
                <isActive>false</isActive>
                <label>8- Autres types de reclamations</label>
            </value>
            <value>
                <fullName>8- Autres types de réclamations</fullName>
                <isActive>false</isActive>
                <label>8- Autres types de réclamations</label>
            </value>
            <value>
                <fullName>9- Supports Digitaux</fullName>
                <isActive>false</isActive>
                <label>9- Supports Digitaux</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/MontantRemboursementCalc__c.field-meta.xml
<CustomField>
    <fullName>MontantRemboursementCalc__c</fullName>
    <description>Montant de remboursement calcule automatiquement pas le systeme</description>
    <label>Montant Remboursement Calc</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case/fields/MontantRembourser__c.field-meta.xml
<CustomField>
    <fullName>MontantRembourser__c</fullName>
    <inlineHelpText>Merci de remplir le montant avec une virgule et non un point</inlineHelpText>
    <label>Montant à rembourser</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Case/fields/Motif__c.field-meta.xml
<CustomField>
    <fullName>Motif__c</fullName>
    <label>Motif</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Famille__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>01- Info process abo</fullName>
            </value>
            <value>
                <fullName>02- Erreur prise abo</fullName>
            </value>
            <value>
                <fullName>03- Click and collect</fullName>
            </value>
            <value>
                <fullName>05- B2B</fullName>
            </value>
            <value>
                <fullName>06- VPC</fullName>
            </value>
            <value>
                <fullName>07- Creation Abonnement</fullName>
            </value>
            <value>
                <fullName>01- Reception carte</fullName>
                <label>01- Réception carte</label>
            </value>
            <value>
                <fullName>02- Reedition payante</fullName>
            </value>
            <value>
                <fullName>03- Reedition gratuite</fullName>
            </value>
            <value>
                <fullName>04- Desabonnement</fullName>
            </value>
            <value>
                <fullName>05- Resiliation</fullName>
            </value>
            <value>
                <fullName>06- Migration UI 1/2/3</fullName>
            </value>
            <value>
                <fullName>07- Reabonnement</fullName>
            </value>
            <value>
                <fullName>08- Retention</fullName>
            </value>
            <value>
                <fullName>09- Retour Carte</fullName>
            </value>
            <value>
                <fullName>10- Retractation</fullName>
            </value>
            <value>
                <fullName>11- Avertissement</fullName>
            </value>
            <value>
                <fullName>12- Annulation Migration</fullName>
            </value>
            <value>
                <fullName>13- Annulation Contrat</fullName>
            </value>
            <value>
                <fullName>04- Dematerialise</fullName>
                <label>04- Dématérialisé</label>
            </value>
            <value>
                <fullName>01- Inscription</fullName>
            </value>
            <value>
                <fullName>02- Solde de points</fullName>
            </value>
            <value>
                <fullName>03- Echange de points</fullName>
            </value>
            <value>
                <fullName>04- Fonctionnement Club</fullName>
            </value>
            <value>
                <fullName>01- Offres UGC</fullName>
            </value>
            <value>
                <fullName>02- Formules UGC+</fullName>
            </value>
            <value>
                <fullName>03- Solo</fullName>
            </value>
            <value>
                <fullName>04- Blue</fullName>
            </value>
            <value>
                <fullName>05- VLO</fullName>
            </value>
            <value>
                <fullName>01- Modalites de reservation</fullName>
                <label>01- Modalités de réservation</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Motif_de_R_siliation__c.field-meta.xml
<CustomField>
    <fullName>Motif_de_R_siliation__c</fullName>
    <label>Motif de Résiliation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Code X</fullName>
            </value>
            <value>
                <fullName>M3</fullName>
            </value>
            <value>
                <fullName>M6</fullName>
            </value>
            <value>
                <fullName>M10</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Pays__c.field-meta.xml
<CustomField>
    <fullName>Pays__c</fullName>
    <description>Champ qui copie le pays du compte</description>
    <formula>TEXT(Account.Pays__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Pays</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/RemboursementFaire__c.field-meta.xml
<CustomField>
    <fullName>RemboursementFaire__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Quand c est coché une demande de remboursement est automatiquement crée</description>
    <label>Remboursement à faire</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/SousMotif__c.field-meta.xml
<CustomField>
    <fullName>SousMotif__c</fullName>
    <label>Sous-motif</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Motif__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>I- Info</fullName>
            </value>
            <value>
                <fullName>R- Récla</fullName>
            </value>
            <value>
                <fullName>A- Action</fullName>
            </value>
            <value>
                <fullName>Click to Call Info</fullName>
            </value>
            <value>
                <fullName>Click to Call Recla</fullName>
            </value>
            <value>
                <fullName>AD- Action DRC</fullName>
            </value>
            <value>
                <fullName>AS- Action Stand</fullName>
            </value>
            <value>
                <fullName>AH- Action Selfcare</fullName>
            </value>
            <value>
                <fullName>R1- 1er rejet</fullName>
            </value>
            <value>
                <fullName>R2- 2nd rejet</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Subscription__c.field-meta.xml
<CustomField>
    <fullName>Subscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Abonnement</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>$Source.AccountId</field>
            <operation>equals</operation>
            <valueField>Zuora__Subscription__c.Zuora__Account__r.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Zuora__Subscription__c</referenceTo>
    <relationshipLabel>Demandes</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/SubscriptionZName__c.field-meta.xml
<CustomField>
    <fullName>SubscriptionZName__c</fullName>
    <description>Stock le name Zuora de la souscription</description>
    <label>Zuora Subscription Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Type_de_d_sabonnement__c.field-meta.xml
<CustomField>
    <fullName>Type_de_d_sabonnement__c</fullName>
    <label>Type de désabonnement</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Désabonnement avec préavis (L)</fullName>
            </value>
            <value>
                <fullName>Désabonnement avec justificatif (E)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Remboursement.recordType-meta.xml
<RecordType>
    <fullName>Remboursement</fullName>
    <active>true</active>
    <businessProcess>Remboursement</businessProcess>
    <label>Remboursement</label>
</RecordType>

force-app/main/default/objects/Zuora__Subscription__c/Zuora__Subscription__c.object-meta.xml
<CustomObject>
    <description>A subscription is a product or service that has recurring charges, such as a monthly flat fee or charges based on usage. Subscriptions can also include one-time charges, such as activation fees.</description>
    <label>Subscription</label>
    <nameField>
        <label>Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Zuora__Subscription__c/fields/DateFinContrat__c.field-meta.xml
<CustomField>
    <fullName>DateFinContrat__c</fullName>
    <description>custom field for Date Fin Contrat pour les cancel sub a term</description>
    <label>Date Fin Contrat</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Zuora__Subscription__c/fields/Zuora__SubscriptionStartDate__c.field-meta.xml
<CustomField>
    <fullName>Zuora__SubscriptionStartDate__c</fullName>
    <description>The date when the subscription term starts. This is equal to the term start date if the subscription is on its initial term. Otherwise, it is the original term start date if the subscription has renewed.</description>
    <label>Subscription Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/SM_Demande.cls
/**
 * Created by mouad on 30/08/2018.
 */

public with sharing class SM_Demande {

    public static String closeStatus(){
        String closeStatus = [SELECT MasterLabel FROM CaseStatus WHERE ApiName = 'Fermee'].MasterLabel;
        return closeStatus;
    }

    public static String getStatus(String status){
        String closeStatus = [SELECT MasterLabel FROM CaseStatus WHERE ApiName = :status].MasterLabel;
        return closeStatus;
    }


    public static Case getDemande(Id ddeId){

        Case demande = [
                SELECT Id, AccountId, ParentId, ContactId, Status, Famille__c, Motif__c, SousMotif__c, DateDemande__c, Pays__c,
                        Origin, MontantRembourser__c, MontantRemboursementCalc__c, RemboursementFaire__c, DemandeRemboursement2__c, Subscription__c, SubscriptionZName__c,
                        Date_fin_engagement__c, DateFinContrat__c, Date_de_D_sabonnement__c, Subscription__r.Zuora__SubscriptionStartDate__c, Type_de_d_sabonnement__c,
                        RecordTypeId, Date_de_R_siliation__c, Motif_de_R_siliation__c,Moyen_de_paiement_souhait__c,Raison_remboursement__c,
                        DateDeRemboursement__c, CreditMemoId__c, Payment__c, Payment__r.Id, Payment__r.Zuora__EXT_ID__c,
                        Mois_de_d_but_remise__c, MontantRemise__c, NombreDeMoisRemise__c, Pallier__c, CouponWelcomeback__c,Subscription__r.Zuora__Zuora_Id__c,Etat_remboursement__c,
                        Offre_de_r_tention__c, Raison_de_d_sabonnement__c, R_sultat_R_tention__c, TECHIdStatut__c
                FROM Case
                WHERE Id = :ddeId
        ];
        return demande; //TODO voir si c une passage en reference ou en valeur ?

    }

    public static Id creerRemboursement(Case demande) {

        demande.Famille__c = 'EF-Finance';
        demande.Motif__c = 'EF-Remboursement';

        insert demande;
        return demande.Id;
    }
    
    public static Date getRemiseDate(Integer moidDebutRemise){
        Date todayDate = Date.today();
        Integer todayYear = todayDate.year();
        
        Date dateRemise = Date.newInstance(todayYear, moidDebutRemise, 1);
        
        if(todayDate > dateRemise){
            dateRemise = dateRemise.addYears(1);
        }
        return dateRemise;
    }
    
    public static Date getDateMoisSuivant(Date currentDate){
    	Integer currentDateMonth = currentDate.month();
        Integer currentDateYear = currentDate.year();
        
        Date dateMoisSuivant = Date.newInstance(currentDateYear, currentDateMonth+1, 1);
        
        if(currentDate > dateMoisSuivant){
            dateMoisSuivant = dateMoisSuivant.addYears(1);
        }
        return dateMoisSuivant;
    }


}