force-app/main/default/objects/Case/fields/Famille__c.field-meta.xml
<CustomField>
    <fullName>Famille__c</fullName>
    <label>Famille</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0- Souscription</fullName>
            </value>
            <value>
                <fullName>1- Vie de l&#39;abonnement</fullName>
            </value>
            <value>
                <fullName>2- Club UGC / fidelite</fullName>
            </value>
            <value>
                <fullName>3- Autres Produits</fullName>
            </value>
            <value>
                <fullName>4- Reservation</fullName>
                <label>4- Réservation</label>
            </value>
            <value>
                <fullName>5- Compte client</fullName>
            </value>
            <value>
                <fullName>6- Prospection</fullName>
            </value>
            <value>
                <fullName>7- Finance</fullName>
            </value>
            <value>
                <fullName>8- Cinema</fullName>
                <label>8- Cinéma</label>
            </value>
            <value>
                <fullName>9- Divers</fullName>
            </value>
            <value>
                <fullName>0- Commentaires</fullName>
                <isActive>false</isActive>
                <label>0- Commentaires</label>
            </value>
            <value>
                <fullName>1- Demandes d info UI</fullName>
                <isActive>false</isActive>
                <label>1- Demandes d info UI</label>
            </value>
            <value>
                <fullName>1- Demandes d&#39;info UI</fullName>
                <isActive>false</isActive>
                <label>1- Demandes d&#39;info UI</label>
            </value>
            <value>
                <fullName>2- Demande d infos generales</fullName>
                <isActive>false</isActive>
                <label>2- Demande d infos generales</label>
            </value>
            <value>
                <fullName>2- Demande d&#39;infos générales</fullName>
                <isActive>false</isActive>
                <label>2- Demande d&#39;infos générales</label>
            </value>
            <value>
                <fullName>3- Autres demandes d&#39;informations</fullName>
                <isActive>false</isActive>
                <label>3- Autres demandes d&#39;informations</label>
            </value>
            <value>
                <fullName>4- Abonnement Carte UGC</fullName>
                <isActive>false</isActive>
                <label>4- Abonnement Carte UGC</label>
            </value>
            <value>
                <fullName>5- Abonnement en attente</fullName>
                <isActive>false</isActive>
                <label>5- Abonnement en attente</label>
            </value>
            <value>
                <fullName>6- GestionCompteUI</fullName>
                <isActive>false</isActive>
                <label>6- GestionCompteUI</label>
            </value>
            <value>
                <fullName>7- Réclamations UI</fullName>
                <isActive>false</isActive>
                <label>7- Réclamations UI</label>
            </value>
            <value>
                <fullName>8- Autres types de reclamations</fullName>
                <isActive>false</isActive>
                <label>8- Autres types de reclamations</label>
            </value>
            <value>
                <fullName>8- Autres types de réclamations</fullName>
                <isActive>false</isActive>
                <label>8- Autres types de réclamations</label>
            </value>
            <value>
                <fullName>9- Supports Digitaux</fullName>
                <isActive>false</isActive>
                <label>9- Supports Digitaux</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Motif__c.field-meta.xml
<CustomField>
    <fullName>Motif__c</fullName>
    <label>Motif</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Famille__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>01- Info process abo</fullName>
            </value>
            <value>
                <fullName>02- Erreur prise abo</fullName>
            </value>
            <value>
                <fullName>03- Click and collect</fullName>
            </value>
            <value>
                <fullName>05- B2B</fullName>
            </value>
            <value>
                <fullName>06- VPC</fullName>
            </value>
            <value>
                <fullName>07- Creation Abonnement</fullName>
            </value>
            <value>
                <fullName>01- Reception carte</fullName>
                <label>01- Réception carte</label>
            </value>
            <value>
                <fullName>02- Reedition payante</fullName>
            </value>
            <value>
                <fullName>03- Reedition gratuite</fullName>
            </value>
            <value>
                <fullName>04- Desabonnement</fullName>
            </value>
            <value>
                <fullName>05- Resiliation</fullName>
            </value>
            <value>
                <fullName>06- Migration UI 1/2/3</fullName>
            </value>
            <value>
                <fullName>07- Reabonnement</fullName>
            </value>
            <value>
                <fullName>08- Retention</fullName>
            </value>
            <value>
                <fullName>09- Retour Carte</fullName>
            </value>
            <value>
                <fullName>10- Retractation</fullName>
            </value>
            <value>
                <fullName>11- Avertissement</fullName>
            </value>
            <value>
                <fullName>12- Annulation Migration</fullName>
            </value>
            <value>
                <fullName>13- Annulation Contrat</fullName>
            </value>
            <value>
                <fullName>04- Dematerialise</fullName>
                <label>04- Dématérialisé</label>
            </value>
            <value>
                <fullName>01- Inscription</fullName>
            </value>
            <value>
                <fullName>02- Solde de points</fullName>
            </value>
            <value>
                <fullName>03- Echange de points</fullName>
            </value>
            <value>
                <fullName>04- Fonctionnement Club</fullName>
            </value>
            <value>
                <fullName>01- Offres UGC</fullName>
            </value>
            <value>
                <fullName>02- Formules UGC+</fullName>
            </value>
            <value>
                <fullName>03- Solo</fullName>
            </value>
            <value>
                <fullName>04- Blue</fullName>
            </value>
            <value>
                <fullName>05- VLO</fullName>
            </value>
            <value>
                <fullName>01- Modalites de reservation</fullName>
                <label>01- Modalités de réservation</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/SousMotif__c.field-meta.xml
<CustomField>
    <fullName>SousMotif__c</fullName>
    <label>Sous-motif</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Motif__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>I- Info</fullName>
            </value>
            <value>
                <fullName>R- Récla</fullName>
            </value>
            <value>
                <fullName>A- Action</fullName>
            </value>
            <value>
                <fullName>Click to Call Info</fullName>
            </value>
            <value>
                <fullName>Click to Call Recla</fullName>
            </value>
            <value>
                <fullName>AD- Action DRC</fullName>
            </value>
            <value>
                <fullName>AS- Action Stand</fullName>
            </value>
            <value>
                <fullName>AH- Action Selfcare</fullName>
            </value>
            <value>
                <fullName>R1- 1er rejet</fullName>
            </value>
            <value>
                <fullName>R2- 2nd rejet</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/TECH_Alert__c.field-meta.xml
<CustomField>
    <fullName>TECH_Alert__c</fullName>
    <defaultValue>false</defaultValue>
    <description>True si une alerte a été lancée sur ce case.</description>
    <label>Alerté</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Global_Parameters__mdt/Global_Parameters__mdt.object-meta.xml
<CustomObject>
    <description>Paramètres globaux de l&#39;application</description>
    <label>Global Parameters</label>
    <pluralLabel>Global Parameters</pluralLabel>
</CustomObject>

force-app/main/default/objects/Global_Parameters__mdt/fields/Nom_Groupe_Chatter__c.field-meta.xml
<CustomField>
    <fullName>Nom_Groupe_Chatter__c</fullName>
    <label>Nom Groupe Chatter</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Batch_Surveillance_Test.cls
@IsTest(SeeAllData=true)
public class Batch_Surveillance_Test {

    @isTest static void alertOnCreatingCases(){
        
        

       	Global_Parameters__mdt ugcOneParam = Utils.getGlobalParameters('UGC_One_Parameters');
        String nomGroup = ugcOneParam.Nom_Groupe_Chatter__c;
        CollaborationGroup groupChatter;

        List<CollaborationGroup> groupes = [SELECT Id, Name FROM CollaborationGroup WHERE Name = :nomGroup];
        System.debug('--#### groupes = '+groupes);
        if(groupes.size() == 1){
            groupChatter = groupes.get(0);
        }else{        
            //créer un group chatter
            groupChatter = new CollaborationGroup(Name = nomGroup, CollaborationType = 'Public');
            insert groupChatter;
        }
        
        System.assertEquals(groupChatter.Id!=null, true);
        
        Case case1 = new Case(Famille__c = 	'2- Demande d\'infos générales', Motif__c = '1- Autres produits et services', 	SousMotif__c = '1- Cartes 5,5+');
        Case case2 = new Case(Famille__c = 	'2- Demande d\'infos générales', Motif__c = '1- Autres produits et services', 	SousMotif__c = '1- Cartes 5,5+');
        Case case3 = new Case(Famille__c = 	'2- Demande d\'infos générales', Motif__c = '1- Autres produits et services', 	SousMotif__c = '1- Cartes 5,5+');
        Case case4 = new Case(Famille__c = 	'2- Demande d\'infos générales', Motif__c = '1- Autres produits et services', 	SousMotif__c = '1- Cartes 5,5+');
        Case case5 = new Case(Famille__c = 	'2- Demande d\'infos générales', Motif__c = '1- Autres produits et services', 	SousMotif__c = '1- Cartes 5,5+');
        
        List<Case> caseList = new List<Case>();
        caseList.add(case1);
        caseList.add(case2);
        caseList.add(case3);
        caseList.add(case4);
        caseList.add(case5);
        
        insert caseList;
        
        System.assertEquals(caseList.get(0).id!=null, true);
        System.assertEquals(caseList.get(1).id!=null, true);
        System.assertEquals(caseList.get(2).id!=null, true);
        System.assertEquals(caseList.get(3).id!=null, true);
        System.assertEquals(caseList.get(4).id!=null, true);
        
        Test.startTest();
        
        Batch_SurveillanceEtAlerteSousMotifs batchLaunch = new Batch_SurveillanceEtAlerteSousMotifs();      
		Database.executebatch(batchLaunch);
        
        Test.stopTest();
        
        Case caseVerif = [SELECT Id, TECH_Alert__c FROM Case WHERE Id = :caseList.get(0).Id];
        
        System.assert(caseVerif.TECH_Alert__c);

        List<FeedItem> chatterFeedLst = [SELECT Id FROM FeedItem WHERE ParentId = :groupChatter.Id];
        System.assert( chatterFeedLst.size() > 0);
        
    }
}