force-app/main/default/objects/Case/fields/Motif__c.field-meta.xml
<CustomField>
    <fullName>Motif__c</fullName>
    <label>Motif</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Famille__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>01- Info process abo</fullName>
            </value>
            <value>
                <fullName>02- Erreur prise abo</fullName>
            </value>
            <value>
                <fullName>03- Click and collect</fullName>
            </value>
            <value>
                <fullName>05- B2B</fullName>
            </value>
            <value>
                <fullName>06- VPC</fullName>
            </value>
            <value>
                <fullName>07- Creation Abonnement</fullName>
            </value>
            <value>
                <fullName>01- Reception carte</fullName>
                <label>01- Réception carte</label>
            </value>
            <value>
                <fullName>02- Reedition payante</fullName>
            </value>
            <value>
                <fullName>03- Reedition gratuite</fullName>
            </value>
            <value>
                <fullName>04- Desabonnement</fullName>
            </value>
            <value>
                <fullName>05- Resiliation</fullName>
            </value>
            <value>
                <fullName>06- Migration UI 1/2/3</fullName>
            </value>
            <value>
                <fullName>07- Reabonnement</fullName>
            </value>
            <value>
                <fullName>08- Retention</fullName>
            </value>
            <value>
                <fullName>09- Retour Carte</fullName>
            </value>
            <value>
                <fullName>10- Retractation</fullName>
            </value>
            <value>
                <fullName>11- Avertissement</fullName>
            </value>
            <value>
                <fullName>12- Annulation Migration</fullName>
            </value>
            <value>
                <fullName>13- Annulation Contrat</fullName>
            </value>
            <value>
                <fullName>04- Dematerialise</fullName>
                <label>04- Dématérialisé</label>
            </value>
            <value>
                <fullName>01- Inscription</fullName>
            </value>
            <value>
                <fullName>02- Solde de points</fullName>
            </value>
            <value>
                <fullName>03- Echange de points</fullName>
            </value>
            <value>
                <fullName>04- Fonctionnement Club</fullName>
            </value>
            <value>
                <fullName>01- Offres UGC</fullName>
            </value>
            <value>
                <fullName>02- Formules UGC+</fullName>
            </value>
            <value>
                <fullName>03- Solo</fullName>
            </value>
            <value>
                <fullName>04- Blue</fullName>
            </value>
            <value>
                <fullName>05- VLO</fullName>
            </value>
            <value>
                <fullName>01- Modalites de reservation</fullName>
                <label>01- Modalités de réservation</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/NbAppelsEntrants__c.field-meta.xml
<CustomField>
    <fullName>NbAppelsEntrants__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Nb Appels Entrants</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case/fields/NbAppelsSortants__c.field-meta.xml
<CustomField>
    <fullName>NbAppelsSortants__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Nb Appels Sortants</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case/fields/NbCourriersEntrants__c.field-meta.xml
<CustomField>
    <fullName>NbCourriersEntrants__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Nb Courriers Entrants</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case/fields/NbCourriersSortants__c.field-meta.xml
<CustomField>
    <fullName>NbCourriersSortants__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Nb courriers sortants</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case/fields/NbCritizr__c.field-meta.xml
<CustomField>
    <fullName>NbCritizr__c</fullName>
    <defaultValue>0</defaultValue>
    <label>NbCritizr</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case/fields/NbEmailsEntrants__c.field-meta.xml
<CustomField>
    <fullName>NbEmailsEntrants__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Nb Emails Entrants</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case/fields/NbEmailsSortants__c.field-meta.xml
<CustomField>
    <fullName>NbEmailsSortants__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Champ Technique pour calculer le nombre d&#39;emails sortants envoyés sur le ticket.
Champ incrémenté par workflow</description>
    <label>Nb emails Sortants</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case/fields/NbFacebook__c.field-meta.xml
<CustomField>
    <fullName>NbFacebook__c</fullName>
    <defaultValue>0</defaultValue>
    <label>NbFacebook</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case/fields/NbFormulaireContact__c.field-meta.xml
<CustomField>
    <fullName>NbFormulaireContact__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Nb Formulaire de Contact</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case/fields/NbTwitter__c.field-meta.xml
<CustomField>
    <fullName>NbTwitter__c</fullName>
    <defaultValue>0</defaultValue>
    <label>NbTwitter</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CsvBatch.cls
global class CsvBatch implements Database.Batchable<sObject>, Database.Stateful {

    	global Database.QueryLocator start(Database.BatchableContext BC){
	 	System.debug('Start method calling');
		String query = 'Select id, NbAppelsEntrants__c, NbCourriersEntrants__c, NbCritizr__c, NbFacebook__c, NbTwitter__c, NbFormulaireContact__c, NbEmailsEntrants__c, NbAppelsSortants__c, NbCourriersSortants__c, NbEmailsSortants__c, Motif__c from case';	
        System.debug('Start  calling');
    	return Database.getQueryLocator(query); 
    }    
    
    
    
    
    global void execute(Database.BatchableContext BC, List<sObject> scope){

        System.debug('Execute method start');
        List<Case> l = (List<Case>)scope;
        List<Id> li = new List<Id>();
        for(Case c : l){
         li.add(c.id);  
        }
        List<Task> camp = [SELECT WhatId,Origine__c from Task WHERE WhatId in: li];

         for (Task t : camp){ 
            for(Case c : l){
             	
                if(c.id  == t.WhatId){
                  
                    if(t.Origine__c == 'Facebook'){
                        c.NbFacebook__c = 0; }
                    
                    else{if(t.Origine__c == 'Twitter'){
                        c.NbTwitter__c = 0; }
                    
                    else{if(t.Origine__c == 'Critizr'){
						c.NbCritizr__c = 0;}}}
                    
                    	if(t.Origine__c == 'Appel entrant'){
                        c.NbAppelsEntrants__c = 0; }
                    
                    else{if(t.Origine__c == 'Courrier entrant'){
                        c.NbCourriersEntrants__c = 0; }
                    
                    else{if(t.Origine__c == 'Email entrant'){
						c.NbEmailsEntrants__c = 0;}
                    
                    else{if(t.Origine__c == 'Formulaire de contact'){
                        c.NbFormulaireContact__c = 0;}}}}
                    
                     if(t.Origine__c == 'Appel sortant'){
                        c.NbAppelsSortants__c = 0; }
                    
                    else{if(t.Origine__c == 'Courrier sortant'){
                        c.NbCourriersSortants__c =0; }
                    
                    else{if(t.Origine__c == 'Email sortant'){
						c.NbEmailsSortants__c = 0;}}}}

                    
                } 
            }
        
        	update l;
        
        for (Task t : camp){ 
            for(Case c : l){
             	
                if(c.id  == t.WhatId){
                    
                     if(t.Origine__c == 'Facebook'){
                        c.NbFacebook__c = Integer.valueOf(c.NbFacebook__c) + 1; }
                    
                    else{if(t.Origine__c == 'Twitter'){
                        c.NbTwitter__c = Integer.valueOf(c.NbTwitter__c) + 1; }
                    
                    else{if(t.Origine__c == 'Critizr'){
						c.NbCritizr__c = Integer.valueOf(c.NbCritizr__c) + 1;}}}
                  
                    	if(t.Origine__c == 'Appel entrant'){
                        c.NbAppelsEntrants__c = Integer.valueOf(c.NbAppelsEntrants__c) + 1; }
                    
                    else{if(t.Origine__c == 'Courrier entrant'){
                        c.NbCourriersEntrants__c = Integer.valueOf(c.NbCourriersEntrants__c) + 1; }
                    
                    else{if(t.Origine__c == 'Email entrant'){
						c.NbEmailsEntrants__c = Integer.valueOf(c.NbEmailsEntrants__c) + 1;}
                    
                    else{if(t.Origine__c == 'Formulaire de contact'){
                        c.NbFormulaireContact__c = Integer.valueOf(c.NbFormulaireContact__c) + 1;}}}}
                    
                    if(t.Origine__c == 'Appel sortant'){
                        c.NbAppelsSortants__c = Integer.valueOf(c.NbAppelsSortants__c) + 1; }
                    
                    else{if(t.Origine__c == 'Courrier sortant'){
                        c.NbCourriersSortants__c = Integer.valueOf(c.NbCourriersSortants__c) + 1; }
                    
                    else{if(t.Origine__c == 'Email sortant'){
						c.NbEmailsSortants__c = Integer.valueOf(c.NbEmailsSortants__c) + 1;}}}}
                } 
            }
  
  		update l;
        
     
    }
    
    global void finish(Database.BatchableContext BC){
    	System.debug('number of fails');

    }
    
}