force-app/main/default/objects/Case/fields/NbCritizr__c.field-meta.xml
<CustomField>
    <fullName>NbCritizr__c</fullName>
    <defaultValue>0</defaultValue>
    <label>NbCritizr</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case/fields/NbFacebook__c.field-meta.xml
<CustomField>
    <fullName>NbFacebook__c</fullName>
    <defaultValue>0</defaultValue>
    <label>NbFacebook</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case/fields/NbTwitter__c.field-meta.xml
<CustomField>
    <fullName>NbTwitter__c</fullName>
    <defaultValue>0</defaultValue>
    <label>NbTwitter</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/maj.cls
global class maj implements Database.Batchable<sObject>, Database.Stateful {

    global Database.QueryLocator start(Database.BatchableContext BC){
	
    string query = 'select id, NbFacebook__c, NbTwitter__c, NbCritizr__c from case where NbFacebook__c = null';
    	return Database.getQueryLocator(query); 
    }  

    global void execute(Database.BatchableContext BC, List<sObject> scope){

        System.debug('Execute method start');
        List<Case> l = (List<Case>)scope;
		For(Case cs : l){
  		cs.NbFacebook__c = 0;
  		cs.NbTwitter__c = 0;
 		cs.NbCritizr__c = 0; 
		}
		update l;
     
    }
    
    global void finish(Database.BatchableContext BC){
    	System.debug('number of fails');

    }
    
}