force-app/main/default/objects/Case/fields/SousMotif__c.field-meta.xml
<CustomField>
    <fullName>SousMotif__c</fullName>
    <label>Sous-motif</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Motif__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>I- Info</fullName>
            </value>
            <value>
                <fullName>R- Récla</fullName>
            </value>
            <value>
                <fullName>A- Action</fullName>
            </value>
            <value>
                <fullName>Click to Call Info</fullName>
            </value>
            <value>
                <fullName>Click to Call Recla</fullName>
            </value>
            <value>
                <fullName>AD- Action DRC</fullName>
            </value>
            <value>
                <fullName>AS- Action Stand</fullName>
            </value>
            <value>
                <fullName>AH- Action Selfcare</fullName>
            </value>
            <value>
                <fullName>R1- 1er rejet</fullName>
            </value>
            <value>
                <fullName>R2- 2nd rejet</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/TECH_Alert__c.field-meta.xml
<CustomField>
    <fullName>TECH_Alert__c</fullName>
    <defaultValue>false</defaultValue>
    <description>True si une alerte a été lancée sur ce case.</description>
    <label>Alerté</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Global_Parameters__mdt/Global_Parameters__mdt.object-meta.xml
<CustomObject>
    <description>Paramètres globaux de l&#39;application</description>
    <label>Global Parameters</label>
    <pluralLabel>Global Parameters</pluralLabel>
</CustomObject>

force-app/main/default/objects/Global_Parameters__mdt/fields/Nom_Groupe_Chatter__c.field-meta.xml
<CustomField>
    <fullName>Nom_Groupe_Chatter__c</fullName>
    <label>Nom Groupe Chatter</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Global_Parameters__mdt/fields/Seuil_Alerte_Par_Heure__c.field-meta.xml
<CustomField>
    <fullName>Seuil_Alerte_Par_Heure__c</fullName>
    <label>Seuil Alerte Par Heure</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Global_Parameters__mdt/fields/Sous_Motifs__c.field-meta.xml
<CustomField>
    <fullName>Sous_Motifs__c</fullName>
    <label>Sous-Motifs</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/Batch_SurveillanceEtAlerteSousMotifs.cls
global class Batch_SurveillanceEtAlerteSousMotifs implements Database.Batchable<sObject> {
             
	
	Datetime dateReference;
	String query;
	Integer seuilAlerte = 5;
    CollaborationGroup groupChatter;
	List<String> sousMotifsLst;
	
	global Batch_SurveillanceEtAlerteSousMotifs() {

		Global_Parameters__mdt ugcOneParam = Utils.getGlobalParameters('UGC_One_Parameters');
       	
		if(ugcOneParam!=null){

			System.debug('--#### Custum settings Sous-Motifs à surveiller = ' + ugcOneParam.Sous_Motifs__c);

			seuilAlerte = Integer.valueOf(ugcOneParam.Seuil_Alerte_Par_Heure__c);
			System.debug('--#### Seuil d\'alerte = ' + seuilAlerte);

			String nomGroupChatter = ugcOneParam.Nom_Groupe_Chatter__c;
	        groupChatter = [SELECT Id, Name FROM CollaborationGroup WHERE Name =: nomGroupChatter].get(0);
	        
	        System.debug('--#### Nom du groupe chatter = ' + nomGroupChatter + ', Id = '+groupChatter.Id);

			String sousMotifs = ugcOneParam.Sous_Motifs__c;
            System.debug('--#### String sousMotifs = ' + sousMotifs);

			sousMotifsLst = new List<String>();
            for(String sousphrase : sousMotifs.split('[\n\r]')){
                if (sousphrase !=''){
	                sousMotifsLst.add(sousphrase.trim());
                }
  			}
        
			System.debug('--#### Liste des sous-motifs à surveiller = ' + sousMotifsLst);
		}else{
			System.debug('--#### ERROR BATCH : ugcOneParam est null !!!!');
		}

        // System.now() donne l'heure de GMT c'est a dire 2 heure de moins qu'à Paris donc pour avoir heure de (Paris - 1) :
		dateReference = System.now().addHours(-1);
		query = 'SELECT Id, SousMotif__c ';
		query += ' FROM Case';
		query += ' WHERE SousMotif__c IN :sousMotifsLst';
		query += ' AND CreatedDate >= :dateReference';
		query += ' AND TECH_Alert__c != TRUE';
		query += ' ORDER BY SousMotif__c';

		System.debug('--#### query = ' + query);
		
	}
	
	global Database.QueryLocator start(Database.BatchableContext BC) {
		return Database.getQueryLocator(query);
	}

   	global void execute(Database.BatchableContext BC, List<sObject> scope) {
		Map<String, List<Id>> createdSousMotifsMap = new Map<String, List<Id>>();
		List<Id> caseIds;
        System.debug('--#### Nombre de cases à traiter = ' + scope.size());

		for(Case c : (List<Case>)scope){
			caseIds = createdSousMotifsMap.get(c.SousMotif__c);
			if(caseIds==null){
				caseIds = new List<Id>();
			}
			caseIds.add(c.Id);
			createdSousMotifsMap.put(c.SousMotif__c, caseIds);
		}

		for(String sousMotif : createdSousMotifsMap.keySet()){
			Integer nbCasesTraites = createdSousMotifsMap.get(sousMotif).size();
			if( nbCasesTraites >= seuilAlerte){
				System.debug('--#### Post Chatter pour le sous-motif = ' + sousMotif + ', Nombre de case créés = ' + nbCasesTraites);
				String message = nbCasesTraites + ' demandes avec le sous-motif "' + sousMotif + '" ont été traitées dans l\'heure.';
                ConnectApi.FeedElement feedElement = ConnectApi.ChatterFeeds.postFeedElement(Network.getNetworkId(), groupChatter.Id, 
                	ConnectApi.FeedElementType.FeedItem, message);
			}
		}
		
		List<Case> cases = new List<Case>();
		
		for(List<Id> ids: createdSousMotifsMap.values()) {
			for(Id id: ids) {
				cases.add(new Case(Id = id, TECH_Alert__c = true));
			}
		}
		
		update cases;

	}
	
	global void finish(Database.BatchableContext BC) {
		
	}
	
}