force-app/main/default/objects/Global_Parameters__mdt/Global_Parameters__mdt.object-meta.xml
<CustomObject>
    <description>Paramètres globaux de l&#39;application</description>
    <label>Global Parameters</label>
    <pluralLabel>Global Parameters</pluralLabel>
</CustomObject>

force-app/main/default/objects/Global_Parameters__mdt/fields/Payment_Run_Time__c.field-meta.xml
<CustomField>
    <fullName>Payment_Run_Time__c</fullName>
    <label>Heure d&#39;exécution Payment Run</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Run_Calendar__c/Payment_Run_Calendar__c.object-meta.xml
<CustomObject>
    <label>Payment Run Calendar</label>
    <nameField>
        <label>Payment Run Calendar Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Run Calendar</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Run_Calendar__c/fields/Batch_Numbers__c.field-meta.xml
<CustomField>
    <fullName>Batch_Numbers__c</fullName>
    <label>Numéros de batch</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Batch15</fullName>
            </value>
            <value>
                <fullName>Batch16</fullName>
            </value>
            <value>
                <fullName>Batch17</fullName>
            </value>
            <value>
                <fullName>Batch18</fullName>
            </value>
            <value>
                <fullName>Batch19</fullName>
            </value>
            <value>
                <fullName>Batch20</fullName>
            </value>
            <value>
                <fullName>Batch21</fullName>
            </value>
            <value>
                <fullName>Batch22</fullName>
            </value>
            <value>
                <fullName>Batch23</fullName>
            </value>
            <value>
                <fullName>Batch24</fullName>
            </value>
            <value>
                <fullName>Batch25</fullName>
            </value>
            <value>
                <fullName>Batch26</fullName>
            </value>
            <value>
                <fullName>Batch27</fullName>
            </value>
            <value>
                <fullName>Batch28</fullName>
            </value>
            <value>
                <fullName>Batch29</fullName>
            </value>
            <value>
                <fullName>Batch30</fullName>
            </value>
            <value>
                <fullName>Batch31</fullName>
            </value>
            <value>
                <fullName>Batch32</fullName>
            </value>
            <value>
                <fullName>Batch33</fullName>
            </value>
            <value>
                <fullName>Batch34</fullName>
            </value>
            <value>
                <fullName>Batch35</fullName>
            </value>
            <value>
                <fullName>Batch36</fullName>
            </value>
            <value>
                <fullName>Batch37</fullName>
            </value>
            <value>
                <fullName>Batch38</fullName>
            </value>
            <value>
                <fullName>Batch39</fullName>
            </value>
            <value>
                <fullName>Batch40</fullName>
            </value>
            <value>
                <fullName>Batch41</fullName>
            </value>
            <value>
                <fullName>Batch42</fullName>
            </value>
            <value>
                <fullName>Batch43</fullName>
            </value>
            <value>
                <fullName>Batch44</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Run_Calendar__c/fields/Date_Execution__c.field-meta.xml
<CustomField>
    <fullName>Date_Execution__c</fullName>
    <label>Date d&#39;exécution</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Payment_Run_Calendar__c/fields/Pays__c.field-meta.xml
<CustomField>
    <fullName>Pays__c</fullName>
    <label>Pays</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>FR</fullName>
                <label>France</label>
            </value>
            <value>
                <fullName>BE</fullName>
                <label>Belgique</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Run_Calendar__c/fields/Planned__c.field-meta.xml
<CustomField>
    <fullName>Planned__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Planifié</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/SchedulePaymentRun.cls
// Extension to schedule payment run of the selected objects
public with sharing class SchedulePaymentRun {

    ApexPages.StandardSetController setCon;
    public String error { get; set; }
    public PageReference originalUrl { get; set; }

    public SchedulePaymentRun(ApexPages.StandardSetController controller) {
        setCon = controller;
    }

    public String getMySelectedSize() {
        return setCon.getSelected().size() + '';
    }
    
    public PageReference scheduleRecords(){
        originalUrl = setCon.cancel();
        String paymentTime = '08:00:00';

        List<Payment_Run_Calendar__c> prId = (List<Payment_Run_Calendar__c>) setCon.getSelected();
        List<Payment_Run_Calendar__c> lstpr = [select Pays__c,Date_Execution__c, Batch_Numbers__c from Payment_Run_Calendar__c where id IN :prId AND Planned__c=false];
        List<Payment_Run_Calendar__c> prToUpdate = new List<Payment_Run_Calendar__c>();
        
        list<Global_Parameters__mdt> globalmdt = new list<Global_Parameters__mdt>([SELECT Payment_Run_Time__c FROM Global_Parameters__mdt LIMIT 1]);
        if(globalmdt.size()>0)
        {
            if(globalmdt[0].Payment_Run_Time__c<>null && globalmdt[0].Payment_Run_Time__c<>'')
            paymentTime = globalmdt[0].Payment_Run_Time__c;
        }


        for(Payment_Run_Calendar__c pr : lstpr)
        {
            String[] lstbatch = pr.Batch_Numbers__c.split(';');

            for(String bt : lstbatch)
            {
                schedulePR(pr.Date_Execution__c,paymentTime,bt,pr.Pays__c);
                
            }

            pr.Planned__c = true;
            prToUpdate.add(pr);

        }

        update prToUpdate;

        return originalUrl;
    }


    public static void schedulePR(Date runDate , String paymentTime, String batch, String codePays)
    {
        String endpoint = '/v1/payment-runs';
        String method = 'POST';
        String wsIn = '';
        String wsOut = '';

        // Retrieve Zuora token
        String accessToken = WS001_CallZuora.access_token;

        // Retrieve Entity code
        String zEntityId = WS001_CallZuora.getZuoraEntityId(codePays);

        System.debug('##ECH scheduleRecords schedulePR runDate >> ' + Util.zDate(runDate)+' '+paymentTime);
        // Call WS
        WSZ.PaymentRunIn wsInObj = new WSZ.PaymentRunIn();
        wsInObj.autoApplyCreditMemo = true;
        wsInObj.autoApplyUnappliedPayment = true;
        wsInObj.collectPayment = true;
        wsInObj.consolidatedPayment = false;
        wsInObj.processPaymentWithClosedPM = false;
        wsInObj.batch = batch;
        wsInObj.runDate = Util.zDate(runDate)+' '+paymentTime;
        
        wsIn = (String) JSON.serialize(wsInObj);

        System.debug('##ECH scheduleRecords schedulePR PaymentRunIn >> ' + wsIn);
        wsOut = WS001_CallZuora.sendRequest(accessToken, endpoint, zEntityId, method, wsIn, 'type1', '211.0');

        System.debug('##ECH scheduleRecords schedulePR wsOut >> ' + wsOut);

    }

}