force-app/main/default/objects/Global_Parameters__mdt/Global_Parameters__mdt.object-meta.xml
<CustomObject>
    <description>Paramètres globaux de l&#39;application</description>
    <label>Global Parameters</label>
    <pluralLabel>Global Parameters</pluralLabel>
</CustomObject>

force-app/main/default/objects/Global_Parameters__mdt/fields/Base_Url_All_iFrame_Hercule__c.field-meta.xml
<CustomField>
    <fullName>Base_Url_All_iFrame_Hercule__c</fullName>
    <label>Base Url All iFrame Hercule</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Global_Parameters__mdt/fields/Base_Url_iFrame_VLO__c.field-meta.xml
<CustomField>
    <fullName>Base_Url_iFrame_VLO__c</fullName>
    <label>Base Url iFrame VLO</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Global_Parameters__mdt/fields/Deployment_Level__c.field-meta.xml
<CustomField>
    <fullName>Deployment_Level__c</fullName>
    <label>Deployment Level</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SATGE-PILOTE</fullName>
                <default>true</default>
                <label>SATGE-PILOTE</label>
            </value>
            <value>
                <fullName>SATGE-LOT1</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Global_Parameters__mdt/fields/Email_Compte_Inconnu__c.field-meta.xml
<CustomField>
    <fullName>Email_Compte_Inconnu__c</fullName>
    <label>Email Compte Inconnu</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Global_Parameters__mdt/fields/EP_RCU_Account_Validation__c.field-meta.xml
<CustomField>
    <fullName>EP_RCU_Account_Validation__c</fullName>
    <label>EndPoint RCU / Account Validation</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Global_Parameters__mdt/fields/Nom_Groupe_Chatter__c.field-meta.xml
<CustomField>
    <fullName>Nom_Groupe_Chatter__c</fullName>
    <label>Nom Groupe Chatter</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Global_Parameters__mdt/fields/Queues_Belges__c.field-meta.xml
<CustomField>
    <fullName>Queues_Belges__c</fullName>
    <description>Nom des queues flammandes prises en compte dans le calcul des primes (séparés par des retour à la ligne).</description>
    <label>Queues Belges</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Global_Parameters__mdt/fields/Queues_Fran_aises__c.field-meta.xml
<CustomField>
    <fullName>Queues_Fran_aises__c</fullName>
    <description>Nom des queues francophones à prendre en compte dans le calcul des primes (séparés par des retours à la ligne).</description>
    <label>Queues Françaises</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Global_Parameters__mdt/fields/Seuil_Alerte_Par_Heure__c.field-meta.xml
<CustomField>
    <fullName>Seuil_Alerte_Par_Heure__c</fullName>
    <label>Seuil Alerte Par Heure</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Global_Parameters__mdt/fields/Sous_Motifs__c.field-meta.xml
<CustomField>
    <fullName>Sous_Motifs__c</fullName>
    <label>Sous-Motifs</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/UGC_Generic_Param__mdt/UGC_Generic_Param__mdt.object-meta.xml
<CustomObject>
    <label>UGC Generic Param</label>
    <pluralLabel>UGC Generic Params</pluralLabel>
</CustomObject>

force-app/main/default/objects/UGC_Generic_Param__mdt/fields/Entite__c.field-meta.xml
<CustomField>
    <fullName>Entite__c</fullName>
    <label>Entite</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>France</fullName>
                <default>true</default>
                <label>France</label>
            </value>
            <value>
                <fullName>Belgique</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/UGC_Generic_Param__mdt/fields/ParamName__c.field-meta.xml
<CustomField>
    <fullName>ParamName__c</fullName>
    <label>ParamName</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UGC_Generic_Param__mdt/fields/ParamValue__c.field-meta.xml
<CustomField>
    <fullName>ParamValue__c</fullName>
    <label>ParamValue</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Utils.cls
public without sharing class Utils {
	
	private static RecordType caseRecordType;
    private static RecordType accRecordType;
    private static Contact contactInconnu;
    
    public static Global_Parameters__mdt ugcGlobalParameters;
	// public static UGC_Generic_Param__mdt ugcGenericParams;
    
	public static Global_Parameters__mdt getGlobalParameters(String developerName){

        if(ugcGlobalParameters==null){
            ugcGlobalParameters = [SELECT Id, Seuil_Alerte_Par_Heure__c, 
                                          Nom_Groupe_Chatter__c, 
                                          Sous_Motifs__c, 
                                          EP_RCU_Account_Validation__c,
                                          Base_Url_All_iFrame_Hercule__c,
                                   	      Base_Url_iFrame_VLO__c,
                                   		  Deployment_Level__c,
                                   		  Email_Compte_Inconnu__c,
                                   		  Queues_Fran_aises__c,
                                   		  Queues_Belges__c
                                     FROM Global_Parameters__mdt
                                    WHERE DeveloperName = :developerName].get(0);
        }
		return ugcGlobalParameters;

	}
	
	public static RecordType getNouvelleDemandeClientCaseRecordType() {
		// RecordType d'un Case
		if(caseRecordType == null) {
			caseRecordType = [select id from RecordType where  IsActive = true and SobjectType ='case' and name ='Nouvelle Demande Client' ] ;
		} 
		return caseRecordType;
	}
	
	public static RecordType getComptePersonelAccountRecordType() {
		// RecordType d'un compte 
		if(accRecordType == null) {
	        accRecordType = [select id from RecordType where  IsActive =true and SobjectType ='account' and name ='Compte personnel' ] ;
		}
		return accRecordType;        
	}
	
	public static Contact getContactInconnu() {
		if(contactInconnu == null) {
			Global_Parameters__mdt param = Utils.getGlobalParameters('UGC_One_Parameters');
			system.debug('## Utils ## email inconnu ' + param.Email_Compte_Inconnu__c );
			contactInconnu = [SELECT Id, AccountId FROM Contact WHERE email = :param.Email_Compte_Inconnu__c ];
		}
		
		return contactInconnu;
	}
	
	public static void createContactInconnu() {
		Global_Parameters__mdt param = Utils.getGlobalParameters('UGC_One_Parameters');
		Account accountInconnu = new Account(LastName='inconnu', FirstName= 'client', PersonEmail= param.Email_Compte_Inconnu__c);
    	insert accountInconnu; 
	}
	
	public static List<String> getQueueNames(String pays) {
		Global_Parameters__mdt param = Utils.getGlobalParameters('UGC_One_Parameters');
    	String[] names;
    	if(pays == 'France') {
    		names = param.Queues_Fran_aises__c.split('\r\n');
    	} else {
    		names = param.Queues_Belges__c.split('\r\n');
    	}		
    	return names;
	}

	Public static UGC_Generic_Param__mdt getUgcGenericParam(String paramName, String entite){


		entite = (entite == null) ? 'N/A' : entite;

		List<UGC_Generic_Param__mdt> ugcGenericParams = [SELECT DeveloperName,Entite__c,ParamName__c,ParamValue__c FROM UGC_Generic_Param__mdt WHERE ParamName__c = :paramName and Entite__c = :entite LIMIT 1];
		UGC_Generic_Param__mdt ugcGenericParam = (ugcGenericParams.size() == 1) ? ugcGenericParams.get(0) : null;
		return ugcGenericParam;
	}

}