force-app/main/default/objects/Account/fields/AdressePostale__c.field-meta.xml
<CustomField>
    <fullName>AdressePostale__c</fullName>
    <description>Champ qui concatène l&#39;adresse postale pour l&#39;afficher dans le bandeau</description>
    <formula>NoVoie__c + &quot; &quot;+ TEXT(TypeVoie__c) + &quot; &quot;+  NomVoie__c + BR() +  Ville__r.Name  + &quot; &quot; + CodePostal__c + BR()+  TEXT(Pays__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Adresse Postale</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/CodePays__c.field-meta.xml
<CustomField>
    <fullName>CodePays__c</fullName>
    <label>Code Pays</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Langue__c.field-meta.xml
<CustomField>
    <fullName>Langue__c</fullName>
    <label>Langue Client</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>FR</fullName>
            </value>
            <value>
                <fullName>NL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/NPAIEMAIL__c.field-meta.xml
<CustomField>
    <fullName>NPAIEMAIL__c</fullName>
    <defaultValue>false</defaultValue>
    <label>NPAI_EMAIL</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/PNDADRESSE__c.field-meta.xml
<CustomField>
    <fullName>PNDADRESSE__c</fullName>
    <defaultValue>false</defaultValue>
    <label>PND_ADRESSE</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/ProduitUGC__c.field-meta.xml
<CustomField>
    <fullName>ProduitUGC__c</fullName>
    <defaultValue>&quot;français&quot;</defaultValue>
    <label>Pays de résidence</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>français</fullName>
                <default>true</default>
                <label>français</label>
            </value>
            <value>
                <fullName>belge</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/AdresseEmail__c.field-meta.xml
<CustomField>
    <fullName>AdresseEmail__c</fullName>
    <description>Champ qui copie la valeur renseigné dans le champ &quot;Email&quot; et &quot;Email complémentaire&quot; sur le compte</description>
    <formula>Contact.Email + BR() +  Account.CliEmailComplementaire__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Adresse Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/AdressePostale__c.field-meta.xml
<CustomField>
    <fullName>AdressePostale__c</fullName>
    <description>Ce champ copie l&#39;adresse postale renseignée sur le compte</description>
    <formula>Account.AdressePostale__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Adresse postale</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/AideReponseClient__c.field-meta.xml
<CustomField>
    <fullName>AideReponseClient__c</fullName>
    <defaultValue>&quot;Veuillez qualifier le ticket&quot;</defaultValue>
    <description>Champ qui sera alimenté automatiquement qu&#39;un statut (Famille, motif, sous motif) est sélectionné</description>
    <label>Aide à la réponse client</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/TECH_GeneratedDoc__c.field-meta.xml
<CustomField>
    <fullName>TECH_GeneratedDoc__c</fullName>
    <defaultValue>false</defaultValue>
    <label>TECH_GeneratedDoc</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/TECH_NBPrintFileTotal__c.field-meta.xml
<CustomField>
    <fullName>TECH_NBPrintFileTotal__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Dénombre le nombre totate de Fil d&#39;impression attendu pour le Case en cours (carte prise en compte)</description>
    <label>TECH_NBPrintFileTotal</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case/fields/TECHIdStatut__c.field-meta.xml
<CustomField>
    <fullName>TECHIdStatut__c</fullName>
    <description>Ce champ calcule d&#39;ID du statut en associant les numéros associé à la famille, motif et sous motif</description>
    <formula>TRIM(LEFT(TEXT(Famille__c),FIND(&quot;-&quot;, TEXT(Famille__c))-1)) &amp;

TRIM(LEFT(TEXT(Motif__c),FIND(&quot;-&quot;, TEXT(Motif__c))-1))&amp;

TRIM(LEFT(TEXT( SousMotif__c ),FIND(&quot;-&quot;, TEXT(SousMotif__c))-1))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ID Statut</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Migration.recordType-meta.xml
<RecordType>
    <fullName>Migration</fullName>
    <active>true</active>
    <businessProcess>Demandes clients</businessProcess>
    <label>Migration</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/Souscription.recordType-meta.xml
<RecordType>
    <fullName>Souscription</fullName>
    <active>true</active>
    <businessProcess>Demandes clients</businessProcess>
    <label>Souscription</label>
</RecordType>

force-app/main/default/objects/Contacts__c/Contacts__c.object-meta.xml
<CustomObject>
    <label>Contacts</label>
    <nameField>
        <label>ID du statut</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contacts__c/fields/AvecCarte__c.field-meta.xml
<CustomField>
    <fullName>AvecCarte__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Avec carte</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contacts__c/fields/FamilleMatrice__c.field-meta.xml
<CustomField>
    <fullName>FamilleMatrice__c</fullName>
    <label>Famille</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0- Souscription</fullName>
            </value>
            <value>
                <fullName>1- Vie de l&#39;abonnement</fullName>
            </value>
            <value>
                <fullName>2 - Club UGC / fidélité</fullName>
            </value>
            <value>
                <fullName>3 - Autres Produits</fullName>
            </value>
            <value>
                <fullName>4 - Réservation</fullName>
            </value>
            <value>
                <fullName>5 - Compte client</fullName>
            </value>
            <value>
                <fullName>6 - Prospection</fullName>
            </value>
            <value>
                <fullName>7 - Finance</fullName>
            </value>
            <value>
                <fullName>8 - Cinéma</fullName>
            </value>
            <value>
                <fullName>9 - Divers</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contacts__c/fields/MotifMatrice__c.field-meta.xml
<CustomField>
    <fullName>MotifMatrice__c</fullName>
    <label>Motif</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>FamilleMatrice__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>01 - Info process abo</fullName>
            </value>
            <value>
                <fullName>02 - Erreur prise abo</fullName>
            </value>
            <value>
                <fullName>03 - Click and collect</fullName>
            </value>
            <value>
                <fullName>04 - Démat</fullName>
            </value>
            <value>
                <fullName>05 - B2B</fullName>
            </value>
            <value>
                <fullName>06 - VPC</fullName>
            </value>
            <value>
                <fullName>07- Création Abo</fullName>
            </value>
            <value>
                <fullName>01 - Réception carte</fullName>
            </value>
            <value>
                <fullName>02 - Réédition payante</fullName>
            </value>
            <value>
                <fullName>03 - Réédition gratuite</fullName>
            </value>
            <value>
                <fullName>04 - Désabonnement</fullName>
            </value>
            <value>
                <fullName>05 - Résiliation</fullName>
            </value>
            <value>
                <fullName>06 - Migration UI 1/2/3</fullName>
            </value>
            <value>
                <fullName>07 - Réabonnement</fullName>
            </value>
            <value>
                <fullName>08 - Rétention</fullName>
            </value>
            <value>
                <fullName>09 - Retour Carte</fullName>
            </value>
            <value>
                <fullName>10 - Rétractation</fullName>
            </value>
            <value>
                <fullName>11 - Avertissement</fullName>
            </value>
            <value>
                <fullName>12 - Annulation Migration</fullName>
            </value>
            <value>
                <fullName>13 - Annulation Contrat</fullName>
            </value>
            <value>
                <fullName>99 - Autre</fullName>
            </value>
            <value>
                <fullName>01 - Inscription</fullName>
            </value>
            <value>
                <fullName>02 - Solde de points</fullName>
            </value>
            <value>
                <fullName>03 - Echange de points</fullName>
            </value>
            <value>
                <fullName>04 - Fonctionnement Club</fullName>
            </value>
            <value>
                <fullName>01 - Offres UGC</fullName>
            </value>
            <value>
                <fullName>02 - Formules UGC+</fullName>
            </value>
            <value>
                <fullName>03 - Solo</fullName>
            </value>
            <value>
                <fullName>04 - Blue</fullName>
            </value>
            <value>
                <fullName>05 - VLO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contacts__c/fields/Nom_du_mod_le_courrier_UU_fran_ais_pdf__c.field-meta.xml
<CustomField>
    <fullName>Nom_du_mod_le_courrier_UU_fran_ais_pdf__c</fullName>
    <label>Nom du modèle courrier UU français(pdf)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contacts__c/fields/Nom_du_mod_le_courrier_UU_n_erlandais__c.field-meta.xml
<CustomField>
    <fullName>Nom_du_mod_le_courrier_UU_n_erlandais__c</fullName>
    <label>Nom du modèle courrier UU néerlandais</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contacts__c/fields/Nom_du_mod_le_email_UU_fran_ais_HTML__c.field-meta.xml
<CustomField>
    <fullName>Nom_du_mod_le_email_UU_fran_ais_HTML__c</fullName>
    <label>Nom du modèle email UU français(HTML)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contacts__c/fields/Nom_du_mod_le_email_UU_n_erlandais__c.field-meta.xml
<CustomField>
    <fullName>Nom_du_mod_le_email_UU_n_erlandais__c</fullName>
    <label>Nom du modèle email UU néerlandais</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contacts__c/fields/NomModeleCourrierEmail__c.field-meta.xml
<CustomField>
    <fullName>NomModeleCourrierEmail__c</fullName>
    <inlineHelpText>Renseigner le nom du modèle de courrier SDOCS en format PDF</inlineHelpText>
    <label>Nom du modèle Courrier (PDF)</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contacts__c/fields/NomModeleEmailHTML__c.field-meta.xml
<CustomField>
    <fullName>NomModeleEmailHTML__c</fullName>
    <inlineHelpText>Renseigner le nom du modèle d&#39;email SDOCS en format HTML</inlineHelpText>
    <label>Nom du modèle Email (HTML)</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contacts__c/fields/Reponse__c.field-meta.xml
<CustomField>
    <fullName>Reponse__c</fullName>
    <description>Coché lorsque le statut génère l&#39;envoi automatisé d&#39;un email/courrier</description>
    <label>Réponse</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Manuelle</fullName>
            </value>
            <value>
                <fullName>Semi-automatique</fullName>
            </value>
            <value>
                <fullName>Automatique</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contacts__c/fields/SousMotifMatrice__c.field-meta.xml
<CustomField>
    <fullName>SousMotifMatrice__c</fullName>
    <label>Sous-Motif</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>MotifMatrice__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>I- Info</fullName>
            </value>
            <value>
                <fullName>R- Récla</fullName>
            </value>
            <value>
                <fullName>A- Action</fullName>
            </value>
            <value>
                <fullName>Click to Call Info</fullName>
            </value>
            <value>
                <fullName>Click to Call Recla</fullName>
            </value>
            <value>
                <fullName>AD- Action DRC</fullName>
            </value>
            <value>
                <fullName>AS- Action Stand</fullName>
            </value>
            <value>
                <fullName>AH- Action Selfcare</fullName>
            </value>
            <value>
                <fullName>R1- 1er rejet</fullName>
            </value>
            <value>
                <fullName>R2- 2nd rejet</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SM_SDoc.cls
public class SM_SDoc {

    public static String TECHIdStatut_007AD = '007AD';  //0- Souscription   -> 07- Creation Abonnement      -> AD- Action DRC
    public static String TECHIdStatut_005AD = '005AD';  //0- Souscription   -> 05- B2B                      -> AD- Action DRC
    public static String TECHIdStatut_005AH = '005AH';  //0- Souscription   -> 05- B2B                      -> AH- Action Selfcare
    public static String TECHIdStatut_007AH = '007AH';  //0- Souscription   -> 07- Creation Abonnement      -> AH- Action Selfcare
    public static String TECHIdStatut_007AS = '007AS';  //0- Souscription   -> 07- Creation Abonnement      -> AS- Action Stand
    public static String TECHIdStatut_106A  = '106A';   //1- Vie de l'abo   -> 06- Migration                -> A- Action
    public static String TECHIdStatut_106AD = '106AD';  //1- Vie de l'abo   -> 06- Migration                -> AD- Action DRC
    public static String TECHIdStatut_106AS = '106AS';  //1- Vie de l'abo   -> 06- Migration                -> AS- Action Stand
    public static String TECHIdStatut_106AH = '106AH';  //1- Vie de l'abo   -> 06- Migration                -> AH- Action Selfcare 
    
    
    public static void makeSdocJobs(List<Case> cases) {
        Set<String> statutCaseSet = new Set<String>();
        Set<String> accountIdSet = new Set<String>();
        Map<ID, Case> mapCases = new Map<ID, Case>();
        
        // recuperation de la liste des "id statut" de case
        for (Case c : cases) {
            mapCases.put(c.Id, c);
            
            if (c.TECHIdStatut__c != null) {
                statutCaseSet.add(c.TECHIdStatut__c);
            }
            if(c.AccountId != null){
                accountIdSet.add(c.AccountId);
            }
        }
        
        system.debug('#### accountIdSet SIZE = ' + accountIdSet.size());
        
        // recuperation des contacts qui possèdent les "id statut"  presents dans la list statutCaseSet 
        // ( contact qui ont le meme statut id que case)
        List<Contacts__c> contactsLst = [SELECT Id, name, FamilleMatrice__c, MotifMatrice__c, SousMotifMatrice__c, 
                                         Reponse__c, 
                                         NomModeleCourrierEmail__c, NomModeleEmailHTML__c,
                                         Nom_du_mod_le_courrier_UU_fran_ais_pdf__c, Nom_du_mod_le_email_UU_fran_ais_HTML__c,
                                         Nom_du_mod_le_courrier_UU_n_erlandais__c, Nom_du_mod_le_email_UU_n_erlandais__c, AvecCarte__c
                                         FROM Contacts__c
                                         WHERE Name IN :statutCaseSet];
        
        
        //recupération des nom des template utilises dans les contacts
        Set<String> nomModelSdocSet = New Set<String>();
        for(Contacts__c c : contactsLst){
            
            if(String.isNotBlank(c.NomModeleCourrierEmail__c))
                nomModelSdocSet.addAll(c.NomModeleCourrierEmail__c.split(';'));
            if(String.isNotBlank(c.NomModeleEmailHTML__c))
                nomModelSdocSet.addAll(c.NomModeleEmailHTML__c.split(';'));
            if(String.isNotBlank(c.Nom_du_mod_le_courrier_UU_fran_ais_pdf__c))
                nomModelSdocSet.addAll(c.Nom_du_mod_le_courrier_UU_fran_ais_pdf__c.split(';'));
            if(String.isNotBlank(c.Nom_du_mod_le_email_UU_fran_ais_HTML__c))    
                nomModelSdocSet.addAll(c.Nom_du_mod_le_email_UU_fran_ais_HTML__c.split(';'));
            if(String.isNotBlank(c.Nom_du_mod_le_courrier_UU_n_erlandais__c))    
                nomModelSdocSet.addAll(c.Nom_du_mod_le_courrier_UU_n_erlandais__c.split(';'));
            if(String.isNotBlank(c.Nom_du_mod_le_email_UU_n_erlandais__c))   
                nomModelSdocSet.addAll(c.Nom_du_mod_le_email_UU_n_erlandais__c.split(';'));
        }
        system.debug('--#### nomModelSdocSet SIZE = ' + nomModelSdocSet.size());
        system.debug('--#### nomModelSdocSet = ' + nomModelSdocSet);
        
        //recuperation des ID des templates
        List<SDOC__SDTemplate__c> nomModelSdocList = [SELECT Id, Name 
                                                      FROM SDOC__SDTemplate__c
                                                      WHERE Name IN :nomModelSdocSet];
        
        system.debug('--#### nomModelSdocList SIZE = ' + nomModelSdocList.size());
        
        Map<String, Id> mapNomSdocsIdSdocs = new Map<String, Id>();
        for(SDOC__SDTemplate__c sdocTemplate : nomModelSdocList){
            system.debug('--#### SDOC NAME AND SDOC ID SIZE = ' + sdocTemplate.Name + ' ' + sdocTemplate.Id);
            mapNomSdocsIdSdocs.put(sdocTemplate.Name, sdocTemplate.Id);
        }
        
        // Préparation d'une Map<idStatut, Contacts__c>
        Map<String, Contacts__c> mapIdStatutContacts = new Map<String, Contacts__c>();
        for(Contacts__c c : contactsLst){
            mapIdStatutContacts.put(c.Name, c);
        }
        
        
        List< SDOC__SDJob__c> jobList = new List< SDOC__SDJob__c> ();
        List<Task> taskToInsert = new List<Task> ();
        
        List<Case> casesToUpdate = [SELECT Id, TECHIdStatut__c, Account.Id, Account.NPAIEMAIL__c, Account.PNDADRESSE__c, 
                                    AideReponseClient__c, AdresseEmail__c, AdressePostale__c , OwnerId,
                                    Account.ProduitUGC__c, Account.CodePays__c, Account.Langue__c, Description, Subject, ContactId
                                    FROM Case WHERE Id IN :mapCases.keySet()];
        
        system.debug('##ECH casesToUpdate :'+casesToUpdate);
        // maj de case a partir de la Map 
        for (Case c : casesToUpdate) {
            
            
            if (c.TECHIdStatut__c != null) {
                system.debug('##ECH c.TECHIdStatut__c 0 :'+c.TECHIdStatut__c);
                Contacts__c contacts = mapIdStatutContacts.get(c.TECHIdStatut__c);
                if(contacts!=null){
                    system.debug('##ECH contacts :'+contacts);
                    system.debug('--#### CASE ACCOUNT = ' + c.Account.Id);
                    Account acc = c.Account;
                    
                    String courrierTemplateName = '';
                    String emailTemplateName = '';
                    
                    system.debug('##ECH acc.CodePays__c :'+acc.CodePays__c);
                    if(acc.CodePays__c == '033'){
                        courrierTemplateName = contacts.NomModeleCourrierEmail__c;
                        emailTemplateName    = contacts.NomModeleEmailHTML__c;
                    } 
                    else if(acc.CodePays__c == '032' && acc.Langue__c == 'FR'){
                        courrierTemplateName = contacts.Nom_du_mod_le_courrier_UU_fran_ais_pdf__c;
                        emailTemplateName    = contacts.Nom_du_mod_le_email_UU_fran_ais_HTML__c;
                    }
                    else if(acc.CodePays__c == '032' && acc.Langue__c == 'NL'){
                        courrierTemplateName = contacts.Nom_du_mod_le_courrier_UU_n_erlandais__c;
                        emailTemplateName    = contacts.Nom_du_mod_le_email_UU_n_erlandais__c;
                    } else {
                        system.debug('##MNE Langue du template impossible a definir >> acc.CodePays__c = '+acc.CodePays__c+' et acc.Langue__c = '+ acc.Langue__c);
                        continue;
                    }
                    
                    system.debug('##ECH courrierTemplateName 0 :'+courrierTemplateName);
                    system.debug('##ECH emailTemplateName 0 :'+emailTemplateName);
                    
                    //BEGIN Compteur Nb Doc
                    Integer nbCarte = contacts.AvecCarte__c ? 1 : 0;
                    Integer nbCourrier = 0;
                    Integer nbCourrierAttachement = 0;
                    
                    system.debug('##MNE AP02_Case makeSdocJobs nbCarte >> '+ nbCarte);
                    system.debug('##MNE AP02_Case makeSdocJobs courrierTemplateName >> '+ courrierTemplateName);
                    
                    if(String.isNotBlank(courrierTemplateName)){
                        list<String> listCourrierTemplateNameTMP = courrierTemplateName.split(';');
                        nbCourrier = listCourrierTemplateNameTMP.size();
                    }
                    
                    system.debug('##MNE AP02_Case makeSdocJobs nbCourrier >> '+ nbCourrier);
                    
                    system.debug('##MNE AP02_Case makeSdocJobs emailTemplateName >> '+ emailTemplateName);
                    
                    if(String.isNotBlank(emailTemplateName)){
                        list<String> listEmailTemplateNameTMP = emailTemplateName.split(';');
                        if(listEmailTemplateNameTMP.size() > 1){
                            Integer cpt = 0;
                            for(String s: listEmailTemplateNameTMP){
                                if(cpt == 0){
                                    cpt++;
                                    continue;
                                } else if (!s.trim().startsWithIgnoreCase('UGC')){
                                    nbCourrierAttachement++;
                                }
                                cpt++;
                            }
                        }
                    }
                    
                    system.debug('##MNE AP02_Case makeSdocJobs nbCourrierAttachement >> '+ nbCourrierAttachement);
                    
                    Integer cptTotal = nbCarte + nbCourrier + nbCourrierAttachement;
                    c.TECH_NBPrintFileTotal__c = cptTotal;
                    system.debug('##MNE AP02_Case makeSdocJobs TECH_NBPrintFileTotal__c >> '+ c.TECH_NBPrintFileTotal__c);
                    //END Compteur Nb Doc
                                      
                    Boolean isHTMLTemplate = isHTMLTemplate(c, acc);
                    Boolean isPDFTemplate = isPDFTemplate(c, acc);
                    
                    if(contacts.Reponse__c == 'Automatique') {
                        system.debug('##ECH contacts.Reponse__c:'+contacts.Reponse__c);
                        
                        system.debug('--#### IN AUTOMATIQUE');
                        if(isHTMLTemplate == null && isPDFTemplate==null) {
                            system.debug('##ECH isHTMLTemplate :'+isHTMLTemplate);
                            system.debug('##ECH isPDFTemplate :'+isPDFTemplate);
                            c.AideReponseClient__c = getHelpMsgChooseTemplate(c, acc);
                        }
                        
                        else if(c.TECHIdStatut__c == TECHIdStatut_007AD || c.TECHIdStatut__c == TECHIdStatut_005AD || c.TECHIdStatut__c == TECHIdStatut_007AS){
                            system.debug('##ECH c.TECHIdStatut__c 1:'+c.TECHIdStatut__c );
                            if(String.isNotBlank(courrierTemplateName)){
                                system.debug('##ECH courrierTemplateName1 :'+courrierTemplateName );
                                list<String> listCourrierTemplateName = courrierTemplateName.split(';');
                                for(String courrierTemplateNameTMP : listCourrierTemplateName){
                                    courrierTemplateNameTMP = courrierTemplateNameTMP.trim();
                                    if(mapNomSdocsIdSdocs.containsKey(courrierTemplateNameTMP)){
                                        SDOC__SDJob__c job = new SDOC__SDJob__c(
                                            SDOC__Start__c=true, 
                                            SDOC__Oid__c=c.Id, 
                                            SDOC__ObjApiName__c='Case', 
                                            SDOC__SendEmail__c='0',
                                            SDOC__Doclist__c= mapNomSdocsIdSdocs.get(courrierTemplateNameTMP));
                                        jobList.add(job);
                                        
                                        taskToInsert.add(createTask('courrier', c));
                                        c.AideReponseClient__c = 'Un courrier a été généré.';
                                        //ECH Flag pour identifier une demande traitée
                                        c.TECH_GeneratedDoc__c = true;
                                    }
                                }
                            }
                        }
                        
                        else if(c.TECHIdStatut__c == TECHIdStatut_005AH || c.TECHIdStatut__c == TECHIdStatut_007AH || c.TECHIdStatut__c == TECHIdStatut_106A || c.TECHIdStatut__c == TECHIdStatut_106AD || c.TECHIdStatut__c == TECHIdStatut_106AS || c.TECHIdStatut__c == TECHIdStatut_106AH ){
                            system.debug('##ECH c.TECHIdStatut__c 2 :'+c.TECHIdStatut__c );
                            if(String.isNotBlank(courrierTemplateName)){
                                system.debug('##ECH courrierTemplateName2 :'+courrierTemplateName );
                                list<String> listCourrierTemplateName = courrierTemplateName.split(';');
                                for(String courrierTemplateNameTMP : listCourrierTemplateName){
                                    courrierTemplateNameTMP = courrierTemplateNameTMP.trim();
                                    if(mapNomSdocsIdSdocs.containsKey(courrierTemplateNameTMP)){
                                        SDOC__SDJob__c job = new SDOC__SDJob__c(
                                            SDOC__Start__c=true, 
                                            SDOC__Oid__c=c.Id, 
                                            SDOC__ObjApiName__c='Case', 
                                            SDOC__SendEmail__c='0',
                                            SDOC__Doclist__c= mapNomSdocsIdSdocs.get(courrierTemplateNameTMP));
                                        jobList.add(job);
                                        
                                        taskToInsert.add(createTask('courrier', c));
                                        c.AideReponseClient__c = 'Un courrier a été généré.';
                                        //ECH Flag pour identifier une demande traitée
                                        c.TECH_GeneratedDoc__c = true;
                                    }
                                }
                                
                            }
                            if(String.isNotBlank(emailTemplateName)){
                                system.debug('##ECH emailTemplateName 1 :'+emailTemplateName );
                                
                                list<String> listEmailTemplateName = emailTemplateName.split(';');
                                system.debug('##ECH listEmailTemplateName  :'+listEmailTemplateName );
                                
                                list<String> listEmailTemplateId = new list<String>();
                                
                                for(String s: listEmailTemplateName){
                                    if(mapNomSdocsIdSdocs.containsKey(s.trim())){
                                        listEmailTemplateId.add(mapNomSdocsIdSdocs.get(s.trim()));
                                    }
                                }
                                system.debug('##ECH listEmailTemplateId  :'+listEmailTemplateId );
                                
                                string listEmailTemplateIdforSDOC = string.join(listEmailTemplateId,',');
                                
                                system.debug('##ECH listEmailTemplateIdforSDOC  :'+listEmailTemplateIdforSDOC );
                                
                                if(String.isNotEmpty(listEmailTemplateIdforSDOC)){
                                    SDOC__SDJob__c job = new SDOC__SDJob__c(
                                        SDOC__Start__c=true, 
                                        SDOC__Oid__c=c.Id, 
                                        SDOC__ObjApiName__c='Case', 
                                        SDOC__SendEmail__c='1',
                                        SDOC__Doclist__c= listEmailTemplateIdforSDOC);
                                    jobList.add(job);
                                    taskToInsert.add(createTask('email', c));
                                    c.AideReponseClient__c = 'Un email a été envoyé au client.';
                                    //ECH Flag pour identifier une demande traitée
                                    c.TECH_GeneratedDoc__c = true;
                                }
                              
                                
                            }
                            
                        }
                        else {
                            if(isHTMLTemplate && String.isNotBlank(emailTemplateName)){
                                
                                system.debug('##ECH emailTemplateName 2 :'+emailTemplateName );
                                list<String> listEmailTemplateName = emailTemplateName.split(';');
                                system.debug('##ECH listEmailTemplateName 2  :'+listEmailTemplateName );
                                
                                list<String> listEmailTemplateId = new list<String>();
                                
                                for(String s: listEmailTemplateName){
                                    if(mapNomSdocsIdSdocs.containsKey(s.trim())){
                                        listEmailTemplateId.add(mapNomSdocsIdSdocs.get(s.trim()));
                                    }
                                }
                                system.debug('##ECH listEmailTemplateId 2  :'+listEmailTemplateId );
                                
                                //listEmailTemplateId.remove(null);
                                
                                string listEmailTemplateIdforSDOC = string.join(listEmailTemplateId,',');
                                
                                system.debug('##ECH listEmailTemplateIdforSDOC 2  :'+listEmailTemplateIdforSDOC );
                                
                                //string emailTemplateNameTMP = string.join(listEmailTemplateName,',');
                                
                                //                                for(String emailTemplateNameTMP : listEmailTemplateName){
                                //                                  emailTemplateNameTMP = emailTemplateNameTMP.trim();
                                if(String.isNotEmpty(listEmailTemplateIdforSDOC)){
                                    SDOC__SDJob__c job = new SDOC__SDJob__c(
                                        SDOC__Start__c=true, 
                                        SDOC__Oid__c=c.Id, 
                                        SDOC__ObjApiName__c='Case', 
                                        SDOC__SendEmail__c='1',
                                        SDOC__Doclist__c= listEmailTemplateIdforSDOC);
                                    jobList.add(job);
                                    taskToInsert.add(createTask('email', c));
                                    c.AideReponseClient__c = 'Un email a été envoyé au client.';
                                    //ECH Flag pour identifier une demande traitée
                                    c.TECH_GeneratedDoc__c = true;
                                }
                                //                              }
                            }
                            
                            if(isPDFTemplate && String.isNotBlank(courrierTemplateName)){
                                system.debug('##ECH courrierTemplateName 3:'+courrierTemplateName);
                                list<String> listCourrierTemplateName = courrierTemplateName.split(';');
                                for(String courrierTemplateNameTMP : listCourrierTemplateName){
                                    courrierTemplateNameTMP = courrierTemplateNameTMP.trim();
                                    if(mapNomSdocsIdSdocs.containsKey(courrierTemplateNameTMP)){
                                        SDOC__SDJob__c job = new SDOC__SDJob__c(
                                            SDOC__Start__c=true, 
                                            SDOC__Oid__c=c.Id, 
                                            SDOC__ObjApiName__c='Case', 
                                            SDOC__SendEmail__c='0',
                                            SDOC__Doclist__c= mapNomSdocsIdSdocs.get(courrierTemplateNameTMP));
                                        jobList.add(job);
                                        
                                        taskToInsert.add(createTask('courrier', c));
                                        c.AideReponseClient__c = 'Un courrier a été généré.';
                                        system.debug('##ECH courrierTemplateName 4:'+courrierTemplateName);
                                        //ECH Flag pour identifier une demande traitée
                                        c.TECH_GeneratedDoc__c = true;   
                                    }
                                }
                            }
                            
                            
                            system.debug('##ECH c.TECHIdStatut__c ELSE :'+c.TECHIdStatut__c );
                            system.debug('##ECH emailTemplateName ELSE:'+emailTemplateName);
                            system.debug('##ECH courrierTemplateName ELSE:'+courrierTemplateName);
                            system.debug('##ECH isHTMLTemplate ELSE :'+isHTMLTemplate);
                            system.debug('##ECH isPDFTemplate ELSE :'+isPDFTemplate);                 
                        }              
                    } 
                    else if(contacts.Reponse__c == 'Semi-automatique'){
                        system.debug('--#### IN SEMI AUTOMATIQUE');
                    } 
                    else {  // cas manuel
                        c.AideReponseClient__c = getHelpMsgChooseTemplate(c, acc);
                    }
                }
                else{
                    c.AideReponseClient__c = 'Veuillez qualifier le ticket';        
                }
                
            } else {
                c.AideReponseClient__c = 'Veuillez qualifier le ticket';                    
            }
        }
        insert jobList;   
        if(taskToInsert.size() > 0){
            insert taskToInsert; 
        } 
        
        update casesToUpdate;
        
        system.debug('--#### OUT OF CASE BOUCLE'); 
    }
    
    private static Boolean isHTMLTemplate(Case c, Account account) {
        if(account == null) {
            system.debug('--#### Account null');
            return null;
        }
        
        system.debug('--#### IN NPAIEMAIL__c ' + account.NPAIEMAIL__c);
        
        if(!account.NPAIEMAIL__c && !isEmpty(c.AdresseEmail__c)) {
            system.debug('--#### IN AdresseEmail__c not null ');
            return true;
        } else {
            return false;
        }
        
    }
    
    private static Boolean isPDFTemplate(Case c, Account account) {
        if(account == null) {
            system.debug('--#### Account null');
            return null;
        }
        
        system.debug('--#### IN PNDADRESSE__c ' + account.PNDADRESSE__c);
        if(!account.PNDADRESSE__c && !isEmpty(c.AdressePostale__c) ) {
            system.debug('--#### IN AdresseEmail__c null OR NPAIEMAIL__c = true');
            system.debug('--#### IN AdressePostale__c not null');
            return true;
        }
        else{
            return false;           
        }
        
    }
    
    public static Task createTask(String canal, Case c){
        Task t = new Task();
        t.ActivityDate = Date.Today();
        t.Description = c.Description;
        if(canal == 'courrier'){
            t.Origine__c = 'Courrier sortant';
        } else {
            t.Origine__c = 'Email sortant';
        }
        t.OwnerId = UserInfo.getUserId();
        t.Priority = 'Normale';
        t.Status = 'Achevée';
        t.Subject = c.Subject;
        t.WhatId = c.Id;
        t.WhoId = c.ContactId;

        return t;
    }
    
    private static String getHelpMsgChooseTemplate(Case c, Account account) {
        if(account == null) {
            system.debug('--#### Account null');
            return null;
        }
        system.debug('--#### IN NPAIEMAIL__c ' + account.NPAIEMAIL__c);
        system.debug('--#### IN PNDADRESSE__c ' + account.PNDADRESSE__c);
        if(!account.NPAIEMAIL__c && c.AdresseEmail__c != null && !isEmpty(c.AdresseEmail__c) ) {
            return 'Pour répondre au client, veuillez sélectionner un modèle d\'email.';
        } else if (!account.PNDADRESSE__c && !isEmpty(c.AdressePostale__c) ) {
            return 'Pour répondre au client, veuillez sélectionner un modèle de courrier.';
        } else {
            return 'Il n’est pas possible de contacter le client par email ou courrier.';
        }
    }
    
    private static Boolean isEmpty(String s) {
        return s == null || s.toUpperCase().replace('<BR>', '').trim() == '';
    }
}