force-app/main/default/objects/Account/fields/Attachment_Body_Contrat__c.field-meta.xml
<CustomField>
    <fullName>Attachment_Body_Contrat__c</fullName>
    <label>Attachment Body Contrat</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Account/fields/Attachment_Id_Contrat__c.field-meta.xml
<CustomField>
    <fullName>Attachment_Id_Contrat__c</fullName>
    <label>Attachment Id Contrat</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Attachment_Body_Contrat__c.field-meta.xml
<CustomField>
    <fullName>Attachment_Body_Contrat__c</fullName>
    <label>Attachment Body Contrat</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Case/fields/Attachment_Id_Contrat__c.field-meta.xml
<CustomField>
    <fullName>Attachment_Id_Contrat__c</fullName>
    <label>Attachment Id Contrat</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Subscription__c.field-meta.xml
<CustomField>
    <fullName>Subscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Abonnement</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>$Source.AccountId</field>
            <operation>equals</operation>
            <valueField>Zuora__Subscription__c.Zuora__Account__r.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Zuora__Subscription__c</referenceTo>
    <relationshipLabel>Demandes</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/SubscriptionZName__c.field-meta.xml
<CustomField>
    <fullName>SubscriptionZName__c</fullName>
    <description>Stock le name Zuora de la souscription</description>
    <label>Zuora Subscription Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/File_Impression__c/File_Impression__c.object-meta.xml
<CustomObject>
    <label>File d&#39;impression</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Files d&#39;impression</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/File_Impression__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Files d&#39;impression</relationshipLabel>
    <relationshipName>Files_d_impression</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/File_Impression__c/fields/Attachment_Body__c.field-meta.xml
<CustomField>
    <fullName>Attachment_Body__c</fullName>
    <label>Attachment Body</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/File_Impression__c/fields/Attachment_Id__c.field-meta.xml
<CustomField>
    <fullName>Attachment_Id__c</fullName>
    <externalId>true</externalId>
    <label>Attachment Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/File_Impression__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Demande</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Files d&#39;impression</relationshipLabel>
    <relationshipName>Files_d_impression</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/File_Impression__c/fields/IsCarte__c.field-meta.xml
<CustomField>
    <fullName>IsCarte__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Carte</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/File_Impression__c/fields/SDoc__c.field-meta.xml
<CustomField>
    <fullName>SDoc__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SDoc</label>
    <referenceTo>SDOC__SDoc__c</referenceTo>
    <relationshipLabel>Files d&#39;impression</relationshipLabel>
    <relationshipName>Files_d_impression</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/File_Impression__c/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Imprime</fullName>
                <label>Imprimé</label>
            </value>
            <value>
                <fullName>En cours d_impression</fullName>
                <label>En cours d&#39;impression</label>
            </value>
            <value>
                <fullName>A Imprimer</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/File_Impression__c/fields/Subscription__c.field-meta.xml
<CustomField>
    <fullName>Subscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Abonnement</label>
    <referenceTo>Zuora__Subscription__c</referenceTo>
    <relationshipLabel>Files d&#39;impression</relationshipLabel>
    <relationshipName>Files_d_impression</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/File_Impression__c/fields/SubscriptionZName__c.field-meta.xml
<CustomField>
    <fullName>SubscriptionZName__c</fullName>
    <externalId>true</externalId>
    <label>Zuora Subscription Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AP03_Attachment.cls
public class AP03_Attachment {
    
    public static void processTriggerAfterInsert (List<Attachment> listAttachment)  { 
        createFileImpressionRecords (listAttachment);
    }
    
    public static void createFileImpressionRecords (List<Attachment> listAttachment)  { 
        system.debug('##MNE AP03_Attachment createFileImpressionRecords listAttachment >> '+listAttachment);
        
        map<Id, Attachment> mapAttachmentBySDocId   = new map<Id, Attachment>();
        
        if(listAttachment == null || listAttachment.size() == 0){
            return;
        }
        
        system.debug('##MNE AP03_Attachment createFileImpressionRecords hello1');

        for(Attachment att : listAttachment){
            if(String.isNotBlank(att.Description)){
                mapAttachmentBySDocId.put(Id.valueOf(att.Description), att);
            }
        }
        
        system.debug('##MNE AP03_Attachment createFileImpressionRecords mapAttachmentBySDocId >> '+mapAttachmentBySDocId);

        List<SDOC__SDoc__c> listSDoc = getSDocNotHTMLBySDocId(mapAttachmentBySDocId.keySet());
        
        system.debug('##MNE AP03_Attachment listSDoc >> '+ listSDoc);
        if(listSDoc == null || listSDoc.size() == 0){
            system.debug('##MNE AP03_Attachment createFileImpressionRecords hello2');
            return;
        }
        
        set<Id> setCaseId = new set<Id>();
        for(SDOC__SDoc__c sDoc : listSDoc){
            setCaseId.add(sDoc.SDOC__ObjectID18__c);
        }

        map<Id, Case> mapCaseById = new map<Id, Case>([SELECT Id, AccountId, Subscription__c, SubscriptionZName__c FROM Case WHERE Id IN : setCaseId]);
        system.debug('##MNE AP03_Attachment createFileImpressionRecords mapCaseById >> '+mapCaseById);

        list<File_Impression__c> listFileImpressionToIsert = new list<File_Impression__c>();
        map<Id, Account> mapAccountByIdToUpdate = new map<Id, Account>();
        map<Id, Case> mapCaseByIdToUpdate = new map<Id, Case>();
        
        for(SDOC__SDoc__c sDoc : listSDoc){
            system.debug('##ECH AP03_Attachment sDoc.SDOC__Attachment_Name__c:'+sDoc.SDOC__Attachment_Name__c);
            if(sDoc.SDOC__Attachment_Name__c.left(3)!='UGC') {
                system.debug('##ECH AP03_Attachment createFileImpressionRecords hello3');
                system.debug('##MNE AP03_Attachment createFileImpressionRecords hello3');
                File_Impression__c fi = new File_Impression__c();
                Case caseTMP = mapCaseById.get(sDoc.SDOC__ObjectID18__c);
                fi.Name                 = sDoc.SDOC__Attachment_Name__c;
                fi.Subscription__c      = caseTMP.Subscription__c;
                fi.SubscriptionZName__c   = caseTMP.SubscriptionZName__c;
                fi.Account__c           = caseTMP.AccountId;
                fi.Attachment_Id__c     = mapAttachmentBySDocId.get(sDoc.Id).Id;
                fi.Case__c              = caseTMP.Id;
                fi.SDoc__c              = sDoc.Id;
                fi.IsCarte__c           = false;
                fi.Statut__c            = 'A Imprimer';
                fi.Attachment_Body__c   = EncodingUtil.base64Encode(mapAttachmentBySDocId.get(sDoc.Id).Body); 
                listFileImpressionToIsert.add(fi);
                
                if(fi.Name.containsIgnoreCase('contrat')){
                	//Sur Account
                	/*Account acc = new Account();
                	acc.Id 							= fi.Account__c;
                	acc.Attachment_Body_Contrat__c 	= fi.Attachment_Body__c;
                	acc.Attachment_Id_Contrat__c	= fi.Attachment_Id__c;
                	if(acc.Id != null){
                		mapAccountByIdToUpdate.put(acc.Id, acc);
                	}*/
                	
                	//Sur Case
                	Case c = new Case();
                	c.Id 							= fi.Case__c;
                	//c.Attachment_Body_Contrat__c 	= fi.Attachment_Body__c;
                	c.Attachment_Id_Contrat__c 		= fi.Attachment_Id__c;
                	if(c.Id != null){
                		mapCaseByIdToUpdate.put(c.Id, c); 
                	}
                	
                }
            }
        }

        if(listFileImpressionToIsert.size() > 0){
            system.debug('##MNE AP03_Attachment createFileImpressionRecords hello4');
            insert listFileImpressionToIsert;
        }
        
        /*if(!mapAccountByIdToUpdate.isEmpty()){
            system.debug('##MNE AP03_Attachment createFileImpressionRecords hello5');
            update mapAccountByIdToUpdate.values();
        }*/
        
        if(!mapCaseByIdToUpdate.isEmpty()){
            system.debug('##MNE AP03_Attachment createFileImpressionRecords hello6');
            update mapCaseByIdToUpdate.values();
        }
    }
    
    
    public static List<SDOC__SDoc__c> getSDocNotHTMLBySDocId (set<Id> setSDocId){
        system.debug('##MNE AP03_Attachment getSDocNotHTMLBySDocId setSDocId >> '+ setSDocId);
        List<SDOC__SDoc__c> listSDocResult = new List<SDOC__SDoc__c>();
        if(setSDocId == null || setSDocId.size() == 0){
            system.debug('##MNE AP03_Attachment getSDocNotHTMLBySDocId hello1');
            return listSDocResult;
        }
                                                                
       List<SDOC__SDoc__c> listSDoc = new List<SDOC__SDoc__c>([SELECT Id, SDOC__Attachment_ID__c, SDOC__RecordDataXML__c, SDOC__GD_Status__c, SDOC__ObjectID18__c,
                                                                SDOC__ObjectType__c, SDOC__Attachment_Name__c, SDOC__Status__c
                                                                FROM SDOC__SDoc__c WHERE Id IN :setSDocId AND SDOC__ObjectType__c = 'Case']); 
                                                                   
        system.debug('##MNE AP03_Attachment getSDocNotHTMLBySDocId listSDoc >> '+listSDoc);
        for(SDOC__SDoc__c sDoc : listSDoc){
            system.debug('##MNE AP03_Attachment getSDocNotHTMLBySDocId hello2 >> '+string.valueOf(sDoc.SDOC__RecordDataXML__c.contains('<DocumentFormat>HTML</DocumentFormat>')));
            if(!sDoc.SDOC__RecordDataXML__c.contains('<DocumentFormat>HTML</DocumentFormat>')){
                system.debug('##MNE AP03_Attachment getSDocNotHTMLBySDocId hello3');
                listSDocResult.add(sDoc);
            }
        }
        return listSDocResult;
    }

}