force-app/main/default/objects/Account/fields/Canal_creation_Maj__c.field-meta.xml
<CustomField>
    <fullName>Canal_creation_Maj__c</fullName>
    <description>champ a utiliser pour savoir si envoi vers RCU UGC . Si canal creation =salesforce alors l&#39;account sera envoyé vers le RCU UGC</description>
    <label>Canal création Maj</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/CliEmailComplementaire__c.field-meta.xml
<CustomField>
    <fullName>CliEmailComplementaire__c</fullName>
    <label>Email Complémentaire</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/ClientResident__c.field-meta.xml
<CustomField>
    <fullName>ClientResident__c</fullName>
    <description>Champ permettant d&#39;identifier un client habitant en France ou Belgique. 
utilisé pour alimenter le champ Code Pays.</description>
    <label>Client résident en</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>France</fullName>
                <default>true</default>
                <label>France</label>
            </value>
            <value>
                <fullName>Belgique</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/CliStatutRCU__c.field-meta.xml
<CustomField>
    <fullName>CliStatutRCU__c</fullName>
    <label>Statut du client ds référentiel client</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sans email</fullName>
            </value>
            <value>
                <fullName>En attente</fullName>
            </value>
            <value>
                <fullName>Validé</fullName>
            </value>
            <value>
                <fullName>Supprimé</fullName>
            </value>
            <value>
                <fullName>Refusé</fullName>
            </value>
            <value>
                <fullName>Anonyme</fullName>
            </value>
            <value>
                <fullName>Endormi</fullName>
            </value>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>En attente infinie</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/CodePays__c.field-meta.xml
<CustomField>
    <fullName>CodePays__c</fullName>
    <label>Code Pays</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/CodePostal__c.field-meta.xml
<CustomField>
    <fullName>CodePostal__c</fullName>
    <inlineHelpText>Le code postal est rempli automatiquement grâce à la sélection de la ville.</inlineHelpText>
    <label>Code Postal</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Pays__c.field-meta.xml
<CustomField>
    <fullName>Pays__c</fullName>
    <label>Pays</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>FRANCE</fullName>
            </value>
            <value>
                <fullName>BELGIQUE</fullName>
            </value>
            <value>
                <fullName>AFGHANISTAN</fullName>
            </value>
            <value>
                <fullName>AFRIQUE DU SUD</fullName>
            </value>
            <value>
                <fullName>ALBANIE</fullName>
            </value>
            <value>
                <fullName>ALGERIE</fullName>
            </value>
            <value>
                <fullName>ALLEMAGNE</fullName>
            </value>
            <value>
                <fullName>ANDORRE</fullName>
            </value>
            <value>
                <fullName>ANGOLA</fullName>
            </value>
            <value>
                <fullName>ANGUILLA</fullName>
            </value>
            <value>
                <fullName>ANTILLES NÉERLANDAISES</fullName>
            </value>
            <value>
                <fullName>ARABIE SAOUDITE</fullName>
            </value>
            <value>
                <fullName>ARGENTINE</fullName>
            </value>
            <value>
                <fullName>ARMENIE</fullName>
            </value>
            <value>
                <fullName>AUSTRALIE</fullName>
            </value>
            <value>
                <fullName>AUTRICHE</fullName>
            </value>
            <value>
                <fullName>AZERBAIDJAN</fullName>
            </value>
            <value>
                <fullName>BAHAMAS</fullName>
            </value>
            <value>
                <fullName>BAHREIN</fullName>
            </value>
            <value>
                <fullName>BANGLADESH</fullName>
            </value>
            <value>
                <fullName>BELARUS</fullName>
            </value>
            <value>
                <fullName>BELIZE</fullName>
            </value>
            <value>
                <fullName>BENIN</fullName>
            </value>
            <value>
                <fullName>BERMUDES</fullName>
            </value>
            <value>
                <fullName>BHOUTAN</fullName>
            </value>
            <value>
                <fullName>BOLIVIE, l&#39;ETAT PLURINATIONAL DE</fullName>
            </value>
            <value>
                <fullName>BOSNIE-HERZEGOVINE</fullName>
            </value>
            <value>
                <fullName>BOTSWANA</fullName>
            </value>
            <value>
                <fullName>BRESIL</fullName>
            </value>
            <value>
                <fullName>BRUNEI DARUSSALAM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/TECH_idCritizr__c.field-meta.xml
<CustomField>
    <fullName>TECH_idCritizr__c</fullName>
    <label>TECH_idCritizr</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/TECH_idFacebook__c.field-meta.xml
<CustomField>
    <fullName>TECH_idFacebook__c</fullName>
    <label>TECH_idFacebook</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/TECH_idInstagram__c.field-meta.xml
<CustomField>
    <fullName>TECH_idInstagram__c</fullName>
    <label>TECH_idInstagram</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/TECH_idTwitter__c.field-meta.xml
<CustomField>
    <fullName>TECH_idTwitter__c</fullName>
    <label>TECH_idTwitter</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Ville__c.field-meta.xml
<CustomField>
    <fullName>Ville__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ville</label>
    <referenceTo>Commune__c</referenceTo>
    <relationshipLabel>Fiches Clients</relationshipLabel>
    <relationshipName>Fiches_Clients</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/CodePostal__c.field-meta.xml
<CustomField>
    <fullName>CodePostal__c</fullName>
    <label>Code postal</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case/fields/Pays__c.field-meta.xml
<CustomField>
    <fullName>Pays__c</fullName>
    <description>Champ qui copie le pays du compte</description>
    <formula>TEXT(Account.Pays__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Pays</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/TECH_idCritizr__c.field-meta.xml
<CustomField>
    <fullName>TECH_idCritizr__c</fullName>
    <label>TECH_idCritizr</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/TECH_idFacebook__c.field-meta.xml
<CustomField>
    <fullName>TECH_idFacebook__c</fullName>
    <label>TECH_idFacebook</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/TECH_idInstagram__c.field-meta.xml
<CustomField>
    <fullName>TECH_idInstagram__c</fullName>
    <label>TECH_idInstagram</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/TECH_idTwitter__c.field-meta.xml
<CustomField>
    <fullName>TECH_idTwitter__c</fullName>
    <label>TECH_idTwitter</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Commune__c/Commune__c.object-meta.xml
<CustomObject>
    <label>Commune</label>
    <nameField>
        <label>Nom de la ville</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Communes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Commune__c/fields/CodePostal__c.field-meta.xml
<CustomField>
    <fullName>CodePostal__c</fullName>
    <label>Code postal</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Commune__c/fields/Pays__c.field-meta.xml
<CustomField>
    <fullName>Pays__c</fullName>
    <label>Pays</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>FRANCE</fullName>
            </value>
            <value>
                <fullName>BELGIQUE</fullName>
            </value>
            <value>
                <fullName>AFGHANISTAN</fullName>
            </value>
            <value>
                <fullName>AFRIQUE DU SUD</fullName>
            </value>
            <value>
                <fullName>ALBANIE</fullName>
            </value>
            <value>
                <fullName>ALGERIE</fullName>
            </value>
            <value>
                <fullName>ALLEMAGNE</fullName>
            </value>
            <value>
                <fullName>ANDORRE</fullName>
            </value>
            <value>
                <fullName>ANGOLA</fullName>
            </value>
            <value>
                <fullName>ANGUILLA</fullName>
            </value>
            <value>
                <fullName>ANTILLES NÉERLANDAISES</fullName>
            </value>
            <value>
                <fullName>ARABIE SAOUDITE</fullName>
            </value>
            <value>
                <fullName>ARGENTINE</fullName>
            </value>
            <value>
                <fullName>ARMENIE</fullName>
            </value>
            <value>
                <fullName>AUSTRALIE</fullName>
            </value>
            <value>
                <fullName>AUTRICHE</fullName>
            </value>
            <value>
                <fullName>AZERBAIDJAN</fullName>
            </value>
            <value>
                <fullName>BAHAMAS</fullName>
            </value>
            <value>
                <fullName>BAHREIN</fullName>
            </value>
            <value>
                <fullName>BANGLADESH</fullName>
            </value>
            <value>
                <fullName>BELARUS</fullName>
            </value>
            <value>
                <fullName>BELIZE</fullName>
            </value>
            <value>
                <fullName>BENIN</fullName>
            </value>
            <value>
                <fullName>BERMUDES</fullName>
            </value>
            <value>
                <fullName>BHOUTAN</fullName>
            </value>
            <value>
                <fullName>BOLIVIE, l&#39;ETAT PLURINATIONAL DE</fullName>
            </value>
            <value>
                <fullName>BOSNIE-HERZEGOVINE</fullName>
            </value>
            <value>
                <fullName>BOTSWANA</fullName>
            </value>
            <value>
                <fullName>BRESIL</fullName>
            </value>
            <value>
                <fullName>BRUNEI DARUSSALAM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Commune__c/fields/Tech_Commune__c.field-meta.xml
<CustomField>
    <fullName>Tech_Commune__c</fullName>
    <externalId>true</externalId>
    <label>Tech_Commune</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/AP01_Account_Test.cls
@IsTest
public class AP01_Account_Test {
	

    private static Account account;
    private static Case cse;
	
	
	private static void init() {
		Utils.createContactInconnu();
		account = new Account(LastName='test', FirstName='test', RecordTypeId = Utils.getComptePersonelAccountRecordType().Id, 
        	PersonEmail='test@test.test', CliEmailComplementaire__c='test@test.test');
        insert account;
	}
	
	@IsTest
	static void testCreateAccountClientFrance() {
		TestHttpCalloutMock mock = new TestHttpCalloutMock();
		Test.setMock(HttpCalloutMock.class, mock);
		Account acc = new Account(LastName='test', FirstName='test', RecordTypeId = Utils.getComptePersonelAccountRecordType().Id, 
        	PersonEmail='test@test.test', ClientResident__c = 'France');
        insert acc;
        Account accVerif = [SELECT Id, ClientResident__c, CodePays__c FROM Account WHERE Id = :acc.Id];
        system.assertEquals('033', accVerif.CodePays__c);
	}
	
	@IsTest
	static void testCreateAccountClientBelgique() {
		TestHttpCalloutMock mock = new TestHttpCalloutMock();
		Test.setMock(HttpCalloutMock.class, mock);
		Account acc = new Account(LastName='test', FirstName='test', RecordTypeId = Utils.getComptePersonelAccountRecordType().Id, 
        	PersonEmail='test@test.test', ClientResident__c = 'Belgique');
        insert acc;
        Account accVerif = [SELECT Id, ClientResident__c, CodePays__c FROM Account WHERE Id = :acc.Id];
        system.assertEquals('032', accVerif.CodePays__c);
	}
	
	@IsTest 
	static void testUpdateAccountParis() {
		TestHttpCalloutMock mock = new TestHttpCalloutMock();
		Test.setMock(HttpCalloutMock.class, mock);
		Commune__c ville = new Commune__c();
		ville.CodePostal__c = '75001';
		ville.Pays__c = 'FRANCE';
		ville.Tech_Commune__c = 'Paris';
		insert ville;
		Account acc = new Account(LastName='test', FirstName='test', RecordTypeId = Utils.getComptePersonelAccountRecordType().Id, 
        	PersonEmail='test@test.test');
        insert acc;
        acc.ville__c = ville.id;
        update acc;
        
        Account accVerif = [SELECT Id, CodePostal__c, Pays__c FROM Account WHERE Id = :acc.Id];
        system.assertEquals('75001', accVerif.CodePostal__c);
        system.assertEquals('FRANCE', accVerif.Pays__c);
	}
	
	@IsTest 
	static void testUpdateAccountRcu() {
		TestHttpCalloutMock mock = new TestHttpCalloutMock();
		Test.setMock(HttpCalloutMock.class, mock);
		Commune__c ville = new Commune__c();
		ville.CodePostal__c = '75001';
		ville.Pays__c = 'FRANCE';
		ville.Tech_Commune__c = 'Paris';
		insert ville;
		
		Test.startTest();
		
		Account acc = new Account(LastName='test', FirstName='test', RecordTypeId = Utils.getComptePersonelAccountRecordType().Id, 
        	PersonEmail='test@test.test', Canal_creation_Maj__c = 'RCU');
        insert acc;
        
        Account accVerif = [SELECT Id, Canal_creation_Maj__c FROM Account WHERE Id = :acc.Id];
        System.assertEquals(null, accVerif.Canal_creation_Maj__c);
        
        acc.Canal_creation_Maj__c = null;
        acc.ville__c = ville.id;
        update acc;
        
        Test.stopTest();
        
        system.assert( mock.counter > 1 ); 
	}
	
    
	@IsTest 
	static void testUpdateAccountRcuTimeout() {
		TestHttpCalloutMock mock = new TestHttpCalloutMock();
		Test.setMock(HttpCalloutMock.class, mock);
		Commune__c ville = new Commune__c();
		ville.CodePostal__c = '75001';
		ville.Pays__c = 'FRANCE';
		ville.Tech_Commune__c = 'Paris';
		insert ville;
		
		Test.startTest();
		
		Account acc = new Account(LastName='test', FirstName='test', RecordTypeId = Utils.getComptePersonelAccountRecordType().Id, 
        	PersonEmail='test@test.test', Canal_creation_Maj__c = 'RCU');
        insert acc;
        
        mock.respond = false; 
        acc.Canal_creation_Maj__c = null;
        acc.ville__c = ville.id;
        update acc;
        
        Test.stopTest();
        
        System.debug('After update: ' + acc); 
        
        
	}
    
    
	@IsTest 
	static void testUpdateAccountRcuKO() {
		TestHttpCalloutMock mock = new TestHttpCalloutMock();
		Test.setMock(HttpCalloutMock.class, mock);
		Commune__c ville = new Commune__c();
		ville.CodePostal__c = '75001';
		ville.Pays__c = 'FRANCE';
		ville.Tech_Commune__c = 'Paris';
		insert ville;
		
		Test.startTest();
		
		Account acc = new Account(LastName='test', FirstName='test', RecordTypeId = Utils.getComptePersonelAccountRecordType().Id, 
        	PersonEmail='test@test.test', Canal_creation_Maj__c = 'RCU');
        insert acc;
        
        mock.respond = false; 
        acc.Canal_creation_Maj__c = 'RCU';
        acc.ville__c = ville.id;
        update acc;
        
        Test.stopTest();
        
        System.debug('After update: ' + acc);
        
        Account accVerif = [SELECT Id, Canal_creation_Maj__c FROM Account WHERE Id = :acc.Id];
        System.assertEquals(null, accVerif.Canal_creation_Maj__c); 
        
        
	}
    
    
    
	@IsTest 
	static void testCreateAccountRcuKO() {
		TestHttpCalloutMock mock = new TestHttpCalloutMock(418, 'I\'m a teapot');
		Test.setMock(HttpCalloutMock.class, mock);

		Test.startTest();
		
		Account acc = new Account(LastName='test', FirstName='test', RecordTypeId = Utils.getComptePersonelAccountRecordType().Id, 
        	PersonEmail='test@test.test', ClientResident__c = 'France');
        insert acc;
        
        
        Test.stopTest();
        
        Account accVerif = [SELECT Id, CliStatutRCU__c
        	FROM Account WHERE Id = :acc.Id];
        
        
        
        system.assertEquals(1, mock.counter);
        system.assertEquals('En attente', accVerif.CliStatutRCU__c);
	}
	
	@IsTest
	static void testCreateAccount() {
		TestHttpCalloutMock mock = new TestHttpCalloutMock();
		Test.setMock(HttpCalloutMock.class, mock);
		Test.startTest();
		Account acc = new Account(LastName='test', FirstName='test', RecordTypeId = Utils.getComptePersonelAccountRecordType().Id, 
        	PersonEmail='test@test.test');
        insert acc;
        Test.stopTest();
        system.assertEquals(1, mock.counter);
        
	}

	@IsTest
    static void updateAccountFacebook() {
    	
    	Test.setMock(HttpCalloutMock.class, new TestHttpCalloutMock());
    	init();
    	
    	cse = new Case () ;
        cse.RecordTypeId =  Utils.getNouvelleDemandeClientCaseRecordType().id ;
        cse.accountId = Utils.getContactInconnu().accountId;
        cse.Status ='à traiter' ;
        cse.TECH_idFacebook__c = 'id fb';
        insert cse;
        
        Test.startTest(); 
        account.TECH_idFacebook__c = 'id fb';
        update account;
        Test.stopTest();
        
        Case caseVerif = [SELECT Id, AccountId FROM Case where Id = :cse.Id];
        
        system.assertEquals(account.id, caseVerif.AccountId);
    }
    
    @IsTest
    static void updateAccountTwitter() {
    	Test.setMock(HttpCalloutMock.class, new TestHttpCalloutMock());
    	init();
    	
    	cse = new Case () ;
        cse.RecordTypeId =  Utils.getNouvelleDemandeClientCaseRecordType().id ;
        cse.accountId = Utils.getContactInconnu().accountId;
        cse.Status ='à traiter' ;
        cse.TECH_idTwitter__c = 'id twitter';
        insert cse;
        
        Test.startTest(); 
        account.TECH_idTwitter__c = 'id twitter';
        update account;
        Test.stopTest();
        
        Case caseVerif = [SELECT Id, AccountId FROM Case where Id = :cse.Id];
        
        system.assertEquals(account.id, caseVerif.AccountId);
    }
    
    
    @IsTest
    static void updateAccountCritizr() {
    	Test.setMock(HttpCalloutMock.class, new TestHttpCalloutMock());
    	init();
    	
    	cse = new Case () ;
        cse.RecordTypeId =  Utils.getNouvelleDemandeClientCaseRecordType().id ;
        cse.accountId = Utils.getContactInconnu().accountId;
        cse.Status ='à traiter' ;
        cse.TECH_idCritizr__c = 'id crit';
        insert cse;
        
        Test.startTest(); 
        account.TECH_idCritizr__c = 'id crit';
        update account;
        Test.stopTest();
        
        Case caseVerif = [SELECT Id, AccountId FROM Case where Id = :cse.Id];
        
        system.assertEquals(account.id, caseVerif.AccountId);
    }
    
    @IsTest
    static void updateAccountInstagram() {
    	Test.setMock(HttpCalloutMock.class, new TestHttpCalloutMock());
    	init();
    	
    	cse = new Case () ;
        cse.RecordTypeId =  Utils.getNouvelleDemandeClientCaseRecordType().id ;
        cse.accountId = Utils.getContactInconnu().accountId;
        cse.Status ='à traiter' ;
        cse.TECH_idInstagram__c = 'id insta';
        insert cse;
    	
        Test.startTest(); 
        account.TECH_idInstagram__c = 'id insta';
        update account;
        Test.stopTest();
        
        Case caseVerif = [SELECT Id, AccountId FROM Case where Id = :cse.Id];
        
        system.assertEquals(account.id, caseVerif.AccountId);
    }
}