force-app/main/default/objects/Account/fields/CliEmailComplementaire__c.field-meta.xml
<CustomField>
    <fullName>CliEmailComplementaire__c</fullName>
    <label>Email Complémentaire</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/ClientResident__c.field-meta.xml
<CustomField>
    <fullName>ClientResident__c</fullName>
    <description>Champ permettant d&#39;identifier un client habitant en France ou Belgique. 
utilisé pour alimenter le champ Code Pays.</description>
    <label>Client résident en</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>France</fullName>
                <default>true</default>
                <label>France</label>
            </value>
            <value>
                <fullName>Belgique</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/IdMonCompte__c.field-meta.xml
<CustomField>
    <fullName>IdMonCompte__c</fullName>
    <label>Id MonCompte</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/NPAIEMAIL__c.field-meta.xml
<CustomField>
    <fullName>NPAIEMAIL__c</fullName>
    <defaultValue>false</defaultValue>
    <label>NPAI_EMAIL</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/PNDADRESSE__c.field-meta.xml
<CustomField>
    <fullName>PNDADRESSE__c</fullName>
    <defaultValue>false</defaultValue>
    <label>PND_ADRESSE</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Global_Parameters__mdt/Global_Parameters__mdt.object-meta.xml
<CustomObject>
    <description>Paramètres globaux de l&#39;application</description>
    <label>Global Parameters</label>
    <pluralLabel>Global Parameters</pluralLabel>
</CustomObject>

force-app/main/default/objects/Global_Parameters__mdt/fields/Base_Url_All_iFrame_Hercule__c.field-meta.xml
<CustomField>
    <fullName>Base_Url_All_iFrame_Hercule__c</fullName>
    <label>Base Url All iFrame Hercule</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Global_Parameters__mdt/fields/Base_Url_iFrame_VLO__c.field-meta.xml
<CustomField>
    <fullName>Base_Url_iFrame_VLO__c</fullName>
    <label>Base Url iFrame VLO</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/LCC_IframeHercule_Test.cls
@IsTest
public class LCC_IframeHercule_Test {
    private static Account accountEmail;
    private static Case cse;
    
    private static void init() {
        // Account test
        accountEmail = new Account(LastName='test', FirstName='test', RecordTypeId = Utils.getComptePersonelAccountRecordType().Id, 
                                   PersonEmail='test@test.test', CliEmailComplementaire__c='test@test.test', NPAIEMAIL__c = false,
                                   PNDADRESSE__c = false, ClientResident__c = 'Belgique', IdMonCompte__c = 'idMonCompte');
        insert accountEmail;
        
        system.debug ('### LOG ### accountEmail =' + accountEmail) ;
        
        cse = new Case () ;
        cse.RecordTypeId = Utils.getNouvelleDemandeClientCaseRecordType().id ;
        cse.AccountId = accountEmail.ID;
        cse.Status ='à traiter' ;
        
        insert cse ;
    }
    
    @IsTest
    public static void getParamsFromCaseTest() {
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new TestHttpCalloutMock());
        init();
        IframeHerculeDto params = LCC_IframeHercule.getParams(cse.Id);
        system.assertEquals('032', params.strCodePays);
        system.assertEquals('idMonCompte', params.strIdMonCompte);
        
        Global_Parameters__mdt param = Utils.getGlobalParameters('UGC_One_Parameters');
        system.assertEquals(param.Base_Url_All_iFrame_Hercule__c, params.strBaseUrl);
        system.assertEquals(param.Base_Url_iFrame_VLO__c, params.strBaseUrlVlo);
        Test.stopTest();
    }
    
    @IsTest
    public static void getParamsFromAccountTest() {
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new TestHttpCalloutMock());
        init();
        IframeHerculeDto params = LCC_IframeHercule.getParams(accountEmail.Id);
        system.assertEquals('032', params.strCodePays);
        system.assertEquals('idMonCompte', params.strIdMonCompte);
        
        Global_Parameters__mdt param = Utils.getGlobalParameters('UGC_One_Parameters');
        system.assertEquals(param.Base_Url_All_iFrame_Hercule__c, params.strBaseUrl);
        system.assertEquals(param.Base_Url_iFrame_VLO__c, params.strBaseUrlVlo);
        Test.stopTest();
    }
}