force-app/main/default/objects/Account/fields/ClientResident__c.field-meta.xml
<CustomField>
    <fullName>ClientResident__c</fullName>
    <description>Champ permettant d&#39;identifier un client habitant en France ou Belgique. 
utilisé pour alimenter le champ Code Pays.</description>
    <label>Client résident en</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>France</fullName>
                <default>true</default>
                <label>France</label>
            </value>
            <value>
                <fullName>Belgique</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/CodePays__c.field-meta.xml
<CustomField>
    <fullName>CodePays__c</fullName>
    <label>Code Pays</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/CodePostal__c.field-meta.xml
<CustomField>
    <fullName>CodePostal__c</fullName>
    <inlineHelpText>Le code postal est rempli automatiquement grâce à la sélection de la ville.</inlineHelpText>
    <label>Code Postal</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/IdMonCompte__c.field-meta.xml
<CustomField>
    <fullName>IdMonCompte__c</fullName>
    <label>Id MonCompte</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/NomVoie__c.field-meta.xml
<CustomField>
    <fullName>NomVoie__c</fullName>
    <label>Nom de la voie</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/NoVoie__c.field-meta.xml
<CustomField>
    <fullName>NoVoie__c</fullName>
    <label>N° de la voie</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Pays__c.field-meta.xml
<CustomField>
    <fullName>Pays__c</fullName>
    <label>Pays</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>FRANCE</fullName>
            </value>
            <value>
                <fullName>BELGIQUE</fullName>
            </value>
            <value>
                <fullName>AFGHANISTAN</fullName>
            </value>
            <value>
                <fullName>AFRIQUE DU SUD</fullName>
            </value>
            <value>
                <fullName>ALBANIE</fullName>
            </value>
            <value>
                <fullName>ALGERIE</fullName>
            </value>
            <value>
                <fullName>ALLEMAGNE</fullName>
            </value>
            <value>
                <fullName>ANDORRE</fullName>
            </value>
            <value>
                <fullName>ANGOLA</fullName>
            </value>
            <value>
                <fullName>ANGUILLA</fullName>
            </value>
            <value>
                <fullName>ANTILLES NÉERLANDAISES</fullName>
            </value>
            <value>
                <fullName>ARABIE SAOUDITE</fullName>
            </value>
            <value>
                <fullName>ARGENTINE</fullName>
            </value>
            <value>
                <fullName>ARMENIE</fullName>
            </value>
            <value>
                <fullName>AUSTRALIE</fullName>
            </value>
            <value>
                <fullName>AUTRICHE</fullName>
            </value>
            <value>
                <fullName>AZERBAIDJAN</fullName>
            </value>
            <value>
                <fullName>BAHAMAS</fullName>
            </value>
            <value>
                <fullName>BAHREIN</fullName>
            </value>
            <value>
                <fullName>BANGLADESH</fullName>
            </value>
            <value>
                <fullName>BELARUS</fullName>
            </value>
            <value>
                <fullName>BELIZE</fullName>
            </value>
            <value>
                <fullName>BENIN</fullName>
            </value>
            <value>
                <fullName>BERMUDES</fullName>
            </value>
            <value>
                <fullName>BHOUTAN</fullName>
            </value>
            <value>
                <fullName>BOLIVIE, l&#39;ETAT PLURINATIONAL DE</fullName>
            </value>
            <value>
                <fullName>BOSNIE-HERZEGOVINE</fullName>
            </value>
            <value>
                <fullName>BOTSWANA</fullName>
            </value>
            <value>
                <fullName>BRESIL</fullName>
            </value>
            <value>
                <fullName>BRUNEI DARUSSALAM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/TypeVoie__c.field-meta.xml
<CustomField>
    <fullName>TypeVoie__c</fullName>
    <label>Type de voie</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ABBAYE</fullName>
            </value>
            <value>
                <fullName>allée</fullName>
            </value>
            <value>
                <fullName>ALLEES</fullName>
            </value>
            <value>
                <fullName>ANCIEN CHE</fullName>
            </value>
            <value>
                <fullName>ANCIEN RTE</fullName>
            </value>
            <value>
                <fullName>ANSE</fullName>
            </value>
            <value>
                <fullName>ARCADE</fullName>
            </value>
            <value>
                <fullName>avenue</fullName>
            </value>
            <value>
                <fullName>BOIS</fullName>
            </value>
            <value>
                <fullName>BOUCLE</fullName>
            </value>
            <value>
                <fullName>boulevard</fullName>
            </value>
            <value>
                <fullName>BOURG</fullName>
            </value>
            <value>
                <fullName>CALE</fullName>
            </value>
            <value>
                <fullName>CAMP</fullName>
            </value>
            <value>
                <fullName>CAMPING</fullName>
            </value>
            <value>
                <fullName>CARRE</fullName>
            </value>
            <value>
                <fullName>CARREFOUR</fullName>
            </value>
            <value>
                <fullName>CARRIERE</fullName>
            </value>
            <value>
                <fullName>CAVEE</fullName>
            </value>
            <value>
                <fullName>CCAL</fullName>
            </value>
            <value>
                <fullName>CENTRE</fullName>
            </value>
            <value>
                <fullName>CHALET</fullName>
            </value>
            <value>
                <fullName>CHATEAU</fullName>
            </value>
            <value>
                <fullName>chaussée</fullName>
            </value>
            <value>
                <fullName>chemin</fullName>
            </value>
            <value>
                <fullName>CHEMINEMENT</fullName>
            </value>
            <value>
                <fullName>CHEMINS</fullName>
            </value>
            <value>
                <fullName>CHEZ</fullName>
            </value>
            <value>
                <fullName>cité</fullName>
            </value>
            <value>
                <fullName>CITES</fullName>
            </value>
            <value>
                <fullName>PRE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Ville__c.field-meta.xml
<CustomField>
    <fullName>Ville__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ville</label>
    <referenceTo>Commune__c</referenceTo>
    <relationshipLabel>Fiches Clients</relationshipLabel>
    <relationshipName>Fiches_Clients</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Commune__c/Commune__c.object-meta.xml
<CustomObject>
    <label>Commune</label>
    <nameField>
        <label>Nom de la ville</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Communes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Commune__c/fields/CodePostal__c.field-meta.xml
<CustomField>
    <fullName>CodePostal__c</fullName>
    <label>Code postal</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Commune__c/fields/Pays__c.field-meta.xml
<CustomField>
    <fullName>Pays__c</fullName>
    <label>Pays</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>FRANCE</fullName>
            </value>
            <value>
                <fullName>BELGIQUE</fullName>
            </value>
            <value>
                <fullName>AFGHANISTAN</fullName>
            </value>
            <value>
                <fullName>AFRIQUE DU SUD</fullName>
            </value>
            <value>
                <fullName>ALBANIE</fullName>
            </value>
            <value>
                <fullName>ALGERIE</fullName>
            </value>
            <value>
                <fullName>ALLEMAGNE</fullName>
            </value>
            <value>
                <fullName>ANDORRE</fullName>
            </value>
            <value>
                <fullName>ANGOLA</fullName>
            </value>
            <value>
                <fullName>ANGUILLA</fullName>
            </value>
            <value>
                <fullName>ANTILLES NÉERLANDAISES</fullName>
            </value>
            <value>
                <fullName>ARABIE SAOUDITE</fullName>
            </value>
            <value>
                <fullName>ARGENTINE</fullName>
            </value>
            <value>
                <fullName>ARMENIE</fullName>
            </value>
            <value>
                <fullName>AUSTRALIE</fullName>
            </value>
            <value>
                <fullName>AUTRICHE</fullName>
            </value>
            <value>
                <fullName>AZERBAIDJAN</fullName>
            </value>
            <value>
                <fullName>BAHAMAS</fullName>
            </value>
            <value>
                <fullName>BAHREIN</fullName>
            </value>
            <value>
                <fullName>BANGLADESH</fullName>
            </value>
            <value>
                <fullName>BELARUS</fullName>
            </value>
            <value>
                <fullName>BELIZE</fullName>
            </value>
            <value>
                <fullName>BENIN</fullName>
            </value>
            <value>
                <fullName>BERMUDES</fullName>
            </value>
            <value>
                <fullName>BHOUTAN</fullName>
            </value>
            <value>
                <fullName>BOLIVIE, l&#39;ETAT PLURINATIONAL DE</fullName>
            </value>
            <value>
                <fullName>BOSNIE-HERZEGOVINE</fullName>
            </value>
            <value>
                <fullName>BOTSWANA</fullName>
            </value>
            <value>
                <fullName>BRESIL</fullName>
            </value>
            <value>
                <fullName>BRUNEI DARUSSALAM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SM_Subscribe.cls
public with sharing class SM_Subscribe {
    public SM_Subscribe() {

    }

    public static zc_ProxyActionsubscribeRequest subscribe(SubscribeIn subIn, Boolean isPreview, Account porteur, Account payeur, List<zc_AmendmentRatePlanData> subOffreRatePlans, Map<String,Object> customSub){

        // String sDateDebutContrat = (String)subMap.get('dateDebutContrat'); //).format('yyyy-MM-dd');
        // Date dateDebutContrat = Date.valueOf(sDateDebutContrat);
        // List<Object> produits = (List<Object>)subMap.get('produit');
        Date dateDebutContrat = subIn.dateDebutContrat;
        String produit = subIn.produit.get(0);
        String typeContrat = (produit.contains('CDI')?'CDI':'CDD');

        // Zuora subscribeRequest
        zc_ProxyActionsubscribeRequest subscribeReq = new zc_ProxyActionsubscribeRequest();
        zc_SubscribeRequest sub = new zc_SubscribeRequest();

        sub.account = subAccount(typeContrat, porteur,customSub);
        sub.billToContact = billToContact(payeur);
        sub.soldToContact = soldToContact(porteur);
        if (subIn.mandateId != null && subIn.iban != null && !isPreview) sub.paymentMethod = paymentMethod(typeContrat, payeur, subIn.iban, subIn.mandateId, customSub); // activer si isPreview = false
        sub.previewOptions = new zc_SubscribeRequestPreviewOptions();
        sub.subscriptionData = new zc_SubscribeRequestSubscriptionData();
        sub.subscribeOptions = new zc_SubscribeRequestSubscribeOptions();
        
        sub.previewOptions.enablePreviewMode = isPreview;
        //sub.previewOptions.previewType = sub.previewOptions.PreviewTypeEnum.//'InvoiceItem';
        sub.previewOptions.numberOfPeriods = 5;


        //invoiceOptions
        sub.subscribeOptions.generateInvoice = true;
        sub.subscribeOptions.processPayments = false;
        sub.subscribeOptions.subscribeInvoiceProcessingOptions = new zc_SubscribeRequestInvProcessingOptions();
        sub.subscribeOptions.subscribeInvoiceProcessingOptions.invoiceDate = Date.today();
        sub.subscribeOptions.subscribeInvoiceProcessingOptions.invoiceTargetDate = dateDebutContrat;
        sub.subscribeOptions.subscribeInvoiceProcessingOptions.invoiceProcessingScope = 'Subscription';

        // subscription Terms
        sub.subscriptionData.subscription = subTerm(typeContrat, dateDebutContrat, subIn, customSub);


        // RatePlans
        sub.subscriptionData.ratePlanData.addAll(subOffreRatePlans);
        subscribeReq.subscribes.add(sub);
  
        return subscribeReq;
    }

    private static zc_SubscribeRequestSubscriptionDataSub subTerm(String typeContrat, Date dateDebutContrat, SubscribeIn subIn, Map<String,Object> customSub){
        
        zc_SubscribeRequestSubscriptionDataSub sub = new zc_SubscribeRequestSubscriptionDataSub();
        Boolean isFutur = (dateDebutContrat == Date.today())?false:true;
        // WSZ.Paiement paiement;

        // if (subMap.containsKey('paiement'))  paiement = (WSZ.Paiement)subMap.get('paiement'); 
            
        
        if (typeContrat == 'CDI') {
            sub.termType = 'TERMED';
            sub.initialTermPeriodType = 'Month';
            sub.renewalTermPeriodType = 'Month';
            sub.initialTerm = 12;
            //sub.renewalTerm = 12;
            sub.renewalSetting = 'RENEW_TO_EVERGREEN';
            sub.autoRenew = true;
            sub.IsInvoiceSeparate = true;
            sub.contractEffectiveDate = dateDebutContrat;
            if (!isFutur) sub.serviceActivationDate = dateDebutContrat;
            if (!isFutur) sub.contractAcceptanceDate = dateDebutContrat;
            if (dateDebutContrat.toStartOfMonth() != dateDebutContrat) {
                sub.termStartDate = dateDebutContrat.toStartOfMonth().addMonths(1);
            }else {
                sub.termStartDate = dateDebutContrat;
            }

        }else if (typeContrat == 'CDD'){
            sub.termType = 'TERMED';
            sub.initialTermPeriodType = 'Month';
            sub.renewalTermPeriodType = 'Month';
            sub.initialTerm = 12;
            sub.renewalTerm = 12;
            sub.renewalSetting = 'RENEW_WITH_SPECIFIC_TERM';
            sub.autoRenew = false;
            sub.IsInvoiceSeparate = true;
            sub.contractEffectiveDate = dateDebutContrat;
            if (!isFutur) sub.serviceActivationDate = dateDebutContrat;
            if (!isFutur) sub.contractAcceptanceDate = dateDebutContrat;            
            sub.termStartDate = dateDebutContrat;
        }

        sub.modeLivraison = subIn.modeLivraison;
        sub.codeOffreCo = (String)customSub.get('codeOffreCo');
        sub.codePromo = subIn.coupon;
        sub.lieu = subIn.lieu;
        sub.agent = subIn.agent;
        sub.payeurCRMID = subIn.payeurSFID;
        sub.numCarteParrain = subIn.numCarteParrain;
        sub.typeContrat = typeContrat;
        if (customSub.containsKey('IsB2B') && customSub.get('IsB2B') == true ) {
            sub.marche = 'BTOB';
        }else {
            sub.marche = 'BTOC';
        }
        sub.codeOffrePrincipale = 'UI1CDI'; //TODO Famille du RatePlan de l'abonnement.
        if (typeContrat == 'CDI') { 
            sub.methodePaiement = 'PRE';
        }else {
            sub.methodePaiement = subIn.paiement.methodePaiement; //TODO si besoin de mapping
        }

        // if (subMap.containsKey('modeLivraison')) sub.modeLivraison = (String)subMap.get('modeLivraison');
        // if (subMap.containsKey('codeOffreCo')) sub.codeOffreCo = (String)subMap.get('codeOffreCo');
        // if (subMap.containsKey('coupon')) sub.codePromo = (String)subMap.get('coupon');
        // if (subMap.containsKey('lieu')) sub.lieu = (String)subMap.get('lieu');
        // if (subMap.containsKey('agent')) sub.agent = (String)subMap.get('agent');
        // if (subMap.containsKey('payeurSFID')) sub.payeurCRMID = (String)subMap.get('payeurSFID');
        // if (subMap.containsKey('numCarteParrain')) sub.numCarteParrain = (String)subMap.get('numCarteParrain');


        return sub;
    }

    private static zc_SubscribeRequestAccount subAccount(String typeContrat, Account acc, Map<String,Object> customSub){

        zc_SubscribeRequestAccount subAcc = new zc_SubscribeRequestAccount();
        Boolean isPreview = (Boolean)customSub.get('isPreview');


        if (typeContrat == 'CDI') {
            //subAcc.id='8adce4216787fdf0016788ffa3cf4110';
            subAcc.name = acc.LastName + ' ' + acc.FirstName;
            subAcc.idMoncompte = acc.IdMonCompte__c;
            subAcc.dateNaissance = acc.PersonBirthdate;
            subAcc.crmId = acc.Id;
            subAcc.autoPay = (isPreview)?false:true; 
            subAcc.batch = 'Batch1';
            subAcc.billCycleDay = 1;
            subAcc.currency2 = 'EUR';
            subAcc.paymentTerm = 'Due Upon Receipt';
        }else if (typeContrat == 'CDD'){
            subAcc.name = acc.LastName + ' ' + acc.FirstName;
            subAcc.idMoncompte = acc.IdMonCompte__c;
            subAcc.dateNaissance = acc.PersonBirthdate;
            subAcc.crmId = acc.Id;
            subAcc.autoPay = false;
            subAcc.batch = 'Batch1';
            subAcc.billCycleDay = 1;
            subAcc.currency2 = 'EUR';
            subAcc.paymentTerm = 'Due Upon Receipt';
            if (customSub.containsKey('IsB2B') && customSub.get('IsB2B') == true) {
                subAcc.defaultPaymentMethodId = Utils.getUgcGenericParam('Zuora_PM_'+'BTB','033').ParamValue__c;
            }else {
                subAcc.defaultPaymentMethodId = Utils.getUgcGenericParam('Zuora_PM_'+'CBI','033').ParamValue__c; //TODO 
            }
            
        }

        return subAcc;

        // Id, Name, LastName, FirstName, PersonBirthdate, IdMonCompte__c, PersonEmail, NoVoie__c, TypeVoie__c, NomVoie__c, 
		//		CodePostal__c, Ville__r.Name, ClientResident__c, CodePays__c, 

    }   

    private static zc_SubscribeRequestBillToContact billToContact(Account acc){
            
            zc_SubscribeRequestBillToContact billTo = new zc_SubscribeRequestBillToContact();
            
            billTo.address1 = acc.NoVoie__c + ' ' + acc.TypeVoie__c + ' ' + acc.NomVoie__c;
            billTo.city = acc.Ville__r.Name;
            billTo.country = acc.Ville__r.Pays__c;
            billTo.firstName = acc.FirstName;
            billTo.lastName = acc.LastName;
            billTo.postalCode = acc.Ville__r.CodePostal__c;
            billTo.personalEmail = acc.PersonEmail;

            return billTo;

        // Id, Name, LastName, FirstName, PersonBirthdate, IdMonCompte__c, PersonEmail, NoVoie__c, TypeVoie__c, NomVoie__c, 
		//		CodePostal__c, Ville__r.Name, ClientResident__c, CodePays__c, 

    }  


    private static zc_SubscribeRequestSoldToContact soldToContact(Account acc){

            zc_SubscribeRequestSoldToContact soldTo = new zc_SubscribeRequestSoldToContact();
            soldTo.address1 = acc.NoVoie__c + ' ' + acc.TypeVoie__c + ' ' + acc.NomVoie__c;
            soldTo.city = acc.Ville__r.Name;
            soldTo.country = acc.Ville__r.Pays__c;
            soldTo.firstName = acc.FirstName;
            soldTo.lastName = acc.LastName;
            soldTo.postalCode = acc.Ville__r.CodePostal__c;
            soldTo.personalEmail = acc.PersonEmail;

            return soldTo;

        // Id, Name, LastName, FirstName, PersonBirthdate, IdMonCompte__c, PersonEmail, NoVoie__c, TypeVoie__c, NomVoie__c, 

    } 

    private static zc_SubscribeRequestPaymentMethod paymentMethod(String typeContrat, Account acc, String iban, String mandateId, Map<String,Object> customSub){

        zc_SubscribeRequestPaymentMethod pm = new zc_SubscribeRequestPaymentMethod();
        if (typeContrat == 'CDI'){
            //zc_SubscribeRequestPaymentMethod.RTypeEnum pp; // = new zc_SubscribeRequestPaymentMethod.RTypeEnum();
            pm.gatewayOptionData = new zc_SubscribeRequestPaymentMethodGat();
            pm.r_type = 'BankTransfer';
            pm.bankTransferType = 'SEPA';
            //pm.IBAN = '';
            pm.bankTransferAccountNumber = iban; //doit etre valide meme pour le test
            pm.existingMandate = 'Yes'; // le mandat est cree meme si en preview
            pm.mandateReceived = 'Yes';
            pm.mandateID = mandateId;
            pm.country = 'FR'; //TODO
            pm.firstName = acc.FirstName;
            pm.lastName = acc.LastName;
            pm.streetName = acc.TypeVoie__c + ' ' + acc.NomVoie__c;
            pm.streetNumber = acc.NoVoie__c;
            pm.postalCode = acc.Ville__r.CodePostal__c;
            pm.city = acc.Ville__r.Name;
        }else if (typeContrat == 'CDD'){
            pm = null;
        }

        return pm;


    }

    // si besoin de faire du mapping champ par champ
    public static SubscribeIn mapToSubscribeIn(Object objIn){
        
        SubscribeIn subIn;
        if (objIn instanceof WSZ.AcquisitionIn) {
            //subIn = (SubscribeIn)objIn;
            subIn = (SubscribeIn)JSON.deserialize(JSON.serialize(objIn,true), SubscribeIn.class);
            // champ1..
            // champ2...etc.

        }else if (objIn instanceof WSZ.PreviewIn){
            subIn = (SubscribeIn)JSON.deserialize(JSON.serialize(objIn,true), SubscribeIn.class);
        }
        return subIn;

    }

    public class SubscribeIn {
        public Date dateDebutContrat;
        public String lieu;
        public String agent;
        public String coupon;
        public String operation;
        //public String produit;
        public String codeOffreCo;
        public String modeLivraison;
        public String numCarteParrain;
        public String iban;
        public String mandateId;
        public List<String> produit;
        public WSZ.Paiement paiement;
        public String payeurSFID;

        // public SubscribeIn(Date dateDebutContrat, String lieu,String agent, String coupon,List<String> produit,String codeOffreCo, String modeLivraison,
        // String numCarteParrain, String iban, String mandateId, WSZ.Paiement paiement){
        //     this.dateDebutContrat = dateDebutContrat;
        //     this.lieu = lieu;
        //     this.agent = agent;
        //     this.coupon = coupon;
        //     this.operation = operation;
        //     this.produit = produit;
        //     this.codeOffreCo = codeOffreCo;
        //     this.modeLivraison = modeLivraison;
        //     this.numCarteParrain = numCarteParrain;
        //     this.iban = iban;
        //     this.mandateId = mandateId;
        //     this.paiement = paiement;    
        //     //this.payeurSFID = payeurSFID;        
        // }        
    }    

}