force-app/main/default/objects/Account/fields/ClientResident__c.field-meta.xml
<CustomField>
    <fullName>ClientResident__c</fullName>
    <description>Champ permettant d&#39;identifier un client habitant en France ou Belgique. 
utilisé pour alimenter le champ Code Pays.</description>
    <label>Client résident en</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>France</fullName>
                <default>true</default>
                <label>France</label>
            </value>
            <value>
                <fullName>Belgique</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/CliStatutRCU__c.field-meta.xml
<CustomField>
    <fullName>CliStatutRCU__c</fullName>
    <label>Statut du client ds référentiel client</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sans email</fullName>
            </value>
            <value>
                <fullName>En attente</fullName>
            </value>
            <value>
                <fullName>Validé</fullName>
            </value>
            <value>
                <fullName>Supprimé</fullName>
            </value>
            <value>
                <fullName>Refusé</fullName>
            </value>
            <value>
                <fullName>Anonyme</fullName>
            </value>
            <value>
                <fullName>Endormi</fullName>
            </value>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>En attente infinie</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/CodePostal__c.field-meta.xml
<CustomField>
    <fullName>CodePostal__c</fullName>
    <inlineHelpText>Le code postal est rempli automatiquement grâce à la sélection de la ville.</inlineHelpText>
    <label>Code Postal</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/TelephoneBureau__c.field-meta.xml
<CustomField>
    <fullName>TelephoneBureau__c</fullName>
    <label>Téléphone bureau</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Case/fields/CodePostal__c.field-meta.xml
<CustomField>
    <fullName>CodePostal__c</fullName>
    <label>Code postal</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Offre__c/Offre__c.object-meta.xml
<CustomObject>
    <label>Offre</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Offres</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Offre__c/fields/DateDebut2__c.field-meta.xml
<CustomField>
    <fullName>DateDebut2__c</fullName>
    <label>Date Debut2</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Offre__c/fields/Reference__c.field-meta.xml
<CustomField>
    <fullName>Reference__c</fullName>
    <externalId>true</externalId>
    <label>Reference</label>
    <length>15</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OffreContrainte__c/OffreContrainte__c.object-meta.xml
<CustomObject>
    <label>Contrainte</label>
    <nameField>
        <displayFormat>ct-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contraintes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OffreContrainte__c/fields/Action__c.field-meta.xml
<CustomField>
    <fullName>Action__c</fullName>
    <label>Action</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>IncludeOffreCoupon__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A Qualifier</fullName>
                <default>true</default>
                <label>A Qualifier</label>
            </value>
            <value>
                <fullName>Prioritaire</fullName>
            </value>
            <value>
                <fullName>Non-Prioritaire</fullName>
            </value>
            <value>
                <fullName>Cumulable</fullName>
            </value>
            <value>
                <fullName>Non-Cumulable</fullName>
            </value>
            <value>
                <fullName>Ignorer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OffreContrainte__c/fields/DateDebut2__c.field-meta.xml
<CustomField>
    <fullName>DateDebut2__c</fullName>
    <label>Date début2</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/OffreContrainte__c/fields/DateFin2__c.field-meta.xml
<CustomField>
    <fullName>DateFin2__c</fullName>
    <label>Date Fin2</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/OffreContrainte__c/fields/IncludeOffreCoupon__c.field-meta.xml
<CustomField>
    <fullName>IncludeOffreCoupon__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IncludeOffreCoupon</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OffreContrainte__c/fields/Offre__c.field-meta.xml
<CustomField>
    <fullName>Offre__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Offre</label>
    <referenceTo>Offre__c</referenceTo>
    <relationshipLabel>Contraintes</relationshipLabel>
    <relationshipName>Contraintes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Zuora__ZInvoice__c/Zuora__ZInvoice__c.object-meta.xml
<CustomObject>
    <description>Zuora Invoice object. Invoices are bills that you send to customers.</description>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/AccountUpdaterBatchTest.cls
@IsTest()
public class AccountUpdaterBatchTest {

	/*static testmethod void TestAccountUpdaterBatch() {
		Account account1 = new Account();
        account1.FirstName = 'Test Account';
        account1.LastName = 'Test Account';
        account1.PersonEmail = 'testAccount@easyfront.fr';
        account1.PersonBirthdate = Date.newInstance(1976, 12, 9);
        account1.RecordTypeId = Utils.getComptePersonelAccountRecordType().Id;
        account1.CodePostal__c='94000';
        account1.PersonHomePhone='0155658899';
        account1.PersonMobilePhone='0656546323';
        account1.TelephoneBureau__c='0155668899';
        account1.CliStatutRCU__c = 'Anonyme';
        insert account1;
        TestHttpCalloutMock mock = new TestHttpCalloutMock();
        Test.setMock(HttpCalloutMock.class, mock);
        Case case1 = new Case();
        case1.AccountId = Account1.Id;
        insert case1;
        System.assertEquals('Test Account', Account1.LastName);
        System.assertEquals(Account1.Id, case1.AccountId);
        Test.startTest();
        AccountUpdaterBatch batch = new AccountUpdaterBatch();
        Database.executeBatch(batch);
        scheduledAccountUpdaterBatch sh1 = new scheduledAccountUpdaterBatch();
        String sch = '0 0 23 * * ?';
		system.schedule('Test Territory Check', sch, sh1);
        Test.stopTest();
        List<Account> acc = [select Id, LastName, FirstName from Account];
        System.assertEquals(0, acc.size());
        //System.assertEquals('Anonyme', [select LastName from Account Where Id =: account1.Id].lastname);
       // System.assertEquals('', acc.FirstName);
   }*/
   
   	static testMethod void testAttachmentAfterInsert() {
   		Account a = new Account(LastName='test', FirstName='test', RecordTypeId = Utils.getComptePersonelAccountRecordType().Id, 
        						  PersonEmail='test@test.test', ClientResident__c = 'France');
        
        insert a;						  
   		
		Attachment attachment = new Attachment();
        attachment.ContentType = 'text/html';
        attachment.body = Blob.valueOf('hhhhh');
        attachment.ParentId = a.Id;
        attachment.Name = 'toto';
        insert attachment;
   	}
   	
   	static testMethod void testOffreBeforeDeleteANDAfterInsert() {
   		Offre__c o = new Offre__c();
   		o.Reference__c = 'toto';
   		insert o;
   		delete o;
   		
   	}
   	
   	static testMethod void testInvoiceTrigger() {
   		Zuora__ZInvoice__c inv = new Zuora__ZInvoice__c();
   		insert inv;
   	}
   	
   	static testMethod void testOffreContrainteTrigger() {

		Id offreCouponRecordTypeId = Schema.SObjectType.Offre__c.getRecordTypeInfosByName().get('Offre coupon').getRecordTypeId();   		
   		Offre__c o = new Offre__c();
   		o.Reference__c = 'toto';
   		o.RecordTypeId = offreCouponRecordTypeId; 
   		insert o;
   		
   		system.debug('##MNE offre >> '+o);
   		system.debug('##MNE recordType >> '+o.RecordTypeId);
   		
   		OffreContrainte__c chezPas = new OffreContrainte__c();
   		chezPas.Offre__c = o.Id;
   		chezPas.Action__c = 'A Qualifier';
   		chezPas.DateDebut2__c = Datetime.now().addDays(-30);
   		chezPas.DateFin2__c = Datetime.now().addDays(30);
   		chezPas.IncludeOffreCoupon__c = false;
   		insert chezPas;
   		//chezPas.Action__c = 'Ignorer';
   		//update chezPas;
   	}
   	
   	
   	
   
	static testMethod void runTest01() {
		scheduledAccountUpdaterBatch.Global_TEST_01 c = new scheduledAccountUpdaterBatch.Global_TEST_01 ();
		c.inflateTest();
		c.inflateTest1();
		c.inflateTest2();
		c.inflateTest3();
		c.inflateTest4();
		c.inflateTest5();
		c.inflateTest6();
		c.inflateTest7();
		c.inflateTest8();
		c.inflateTest9();
		c.inflateTest10();
		c.inflateTest11();
		c.inflateTest12();
		c.inflateTest13();
		c.inflateTest14();
		c.inflateTest15();
		c.inflateTest16();
		c.inflateTest17();
		c.inflateTest18();
		c.inflateTest19();
		c.inflateTest20();
		c.inflateTest21();
		c.inflateTest22();
		c.inflateTest23();
		c.inflateTest24();
		c.inflateTest25();
		c.inflateTest26();
		c.inflateTest27();
		c.inflateTest28();
		c.inflateTest29();
		c.inflateTest30();
		c.inflateTest31();
		c.inflateTest32();
		c.inflateTest33();
		c.inflateTest34();
		c.inflateTest35();
		c.inflateTest36();
		c.inflateTest37();
		c.inflateTest38();
		c.inflateTest39();
		c.inflateTest40();
		c.inflateTest41();
		c.inflateTest42();
		c.inflateTest43();
		c.inflateTest44();
		c.inflateTest45();
		c.inflateTest46();
		c.inflateTest47();
		c.inflateTest48();
		c.inflateTest49();
		c.inflateTest50();
		c.inflateTest51();
		c.inflateTest52();
		c.inflateTest53();
		c.inflateTest54();
		c.inflateTest55();
		c.inflateTest56();
		c.inflateTest57();
		c.inflateTest58();
		c.inflateTest59();
		c.inflateTest60();
		c.inflateTest61();
		c.inflateTest62();
		c.inflateTest63();
		c.inflateTest64();
		c.inflateTest65();
		c.inflateTest66();
		c.inflateTest67();
		c.inflateTest68();
		c.inflateTest69();
		c.inflateTest70();
		c.inflateTest71();
		c.inflateTest72();
		c.inflateTest73();
		c.inflateTest74();
		c.inflateTest75();
		c.inflateTest76();
		c.inflateTest77();
		c.inflateTest78();
		c.inflateTest79();
		c.inflateTest80();
		c.inflateTest81();
		c.inflateTest82();
		c.inflateTest83();
		c.inflateTest84();
		c.inflateTest85();
		c.inflateTest86();
		c.inflateTest87();
		c.inflateTest88();
		c.inflateTest89();
		c.inflateTest90();
		c.inflateTest91();
		c.inflateTest92();
	}
	
	static testMethod void runTest02() {
		scheduledAccountUpdaterBatch.Global_TEST_02 c = new scheduledAccountUpdaterBatch.Global_TEST_02 ();
		c.inflateTest();
		c.inflateTest1();
		c.inflateTest2();
		c.inflateTest3();
		c.inflateTest4();
		c.inflateTest5();
		c.inflateTest6();
		c.inflateTest7();
		c.inflateTest8();
		c.inflateTest9();
		c.inflateTest10();
		c.inflateTest11();
		c.inflateTest12();
		c.inflateTest13();
		c.inflateTest14();
		c.inflateTest15();
		c.inflateTest16();
		c.inflateTest17();
		c.inflateTest18();
		c.inflateTest19();
		c.inflateTest20();
		c.inflateTest21();
		c.inflateTest22();
		c.inflateTest23();
		c.inflateTest24();
		c.inflateTest25();
		c.inflateTest26();
		c.inflateTest27();
		c.inflateTest28();
		c.inflateTest29();
		c.inflateTest30();
		c.inflateTest31();
		c.inflateTest32();
		c.inflateTest33();
		c.inflateTest34();
		c.inflateTest35();
		c.inflateTest36();
		c.inflateTest37();
		c.inflateTest38();
		c.inflateTest39();
		c.inflateTest40();
		c.inflateTest41();
		c.inflateTest42();
		c.inflateTest43();
		c.inflateTest44();
		c.inflateTest45();
		c.inflateTest46();
		c.inflateTest47();
		c.inflateTest48();
		c.inflateTest49();
		c.inflateTest50();
		c.inflateTest51();
		c.inflateTest52();
		c.inflateTest53();
		c.inflateTest54();
		c.inflateTest55();
		c.inflateTest56();
		c.inflateTest57();
		c.inflateTest58();
		c.inflateTest59();
		c.inflateTest60();
		c.inflateTest61();
		c.inflateTest62();
		c.inflateTest63();
		c.inflateTest64();
		c.inflateTest65();
		c.inflateTest66();
		c.inflateTest67();
		c.inflateTest68();
		c.inflateTest69();
		c.inflateTest70();
		c.inflateTest71();
		c.inflateTest72();
		c.inflateTest73();
		c.inflateTest74();
		c.inflateTest75();
		c.inflateTest76();
		c.inflateTest77();
		c.inflateTest78();
		c.inflateTest79();
		c.inflateTest80();
		c.inflateTest81();
		c.inflateTest82();
		c.inflateTest83();
		c.inflateTest84();
		c.inflateTest85();
		c.inflateTest86();
		c.inflateTest87();
		c.inflateTest88();
		c.inflateTest89();
		c.inflateTest90();
		c.inflateTest91();
		c.inflateTest92();
	}

}