force-app/main/default/objects/Account/fields/ClientResident__c.field-meta.xml
<CustomField>
    <fullName>ClientResident__c</fullName>
    <description>Champ permettant d&#39;identifier un client habitant en France ou Belgique. 
utilisé pour alimenter le champ Code Pays.</description>
    <label>Client résident en</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>France</fullName>
                <default>true</default>
                <label>France</label>
            </value>
            <value>
                <fullName>Belgique</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/CodeFinContrat__c.field-meta.xml
<CustomField>
    <fullName>CodeFinContrat__c</fullName>
    <label>Code Fin Contrat</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>L</fullName>
            </value>
            <value>
                <fullName>E</fullName>
            </value>
            <value>
                <fullName>X</fullName>
            </value>
            <value>
                <fullName>M</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Eligibilite_Reabo__c.field-meta.xml
<CustomField>
    <fullName>Eligibilite_Reabo__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Flag d&#39;éligibilité de réabonnement du client</description>
    <label>Eligibilité Réabonnement</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Zuora__Subscription__c/Zuora__Subscription__c.object-meta.xml
<CustomObject>
    <description>A subscription is a product or service that has recurring charges, such as a monthly flat fee or charges based on usage. Subscriptions can also include one-time charges, such as activation fees.</description>
    <label>Subscription</label>
    <nameField>
        <label>Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Zuora__Subscription__c/fields/CodeFinContrat__c.field-meta.xml
<CustomField>
    <fullName>CodeFinContrat__c</fullName>
    <label>Code Fin Contrat</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>L</fullName>
            </value>
            <value>
                <fullName>E</fullName>
            </value>
            <value>
                <fullName>M</fullName>
            </value>
            <value>
                <fullName>X</fullName>
            </value>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>V</fullName>
            </value>
            <value>
                <fullName>S</fullName>
            </value>
            <value>
                <fullName>R</fullName>
            </value>
            <value>
                <fullName>P</fullName>
            </value>
            <value>
                <fullName>D</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Zuora__Subscription__c/fields/TypeContrat__c.field-meta.xml
<CustomField>
    <fullName>TypeContrat__c</fullName>
    <description>CDI ou CDD</description>
    <label>Type Contrat</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Zuora__Subscription__c/fields/Zuora__Account__c.field-meta.xml
<CustomField>
    <fullName>Zuora__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Zuora__Subscription__c/fields/Zuora__ContractEffectiveDate__c.field-meta.xml
<CustomField>
    <fullName>Zuora__ContractEffectiveDate__c</fullName>
    <description>This is the date on which the contract becomes effective, and will trigger charges that have their trigger event set to Upon Contract Effective.</description>
    <label>Contract Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Zuora__Subscription__c/fields/Zuora__SubscriptionEndDate__c.field-meta.xml
<CustomField>
    <fullName>Zuora__SubscriptionEndDate__c</fullName>
    <description>This is when the subscription ends. This is always equal to term end date, unless the subscription has been cancelled. If the subscription has been cancelled, this is set to the cancellation date.</description>
    <label>Subscription End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Zuora__Subscription__c/fields/Zuora__TermEndDate__c.field-meta.xml
<CustomField>
    <fullName>Zuora__TermEndDate__c</fullName>
    <label>Term End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Zuora__Subscription__c/fields/Zuora__Zuora_Id__c.field-meta.xml
<CustomField>
    <fullName>Zuora__Zuora_Id__c</fullName>
    <description>The Zuora Id (external primary key) of this Subscription.</description>
    <inlineHelpText>The Zuora Id (external primary key) of this Subscription.</inlineHelpText>
    <label>Zuora Id (Deprecated)</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TestUpdateAccountReaboTrigger.cls
@isTest
private class TestUpdateAccountReaboTrigger {
    @isTest static void TestUpdateSub1() {
        
        

        Account Acc = new Account();
        Acc.LastName ='TEST TRIG UGC LName';
        Acc.FirstName = 'TEST TRIG UGC FName';
        Acc.ClientResident__c = 'France';
        Acc.PersonEmail = 'blabla@gamil.com';
        insert Acc;
        
        Zuora__Subscription__c sub = new Zuora__Subscription__c();
        sub.Name='Test TRIG UGC Sub';
        sub.Zuora__Zuora_Id__c= 'Test TRIG UGC Sub';
        sub.Zuora__Account__c=Acc.id;
        sub.CodeFinContrat__c = 'E';
        sub.TypeContrat__c ='CDI';
        sub.Zuora__ContractEffectiveDate__c = Date.today()-100;
        sub.Zuora__SubscriptionEndDate__c = Date.today()+10;
        sub.Zuora__TermEndDate__c = Date.today()-25;
        
		insert sub;
        
        Zuora__Subscription__c sub2 = new Zuora__Subscription__c();
        sub2.Name='Test TRIG UGC Sub2';
        sub2.Zuora__Zuora_Id__c= 'Test TRIG UGC Sub2';
        sub2.Zuora__Account__c=Acc.id;
        sub2.CodeFinContrat__c = 'L';
        sub.TypeContrat__c ='CDI';
        sub2.Zuora__ContractEffectiveDate__c = Date.today()-150;
        sub2.Zuora__SubscriptionEndDate__c = Date.today()+10;
        sub2.Zuora__TermEndDate__c = Date.today()-25;
		insert sub2;
                
        list<Account> acclist = [select CodeFinContrat__c,Eligibilite_Reabo__c from Account where id =:Acc.Id];
     	
        if (acclist.size() == 0)
        	System.assertEquals(0,acclist.size());
        else
        {
            //System.assertEquals('E',acclist[0].CodeFinContrat__c);
        	//System.assertEquals(true,acclist[0].Eligibilite_Reabo__c);
        }
      
    }
    
    @isTest static void TestUpdateSub2() {
        
        

        Account Acc = new Account();
        Acc.LastName ='TEST TRIG UGC LName';
        Acc.FirstName = 'TEST TRIG UGC FName';
        Acc.ClientResident__c = 'France';
        Acc.PersonEmail = 'blabla@gamil.com';
        insert Acc;
        
        Zuora__Subscription__c sub = new Zuora__Subscription__c();
        sub.Name='Test TRIG UGC Sub';
        sub.Zuora__Zuora_Id__c= 'Test TRIG UGC Sub';
        sub.Zuora__Account__c=Acc.id;
        sub.CodeFinContrat__c = 'E';
        sub.TypeContrat__c ='CDI';
        sub.Zuora__ContractEffectiveDate__c = Date.today()-100;
        sub.Zuora__SubscriptionEndDate__c = Date.today()+10;
        sub.Zuora__TermEndDate__c = Date.today()-25;
        
		insert sub;
        
        Zuora__Subscription__c sub2 = new Zuora__Subscription__c();
        sub2.Name='Test TRIG UGC Sub2';
        sub2.Zuora__Zuora_Id__c= 'Test TRIG UGC Sub2';
        sub2.Zuora__Account__c=Acc.id;
        sub2.CodeFinContrat__c = 'L';
        sub.TypeContrat__c ='CDI';
        sub2.Zuora__ContractEffectiveDate__c = Date.today()-150;
        sub2.Zuora__SubscriptionEndDate__c = Date.today()+10;
        sub2.Zuora__TermEndDate__c = Date.today()-25;
		insert sub2;
        
        sub2.CodeFinContrat__c = 'X';
        update sub2;
                
        list<Account> acclist = [select CodeFinContrat__c,Eligibilite_Reabo__c from Account where id =:Acc.Id];
     	
        if (acclist.size() == 0)
        	System.assertEquals(0,acclist.size());
        else
        {
            //System.assertEquals('E',acclist[0].CodeFinContrat__c);
        	//System.assertEquals(true,acclist[0].Eligibilite_Reabo__c);
        }
      
    }
    @isTest static void TestUpdateSub3() {
        
        

        Account Acc = new Account();
        Acc.LastName ='TEST TRIG UGC LName';
        Acc.FirstName = 'TEST TRIG UGC FName';
        Acc.ClientResident__c = 'France';
        Acc.PersonEmail = 'blabla@gamil.com';
        insert Acc;
        
        Zuora__Subscription__c sub = new Zuora__Subscription__c();
        sub.Name='Test TRIG UGC Sub';
        sub.Zuora__Zuora_Id__c= 'Test TRIG UGC Sub';
        sub.Zuora__Account__c=Acc.id;
        sub.CodeFinContrat__c = 'E';
        sub.TypeContrat__c ='CDI';
        sub.Zuora__ContractEffectiveDate__c = Date.today()-100;
        sub.Zuora__SubscriptionEndDate__c = Date.today()+10;
        sub.Zuora__TermEndDate__c = Date.today()-25;
        
		insert sub;
        
        Zuora__Subscription__c sub2 = new Zuora__Subscription__c();
        sub2.Name='Test TRIG UGC Sub2';
        sub2.Zuora__Zuora_Id__c= 'Test TRIG UGC Sub2';
        sub2.Zuora__Account__c=Acc.id;
        sub2.CodeFinContrat__c = 'L';
        sub.TypeContrat__c ='CDI';
        sub2.Zuora__ContractEffectiveDate__c = Date.today()-150;
        sub2.Zuora__SubscriptionEndDate__c = Date.today()+10;
        sub2.Zuora__TermEndDate__c = Date.today()-25;
		insert sub2;
        
        sub.Zuora__ContractEffectiveDate__c = Date.today()-200;
        update sub;
                
        list<Account> acclist = [select CodeFinContrat__c,Eligibilite_Reabo__c from Account where id =:Acc.Id];
     	
        if (acclist.size() == 0)
        	System.assertEquals(0,acclist.size());
        else
        {
            //System.assertEquals('E',acclist[0].CodeFinContrat__c);
        	//System.assertEquals(true,acclist[0].Eligibilite_Reabo__c);
        }
      
    }
    
    @isTest static void TestUpdateSub4() {
        
        

        Account Acc = new Account();
        Acc.LastName ='TEST TRIG UGC LName';
        Acc.FirstName = 'TEST TRIG UGC FName';
        Acc.ClientResident__c = 'France';
        Acc.PersonEmail = 'blabla@gamil.com';
        insert Acc;
        
        Zuora__Subscription__c sub = new Zuora__Subscription__c();
        sub.Name='Test TRIG UGC Sub';
        sub.Zuora__Zuora_Id__c= 'Test TRIG UGC Sub';
        sub.Zuora__Account__c=Acc.id;
        sub.CodeFinContrat__c = 'E';
        sub.TypeContrat__c ='CDI';
        sub.Zuora__ContractEffectiveDate__c = Date.today()-100;
        sub.Zuora__SubscriptionEndDate__c = Date.today()+10;
        sub.Zuora__TermEndDate__c = Date.today()-25;
        
		insert sub;
        
        Zuora__Subscription__c sub2 = new Zuora__Subscription__c();
        sub2.Name='Test TRIG UGC Sub2';
        sub2.Zuora__Zuora_Id__c= 'Test TRIG UGC Sub2';
        sub2.Zuora__Account__c=Acc.id;
        sub2.CodeFinContrat__c = 'L';
        sub.TypeContrat__c ='CDI';
        sub2.Zuora__ContractEffectiveDate__c = Date.today()-150;
        sub2.Zuora__SubscriptionEndDate__c = Date.today()-100;
        sub2.Zuora__TermEndDate__c = Date.today()-100;
		insert sub2;
        
        sub.Zuora__ContractEffectiveDate__c = Date.today()-200;
        sub.CodeFinContrat__c = 'M';
        update sub;
                
        list<Account> acclist = [select CodeFinContrat__c,Eligibilite_Reabo__c from Account where id =:Acc.Id];
     	
        if (acclist.size() == 0)
        	System.assertEquals(0,acclist.size());
        else
        {
            //System.assertEquals('L',acclist[0].CodeFinContrat__c);
        	//System.assertEquals(false,acclist[0].Eligibilite_Reabo__c);
        }
      
    }
    
    
    
}