force-app/main/default/objects/Account/fields/ClientResident__c.field-meta.xml
<CustomField>
    <fullName>ClientResident__c</fullName>
    <description>Champ permettant d&#39;identifier un client habitant en France ou Belgique. 
utilisé pour alimenter le champ Code Pays.</description>
    <label>Client résident en</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>France</fullName>
                <default>true</default>
                <label>France</label>
            </value>
            <value>
                <fullName>Belgique</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/TECH_idCritizr__c.field-meta.xml
<CustomField>
    <fullName>TECH_idCritizr__c</fullName>
    <label>TECH_idCritizr</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/TECH_idFacebook__c.field-meta.xml
<CustomField>
    <fullName>TECH_idFacebook__c</fullName>
    <label>TECH_idFacebook</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/TECH_idInstagram__c.field-meta.xml
<CustomField>
    <fullName>TECH_idInstagram__c</fullName>
    <label>TECH_idInstagram</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/TECH_idTwitter__c.field-meta.xml
<CustomField>
    <fullName>TECH_idTwitter__c</fullName>
    <label>TECH_idTwitter</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Famille__c.field-meta.xml
<CustomField>
    <fullName>Famille__c</fullName>
    <label>Famille</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0- Souscription</fullName>
            </value>
            <value>
                <fullName>1- Vie de l&#39;abonnement</fullName>
            </value>
            <value>
                <fullName>2- Club UGC / fidelite</fullName>
            </value>
            <value>
                <fullName>3- Autres Produits</fullName>
            </value>
            <value>
                <fullName>4- Reservation</fullName>
                <label>4- Réservation</label>
            </value>
            <value>
                <fullName>5- Compte client</fullName>
            </value>
            <value>
                <fullName>6- Prospection</fullName>
            </value>
            <value>
                <fullName>7- Finance</fullName>
            </value>
            <value>
                <fullName>8- Cinema</fullName>
                <label>8- Cinéma</label>
            </value>
            <value>
                <fullName>9- Divers</fullName>
            </value>
            <value>
                <fullName>0- Commentaires</fullName>
                <isActive>false</isActive>
                <label>0- Commentaires</label>
            </value>
            <value>
                <fullName>1- Demandes d info UI</fullName>
                <isActive>false</isActive>
                <label>1- Demandes d info UI</label>
            </value>
            <value>
                <fullName>1- Demandes d&#39;info UI</fullName>
                <isActive>false</isActive>
                <label>1- Demandes d&#39;info UI</label>
            </value>
            <value>
                <fullName>2- Demande d infos generales</fullName>
                <isActive>false</isActive>
                <label>2- Demande d infos generales</label>
            </value>
            <value>
                <fullName>2- Demande d&#39;infos générales</fullName>
                <isActive>false</isActive>
                <label>2- Demande d&#39;infos générales</label>
            </value>
            <value>
                <fullName>3- Autres demandes d&#39;informations</fullName>
                <isActive>false</isActive>
                <label>3- Autres demandes d&#39;informations</label>
            </value>
            <value>
                <fullName>4- Abonnement Carte UGC</fullName>
                <isActive>false</isActive>
                <label>4- Abonnement Carte UGC</label>
            </value>
            <value>
                <fullName>5- Abonnement en attente</fullName>
                <isActive>false</isActive>
                <label>5- Abonnement en attente</label>
            </value>
            <value>
                <fullName>6- GestionCompteUI</fullName>
                <isActive>false</isActive>
                <label>6- GestionCompteUI</label>
            </value>
            <value>
                <fullName>7- Réclamations UI</fullName>
                <isActive>false</isActive>
                <label>7- Réclamations UI</label>
            </value>
            <value>
                <fullName>8- Autres types de reclamations</fullName>
                <isActive>false</isActive>
                <label>8- Autres types de reclamations</label>
            </value>
            <value>
                <fullName>8- Autres types de réclamations</fullName>
                <isActive>false</isActive>
                <label>8- Autres types de réclamations</label>
            </value>
            <value>
                <fullName>9- Supports Digitaux</fullName>
                <isActive>false</isActive>
                <label>9- Supports Digitaux</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Motif__c.field-meta.xml
<CustomField>
    <fullName>Motif__c</fullName>
    <label>Motif</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Famille__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>01- Info process abo</fullName>
            </value>
            <value>
                <fullName>02- Erreur prise abo</fullName>
            </value>
            <value>
                <fullName>03- Click and collect</fullName>
            </value>
            <value>
                <fullName>05- B2B</fullName>
            </value>
            <value>
                <fullName>06- VPC</fullName>
            </value>
            <value>
                <fullName>07- Creation Abonnement</fullName>
            </value>
            <value>
                <fullName>01- Reception carte</fullName>
                <label>01- Réception carte</label>
            </value>
            <value>
                <fullName>02- Reedition payante</fullName>
            </value>
            <value>
                <fullName>03- Reedition gratuite</fullName>
            </value>
            <value>
                <fullName>04- Desabonnement</fullName>
            </value>
            <value>
                <fullName>05- Resiliation</fullName>
            </value>
            <value>
                <fullName>06- Migration UI 1/2/3</fullName>
            </value>
            <value>
                <fullName>07- Reabonnement</fullName>
            </value>
            <value>
                <fullName>08- Retention</fullName>
            </value>
            <value>
                <fullName>09- Retour Carte</fullName>
            </value>
            <value>
                <fullName>10- Retractation</fullName>
            </value>
            <value>
                <fullName>11- Avertissement</fullName>
            </value>
            <value>
                <fullName>12- Annulation Migration</fullName>
            </value>
            <value>
                <fullName>13- Annulation Contrat</fullName>
            </value>
            <value>
                <fullName>04- Dematerialise</fullName>
                <label>04- Dématérialisé</label>
            </value>
            <value>
                <fullName>01- Inscription</fullName>
            </value>
            <value>
                <fullName>02- Solde de points</fullName>
            </value>
            <value>
                <fullName>03- Echange de points</fullName>
            </value>
            <value>
                <fullName>04- Fonctionnement Club</fullName>
            </value>
            <value>
                <fullName>01- Offres UGC</fullName>
            </value>
            <value>
                <fullName>02- Formules UGC+</fullName>
            </value>
            <value>
                <fullName>03- Solo</fullName>
            </value>
            <value>
                <fullName>04- Blue</fullName>
            </value>
            <value>
                <fullName>05- VLO</fullName>
            </value>
            <value>
                <fullName>01- Modalites de reservation</fullName>
                <label>01- Modalités de réservation</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/SousMotif__c.field-meta.xml
<CustomField>
    <fullName>SousMotif__c</fullName>
    <label>Sous-motif</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Motif__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>I- Info</fullName>
            </value>
            <value>
                <fullName>R- Récla</fullName>
            </value>
            <value>
                <fullName>A- Action</fullName>
            </value>
            <value>
                <fullName>Click to Call Info</fullName>
            </value>
            <value>
                <fullName>Click to Call Recla</fullName>
            </value>
            <value>
                <fullName>AD- Action DRC</fullName>
            </value>
            <value>
                <fullName>AS- Action Stand</fullName>
            </value>
            <value>
                <fullName>AH- Action Selfcare</fullName>
            </value>
            <value>
                <fullName>R1- 1er rejet</fullName>
            </value>
            <value>
                <fullName>R2- 2nd rejet</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/TECH_idCritizr__c.field-meta.xml
<CustomField>
    <fullName>TECH_idCritizr__c</fullName>
    <label>TECH_idCritizr</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/TECH_idFacebook__c.field-meta.xml
<CustomField>
    <fullName>TECH_idFacebook__c</fullName>
    <label>TECH_idFacebook</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/TECH_idInstagram__c.field-meta.xml
<CustomField>
    <fullName>TECH_idInstagram__c</fullName>
    <label>TECH_idInstagram</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/TECH_idTwitter__c.field-meta.xml
<CustomField>
    <fullName>TECH_idTwitter__c</fullName>
    <label>TECH_idTwitter</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contacts__c/Contacts__c.object-meta.xml
<CustomObject>
    <label>Contacts</label>
    <nameField>
        <label>ID du statut</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contacts__c/fields/Famille_Statut__c.field-meta.xml
<CustomField>
    <fullName>Famille_Statut__c</fullName>
    <label>Famille Statut</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contacts__c/fields/Motif_Statut__c.field-meta.xml
<CustomField>
    <fullName>Motif_Statut__c</fullName>
    <label>Motif Statut</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contacts__c/fields/SousMotif_Statut__c.field-meta.xml
<CustomField>
    <fullName>SousMotif_Statut__c</fullName>
    <label>Sous-Motif Statut</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contacts__c/fields/ValeurALCMEON__c.field-meta.xml
<CustomField>
    <fullName>ValeurALCMEON__c</fullName>
    <label>Valeur ALCMEON</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Rejected_Notification__c/Rejected_Notification__c.object-meta.xml
<CustomObject>
    <label>Rejected Notification</label>
    <nameField>
        <displayFormat>RN-{0000}</displayFormat>
        <label>Rejected Notification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rejected Notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Rejected_Notification__c/fields/json__c.field-meta.xml
<CustomField>
    <fullName>json__c</fullName>
    <label>json</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/AlcmeonNotificationHandler_Test.cls
@IsTest
public class AlcmeonNotificationHandler_Test {
    
    private static void  handleCases(String jsonEntry){
        
        Test.startTest();
        
        //As Per Best Practice it is important to instantiate the Rest Context 
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();
        
        req.requestURI = '/services/apexrest/AlcmeonNotification/*';  //Request URL
        req.httpMethod = 'POST';//HTTP Request Type
        req.requestBody = Blob.valueof(jsonEntry);
        RestContext.request = req;
        RestContext.response= res;
        String resp = AlcmeonNotificationHandler.HandleCases();
      
        Test.stopTest();
        
    }
    
    @IsTest
    static void handleNonAnswerTest() {
    	Test.setMock(HttpCalloutMock.class, new TestHttpCalloutMock());
    	
    	
    	String jsonEntry = '[{"action": {"status": "ok", "account": {"type": "facebook", "id": 220, "name": "UGC"},' 
        	+ ' "task": {"tags": [{"id": 3, "value": {"id": 74, "value": {"fr": "Fran\\u00e7ais", "en": "French", "nl": "Frans", "es": "Franc\\u00e9s"}},' 
        	+ '  "name": {"fr": "Langue", "en": "Language", "nl": "Taal", "es": "Idioma"}},' 
        	+ '  {"id": 40, "value": {"id": 440, "value": {"fr": "Aucun", "en": "None", "nl": "Geen", "es": "Ninguna"}},' 
        	+ '  "name": {"fr": "Motifs de contacts", "en": "Motifs de contacts", "nl": "Motifs de contacts", "es": "Motifs de contacts"}},' 
        	+ '  {"id": 47, "value": {"id": 476, "value": {"fr": "Aucun", "en": "None", "nl": "Geen", "es": "Ninguna"}},' 
        	+ '  "name": {"fr": "Motifs de contacts 2", "en": "Motifs de contacts 2", "nl": "Motifs de contacts 2", "es": "Motifs de contacts 2"}}],' 
        	+ '  "url": "https://alcmeon.com/c/65/task/20173641/acquire-and-process/", "state": "pending", "conversation_id": 18194699,' 
        	+ '  "message": {"content": "belle phrase", "attachments": [], "time": "17:31:26", "date": "2017-10-30",' 
        	+ '  "author": {"facebook_author": {"first_name": "Oussama", "last_name": "Jabbari", "name": "Oussama Jabbari"},' 
        	+ '  "id": 9432384, "name": "Oussama Jabbari"}, "external_id": "1666773876706562_1675753925808557",' 
        	+ '  "id": 28994810, "is_private": 0, "discussion_id": 18717657}, "id": 20173641},' 
        	+ '  "user": {"is_bot": 1, "id": 1302, "name": "Alcmeon Bot", "email": "alcmeon-bot-company-65@alc.cx"}, "time": "17:31:39", "date": "2017-10-30",' 
        	+ '  "type": "task-create", "id": 18095064}, "id": 1}]';
        AlcmeonNotificationHandler_Test.handleCases(jsonEntry);
        List<Case> cases = [SELECT Id FROM Case];
       
    }
    
    
    @IsTest
    static void isError() {
    	Test.setMock(HttpCalloutMock.class, new TestHttpCalloutMock());
    	
    	
    	String jsonEntry = '{"action": {"status": "ok", "account": {"type": "facebook", "id": 220, "name": "UGC"},' 
        	+ ' "task": {"tags": [{"id": 3, "value": {"id": 74, "value": {"fr": "Fran\\u00e7ais", "en": "French", "nl": "Frans", "es": "Franc\\u00e9s"}},' 
        	+ '  "name": {"fr": "Langue", "en": "Language", "nl": "Taal", "es": "Idioma"}},' 
        	+ '  {"id": 40, "value": {"id": 440, "value": {"fr": "Aucun", "en": "None", "nl": "Geen", "es": "Ninguna"}},' 
        	+ '  "name": {"fr": "Motifs de contacts", "en": "Motifs de contacts", "nl": "Motifs de contacts", "es": "Motifs de contacts"}},' 
        	+ '  {"id": 47, "value": {"id": 476, "value": {"fr": "Aucun", "en": "None", "nl": "Geen", "es": "Ninguna"}},' 
        	+ '  "name": {"fr": "Motifs de contacts 2", "en": "Motifs de contacts 2", "nl": "Motifs de contacts 2", "es": "Motifs de contacts 2"}}],' 
        	+ '  "url": "https://alcmeon.com/c/65/task/20173641/acquire-and-process/", "state": "pending", "conversation_id": 18194699,' 
        	+ '  "message": {"content": "belle phrase", "attachments": [], "time": "17:31:26", "date": "2017-10-30",' 
        	+ '  "author": {"facebook_author": {"first_name": "Oussama", "last_name": "Jabbari", "name": "Oussama Jabbari"},' 
        	+ '  "id": 9432384, "name": "Oussama Jabbari"}, "external_id": "1666773876706562_1675753925808557",' 
        	+ '  "id": 28994810, "is_private": 0, "discussion_id": 18717657}, "id": 20173641},' 
        	+ '  "user": {"is_bot": 1, "id": 1302, "name": "Alcmeon Bot", "email": "alcmeon-bot-company-65@alc.cx"}, "time": "17:31:39", "date": "2017-10-30",' 
        	+ '  "type": "task-create", "id": 18095064}, "id": 1}';
        AlcmeonNotificationHandler_Test.handleCases(jsonEntry);
       
    }
    
    
    
    
    
    
    @IsTest
    static void handleEmptyTest() {
    	Test.setMock(HttpCalloutMock.class, new TestHttpCalloutMock());
    	
    	
    	String jsonEntry = '';
        handleCases(jsonEntry);
        List<Case> cases = [SELECT Id FROM Case];
        system.assertEquals(0, cases.size());
    }
    
    @IsTest 
    static void handleAnswerTest() {
    	Test.setMock(HttpCalloutMock.class, new TestHttpCalloutMock());
    	
    	
    	Utils.createContactInconnu();
    	
    	Profile prof = [select id from profile where name = 'Chargé de Clientèle'];
    	
    	User u = new user();
		u.LastName = 'Boudot';
		u.Email = 'chargeclientele03@ugc.fr';
		u.Alias = 'Tcode';
		u.Username = 'chargeclientele03@ugc.fr';
		u.CommunityNickname = 'test12';
		u.LocaleSidKey = 'en_US';
		u.TimeZoneSidKey = 'GMT';
		u.ProfileID = prof.Id;
		u.LanguageLocaleKey = 'en_US';
		u.EmailEncodingKey = 'UTF-8';
		insert u;
		
		Contacts__c c = new Contacts__c();
        /*
		c.ValeurALCMEON__c = '008 Autres';
		c.Famille_Statut__c = '6- GestionCompteUI';
		c.Motif_Statut__c = '1- Réédition de carte gratuite';
		c.SousMotif_Statut__c = '6- Réedition sans frais';
		*/
		c.ValeurALCMEON__c = '115 réclamation solde de points';
		c.Famille_Statut__c = '9- Supports Digitaux';
		c.Motif_Statut__c = '3- UGC fidélité';
		c.SousMotif_Statut__c = '5- Réclamation solde de points';
		
		insert c;
    	String jsonEntry = '[{"action": {"status": "pending", "account": {"type": "critizr", "id": 250, "name": "UGC / Critizr"},' 
        	+ '  "task": {"tags": [{"id": 3, "value": {"id": 74, "value": {"fr": "Fran\\u00e7ais", "en": "French", "nl": "Frans", "es": "Franc\\u00e9s"}},' 
        	+ '  "name": {"fr": "Langue", "en": "Language", "nl": "Taal", "es": "Idioma"}},' 
        	+ '  {"id": 40, "value": {"id": 472,' 
        	+ '  "value": {"fr": "008 Autres", "en": "Infos Services Produits Digital",' 
        	+ '  "nl": "Infos Services Produits Digital", "es": "Infos Services Produits Digital"}},' 
        	+ '  "name": {"fr": "Motifs de contacts", "en": "Motifs de contacts", "nl": "Motifs de contacts", "es": "Motifs de contacts"}},' 
        	+ '  {"id": 47, "value": {"id": 504, "value": {"fr": "115 réclamation solde de points", "en": "115 réclamation solde de points",' 
        	+ '  "nl": "115 réclamation solde de points", "es": "115 réclamation solde de points"}},' 
        	+ '  "name": {"fr": "Motifs de contacts 2", "en": "Motifs de contacts 2", "nl": "Motifs de contacts 2", "es": "Motifs de contacts 2"}}],' 
        	+ '  "url": "https://alcmeon.com/c/65/task/20161430/acquire-and-process/", "state": "assigned", "conversation_id": 18189955,' 
        	+ '  "message": {"content": "Le cin\\u00e9ma est tr\\u00e8s tr\\u00e8s bien et la qualit\\u00e9 est pr\\u00e9sente ",' 
        	+ '  "attachments": [], "time": "11:33:22", "date": "2017-10-29", "author": {"id": 9429465, "name": "Marius"},' 
        	+ '  "external_id": "4179067", "id": 28973214, "is_private": 0, "discussion_id": 18750901}, "id": 20161430},' 
        	+ '  "data": {"answers": [{"content": "Bonjour Marius,\\nNous vous remercions de votre compliment et esp\\u00e9rons vous revoir bient\\u00f4t.\\nBien \\u00e0 vous,\\nFlorian/UGC",' 
        	+ '  "pictures": []}], "is_private": 0},' 
        	+ '  "user": {"is_bot": 0, "id": 882, "name": "Florian Boudot", "email": "chargeclientele03@ugc.fr"}' 
        	+ ' , "time": "17:39:06", "date": "2017-10-30", "type": "answer", "id": 18095600}, "id": 22}]';
    	
		handleCases(jsonEntry);
    	
    	
        List<Case> cases = [SELECT Id, Origin, OwnerId, TECH_idCritizr__c, AccountId, Famille__c, Motif__c, SousMotif__c FROM Case];
      
        
        List<Task> tasks = [SELECT Id, WhatId, WhoId, Origine__c, Description, ActivityDate, OwnerId FROM Task];
        
       
        //Date d = Date.valueOf('2017-10-30');
        Boolean messageOk = false;
        Boolean answerOk = false;
        String descriptions = '';
        for(Task task: tasks) {
        	
        	descriptions += '\n' + task.description;
        	if(task.description == 'Le cinéma est très très bien et la qualité est présente') {
        		messageOk = true;
        	}
        	if(task.description == 'Bonjour Marius,\nNous vous remercions de votre compliment et espérons vous revoir bientôt.\nBien à vous,\nFlorian/UGC') {
        		answerOk = true;
        	}
        }
      
        
    }
    
      @IsTest 
    static void handleAnswerTeswittert() {
    	Test.setMock(HttpCalloutMock.class, new TestHttpCalloutMock());
    	Utils.createContactInconnu();
    	
    	Profile prof = [select id from profile where name = 'Chargé de Clientèle'];
    	
    	User u = new user();
		u.LastName = 'Boudot';
		u.Email = 'chargeclientele03@ugc.fr';
		u.Alias = 'Tcode';
		u.Username = 'chargeclientele03@ugc.fr';
		u.CommunityNickname = 'test12';
		u.LocaleSidKey = 'en_US';
		u.TimeZoneSidKey = 'GMT';
		u.ProfileID = prof.Id;
		u.LanguageLocaleKey = 'en_US';
		u.EmailEncodingKey = 'UTF-8';
		insert u;
		
		Contacts__c c = new Contacts__c();
        /*
		c.ValeurALCMEON__c = '008 Autres';
		c.Famille_Statut__c = '6- GestionCompteUI';
		c.Motif_Statut__c = '1- Réédition de carte gratuite';
		c.SousMotif_Statut__c = '6- Réedition sans frais';
		*/
		c.ValeurALCMEON__c = '115 réclamation solde de points';
		c.Famille_Statut__c = '9- Supports Digitaux';
		c.Motif_Statut__c = '3- UGC fidélité';
		c.SousMotif_Statut__c = '5- Réclamation solde de points';
		
		insert c;
    	String jsonEntry = '[{"action": {"status": "pending", "account": {"type": "twitter", "id": 250, "name": "UGC / Critizr"},' 
        	+ '  "task": {"tags": [{"id": 3, "value": {"id": 74, "value": {"fr": "Fran\\u00e7ais", "en": "French", "nl": "Frans", "es": "Franc\\u00e9s"}},' 
        	+ '  "name": {"fr": "Langue", "en": "Language", "nl": "Taal", "es": "Idioma"}},' 
        	+ '  {"id": 40, "value": {"id": 472,' 
        	+ '  "value": {"fr": "008 Autres", "en": "Infos Services Produits Digital",' 
        	+ '  "nl": "Infos Services Produits Digital", "es": "Infos Services Produits Digital"}},' 
        	+ '  "name": {"fr": "Motifs de contacts", "en": "Motifs de contacts", "nl": "Motifs de contacts", "es": "Motifs de contacts"}},' 
        	+ '  {"id": 47, "value": {"id": 504, "value": {"fr": "115 réclamation solde de points", "en": "115 réclamation solde de points",' 
        	+ '  "nl": "115 réclamation solde de points", "es": "115 réclamation solde de points"}},' 
        	+ '  "name": {"fr": "Motifs de contacts 2", "en": "Motifs de contacts 2", "nl": "Motifs de contacts 2", "es": "Motifs de contacts 2"}}],' 
        	+ '  "url": "https://alcmeon.com/c/65/task/20161430/acquire-and-process/", "state": "assigned", "conversation_id": 18189955,' 
        	+ '  "message": {"content": "Le cin\\u00e9ma est tr\\u00e8s tr\\u00e8s bien et la qualit\\u00e9 est pr\\u00e9sente ",' 
        	+ '  "attachments": [], "time": "11:33:22", "date": "2017-10-29", "author": {"id": 9429465, "name": "Marius"},' 
        	+ '  "external_id": "4179067", "id": 28973214, "is_private": 0, "discussion_id": 18750901}, "id": 20161430},' 
        	+ '  "data": {"answers": [{"content": "Bonjour Marius,\\nNous vous remercions de votre compliment et esp\\u00e9rons vous revoir bient\\u00f4t.\\nBien \\u00e0 vous,\\nFlorian/UGC",' 
        	+ '  "pictures": []}], "is_private": 0},' 
        	+ '  "user": {"is_bot": 0, "id": 882, "name": "Florian Boudot", "email": "chargeclientele03@ugc.fr"}' 
        	+ ' , "time": "17:39:06", "date": "2017-10-30", "type": "answer", "id": 18095600}, "id": 22}]';
    	
		handleCases(jsonEntry);
    	
    	
        List<Case> cases = [SELECT Id, Origin, OwnerId, TECH_idCritizr__c, AccountId, Famille__c, Motif__c, SousMotif__c FROM Case];
      
        
        List<Task> tasks = [SELECT Id, WhatId, WhoId, Origine__c, Description, ActivityDate, OwnerId FROM Task];
        
       
        //Date d = Date.valueOf('2017-10-30');
        Boolean messageOk = false;
        Boolean answerOk = false;
        String descriptions = '';
        for(Task task: tasks) {
        	
        	descriptions += '\n' + task.description;
        	if(task.description == 'Le cinéma est très très bien et la qualité est présente') {
        		messageOk = true;
        	}
        	if(task.description == 'Bonjour Marius,\nNous vous remercions de votre compliment et espérons vous revoir bientôt.\nBien à vous,\nFlorian/UGC') {
        		answerOk = true;
        	}
        }
      
        
    }
    
    
     @IsTest 
    static void handleAnswerTestinsta() {
    	Test.setMock(HttpCalloutMock.class, new TestHttpCalloutMock());
    	Utils.createContactInconnu();
    	
    	Profile prof = [select id from profile where name = 'Chargé de Clientèle'];
    	
    	User u = new user();
		u.LastName = 'Boudot';
		u.Email = 'chargeclientele03@ugc.fr';
		u.Alias = 'Tcode';
		u.Username = 'chargeclientele03@ugc.fr';
		u.CommunityNickname = 'test12';
		u.LocaleSidKey = 'en_US';
		u.TimeZoneSidKey = 'GMT';
		u.ProfileID = prof.Id;
		u.LanguageLocaleKey = 'en_US';
		u.EmailEncodingKey = 'UTF-8';
		insert u;
		
		Contacts__c c = new Contacts__c();
        /*
		c.ValeurALCMEON__c = '008 Autres';
		c.Famille_Statut__c = '6- GestionCompteUI';
		c.Motif_Statut__c = '1- Réédition de carte gratuite';
		c.SousMotif_Statut__c = '6- Réedition sans frais';
		*/
		c.ValeurALCMEON__c = '115 réclamation solde de points';
		c.Famille_Statut__c = '9- Supports Digitaux';
		c.Motif_Statut__c = '3- UGC fidélité';
		c.SousMotif_Statut__c = '5- Réclamation solde de points';
		
		insert c;
    	String jsonEntry = '[{"action": {"status": "pending", "account": {"type": "facebook", "id": 426, "name": "Annick Maeckelberghe"},' 
        	+ '  "task": {"tags": [{"id": 3, "value": {"id": 74, "value": {"fr": "Fran\\u00e7ais", "en": "French", "nl": "Frans", "es": "Franc\\u00e9s"}},' 
        	+ '  "name": {"fr": "Langue", "en": "Language", "nl": "Taal", "es": "Idioma"}},' 
        	+ '  {"id": 40, "value": {"id": 472,' 
        	+ '  "value": {"fr": "008 Autres", "en": "Infos Services Produits Digital",' 
        	+ '  "nl": "Infos Services Produits Digital", "es": "Infos Services Produits Digital"}},' 
        	+ '  "name": {"fr": "Motifs de contacts", "en": "Motifs de contacts", "nl": "Motifs de contacts", "es": "Motifs de contacts"}},' 
        	+ '  {"id": 47, "value": {"id": 504, "value": {"fr": "115 réclamation solde de points", "en": "115 réclamation solde de points",' 
        	+ '  "nl": "115 réclamation solde de points", "es": "115 réclamation solde de points"}},' 
        	+ '  "name": {"fr": "Motifs de contacts 2", "en": "Motifs de contacts 2", "nl": "Motifs de contacts 2", "es": "Motifs de contacts 2"}}],' 
        	+ '  "url": "https://alcmeon.com/c/65/task/20161430/acquire-and-process/", "state": "assigned", "conversation_id": 18189955,' 
        	+ '  "message": {"content": "Le cin\\u00e9ma est tr\\u00e8s tr\\u00e8s bien et la qualit\\u00e9 est pr\\u00e9sente ",' 
        	+ '  "attachments": [], "time": "11:33:22", "date": "2017-10-29", "author": {"id": 9429465, "name": "Marius"},' 
        	+ '  "external_id": "4179067", "id": 28973214, "is_private": 0, "discussion_id": 18750901}, "id": 20161430},' 
        	+ '  "data": {"answers": [{"content": "Bonjour Marius,\\nNous vous remercions de votre compliment et esp\\u00e9rons vous revoir bient\\u00f4t.\\nBien \\u00e0 vous,\\nFlorian/UGC",' 
        	+ '  "pictures": []}], "is_private": 0},' 
        	+ '  "user": {"is_bot": 0, "id": 882, "name": "Florian Boudot", "email": "chargeclientele03@ugc.fr"}' 
        	+ ' , "time": "17:39:06", "date": "2017-10-30", "type": "answer", "id": 18095600}, "id": 22}]';
    	
		handleCases(jsonEntry);
    	
    	
        List<Case> cases = [SELECT Id, Origin, OwnerId, TECH_idCritizr__c, AccountId, Famille__c, Motif__c, SousMotif__c FROM Case];
      
        
        List<Task> tasks = [SELECT Id, WhatId, WhoId, Origine__c, Description, ActivityDate, OwnerId FROM Task];
        
       
        //Date d = Date.valueOf('2017-10-30');
        Boolean messageOk = false;
        Boolean answerOk = false;
        String descriptions = '';
        for(Task task: tasks) {
        	
        	descriptions += '\n' + task.description;
        	if(task.description == 'Le cinéma est très très bien et la qualité est présente') {
        		messageOk = true;
        	}
        	if(task.description == 'Bonjour Marius,\nNous vous remercions de votre compliment et espérons vous revoir bientôt.\nBien à vous,\nFlorian/UGC') {
        		answerOk = true;
        	}
        }
      
        
    }
    
    
    
    
    @IsTest
    public static void testIdentifyContact() {
    	Test.setMock(HttpCalloutMock.class, new TestHttpCalloutMock());
    	
    	
    	Utils.createContactInconnu();
    	
    	Profile prof = [select id from profile where name = 'Chargé de Clientèle'];
    	
    	User u = new user();
		u.LastName = 'Boudot';
		u.Email = 'chargeclientele03@ugc.fr';
		u.Alias = 'Tcode';
		u.Username = 'chargeclientele03@ugc.fr';
		u.CommunityNickname = 'test12';
		u.LocaleSidKey = 'en_US';
		u.TimeZoneSidKey = 'GMT';
		u.ProfileID = prof.Id;
		u.LanguageLocaleKey = 'en_US';
		u.EmailEncodingKey = 'UTF-8';
		insert u;
		
		Contacts__c c = new Contacts__c();
        /*
		c.ValeurALCMEON__c = '008 Autres';
		c.Famille_Statut__c = '6- GestionCompteUI';
		c.Motif_Statut__c = '1- Réédition de carte gratuite';
		c.SousMotif_Statut__c = '6- Réedition sans frais';
		*/
		c.ValeurALCMEON__c = '115 réclamation solde de points';
		c.Famille_Statut__c = '9- Supports Digitaux';
		c.Motif_Statut__c = '3- UGC fidélité';
		c.SousMotif_Statut__c = '5- Réclamation solde de points';
		
		insert c;
		
		Account acc = new Account(LastName='test', FirstName='test', RecordTypeId = Utils.getComptePersonelAccountRecordType().Id, 
        	PersonEmail='test@test.test', ClientResident__c = 'France', TECH_idCritizr__c='250', TECH_idInstagram__c='251', TECH_idTwitter__c = '252', TECH_idFacebook__c  = '253');
        insert acc;
		
    	String jsonEntry = '[{"action": {"status": "pending", "account": {"type": "critizr", "id": 250, "name": "UGC / Critizr"},' 
        	+ '  "task": {"tags": [{"id": 3, "value": {"id": 74, "value": {"fr": "Fran\\u00e7ais", "en": "French", "nl": "Frans", "es": "Franc\\u00e9s"}},' 
        	+ '  "name": {"fr": "Langue", "en": "Language", "nl": "Taal", "es": "Idioma"}},' 
        	+ '  {"id": 40, "value": {"id": 472,' 
        	+ '  "value": {"fr": "008 Autres", "en": "Infos Services Produits Digital",' 
        	+ '  "nl": "Infos Services Produits Digital", "es": "Infos Services Produits Digital"}},' 
        	+ '  "name": {"fr": "Motifs de contacts", "en": "Motifs de contacts", "nl": "Motifs de contacts", "es": "Motifs de contacts"}},' 
        	+ '  {"id": 47, "value": {"id": 504, "value": {"fr": "115 réclamation solde de points", "en": "115 réclamation solde de points",' 
        	+ '  "nl": "115 réclamation solde de points", "es": "115 réclamation solde de points"}},' 
        	+ '  "name": {"fr": "Motifs de contacts 2", "en": "Motifs de contacts 2", "nl": "Motifs de contacts 2", "es": "Motifs de contacts 2"}}],' 
        	+ '  "url": "https://alcmeon.com/c/65/task/20161430/acquire-and-process/", "state": "assigned", "conversation_id": 18189955,' 
        	+ '  "message": {"content": "Le cin\\u00e9ma est tr\\u00e8s tr\\u00e8s bien et la qualit\\u00e9 est pr\\u00e9sente ",' 
        	+ '  "attachments": [], "time": "11:33:22", "date": "2017-10-29", "author": {"id": 9429465, "name": "Marius"},' 
        	+ '  "external_id": "4179067", "id": 28973214, "is_private": 0, "discussion_id": 18750901}, "id": 20161430},' 
        	+ '  "data": {"answers": [{"content": "Bonjour Marius,\\nNous vous remercions de votre compliment et esp\\u00e9rons vous revoir bient\\u00f4t.\\nBien \\u00e0 vous,\\nFlorian/UGC",' 
        	+ '  "pictures": []}], "is_private": 0},' 
        	+ '  "user": {"is_bot": 0, "id": 882, "name": "Florian Boudot", "email": "chargeclientele03@ugc.fr"}' 
        	+ ' , "time": "17:39:06", "date": "2017-10-30", "type": "answer", "id": 18095600}, "id": 22}]';
    	handleCases(jsonEntry);
    	
    	List<Case> cases = [SELECT Id, AccountId FROM Case];
     
    }
    
    @IsTest
    public static void testMultiAnswer() {
    	Test.setMock(HttpCalloutMock.class, new TestHttpCalloutMock());
    	
    	
    	Utils.createContactInconnu();
    	
    	Profile prof = [select id from profile where name = 'Chargé de Clientèle'];
    	
    	User u = new user();
		u.LastName = 'Boudot';
		u.Email = 'chargeclientele03@ugc.fr';
		u.Alias = 'Tcode';
		u.Username = 'chargeclientele03@ugc.fr';
		u.CommunityNickname = 'test12';
		u.LocaleSidKey = 'en_US';
		u.TimeZoneSidKey = 'GMT';
		u.ProfileID = prof.Id;
		u.LanguageLocaleKey = 'en_US';
		u.EmailEncodingKey = 'UTF-8';
		insert u;
		
		Contacts__c c = new Contacts__c();
		c.ValeurALCMEON__c = '115 réclamation solde de points';
		c.Famille_Statut__c = '9- Supports Digitaux';
		c.Motif_Statut__c = '3- UGC fidélité';
		c.SousMotif_Statut__c = '5- Réclamation solde de points';
		
		insert c;
		
    	String jsonEntry = '[{"action": {"status": "pending", "account": {"type": "instagram", "id": 250, "name": "UGC / Critizr"},' 
        	+ '  "task": {"tags": [{"id": 3, "value": {"id": 74, "value": {"fr": "Fran\\u00e7ais", "en": "French", "nl": "Frans", "es": "Franc\\u00e9s"}},' 
        	+ '  "name": {"fr": "Langue", "en": "Language", "nl": "Taal", "es": "Idioma"}},' 
        	+ '  {"id": 40, "value": {"id": 472,' 
        	+ '  "value": {"fr": "008 Autres", "en": "Infos Services Produits Digital",' 
        	+ '  "nl": "Infos Services Produits Digital", "es": "Infos Services Produits Digital"}},' 
        	+ '  "name": {"fr": "Motifs de contacts", "en": "Motifs de contacts", "nl": "Motifs de contacts", "es": "Motifs de contacts"}},' 
        	+ '  {"id": 47, "value": {"id": 504, "value": {"fr": "115 réclamation solde de points", "en": "115 réclamation solde de points",' 
        	+ '  "nl": "115 réclamation solde de points", "es": "115 réclamation solde de points"}},' 
        	+ '  "name": {"fr": "Motifs de contacts 2", "en": "Motifs de contacts 2", "nl": "Motifs de contacts 2", "es": "Motifs de contacts 2"}}],' 
        	+ '  "url": "https://alcmeon.com/c/65/task/20161430/acquire-and-process/", "state": "assigned", "conversation_id": 18189955,' 
        	+ '  "message": {"content": "Le cin\\u00e9ma est tr\\u00e8s tr\\u00e8s bien et la qualit\\u00e9 est pr\\u00e9sente ",' 
        	+ '  "attachments": [], "time": "11:33:22", "date": "2017-10-29", "author": {"id": 9429465, "name": "Marius"},' 
        	+ '  "external_id": "4179067", "id": 28973214, "is_private": 0, "discussion_id": 18750901}, "id": 20161430},' 
        	+ '  "data": {"answers": [{"content": "FOO", "pictures": []}, {"content": "BAR", "pictures": []}], "is_private": 0},' 
        	+ '  "user": {"is_bot": 0, "id": 882, "name": "Florian Boudot", "email": "chargeclientele03@ugc.fr"}' 
        	+ ' , "time": "17:39:06", "date": "2017-10-30", "type": "answer", "id": 18095600}, "id": 22}]';
    	handleCases(jsonEntry);
    	
    	List<Case> cases = [SELECT Id FROM Case];
       
        
        List<Task> tasks = [SELECT Id, WhatId, WhoId, Origine__c, Description, ActivityDate, OwnerId FROM Task];
        
       
        //Date d = Date.valueOf('2017-10-30');
        Boolean messageOk1 = false;
        Boolean messageOk2 = false;
        Boolean answerOk1 = false;
        Boolean answerOk2 = false;
        String descriptions = '';
        Id case1Id = null;
        Id case2Id = null;
        for(Task task: tasks) {
        	system.assert(task.whatId != null);
        	descriptions += '\n' + task.description;
        	if(task.description == 'Le cinéma est très très bien et la qualité est présente' && task.whatId == cases.get(0).Id) {
        		messageOk1 = true;
        	}
        	if(task.description == 'Le cinéma est très très bien et la qualité est présente' && task.whatId == cases.get(1).Id) {
        		messageOk2 = true;
        	}
        	if(task.description == 'FOO') {
        		answerOk1 = true;
        		case1Id = task.whatId;
        	}
        	if(task.description == 'BAR') {
        		answerOk2 = true;
        		case2Id = task.whatId;
        	}
        }
      

    }
    
    @IsTest
    public static void testNoContacts() {
    	Test.setMock(HttpCalloutMock.class, new TestHttpCalloutMock());
    	
    	Utils.createContactInconnu();
    	
    	Profile prof = [select id from profile where name = 'Chargé de Clientèle'];
    	
    	User u = new user();
		u.LastName = 'Boudot';
		u.Email = 'chargeclientele03@ugc.fr';
		u.Alias = 'Tcode';
		u.Username = 'chargeclientele03@ugc.fr';
		u.CommunityNickname = 'test12';
		u.LocaleSidKey = 'en_US';
		u.TimeZoneSidKey = 'GMT';
		u.ProfileID = prof.Id;
		u.LanguageLocaleKey = 'en_US';
		u.EmailEncodingKey = 'UTF-8';
		insert u;
		
		
    	String jsonEntry = '[{"action": {"status": "pending", "account": {"type": "twitter", "id": 250, "name": "UGC / Critizr"},' 
        	+ '  "task": {"tags": [{"id": 3, "value": {"id": 74, "value": {"fr": "Fran\\u00e7ais", "en": "French", "nl": "Frans", "es": "Franc\\u00e9s"}},' 
        	+ '  "name": {"fr": "Langue", "en": "Language", "nl": "Taal", "es": "Idioma"}},' 
        	+ '  {"id": 40, "value": {"id": 472,' 
        	+ '  "value": {"fr": "008 Autres", "en": "Infos Services Produits Digital",' 
        	+ '  "nl": "Infos Services Produits Digital", "es": "Infos Services Produits Digital"}},' 
        	+ '  "name": {"fr": "Motifs de contacts", "en": "Motifs de contacts", "nl": "Motifs de contacts", "es": "Motifs de contacts"}},' 
        	+ '  {"id": 47, "value": {"id": 504, "value": {"fr": "115 réclamation solde de points", "en": "115 réclamation solde de points",' 
        	+ '  "nl": "115 réclamation solde de points", "es": "115 réclamation solde de points"}},' 
        	+ '  "name": {"fr": "Motifs de contacts 2", "en": "Motifs de contacts 2", "nl": "Motifs de contacts 2", "es": "Motifs de contacts 2"}}],' 
        	+ '  "url": "https://alcmeon.com/c/65/task/20161430/acquire-and-process/", "state": "assigned", "conversation_id": 18189955,' 
        	+ '  "message": {"content": "Le cin\\u00e9ma est tr\\u00e8s tr\\u00e8s bien et la qualit\\u00e9 est pr\\u00e9sente ",' 
        	+ '  "attachments": [], "time": "11:33:22", "date": "2017-10-29", "author": {"id": 9429465, "name": "Marius"},' 
        	+ '  "external_id": "4179067", "id": 28973214, "is_private": 0, "discussion_id": 18750901}, "id": 20161430},' 
        	+ '  "data": {"answers": [{"content": "FOO", "pictures": []}, {"content": "BAR", "pictures": []}], "is_private": 0},' 
        	+ '  "user": {"is_bot": 0, "id": 882, "name": "Florian Boudot", "email": "chargeclientele03@ugc.fr"}' 
        	+ ' , "time": "17:39:06", "date": "2017-10-30", "type": "answer", "id": 18095600}, "id": 22}]';
    	handleCases(jsonEntry);
    	
    	List<Case> cases = [SELECT Id FROM Case];
      
        
        List<Rejected_Notification__c> rns = [SELECT json__c FROM Rejected_Notification__c];
       
        
        
    }
    

}