force-app/main/default/objects/Account/fields/CliEmailComplementaire__c.field-meta.xml
<CustomField>
    <fullName>CliEmailComplementaire__c</fullName>
    <label>Email Complémentaire</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/NPAIEMAIL__c.field-meta.xml
<CustomField>
    <fullName>NPAIEMAIL__c</fullName>
    <defaultValue>false</defaultValue>
    <label>NPAI_EMAIL</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/PNDADRESSE__c.field-meta.xml
<CustomField>
    <fullName>PNDADRESSE__c</fullName>
    <defaultValue>false</defaultValue>
    <label>PND_ADRESSE</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/CommentairesInternes__c.field-meta.xml
<CustomField>
    <fullName>CommentairesInternes__c</fullName>
    <label>Commentaires internes (200 caracts max)</label>
    <length>33000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/Date_de_creation__c.field-meta.xml
<CustomField>
    <fullName>Date_de_creation__c</fullName>
    <defaultValue>now()</defaultValue>
    <label>Date de création</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case/fields/Famille__c.field-meta.xml
<CustomField>
    <fullName>Famille__c</fullName>
    <label>Famille</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0- Souscription</fullName>
            </value>
            <value>
                <fullName>1- Vie de l&#39;abonnement</fullName>
            </value>
            <value>
                <fullName>2- Club UGC / fidelite</fullName>
            </value>
            <value>
                <fullName>3- Autres Produits</fullName>
            </value>
            <value>
                <fullName>4- Reservation</fullName>
                <label>4- Réservation</label>
            </value>
            <value>
                <fullName>5- Compte client</fullName>
            </value>
            <value>
                <fullName>6- Prospection</fullName>
            </value>
            <value>
                <fullName>7- Finance</fullName>
            </value>
            <value>
                <fullName>8- Cinema</fullName>
                <label>8- Cinéma</label>
            </value>
            <value>
                <fullName>9- Divers</fullName>
            </value>
            <value>
                <fullName>0- Commentaires</fullName>
                <isActive>false</isActive>
                <label>0- Commentaires</label>
            </value>
            <value>
                <fullName>1- Demandes d info UI</fullName>
                <isActive>false</isActive>
                <label>1- Demandes d info UI</label>
            </value>
            <value>
                <fullName>1- Demandes d&#39;info UI</fullName>
                <isActive>false</isActive>
                <label>1- Demandes d&#39;info UI</label>
            </value>
            <value>
                <fullName>2- Demande d infos generales</fullName>
                <isActive>false</isActive>
                <label>2- Demande d infos generales</label>
            </value>
            <value>
                <fullName>2- Demande d&#39;infos générales</fullName>
                <isActive>false</isActive>
                <label>2- Demande d&#39;infos générales</label>
            </value>
            <value>
                <fullName>3- Autres demandes d&#39;informations</fullName>
                <isActive>false</isActive>
                <label>3- Autres demandes d&#39;informations</label>
            </value>
            <value>
                <fullName>4- Abonnement Carte UGC</fullName>
                <isActive>false</isActive>
                <label>4- Abonnement Carte UGC</label>
            </value>
            <value>
                <fullName>5- Abonnement en attente</fullName>
                <isActive>false</isActive>
                <label>5- Abonnement en attente</label>
            </value>
            <value>
                <fullName>6- GestionCompteUI</fullName>
                <isActive>false</isActive>
                <label>6- GestionCompteUI</label>
            </value>
            <value>
                <fullName>7- Réclamations UI</fullName>
                <isActive>false</isActive>
                <label>7- Réclamations UI</label>
            </value>
            <value>
                <fullName>8- Autres types de reclamations</fullName>
                <isActive>false</isActive>
                <label>8- Autres types de reclamations</label>
            </value>
            <value>
                <fullName>8- Autres types de réclamations</fullName>
                <isActive>false</isActive>
                <label>8- Autres types de réclamations</label>
            </value>
            <value>
                <fullName>9- Supports Digitaux</fullName>
                <isActive>false</isActive>
                <label>9- Supports Digitaux</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Motif__c.field-meta.xml
<CustomField>
    <fullName>Motif__c</fullName>
    <label>Motif</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Famille__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>01- Info process abo</fullName>
            </value>
            <value>
                <fullName>02- Erreur prise abo</fullName>
            </value>
            <value>
                <fullName>03- Click and collect</fullName>
            </value>
            <value>
                <fullName>05- B2B</fullName>
            </value>
            <value>
                <fullName>06- VPC</fullName>
            </value>
            <value>
                <fullName>07- Creation Abonnement</fullName>
            </value>
            <value>
                <fullName>01- Reception carte</fullName>
                <label>01- Réception carte</label>
            </value>
            <value>
                <fullName>02- Reedition payante</fullName>
            </value>
            <value>
                <fullName>03- Reedition gratuite</fullName>
            </value>
            <value>
                <fullName>04- Desabonnement</fullName>
            </value>
            <value>
                <fullName>05- Resiliation</fullName>
            </value>
            <value>
                <fullName>06- Migration UI 1/2/3</fullName>
            </value>
            <value>
                <fullName>07- Reabonnement</fullName>
            </value>
            <value>
                <fullName>08- Retention</fullName>
            </value>
            <value>
                <fullName>09- Retour Carte</fullName>
            </value>
            <value>
                <fullName>10- Retractation</fullName>
            </value>
            <value>
                <fullName>11- Avertissement</fullName>
            </value>
            <value>
                <fullName>12- Annulation Migration</fullName>
            </value>
            <value>
                <fullName>13- Annulation Contrat</fullName>
            </value>
            <value>
                <fullName>04- Dematerialise</fullName>
                <label>04- Dématérialisé</label>
            </value>
            <value>
                <fullName>01- Inscription</fullName>
            </value>
            <value>
                <fullName>02- Solde de points</fullName>
            </value>
            <value>
                <fullName>03- Echange de points</fullName>
            </value>
            <value>
                <fullName>04- Fonctionnement Club</fullName>
            </value>
            <value>
                <fullName>01- Offres UGC</fullName>
            </value>
            <value>
                <fullName>02- Formules UGC+</fullName>
            </value>
            <value>
                <fullName>03- Solo</fullName>
            </value>
            <value>
                <fullName>04- Blue</fullName>
            </value>
            <value>
                <fullName>05- VLO</fullName>
            </value>
            <value>
                <fullName>01- Modalites de reservation</fullName>
                <label>01- Modalités de réservation</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/SousMotif__c.field-meta.xml
<CustomField>
    <fullName>SousMotif__c</fullName>
    <label>Sous-motif</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Motif__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>I- Info</fullName>
            </value>
            <value>
                <fullName>R- Récla</fullName>
            </value>
            <value>
                <fullName>A- Action</fullName>
            </value>
            <value>
                <fullName>Click to Call Info</fullName>
            </value>
            <value>
                <fullName>Click to Call Recla</fullName>
            </value>
            <value>
                <fullName>AD- Action DRC</fullName>
            </value>
            <value>
                <fullName>AS- Action Stand</fullName>
            </value>
            <value>
                <fullName>AH- Action Selfcare</fullName>
            </value>
            <value>
                <fullName>R1- 1er rejet</fullName>
            </value>
            <value>
                <fullName>R2- 2nd rejet</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DisplayCases_CC_Test.cls
@IsTest
public class DisplayCases_CC_Test {
    
    private static Account account;
    private static Account account2;
    private static List<Case> cases;
    
    
    private static void init() {
    	// Account test
        account = new Account(LastName='test', FirstName='test', RecordTypeId = Utils.getComptePersonelAccountRecordType().Id, 
        	PersonEmail='test@test.test', CliEmailComplementaire__c='test@test.test', NPAIEMAIL__c = false, PNDADRESSE__c = false);
        insert account;
        
        account2 = new Account(LastName='test2', FirstName='test2', RecordTypeId = Utils.getComptePersonelAccountRecordType().Id, 
        	PersonEmail='test2@test.test', CliEmailComplementaire__c='test2@test.test', NPAIEMAIL__c = false, PNDADRESSE__c = false);
        insert account2;
        
        cases = new List<Case>();
        
        Case cse = new Case () ;
        cse.RecordTypeId =  Utils.getNouvelleDemandeClientCaseRecordType().id ;
        cse.AccountId = account.ID;
        cse.Status ='à traiter' ;
        cse.RecordTypeId = Utils.getNouvelleDemandeClientCaseRecordType().id ;
        cse.Origin = 'E-mail';
        cse.Famille__c = '6- GestionCompteUI' ;
        cse.CommentairesInternes__c = 'Case 0';
        cases.add(cse);
        
        cse = new Case () ;
        cse.RecordTypeId = Utils.getNouvelleDemandeClientCaseRecordType().id ;
        cse.AccountId = account.ID;
        cse.Status ='à traiter' ;
        cse.RecordTypeId = Utils.getNouvelleDemandeClientCaseRecordType().id ;
        cse.Origin = 'E-mail';
        cse.Famille__c ='2- Demande d\'infos générales' ;
        cse.CommentairesInternes__c = 'Case 1';
        cases.add(cse);
        
        cse = new Case () ;
        cse.RecordTypeId = Utils.getNouvelleDemandeClientCaseRecordType().id ;
        cse.AccountId = account.ID;
        cse.Status ='à traiter' ;
        cse.RecordTypeId = Utils.getNouvelleDemandeClientCaseRecordType().id ;
        cse.Origin = 'E-mail';
        cse.Famille__c ='2- Demande d\'infos générales' ;
        cse.CommentairesInternes__c = 'Case 2';
        cases.add(cse);
        
        cse = new Case () ;
        cse.RecordTypeId = Utils.getNouvelleDemandeClientCaseRecordType().id ;
        cse.AccountId = account.ID;
        cse.Status ='à traiter' ;
        cse.RecordTypeId = Utils.getNouvelleDemandeClientCaseRecordType().id ;
        cse.Origin = 'E-mail';
        cse.Famille__c ='2- Demande d\'infos générales' ;
        cse.CommentairesInternes__c = 'Case 3';
        cases.add(cse);
        
        cse = new Case () ;
        cse.RecordTypeId = Utils.getNouvelleDemandeClientCaseRecordType().id ;
        cse.AccountId = account.ID;
        cse.Status ='à traiter' ;
        cse.RecordTypeId = Utils.getNouvelleDemandeClientCaseRecordType().id ;
        cse.Origin = 'E-mail';
        cse.CommentairesInternes__c = 'Case 4';
        cases.add(cse);
        
        cse = new Case () ;
        cse.RecordTypeId = Utils.getNouvelleDemandeClientCaseRecordType().id ;
        cse.AccountId = account.ID;
        cse.Status ='à traiter' ;
        cse.RecordTypeId = Utils.getNouvelleDemandeClientCaseRecordType().id ;
        cse.Origin = 'E-mail';
        cse.CommentairesInternes__c = 'Case 5';
        cases.add(cse);
        
        cse = new Case () ;
        cse.RecordTypeId = Utils.getNouvelleDemandeClientCaseRecordType().id ;
        cse.AccountId = account.ID;
        cse.Status ='à traiter' ;
        cse.RecordTypeId = Utils.getNouvelleDemandeClientCaseRecordType().id ;
        cse.Origin = 'E-mail';
        cse.CommentairesInternes__c = 'Case 6';
        cases.add(cse);
        
        cse = new Case () ;
        cse.RecordTypeId = Utils.getNouvelleDemandeClientCaseRecordType().id ;
        cse.AccountId = account2.ID;
        cse.Status ='à traiter' ;
        cse.RecordTypeId = Utils.getNouvelleDemandeClientCaseRecordType().id ;
        cse.Origin = 'E-mail';
        cse.CommentairesInternes__c = 'Case 7';
        cases.add(cse);
        
        cse = new Case () ;
        cse.RecordTypeId = Utils.getNouvelleDemandeClientCaseRecordType().id ;
        cse.AccountId = account2.ID;
        cse.Status ='à traiter' ;
        cse.RecordTypeId = Utils.getNouvelleDemandeClientCaseRecordType().id ;
        cse.Origin = 'E-mail';
        cse.CommentairesInternes__c = 'Case 8';
        cases.add(cse);
        
        insert cases;
        
        Task task1 = new Task();
        task1.whatId = cases.get(8).Id;
        task1.subject = 'task 1';
        task1.activityDate = Date.valueOf('2017-01-01'); 
        task1.origine__c = 'Email entrant';
        insert task1;
        
        Task task2 = new Task();
        task2.whatId = cases.get(8).Id;
        task2.subject = 'task 2';
        task2.activityDate = Date.valueOf('2017-01-02');
        task2.origine__c = 'Email sortant';
        insert task2;
    }
    
    private static void compareListsInt(List<Integer> l1, List<Integer> l2) {
    	system.assertEquals(l1.size(), l2.size());
    	for(Integer i = 0; i < l1.size(); ++i) {
    		system.assertEquals(l1.get(i), l2.get(i), 'Inégalité à l\'indice ' + i);
    	}
    }
    
    @IsTest
    static void getCasesByAccountIdTest() {
    	Test.setMock(HttpCalloutMock.class, new TestHttpCalloutMock());
        init();
        
        List<Integer> expectedPages = new List<Integer> {1, 2, 3};
        
    	DisplayCases_CC.CasePageWrapper res = DisplayCases_CC.getCases(account.Id, 1, 3, 'Famille__c', true, '', '');
    	compareListsInt(expectedPages, res.numberPages);
    	system.assertEquals(3, res.pageSize);
    	system.assertEquals(1, res.page);
    	system.assertEquals(3, res.cases.size());
    	system.assertEquals('E-mail', res.cases.get(0).Origin);
    	system.assertEquals(null, res.cases.get(0).Famille__c);
    	
    	res = DisplayCases_CC.getCases(account.Id, 3, 3, 'Famille__c', true, '', '');
    	
    	compareListsInt(expectedPages, res.numberPages);
    	system.assertEquals(3, res.pageSize);
    	system.assertEquals(3, res.page);
    	system.assertEquals(1, res.cases.size());
    	system.assertEquals('E-mail', res.cases.get(0).Origin);
    	system.assertEquals('2- Demande d\'infos générales', res.cases.get(0).Famille__c);
    	
    }
    
    
    @IsTest
    static void getCasesByCaseIdTest() {
    	Test.setMock(HttpCalloutMock.class, new TestHttpCalloutMock());
        init();
        
        List<Integer> expectedPages = new List<Integer> {1, 2, 3};
        
    	DisplayCases_CC.CasePageWrapper res = DisplayCases_CC.getCases(cases.get(1).Id, 1, 3, 'Famille__c', false, '', '');
    	compareListsInt(expectedPages, res.numberPages);
    	system.assertEquals(3, res.pageSize);
    	system.assertEquals(1, res.page);
    	system.assertEquals(3, res.cases.size());
    	system.assertEquals('E-mail', res.cases.get(0).Origin);
    	system.assertEquals( '2- Demande d\'infos générales', res.cases.get(0).Famille__c);
    	
    	res = DisplayCases_CC.getCases(account.Id, 3, 3, 'Famille__c', false, '', '');
    	
    	compareListsInt(expectedPages, res.numberPages);
    	system.assertEquals(3, res.pageSize);
    	system.assertEquals(3, res.page);
    	system.assertEquals(1, res.cases.size());
    	system.assertEquals('E-mail', res.cases.get(0).Origin);
    	system.assertEquals(null, res.cases.get(0).Famille__c);
    	
    }
    
    @IsTest
    static void getActivitiesTest() {
    	Test.setMock(HttpCalloutMock.class, new TestHttpCalloutMock());
        init();
        
        List<Task> res = DisplayCases_CC.getActivities(cases.get(8).Id);
        system.assertEquals(3, res.size());
        system.assertEquals('task 1', res.get(1).Subject);
        system.assertEquals('task 2', res.get(2).Subject);
    }
    
    @IsTest
    static void getCasesSearchTest() {
    	Test.setMock(HttpCalloutMock.class, new TestHttpCalloutMock());
        init();
        
        List<Integer> expectedPages = new List<Integer> {1};
        
    	DisplayCases_CC.CasePageWrapper res = DisplayCases_CC.getCases(account.Id, 1, 3, 'Famille__c', true, 'Famille__c', 'Gestion');
    	system.debug('## DisplayCases_CC_Test ## ' + res);
    	compareListsInt(expectedPages, res.numberPages);
    	system.assertEquals(3, res.pageSize);
    	system.assertEquals(1, res.page);
    	system.assertEquals(1, res.cases.size());
    	system.assertEquals(cases.get(0).Id, res.cases.get(0).Id);
    	system.assertEquals('6- GestionCompteUI', res.cases.get(0).Famille__c);
    	
    	
    }
    
    @IsTest
    static void getCaseFieldsIdLabelsTest() {
    	Map<String, String> res = DisplayCases_CC.getCaseFieldsIdLabels();
    	system.assertEquals(6, res.size());
    	Map<String, Schema.SObjectType> GlobalMap = Schema.getGlobalDescribe();
        Schema.DescribeSObjectResult obj = GlobalMap.get('Case').getDescribe();
        Map<String, Schema.SObjectField> fieldMap = obj.fields.getMap();
        
    	system.assertEquals(fieldMap.get('CaseNumber').getDescribe().getLabel(), res.get('CaseNumber'));
    	system.assertEquals(fieldMap.get('Origin').getDescribe().getLabel(), res.get('Origin'));
    	system.assertEquals(fieldMap.get('Date_de_creation__c').getDescribe().getLabel(), res.get('Date_de_creation__c'));
    	system.assertEquals(fieldMap.get('Famille__c').getDescribe().getLabel(), res.get('Famille__c'));
    	system.assertEquals(fieldMap.get('Motif__c').getDescribe().getLabel(), res.get('Motif__c'));
    	system.assertEquals(fieldMap.get('SousMotif__c').getDescribe().getLabel(), res.get('SousMotif__c'));
    	
    }
    
    @IsTest
    static void getOriginLabelsTest() {
    	Map<String, String> res = DisplayCases_CC.getOriginLabels();
    	system.assertEquals(10, res.size());
    	System.debug('## DisplayCases_CC_Test ## labels: ' + res);
    	system.assert(res.containsKey('E-mail'));
    }
    
    @IsTest
    static void getCommentairesInternesLabelTest() {
    	String label = DisplayCases_CC.getCommentairesInternesLabel();
    	Map<String, Schema.SObjectType> GlobalMap = Schema.getGlobalDescribe();
        Schema.DescribeSObjectResult obj = GlobalMap.get('Case').getDescribe();
        Map<String, Schema.SObjectField> fieldMap = obj.fields.getMap();
        system.assertEquals(fieldMap.get('CommentairesInternes__c').getDescribe().getLabel(), label);
    	 
    }
    
    @IsTest
    static void getContactIdsTest() {
    	Test.setMock(HttpCalloutMock.class, new TestHttpCalloutMock());
        init();
        DisplayCases_CC.IdsDto res = DisplayCases_CC.getContactIds(account2.Id);
        system.assertEquals(account2.id, res.accountId);
        Contact contact = [SELECT id, accountId FROM Contact where id = :res.contactId];
        system.assertEquals(account2.id, contact.accountId);
        
        res = DisplayCases_CC.getContactIds(cases.get(3).Id);
        system.assertEquals(account.id, res.accountId);
        contact = [SELECT id, accountId FROM Contact where id = :res.contactId];
        system.assertEquals(account.id, contact.accountId);
    }
}