force-app/main/default/objects/Account/fields/CliStatutRCU__c.field-meta.xml
<CustomField>
    <fullName>CliStatutRCU__c</fullName>
    <label>Statut du client ds référentiel client</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sans email</fullName>
            </value>
            <value>
                <fullName>En attente</fullName>
            </value>
            <value>
                <fullName>Validé</fullName>
            </value>
            <value>
                <fullName>Supprimé</fullName>
            </value>
            <value>
                <fullName>Refusé</fullName>
            </value>
            <value>
                <fullName>Anonyme</fullName>
            </value>
            <value>
                <fullName>Endormi</fullName>
            </value>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>En attente infinie</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/CodePostal__c.field-meta.xml
<CustomField>
    <fullName>CodePostal__c</fullName>
    <inlineHelpText>Le code postal est rempli automatiquement grâce à la sélection de la ville.</inlineHelpText>
    <label>Code Postal</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/TelephoneBureau__c.field-meta.xml
<CustomField>
    <fullName>TelephoneBureau__c</fullName>
    <label>Téléphone bureau</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Case/fields/CodePostal__c.field-meta.xml
<CustomField>
    <fullName>CodePostal__c</fullName>
    <label>Code postal</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/Test_AccountUpdaterBatch.cls
@IsTest()

public class Test_AccountUpdaterBatch {
    
 
     static testmethod void TestAccountUpdaterBatch() {
         
         //  Créer un account
         system.debug('création du account');
         
         Account account1 = new Account();
         
         
      	 account1.FirstName = 'Test Account'; 
         account1.LastName = 'Test Account';
         account1.PersonEmail = 'testAccount@easyfront.fr';
         account1.PersonBirthdate = Date.newInstance(1976, 12, 9);
         account1.RecordTypeId = '0120Y000000ZZgEQAW';
         account1.CodePostal__c='94000';
         account1.PersonHomePhone='0155658899';
         account1.PersonMobilePhone='0656546323';
         account1.TelephoneBureau__c='0155668899';
         account1.CliStatutRCU__c = 'Anonyme';
      	 insert account1; 
         //Inserer l'account dans la BD
         TestHttpCalloutMock mock = new TestHttpCalloutMock();
    	 Test.setMock(HttpCalloutMock.class, mock);
		  
         
         //  Créer un case relié à l'account precedent
         Case case1 = new Case();
         
         case1.AccountId = Account1.Id;
         
         insert case1;
         
         // Vérifier si l'account et le case ont bien été créé
         System.assertEquals('Test Account', Account1.LastName);
      	 System.assertEquals(Account1.Id, case1.AccountId);
         User usr= [Select Id from User where Username = 'automate@ugc.com'];
         // Lancer le test du batch
         system.debug('user ='+usr.Id);
        
         Test.startTest();
         system.runAs(usr)
         {
         
         AccountUpdaterBatch batch = new AccountUpdaterBatch();
         Database.executeBatch(batch);
        }
        
         // Vérifier que les champs du account en question sont mis à blanc
        
        
      	List<Account> acc = [select Id, LastName, FirstName from Account]; 
         system.debug('Lastname ='+acc);
         Test.stopTest();
         
         //System.assertEquals('Anonyme', [select LastName from Account Where Id =: account1.Id].lastname);
        // System.assertEquals('', acc.FirstName);
         
           
         
         

         
         
    }
    
}