force-app/main/default/objects/Account/fields/CodePays__c.field-meta.xml
<CustomField>
    <fullName>CodePays__c</fullName>
    <label>Code Pays</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/CouponWelcomeback__c.field-meta.xml
<CustomField>
    <fullName>CouponWelcomeback__c</fullName>
    <label>Coupon Welcome back</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Coupon__c/Coupon__c.object-meta.xml
<CustomObject>
    <label>Coupon</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Coupons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Offre__c/Offre__c.object-meta.xml
<CustomObject>
    <label>Offre</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Offres</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Offre__c/fields/Coupon__c.field-meta.xml
<CustomField>
    <fullName>Coupon__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>test git</description>
    <label>Coupon</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Coupon__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>BtoC generique, BtoC multiples, BtoB, BtoC Nominatif Client, BtoC Nominatif Agent</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Coupon__c</referenceTo>
    <relationshipLabel>Offres</relationshipLabel>
    <relationshipName>Offres</relationshipName>
    <type>Lookup</type>
</CustomField>

liv/apex/Evo_407.cls
// Id couponID = [Select Id from Coupon__c where Name='Welcome Back' Limit 1].Id;
// SM_Coupon.generateCouponItem(couponID,'0010E00000Voo31QAB');

String offreWelcomeBack = Utils.getUgcGenericParam('Welcome Back Offre Name','033').ParamValue__c;
System.debug(offreWelcomeBack);
Id parentCouponID = [Select Coupon__c from Offre__c where Name = :offreWelcomeBack Limit 1].Coupon__c;
//Id parentCouponID = [Select Id from Coupon__c where Name=:offreWelcomeBack Limit 1].Id;
System.debug(parentCouponID);
Integer validiteCoupon = Integer.valueOf(Utils.getUgcGenericParam('Welcome Back Coupon Validite','033').ParamValue__c);
SM_Coupon.generateCouponItem(parentCouponID,'0015E00000lfpvRQAQ',Date.today(),Date.today().addMonths(validiteCoupon));

// Select CodePays__c from Account where Id='0010E00000Voo31QAB'

// Select CouponWelcomeback__c from Case where Id='5000E000009jMGLQA2'

String offreAboTier = Utils.getUgcGenericParam('Abo Tier Offre Name','033').ParamValue__c;
Integer validiteCoupon_AT = Integer.valueOf(Utils.getUgcGenericParam('Abo Tier Coupon Validite','033').ParamValue__c);
Id parentCouponID_AT = [Select Coupon__c from Offre__c where Name = :offreAboTier Limit 1].Coupon__c;
String coupon_AT = SM_Coupon.generateCouponItem(parentCouponID_AT,null,date.Today(),date.Today().addMonths(validiteCoupon_AT));