force-app/main/default/objects/Account/fields/CodePays__c.field-meta.xml
<CustomField>
    <fullName>CodePays__c</fullName>
    <label>Code Pays</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/ProduitUGC__c.field-meta.xml
<CustomField>
    <fullName>ProduitUGC__c</fullName>
    <defaultValue>&quot;français&quot;</defaultValue>
    <label>Pays de résidence</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>français</fullName>
                <default>true</default>
                <label>français</label>
            </value>
            <value>
                <fullName>belge</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Date_fin_engagement__c.field-meta.xml
<CustomField>
    <fullName>Date_fin_engagement__c</fullName>
    <label>TECH_Date de fin d&#39;engagement</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/DateDemande__c.field-meta.xml
<CustomField>
    <fullName>DateDemande__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Date de la demande</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/Mois_de_d_but_remise__c.field-meta.xml
<CustomField>
    <fullName>Mois_de_d_but_remise__c</fullName>
    <label>Mois de début remise</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Janvier</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Février</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Mars</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Avril</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Mai</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>Juin</label>
            </value>
            <value>
                <fullName>7</fullName>
                <label>Juillet</label>
            </value>
            <value>
                <fullName>8</fullName>
                <label>Août</label>
            </value>
            <value>
                <fullName>9</fullName>
                <label>Septembre</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>Octobre</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>Novembre</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>Décembre</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Offre_de_r_tention__c.field-meta.xml
<CustomField>
    <fullName>Offre_de_r_tention__c</fullName>
    <label>Offre de rétention</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Points fidélité</fullName>
                <label>Points fidélité (Bronze)</label>
            </value>
            <value>
                <fullName>REMRETARG</fullName>
                <label>1 mois gratuit + bonus (Argent)</label>
            </value>
            <value>
                <fullName>REMRETOR</fullName>
                <label>2 mois gratuits (Or)</label>
            </value>
            <value>
                <fullName>REMRETPLAT</fullName>
                <label>2 mois gratuits + bonus (Platine)</label>
            </value>
            <value>
                <fullName>Hausse tarifaire</fullName>
            </value>
            <value>
                <fullName>1 mois gratuit</fullName>
                <isActive>false</isActive>
                <label>1 mois gratuit</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/R_sultat_R_tention__c.field-meta.xml
<CustomField>
    <fullName>R_sultat_R_tention__c</fullName>
    <label>Résultat Rétention</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Accepté</fullName>
            </value>
            <value>
                <fullName>Refuse avec desabonnement</fullName>
                <label>Refusé avec désabonnement</label>
            </value>
            <value>
                <fullName>Refuse sans desabonnement</fullName>
                <label>Refusé sans désabonnement</label>
            </value>
            <value>
                <fullName>Client indécis</fullName>
            </value>
            <value>
                <fullName>Refuse avec desabonnement E</fullName>
                <isActive>false</isActive>
                <label>Refusé avec désabonnement E</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Raison_de_d_sabonnement__c.field-meta.xml
<CustomField>
    <fullName>Raison_de_d_sabonnement__c</fullName>
    <label>Raison de désabonnement</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1- Frais de réédition</fullName>
            </value>
            <value>
                <fullName>2- Régularisation</fullName>
            </value>
            <value>
                <fullName>3- Trop cher</fullName>
            </value>
            <value>
                <fullName>4- Rentabilité</fullName>
            </value>
            <value>
                <fullName>5- Pas de consommation</fullName>
            </value>
            <value>
                <fullName>6- Concurrence</fullName>
            </value>
            <value>
                <fullName>7- Insécurité</fullName>
            </value>
            <value>
                <fullName>8- Va au cinéma seul</fullName>
            </value>
            <value>
                <fullName>9- Places via le CE</fullName>
            </value>
            <value>
                <fullName>10- Femme enceinte</fullName>
            </value>
            <value>
                <fullName>11- Raison de santé</fullName>
            </value>
            <value>
                <fullName>12- Départ Hors Zone</fullName>
            </value>
            <value>
                <fullName>13- Prison</fullName>
            </value>
            <value>
                <fullName>14- Chômage</fullName>
            </value>
            <value>
                <fullName>15- Décès</fullName>
            </value>
            <value>
                <fullName>16- Programmation</fullName>
            </value>
            <value>
                <fullName>17- Mécontent d&#39;UGC</fullName>
            </value>
            <value>
                <fullName>18- Problème technique</fullName>
            </value>
            <value>
                <fullName>19- Suspension</fullName>
            </value>
            <value>
                <fullName>20- Pas de raison donnée</fullName>
            </value>
            <value>
                <fullName>21- Autres</fullName>
            </value>
            <value>
                <fullName>Manque de temps</fullName>
                <isActive>false</isActive>
                <label>Manque de temps</label>
            </value>
            <value>
                <fullName>Programation</fullName>
                <isActive>false</isActive>
                <label>Programation</label>
            </value>
            <value>
                <fullName>Rentabilité</fullName>
                <isActive>false</isActive>
                <label>Rentabilité</label>
            </value>
            <value>
                <fullName>Tarif</fullName>
                <isActive>false</isActive>
                <label>Tarif</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Type_de_d_sabonnement__c.field-meta.xml
<CustomField>
    <fullName>Type_de_d_sabonnement__c</fullName>
    <label>Type de désabonnement</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Désabonnement avec préavis (L)</fullName>
            </value>
            <value>
                <fullName>Désabonnement avec justificatif (E)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Souscription.recordType-meta.xml
<RecordType>
    <fullName>Souscription</fullName>
    <active>true</active>
    <businessProcess>Demandes clients</businessProcess>
    <label>Souscription</label>
</RecordType>

force-app/main/default/objects/ProdRatePlan__c/ProdRatePlan__c.object-meta.xml
<CustomObject>
    <description>Objet qui contient les objets zuora, ne fait pas partie de Z360</description>
    <label>Prod Rate Plan</label>
    <nameField>
        <label>Nom Produit</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prod Rate Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ProdRatePlan__c/fields/Reference__c.field-meta.xml
<CustomField>
    <fullName>Reference__c</fullName>
    <externalId>true</externalId>
    <label>Reference</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProdRatePlanCharge__c/ProdRatePlanCharge__c.object-meta.xml
<CustomObject>
    <label>Prod Charges</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prod Charges</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ProdRatePlanCharge__c/fields/ProdRatePlan__c.field-meta.xml
<CustomField>
    <fullName>ProdRatePlan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ProdRatePlan</label>
    <referenceTo>ProdRatePlan__c</referenceTo>
    <relationshipName>RatePlanCharges</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProdRatePlanCharge__c/fields/zid__c.field-meta.xml
<CustomField>
    <fullName>zid__c</fullName>
    <label>zid</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Zuora__Subscription__c/Zuora__Subscription__c.object-meta.xml
<CustomObject>
    <description>A subscription is a product or service that has recurring charges, such as a monthly flat fee or charges based on usage. Subscriptions can also include one-time charges, such as activation fees.</description>
    <label>Subscription</label>
    <nameField>
        <label>Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Zuora__Subscription__c/fields/TypeContrat__c.field-meta.xml
<CustomField>
    <fullName>TypeContrat__c</fullName>
    <description>CDI ou CDD</description>
    <label>Type Contrat</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Zuora__Subscription__c/fields/Zuora__Account__c.field-meta.xml
<CustomField>
    <fullName>Zuora__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Zuora__Subscription__c/fields/Zuora__External_Id__c.field-meta.xml
<CustomField>
    <fullName>Zuora__External_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>This field holds the Zuora object ID, and is used as external ID for data synchronization between Salesforce and Zuora.</description>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Zuora__Subscription__c/fields/Zuora__Status__c.field-meta.xml
<CustomField>
    <fullName>Zuora__Status__c</fullName>
    <label>Status</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SM003_Retention.cls
public without sharing class SM003_Retention {
    
    public static void retention(String caseId){
        System.debug('##MNE SM003_Retention retention caseId >> ' + caseId);
        
        if(caseId == null){
            throw new MyException('No Id Case found for Retention');
        }
        Case c = [SELECT Id, Status, DateDemande__c, AccountId, Offre_de_r_tention__c, Mois_de_d_but_remise__c, Raison_de_d_sabonnement__c, Type_de_d_sabonnement__c, R_sultat_R_tention__c, Date_fin_engagement__c FROM Case WHERE Id =:caseId].get(0);
        
        if((c.Offre_de_r_tention__c == null   || c.Offre_de_r_tention__c == '')
        || (c.Raison_de_d_sabonnement__c == null   || c.Raison_de_d_sabonnement__c == '')
        || (c.R_sultat_R_tention__c == null || c.R_sultat_R_tention__c == '') ){
            System.debug('##MNE SM003_Retention retention field empty >> "Offre de rétention", "Raison de désabonnement" et "Résultat Rétention"');
            throw new MyException('Merci de renseigner les champ : "Offre de rétention", "Raison de désabonnement" et "Résultat Rétention"');
        }
        
        if(c.Offre_de_r_tention__c == 'Hausse tarifaire'){
            System.debug('##MNE SM003_Retention retention Offre de rétention "Hausse tarifaire" choisi');
            throw new MyException('Poduit non fonctionnel : "Hausse tarifaire"');
        }
        
        if(c.R_sultat_R_tention__c != null && (c.R_sultat_R_tention__c == 'Refuse sans desabonnement' || c.R_sultat_R_tention__c == 'Client indécis') ){
            c.Status = 'EnCours';
            update c;
            System.debug('##MNE SM003_Retention retention case closed EnCours');
            return;
        } else if(c.R_sultat_R_tention__c != null && c.R_sultat_R_tention__c == 'Accepté'){
            System.debug('##MNE SM003_Retention retention go to rentention in zuora');
            executeRetention(c);
            c.Status = 'EnCours';
            update c;
        } else if(c.R_sultat_R_tention__c != null && c.R_sultat_R_tention__c == 'Refuse avec desabonnement'){
            System.debug('##MNE SM003_Retention retention go to desabonnement');
            SM_Desabonnement.desabonner(c.Id);
            c.Status = 'EnCours';
            update c;
        }
    }
    
    public static void executeRetention(Case c){
        system.debug('##MNE SM003_Retention executeRetention case >> '+c);
        
        //mois obligatoir si l'offre proposé != Points fidélité && != Hausse tarifaire
        if( (c.Mois_de_d_but_remise__c == null || c.Mois_de_d_but_remise__c == '') 
        &&  (c.Offre_de_r_tention__c != 'Points fidélité' && c.Offre_de_r_tention__c != 'Hausse tarifaire') ){
            system.debug('##MNE SM003_Retention executeRetention field empty >> "Mois de début remise"');
            throw new MyException('Merci de renseigner le champ : "Mois de début remise"');
        }
        
        Id accId = c.AccountId;
        list<Zuora__Subscription__c> listSub = new list<Zuora__Subscription__c>([SELECT Zuora__External_Id__c, Zuora__Account__r.ProduitUGC__c, Zuora__Account__r.CodePays__c, TypeContrat__c FROM Zuora__Subscription__c WHERE Zuora__Account__c =:accId AND Zuora__Status__c = 'Active' ORDER BY CreatedDate DESC NULLS FIRST LIMIT 1]);
        
        if(listSub.size() == 0){
            system.debug('##MNE SM003_Retention executeRetention Pas de souscription trouvée.');
            throw new MyException('Pas de souscription trouvée.');
        }
        
        Zuora__Subscription__c sub = listSub.get(0);
        
        if(sub.TypeContrat__c == 'CDD'){
            system.debug('##MNE SM003_Retention executeRetention Pas possible pour CDD.');
            throw new MyException('La rétention n\'est pas possible pour un utilisateur en CDD.');
        }
        
        String zuoraSubId = listSub.get(0).Zuora__External_Id__c;
        String zEntityId = WS001_CallZuora.getZuoraEntityId(listSub.get(0).Zuora__Account__r.CodePays__c);
        String ProductRatePlanId;
        String ProductRatePlanChargeId;
        //SM001_GesteCommercial.Body res = new SM001_GesteCommercial.Body();
        list<SM001_GesteCommercial.Amendment> listAmendment = new list<SM001_GesteCommercial.Amendment>();
        
        if(c.Offre_de_r_tention__c != 'Points fidélité'){
        //if(c.Offre_de_r_tention__c != 'Points fidélité' && c.Offre_de_r_tention__c != 'Hausse tarifaire'){
            
            String prefixe = '';
            if(listSub.get(0).Zuora__Account__r.CodePays__c == '033'){
                prefixe = 'FR';
            }else if(listSub.get(0).Zuora__Account__r.CodePays__c == '032'){
                prefixe = 'BE';
            }
            
            String productRatePlanReference = prefixe + c.Offre_de_r_tention__c;
            list<ProdRatePlanCharge__c> listProdRatePlanCharge = new list<ProdRatePlanCharge__c>([SELECT Reference__c, zid__c, ProdRatePlan__r.zid__c FROM ProdRatePlanCharge__c WHERE Reference__c = :productRatePlanReference]);
            if(listProdRatePlanCharge.size() == 0){
                system.debug('##MNE SM003_Retention executeRetention Pas de Product Rate Plan Charge trouvée pour la remise de rétention');
                throw new MyException('Pas de Product Rate Plan Charge trouvée pour la remise de rétention.');
            }
            
            ProdRatePlanCharge__c prodRatePlanCharge = listProdRatePlanCharge.get(0);
            ProductRatePlanId = prodRatePlanCharge.ProdRatePlan__r.zid__c;
            ProductRatePlanChargeId = prodRatePlanCharge.zid__c;
            
            Integer moisDebutRemise = Integer.valueOf(c.Mois_de_d_but_remise__c);
            Date dateDebutRemise = SM_Demande.getRemiseDate(moisDebutRemise);
            
            system.debug('##MNE SM003_Retention executeRetention dateDebutRemise >> '+dateDebutRemise);
            
            //add product remise
            SM001_GesteCommercial.Amendment addPr = new SM001_GesteCommercial.Amendment(zuoraSubId, ProductRatePlanId, ProductRatePlanChargeId, dateDebutRemise);
            //res.requests.get(0).Amendments.add(addPr);
            listAmendment.add(addPr);
        }
        
        //Renew
        Date contractEffectiveDate;
        Date termStartDate;
        if(c.Date_fin_engagement__c >= Date.today() ){
            contractEffectiveDate = c.Date_fin_engagement__c;
            termStartDate = c.Date_fin_engagement__c;
        } else {
            contractEffectiveDate = Date.today();
            termStartDate = Date.today();
        }
        //SM001_GesteCommercial.Amendment renew = new SM001_GesteCommercial.Amendment(zuoraSubId);
        SM001_GesteCommercial.Amendment renew = new SM001_GesteCommercial.Amendment(zuoraSubId, contractEffectiveDate, termStartDate);
        //res.requests.get(0).Amendments.add(renew);
        listAmendment.add(0,renew);
        
        
        
        
        
        /*String inBody = JSON.serialize(res);
        inBody = inBody.replace('null','""');
        System.debug('##MNE SM003_Retention executeRetention inBody >> '+inBody);
        
        String repWS = SM001_GesteCommercial.sendAmendRequest(inBody, zEntityId);
        System.debug('##MNE SM003_Retention executeRetention repWS >> '+repWS);
        
        SM001_GesteCommercial.Resultat resApex =   (SM001_GesteCommercial.Resultat)System.JSON.deserialize(repWS, SM001_GesteCommercial.Resultat.class);
        System.debug('##MNE SM003_Retention executeRetention resApex >> '+resApex);
        
        Boolean success = true;
        String messageError = '';
        if(resApex != null && resApex.results != null  && resApex.results.size() > 0){
            for(SM001_GesteCommercial.Result r : resApex.results){
                if(!r.Success){
                    if(r.Errors != null && r.Errors.size() > 0){
                        throw new MyException(r.Errors.get(0).Message);
                    }
                }
            }
        }*/
        
        
        
        ////
        for(SM001_GesteCommercial.Amendment amend : listAmendment){
            SM001_GesteCommercial.Body res = new SM001_GesteCommercial.Body();
            res.requests.get(0).Amendments.add(amend);
            String inBody = JSON.serialize(res);
            inBody = inBody.replace('null','""');
            System.debug('##MNE SM003_Retention executeRetention inBody >> '+inBody);
            
            String repWS = SM001_GesteCommercial.sendAmendRequest(inBody, zEntityId);
            System.debug('##MNE SM003_Retention executeRetention repWS >> '+repWS);
            
            SM001_GesteCommercial.Resultat resApex =   (SM001_GesteCommercial.Resultat)System.JSON.deserialize(repWS, SM001_GesteCommercial.Resultat.class);
            System.debug('##MNE SM003_Retention executeRetention resApex >> '+resApex);
            
            Boolean success = true;
            String messageError = '';
            if(resApex != null && resApex.results != null  && resApex.results.size() > 0){
                for(SM001_GesteCommercial.Result r : resApex.results){
                    if(!r.Success){
                        if(r.Errors != null && r.Errors.size() > 0){
                            throw new MyException(r.Errors.get(0).Message);
                        }
                    }
                }
            }
        }
        
        
        
        
        
        
     }
     
    private class MyException extends Exception {
    }

}