force-app/main/default/objects/Account/fields/CodeFinContrat__c.field-meta.xml
<CustomField>
    <fullName>CodeFinContrat__c</fullName>
    <label>Code Fin Contrat</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>L</fullName>
            </value>
            <value>
                <fullName>E</fullName>
            </value>
            <value>
                <fullName>X</fullName>
            </value>
            <value>
                <fullName>M</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/CodePays__c.field-meta.xml
<CustomField>
    <fullName>CodePays__c</fullName>
    <label>Code Pays</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Payeur__c.field-meta.xml
<CustomField>
    <fullName>Payeur__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payeur</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Payeur de</relationshipLabel>
    <relationshipName>Comptes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/DateFinContrat__c.field-meta.xml
<CustomField>
    <fullName>DateFinContrat__c</fullName>
    <label>TECH_Date de fin de contrat</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/Subscription__c.field-meta.xml
<CustomField>
    <fullName>Subscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Abonnement</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>$Source.AccountId</field>
            <operation>equals</operation>
            <valueField>Zuora__Subscription__c.Zuora__Account__r.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Zuora__Subscription__c</referenceTo>
    <relationshipLabel>Demandes</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Souscription.recordType-meta.xml
<RecordType>
    <fullName>Souscription</fullName>
    <active>true</active>
    <businessProcess>Demandes clients</businessProcess>
    <label>Souscription</label>
</RecordType>

force-app/main/default/objects/File_Impression__c/File_Impression__c.object-meta.xml
<CustomObject>
    <label>File d&#39;impression</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Files d&#39;impression</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/File_Impression__c/fields/Subscription__c.field-meta.xml
<CustomField>
    <fullName>Subscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Abonnement</label>
    <referenceTo>Zuora__Subscription__c</referenceTo>
    <relationshipLabel>Files d&#39;impression</relationshipLabel>
    <relationshipName>Files_d_impression</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Zuora__Subscription__c/Zuora__Subscription__c.object-meta.xml
<CustomObject>
    <description>A subscription is a product or service that has recurring charges, such as a monthly flat fee or charges based on usage. Subscriptions can also include one-time charges, such as activation fees.</description>
    <label>Subscription</label>
    <nameField>
        <label>Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Zuora__Subscription__c/fields/CodeFinContrat__c.field-meta.xml
<CustomField>
    <fullName>CodeFinContrat__c</fullName>
    <label>Code Fin Contrat</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>L</fullName>
            </value>
            <value>
                <fullName>E</fullName>
            </value>
            <value>
                <fullName>M</fullName>
            </value>
            <value>
                <fullName>X</fullName>
            </value>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>V</fullName>
            </value>
            <value>
                <fullName>S</fullName>
            </value>
            <value>
                <fullName>R</fullName>
            </value>
            <value>
                <fullName>P</fullName>
            </value>
            <value>
                <fullName>D</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Zuora__Subscription__c/fields/DateFinContrat__c.field-meta.xml
<CustomField>
    <fullName>DateFinContrat__c</fullName>
    <description>custom field for Date Fin Contrat pour les cancel sub a term</description>
    <label>Date Fin Contrat</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Zuora__Subscription__c/fields/Marche__c.field-meta.xml
<CustomField>
    <fullName>Marche__c</fullName>
    <description>BTOB, BTOC</description>
    <label>Marche</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Zuora__Subscription__c/fields/Payeur__c.field-meta.xml
<CustomField>
    <fullName>Payeur__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payeur</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contrat (Payeur)</relationshipLabel>
    <relationshipName>PayeurSubscription</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Zuora__Subscription__c/fields/PayeurCRMID__c.field-meta.xml
<CustomField>
    <fullName>PayeurCRMID__c</fullName>
    <label>PayeurCRMID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Zuora__Subscription__c/fields/Tech_AvecRembouesement__c.field-meta.xml
<CustomField>
    <fullName>Tech_AvecRembouesement__c</fullName>
    <label>Tech_AvecRembouesement</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Zuora__Subscription__c/fields/Tech_DetteFraisGestion__c.field-meta.xml
<CustomField>
    <fullName>Tech_DetteFraisGestion__c</fullName>
    <label>Tech_DetteFraisGestion</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Zuora__Subscription__c/fields/Tech_DetteNonEchue__c.field-meta.xml
<CustomField>
    <fullName>Tech_DetteNonEchue__c</fullName>
    <label>Tech_DetteNonEchue</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Zuora__Subscription__c/fields/Tech_DetteTargetDate__c.field-meta.xml
<CustomField>
    <fullName>Tech_DetteTargetDate__c</fullName>
    <label>Tech_DetteTargetDate</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Zuora__Subscription__c/fields/TypeContrat__c.field-meta.xml
<CustomField>
    <fullName>TypeContrat__c</fullName>
    <description>CDI ou CDD</description>
    <label>Type Contrat</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Zuora__Subscription__c/fields/Zuora__Account__c.field-meta.xml
<CustomField>
    <fullName>Zuora__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Zuora__Subscription__c/fields/Zuora__CancelledDate__c.field-meta.xml
<CustomField>
    <fullName>Zuora__CancelledDate__c</fullName>
    <description>The date of the Amendment object that canceled the subscription.</description>
    <label>Cancelled Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Zuora__Subscription__c/fields/Zuora__ContractEffectiveDate__c.field-meta.xml
<CustomField>
    <fullName>Zuora__ContractEffectiveDate__c</fullName>
    <description>This is the date on which the contract becomes effective, and will trigger charges that have their trigger event set to Upon Contract Effective.</description>
    <label>Contract Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Zuora__Subscription__c/fields/Zuora__CurrentTerm__c.field-meta.xml
<CustomField>
    <fullName>Zuora__CurrentTerm__c</fullName>
    <label>Current Term</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Zuora__Subscription__c/fields/Zuora__CurrentTermPeriodType__c.field-meta.xml
<CustomField>
    <fullName>Zuora__CurrentTermPeriodType__c</fullName>
    <description>The period type for the current subscription term.</description>
    <inlineHelpText>The period type of the current subscription term.</inlineHelpText>
    <label>Current Term Period Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Month</fullName>
            </value>
            <value>
                <fullName>Year</fullName>
            </value>
            <value>
                <fullName>Day</fullName>
            </value>
            <value>
                <fullName>Week</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Zuora__Subscription__c/fields/Zuora__CustomerAccount__c.field-meta.xml
<CustomField>
    <fullName>Zuora__CustomerAccount__c</fullName>
    <deleteConstraint>Cascade</deleteConstraint>
    <label>Billing Account</label>
    <referenceTo>Zuora__CustomerAccount__c</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Zuora__Subscription__c/fields/Zuora__External_Id__c.field-meta.xml
<CustomField>
    <fullName>Zuora__External_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>This field holds the Zuora object ID, and is used as external ID for data synchronization between Salesforce and Zuora.</description>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Zuora__Subscription__c/fields/Zuora__NextChargeDate__c.field-meta.xml
<CustomField>
    <fullName>Zuora__NextChargeDate__c</fullName>
    <label>Next Charge Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Zuora__Subscription__c/fields/Zuora__NextRenewalDate__c.field-meta.xml
<CustomField>
    <fullName>Zuora__NextRenewalDate__c</fullName>
    <label>Next Renewal Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Zuora__Subscription__c/fields/Zuora__PreviousSubscriptionId__c.field-meta.xml
<CustomField>
    <fullName>Zuora__PreviousSubscriptionId__c</fullName>
    <description>The subscription ID immediately prior to the current subscription.</description>
    <label>Previous Subscription Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Zuora__Subscription__c/fields/Zuora__Status__c.field-meta.xml
<CustomField>
    <fullName>Zuora__Status__c</fullName>
    <label>Status</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Zuora__Subscription__c/fields/Zuora__SubscriptionEndDate__c.field-meta.xml
<CustomField>
    <fullName>Zuora__SubscriptionEndDate__c</fullName>
    <description>This is when the subscription ends. This is always equal to term end date, unless the subscription has been cancelled. If the subscription has been cancelled, this is set to the cancellation date.</description>
    <label>Subscription End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Zuora__Subscription__c/fields/Zuora__SubscriptionNumber__c.field-meta.xml
<CustomField>
    <fullName>Zuora__SubscriptionNumber__c</fullName>
    <externalId>true</externalId>
    <label>Subscription Number</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Zuora__Subscription__c/fields/Zuora__SubscriptionStartDate__c.field-meta.xml
<CustomField>
    <fullName>Zuora__SubscriptionStartDate__c</fullName>
    <description>The date when the subscription term starts. This is equal to the term start date if the subscription is on its initial term. Otherwise, it is the original term start date if the subscription has renewed.</description>
    <label>Subscription Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Zuora__Subscription__c/fields/Zuora__TermEndDate__c.field-meta.xml
<CustomField>
    <fullName>Zuora__TermEndDate__c</fullName>
    <label>Term End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Zuora__Subscription__c/fields/Zuora__TermSettingType__c.field-meta.xml
<CustomField>
    <fullName>Zuora__TermSettingType__c</fullName>
    <description>Case sensitive. Denotes if a subscription is evergreen (has no end date or term length) or has a term.</description>
    <label>Term Setting Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>TERMED</fullName>
            </value>
            <value>
                <fullName>EVERGREEN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Zuora__Subscription__c/fields/Zuora__TermStartDate__c.field-meta.xml
<CustomField>
    <fullName>Zuora__TermStartDate__c</fullName>
    <label>Term Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Zuora__Subscription__c/fields/Zuora__Zuora_Id__c.field-meta.xml
<CustomField>
    <fullName>Zuora__Zuora_Id__c</fullName>
    <description>The Zuora Id (external primary key) of this Subscription.</description>
    <inlineHelpText>The Zuora Id (external primary key) of this Subscription.</inlineHelpText>
    <label>Zuora Id (Deprecated)</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Zuora__SubscriptionProductCharge__c/Zuora__SubscriptionProductCharge__c.object-meta.xml
<CustomObject>
    <label>Subscription Product &amp; Charge</label>
    <nameField>
        <label>Subscription Charge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscription Product &amp; Charges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Zuora__SubscriptionProductCharge__c/fields/Zuora__Zuora_Id__c.field-meta.xml
<CustomField>
    <fullName>Zuora__Zuora_Id__c</fullName>
    <description>The Zuora Id (external primary key) of this Subscription Product &amp; Charge.</description>
    <inlineHelpText>The Zuora Id (external primary key) of this Subscription Product &amp; Charge.</inlineHelpText>
    <label>Zuora Id</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SM_Subscription.cls
public with sharing class SM_Subscription {
	
    public static Zuora__Subscription__c getSubscription(Id subId) {
    	system.debug('##MNE SM_Subscription getSubscription subId >> '+subId);
        Zuora__Subscription__c subscription = [
                SELECT  Id,Name,TypeContrat__c,CodeFinContrat__c,Tech_AvecRembouesement__c,DateFinContrat__c,Marche__c,Tech_DetteFraisGestion__c,
						Tech_DetteNonEchue__c,Tech_DetteTargetDate__c,Zuora__SubscriptionNumber__c,Zuora__Status__c,Zuora__CancelledDate__c,
						Zuora__TermEndDate__c,Zuora__SubscriptionEndDate__c,Zuora__TermStartDate__c,Zuora__SubscriptionStartDate__c,Zuora__ContractEffectiveDate__c,
						Zuora__NextChargeDate__c,Zuora__NextRenewalDate__c,Zuora__PreviousSubscriptionId__c,Zuora__External_Id__c,Zuora__CurrentTermPeriodType__c,
						Zuora__CurrentTerm__c,Zuora__TermSettingType__c,Zuora__Zuora_Id__c,Zuora__Account__r.Id,Zuora__Account__r.CodePays__c,Zuora__Account__r.PersonContactId,
						Zuora__CustomerAccount__r.Zuora__Balance__c,Zuora__CustomerAccount__r.Zuora__Zuora_Id__c
                FROM Zuora__Subscription__c
                WHERE Id = :subId
        ];
       return subscription;
    }


    public static Zuora__Subscription__c getSubscriptionByZID(String subZId) {
        //TODO: dans le cas ou la demande doit traiter une souscription non active ou ex. client qui a plusieurs subscriptions (doublons à traiter)
        //il faut songer à lier la demande à la souscription automatiquement à la création (si une seul active) et prevoir un lookup pour
        // laisser le CC selection une souscription si l'action doit se faire sur une souscription autre que celle renvoyé par getActiveSub..
        System.debug('##MBEN:setSub');
        List<Zuora__Subscription__c> subscriptions = [
                SELECT  Id,Name,TypeContrat__c,CodeFinContrat__c,Tech_AvecRembouesement__c,DateFinContrat__c,Marche__c,Tech_DetteFraisGestion__c,
						Tech_DetteNonEchue__c,Tech_DetteTargetDate__c,Zuora__SubscriptionNumber__c,Zuora__Status__c,Zuora__CancelledDate__c,
						Zuora__TermEndDate__c,Zuora__SubscriptionEndDate__c,Zuora__TermStartDate__c,Zuora__SubscriptionStartDate__c,Zuora__ContractEffectiveDate__c,
						Zuora__NextChargeDate__c,Zuora__NextRenewalDate__c,Zuora__PreviousSubscriptionId__c,Zuora__External_Id__c,Zuora__CurrentTermPeriodType__c,
						Zuora__CurrentTerm__c,Zuora__TermSettingType__c,Zuora__Zuora_Id__c,Zuora__Account__r.Id,Zuora__Account__r.CodePays__c,Zuora__Account__r.PersonContactId,
						Zuora__CustomerAccount__r.Zuora__Balance__c,Zuora__CustomerAccount__r.Zuora__Zuora_Id__c
                FROM Zuora__Subscription__c
                WHERE Zuora__External_Id__c = :subZId
        ];
        if (subscriptions.size() == 0){
            return null;
        }else if (subscriptions.size() == 1){
            return subscriptions.get(0);
        }else {
            return null;
        }
    }
    
    
    public static WRPRep getActiveSubscriptionId(Id accId) {
    	system.debug('##MNE SM_Subscription getActiveSubscriptionId accId >> '+accId);
        Date d1 = Date.today();
        List<Zuora__Subscription__c> subscriptions = [
                SELECT  Id,Name,TypeContrat__c,CodeFinContrat__c,Tech_AvecRembouesement__c,DateFinContrat__c,Marche__c,Tech_DetteFraisGestion__c,
						Tech_DetteNonEchue__c,Tech_DetteTargetDate__c,Zuora__SubscriptionNumber__c,Zuora__Status__c,Zuora__CancelledDate__c,
						Zuora__TermEndDate__c,Zuora__SubscriptionEndDate__c,Zuora__TermStartDate__c,Zuora__SubscriptionStartDate__c,Zuora__ContractEffectiveDate__c,
						Zuora__NextChargeDate__c,Zuora__NextRenewalDate__c,Zuora__PreviousSubscriptionId__c,Zuora__External_Id__c,Zuora__CurrentTermPeriodType__c,
						Zuora__CurrentTerm__c,Zuora__TermSettingType__c,Zuora__Zuora_Id__c,Zuora__Account__r.Id,Zuora__Account__r.CodePays__c,Zuora__Account__r.PersonContactId,
						Zuora__CustomerAccount__r.Zuora__Balance__c,Zuora__CustomerAccount__r.Zuora__Zuora_Id__c
                FROM Zuora__Subscription__c
                WHERE Zuora__Account__r.Id = :accId
                AND ( Zuora__SubscriptionEndDate__c > :d1 OR Zuora__SubscriptionEndDate__c = NULL )
                ORDER BY CreatedDate DESC
        ];
        
		system.debug('##MNE SM_Subscription getActiveSubscriptionId subscriptions >> '+subscriptions);
        if (subscriptions.isEmpty()) {
            return null;
        } else {
            return new WRPRep(subscriptions[0].Id, subscriptions[0].Zuora__Zuora_Id__c, subscriptions[0].Name);
        }
    }
    
    //Non utilisé
    public static list<Zuora__Subscription__c> getActiveSubscriptionBySetAccId(set<Id> setAccId) {
    	system.debug('##MNE SM_Subscription getActiveSubscriptionBySetAccId setAccId >> '+setAccId);
        Date d1 = Date.today();
        list<Zuora__Subscription__c> listSub = new list<Zuora__Subscription__c>([
                SELECT  Id,Name,TypeContrat__c,CodeFinContrat__c,Tech_AvecRembouesement__c,DateFinContrat__c,Marche__c,Tech_DetteFraisGestion__c,
						Tech_DetteNonEchue__c,Tech_DetteTargetDate__c,Zuora__SubscriptionNumber__c,Zuora__Status__c,Zuora__CancelledDate__c,
						Zuora__TermEndDate__c,Zuora__SubscriptionEndDate__c,Zuora__TermStartDate__c,Zuora__SubscriptionStartDate__c,Zuora__ContractEffectiveDate__c,
						Zuora__NextChargeDate__c,Zuora__NextRenewalDate__c,Zuora__PreviousSubscriptionId__c,Zuora__External_Id__c,Zuora__CurrentTermPeriodType__c,
						Zuora__CurrentTerm__c,Zuora__TermSettingType__c,Zuora__Zuora_Id__c,Zuora__Account__r.Id,Zuora__Account__r.CodePays__c,Zuora__Account__r.PersonContactId,
						Zuora__CustomerAccount__r.Zuora__Balance__c,Zuora__CustomerAccount__r.Zuora__Zuora_Id__c
                FROM Zuora__Subscription__c
                WHERE Zuora__Account__r.Id IN :setAccId
                AND ( Zuora__SubscriptionEndDate__c > :d1 OR Zuora__SubscriptionEndDate__c = NULL )
                ORDER BY CreatedDate DESC
        ]);
		system.debug('##MNE SM_Subscription getActiveSubscriptionBySetAccId listSub >> '+listSub);
        return listSub;
    }
    
    //Non utilisé
    public static list<Zuora__Subscription__c> getSubscriptionBySetName(set<String> setName) {
    	system.debug('##MNE SM_Subscription getSubscriptionBySetName setName >> '+setName);
        list<Zuora__Subscription__c> listSub = new list<Zuora__Subscription__c>([
                SELECT  Id,Name,TypeContrat__c,CodeFinContrat__c,Tech_AvecRembouesement__c,DateFinContrat__c,Marche__c,Tech_DetteFraisGestion__c,
						Tech_DetteNonEchue__c,Tech_DetteTargetDate__c,Zuora__SubscriptionNumber__c,Zuora__Status__c,Zuora__CancelledDate__c,
						Zuora__TermEndDate__c,Zuora__SubscriptionEndDate__c,Zuora__TermStartDate__c,Zuora__SubscriptionStartDate__c,Zuora__ContractEffectiveDate__c,
						Zuora__NextChargeDate__c,Zuora__NextRenewalDate__c,Zuora__PreviousSubscriptionId__c,Zuora__External_Id__c,Zuora__CurrentTermPeriodType__c,
						Zuora__CurrentTerm__c,Zuora__TermSettingType__c,Zuora__Zuora_Id__c,Zuora__Account__r.Id,Zuora__Account__r.CodePays__c,Zuora__Account__r.PersonContactId,
						Zuora__CustomerAccount__r.Zuora__Balance__c,Zuora__CustomerAccount__r.Zuora__Zuora_Id__c
                FROM Zuora__Subscription__c
                WHERE Zuora__SubscriptionNumber__c IN :setName
                ORDER BY CreatedDate DESC
        ]);
		system.debug('##MNE SM_Subscription getSubscriptionBySetName listSub >> '+listSub);
        return listSub;
    }
    
    
    public static list<Zuora__Subscription__c> getActiveSubscriptionBySetNameORSetAccId(set<String> setName, set<Id> setAccId) {
    	system.debug('##MNE SM_Subscription getActiveSubscriptionBySetAccIdAndSetName setName >> '+setName);
    	system.debug('##MNE SM_Subscription getActiveSubscriptionBySetAccIdAndSetName setAccId >> '+setAccId);
        Date d1 = Date.today();
        list<Zuora__Subscription__c> listSub = new list<Zuora__Subscription__c>([
                SELECT  Id,Name,TypeContrat__c,CodeFinContrat__c,Tech_AvecRembouesement__c,DateFinContrat__c,Marche__c,Tech_DetteFraisGestion__c,
						Tech_DetteNonEchue__c,Tech_DetteTargetDate__c,Zuora__SubscriptionNumber__c,Zuora__Status__c,Zuora__CancelledDate__c,
						Zuora__TermEndDate__c,Zuora__SubscriptionEndDate__c,Zuora__TermStartDate__c,Zuora__SubscriptionStartDate__c,Zuora__ContractEffectiveDate__c,
						Zuora__NextChargeDate__c,Zuora__NextRenewalDate__c,Zuora__PreviousSubscriptionId__c,Zuora__External_Id__c,Zuora__CurrentTermPeriodType__c,
						Zuora__CurrentTerm__c,Zuora__TermSettingType__c,Zuora__Zuora_Id__c,Zuora__Account__r.Id,Zuora__Account__r.CodePays__c,Zuora__Account__r.PersonContactId,
						Zuora__CustomerAccount__r.Zuora__Balance__c,Zuora__CustomerAccount__r.Zuora__Zuora_Id__c
                FROM Zuora__Subscription__c
                WHERE Zuora__SubscriptionNumber__c IN :setName
				OR (Zuora__Account__r.Id IN :setAccId AND (Zuora__SubscriptionEndDate__c > :d1 OR Zuora__SubscriptionEndDate__c = NULL))
                ORDER BY CreatedDate DESC
        ]);
		system.debug('##MNE SM_Subscription getActiveSubscriptionBySetAccIdAndSetName listSub >> '+listSub);
        return listSub;
    }
    
    
    public static Zuora__Subscription__c getActiveSubscriptionByNameORAccId(String subName, Id accId) {
    	system.debug('##MNE SM_Subscription getActiveSubscriptionByNameORAccId subName >> '+subName);
    	system.debug('##MNE SM_Subscription getActiveSubscriptionByNameORAccId accId >> '+accId);
		list<Zuora__Subscription__c> listSub = null;
		if(String.isNotEmpty(subName)){
			listSub = SM_Subscription.getSubscriptionBySetName(new set<String>{subName});
		} else if(accId != null){
			listSub = SM_Subscription.getActiveSubscriptionBySetAccId(new set<Id>{accId});
		} else {
			return null;
		}
		
		if(listSub.size() != 1){
			return null;
		}
		system.debug('##MNE SM_Subscription getActiveSubscriptionByNameORAccId listSub.get(0) >> '+listSub.get(0));
		return listSub.get(0);
	}
    

    // method updateWS
    public static WSZ.SubOut updateSub(String subId, Object sub, String zEntityId) {
        System.debug('##MBEN: updateWS');
        String endpoint = '/v1/object/subscription/' + subId;
        String method = 'PUT';
        String wsIn = '';
        String wsOut = '';
        String accessToken = WS001_CallZuora.access_token;
        wsIn = Util.serializeSobject(sub);
        System.debug('##MBEN7: |' + wsIn + '|');
        wsOut = WS001_CallZuora.sendRequest(accessToken, endpoint, zEntityId, method, wsIn,'type1', null);
        return (WSZ.SubOut) JSON.deserializeStrict(wsOut, WSZ.SubOut.class);
    }
    
    
    // method cancelWS
    public static WSZ.SubCancelOut cancelSub(String cancellationEffectiveDate, String policy, String subId, Boolean runBilling, String targetDate, String zEntityId) {
        System.debug('##MBEN: cancelWS');
        system.debug('##MNE SM_Subscription cancelSub cancellationEffectiveDate >> '+cancellationEffectiveDate);
        system.debug('##MNE SM_Subscription cancelSub policy >> '+policy);
        system.debug('##MNE SM_Subscription cancelSub subId >> '+subId);
        system.debug('##MNE SM_Subscription cancelSub runBilling >> '+runBilling);
        system.debug('##MNE SM_Subscription cancelSub targetDate >> '+targetDate);
        
        String endpoint = '/v1/subscriptions/' + subId + '/cancel';
        String method = 'PUT';
        String wsIn = '';
        String wsOut = '';
        String accessToken = WS001_CallZuora.access_token;

        WSZ.SubCancelIn wsInObj = new WSZ.SubCancelIn();
        if(policy == 'EndOfLastInvoicePeriod'){
        	wsInObj.cancellationPolicy = policy;
        } else {
        	wsInObj.cancellationEffectiveDate = cancellationEffectiveDate;
	        wsInObj.cancellationPolicy = policy;
	        wsInObj.runBilling = runBilling;
        }
        wsInObj.targetDate = targetDate;
        
        System.debug('##MBEN6: |' + wsInObj.cancellationEffectiveDate + '|' + wsInObj.cancellationPolicy);
        wsIn = (String) JSON.serialize(wsInObj);
        System.debug('##MBEN7: |' + wsIn + '|');
        wsOut = WS001_CallZuora.sendRequest(accessToken, endpoint, zEntityId, method, wsIn, 'type1', '211.0');
        System.debug('##MBEN7: cancel executed |' + wsIn + '|');
        return (WSZ.SubCancelOut) JSON.deserializeStrict(wsOut, WSZ.SubCancelOut.class);
    }
    
    
    // method deleteWS: Annuler un desabonnement
    public static WSZ.SubOut deleteSub(String subId, String zEntityId) {
        String endpoint = '/v1/object/subscription/' + subId;
        String method = 'DELETE';
        String wsIn = null;
        String wsOut = '';
        String accessToken = WS001_CallZuora.access_token;

        wsOut = WS001_CallZuora.sendRequest(accessToken, endpoint, zEntityId, method, wsIn, 'type1', null);
        return (WSZ.SubOut) JSON.deserializeStrict(wsOut, WSZ.SubOut.class);
    }
    
    
    public without sharing class WRPRep {
        public Id subscriptionId            { get; set; }
        public String zuoraSubscriptionId   { get; set; }
        public String subscriptionName   { get; set; }
        
        public WRPRep(Id subscriptionId, String zuoraSubscriptionId, String subscriptionName) {
            this.subscriptionId         = subscriptionId;
            this.zuoraSubscriptionId    = zuoraSubscriptionId;
            this.subscriptionName    	= subscriptionName;
        }
    }
    
    public static list<WSZ.DeleteOut> deleteZObject(list<String> listZObjectId, String zObjectName, String zEntityId) {
        String endpoint = '/v1/action/delete';
        String method = 'POST';
        String wsIn = '';
        String wsOut = '';
        String accessToken = WS001_CallZuora.access_token;
        
        WSZ.DeleteIn wsInObj = new WSZ.DeleteIn(listZObjectId, zObjectName);
		wsIn = (String) JSON.serialize(wsInObj);
		wsIn = wsIn.replace('typeX','type');
		
		system.debug('##MNE SM_Subscription deleteZObject wsIn >> '+wsIn);
		
        wsOut = WS001_CallZuora.sendRequest(accessToken, endpoint, zEntityId, method, wsIn, 'type1', null);
        
        system.debug('##MNE SM_Subscription deleteZObject wsOut >> '+wsOut);
        
        return (list<WSZ.DeleteOut>) JSON.deserializeStrict(wsOut, list<WSZ.DeleteOut>.class);   
    }


    // method updateWS zuora using Action/update input: list of sub ids and fields to update.
    // update key: Zuora__Zuora_Id__c
    public static List<WSZ.SubOut> updateSub2(List<Zuora__Subscription__c> subs, String zEntityId) {
        System.debug('##MBEN: updateWS');
        String endpoint = '/v1/action/update';
        String method = 'POST';
        String wsIn = '';
        String wsOut = '';
        WSZ.WRPOauthLogin tokObj = WS001_CallZuora.access_token2;

        WSZ.SubUpdateIn subUpdateIn = new WSZ.SubUpdateIn(subs);
        wsIn = (String) JSON.serialize(subUpdateIn);
        wsIn = wsIn.replace('Zuora__Zuora_Id__c','Id');
        System.debug('##MBEN7: |' + wsIn + '|');
        wsOut = WS001_CallZuora.sendRequest(tokObj.access_token, endpoint, zEntityId, method, wsIn,'type1',null);
        WS001_CallZuora.update_token2(tokObj);
        return (List<WSZ.SubOut>) JSON.deserializeStrict(wsOut, List<WSZ.SubOut>.class);
    }
    
    
    //##MNE 18/09/2019
    public static void SubscriptionBeforeInsert (List<Zuora__Subscription__c> listSubscriptions)  {   
    	system.debug('##MNE SM_Subscription SubscriptionBeforeInsert listSubscriptions >> '+listSubscriptions);
    	if(listSubscriptions != null && listSubscriptions.size() > 0){
    		checkPayeurSubscription(null, listSubscriptions);
    	}
    }
    
    //##MNE 18/09/2019
    public static void SubscriptionBeforeUpdate (map<Id, Zuora__Subscription__c> mapOldSubscriptions, List<Zuora__Subscription__c> listSubscriptions)  { 
    	system.debug('##MNE SM_Subscription SubscriptionBeforeUpdate mapOldSubscriptions >> '+mapOldSubscriptions); 
    	system.debug('##MNE SM_Subscription SubscriptionBeforeUpdate listSubscriptions >> '+listSubscriptions);
    	if(listSubscriptions != null && listSubscriptions.size() > 0){
    		checkPayeurSubscription(mapOldSubscriptions, listSubscriptions);
    	} 
    }
    
    //##MNE 18/09/2019
    public static void checkPayeurSubscription (map<Id, Zuora__Subscription__c> mapOldSubscriptions, List<Zuora__Subscription__c> listSubscriptions)  {
    	system.debug('##MNE SM_Subscription checkPayeurSubscription mapOldSubscriptions >> '+mapOldSubscriptions); 
    	system.debug('##MNE SM_Subscription checkPayeurSubscription listSubscriptions >> '+listSubscriptions);

    	if(listSubscriptions == null || listSubscriptions.size() == 0){
    		return;
    	} 
    	map<Id, Account> mapAccountToUpdateById = new map<Id, Account>();
    	set<Id> setAccountId = new set<Id>();
    	for(Zuora__Subscription__c sub : listSubscriptions){
    		Account acc = null;
    		if(sub.Zuora__Account__c != null){
    			setAccountId.add(sub.Zuora__Account__c);
    			acc = new Account(Id = sub.Zuora__Account__c);
    		}
    		
    		Zuora__Subscription__c oldSub = null;
    		if(mapOldSubscriptions != null && mapOldSubscriptions.containsKey(sub.Id)){
    			oldSub = mapOldSubscriptions.get(sub.Id);
    		}
    		
    		if(oldSub == null && sub.PayeurCRMID__c != sub.Zuora__Account__c){
				sub.Payeur__c = sub.PayeurCRMID__c;
				if(acc != null){
					acc.Payeur__c = sub.PayeurCRMID__c;
					mapAccountToUpdateById.put(acc.Id, acc);
				}
			}
			else if(oldSub != null ){
				if(oldSub.PayeurCRMID__c != sub.PayeurCRMID__c) {
					if(sub.PayeurCRMID__c == sub.Zuora__Account__c){
						if(acc != null){
							acc.Payeur__c = null;
							mapAccountToUpdateById.put(acc.Id, acc);
						}
					}
					else if(sub.PayeurCRMID__c != sub.Zuora__Account__c ) {
						sub.Payeur__c = sub.PayeurCRMID__c;
						if(acc != null){
							acc.Payeur__c = sub.PayeurCRMID__c;
							mapAccountToUpdateById.put(acc.Id, acc);
						}
					}
				}
			}
    	}
    	
    	if(setAccountId.size() > 0){
    		list<Account> accountToUpdate = new list<Account>();
	    	map<Id, Account> mapAccountById = new map<Id, Account>([SELECT Id FROM Account WHERE Id  IN :setAccountId]);
	    	set<Id> setAccountIdFromMap = mapAccountById.keySet();
	    	
	    	if(setAccountIdFromMap != null && setAccountIdFromMap.size() > 0){
		    	for(Id accId : setAccountIdFromMap){
		    		if(mapAccountToUpdateById.containsKey(accId)){
		    			accountToUpdate.add(mapAccountToUpdateById.get(accId));
		    		}
		    	}
		    	system.debug('##MNE SM_Subscription checkPayeurSubscription accountToUpdate >> '+accountToUpdate);
		    	if(accountToUpdate.size() > 0){
		    		update accountToUpdate;
		    	} 
    		}
    	}
    }
    

	/*//Non utilisé
    public static Zuora__Subscription__c getSubscriptionByName(String name) {
        //TODO: dans le cas ou la demande doit traiter une souscription non active ou ex. client qui a plusieurs subscriptions (doublons à traiter)
        //il faut songer à lier la demande à la souscription automatiquement à la création (si une seul active) et prevoir un lookup pour
        // laisser le CC selection une souscription si l'action doit se faire sur une souscription autre que celle renvoyé par getActiveSub..
        System.debug('##MBEN:setSub');
        Zuora__Subscription__c subscription = [
                SELECT  Id,Name,TypeContrat__c,CodeFinContrat__c,Tech_AvecRembouesement__c,DateFinContrat__c,Marche__c,Tech_DetteFraisGestion__c,
						Tech_DetteNonEchue__c,Tech_DetteTargetDate__c,Zuora__SubscriptionNumber__c,Zuora__Status__c,Zuora__CancelledDate__c,
						Zuora__TermEndDate__c,Zuora__SubscriptionEndDate__c,Zuora__TermStartDate__c,Zuora__SubscriptionStartDate__c,Zuora__ContractEffectiveDate__c,
						Zuora__NextChargeDate__c,Zuora__NextRenewalDate__c,Zuora__PreviousSubscriptionId__c,Zuora__External_Id__c,Zuora__CurrentTermPeriodType__c,
						Zuora__CurrentTerm__c,Zuora__TermSettingType__c,Zuora__Zuora_Id__c,Zuora__Account__r.Id,Zuora__Account__r.CodePays__c,Zuora__Account__r.PersonContactId,
						Zuora__CustomerAccount__r.Zuora__Balance__c,Zuora__CustomerAccount__r.Zuora__Zuora_Id__c
                FROM Zuora__Subscription__c
                WHERE Zuora__SubscriptionNumber__c = :name
        ];
        return subscription;
    }*/
    
    /*//non utiliser
    public static list<Zuora__Subscription__c> getActiveSubscriptionBySetNameORSetZSubIdORSetAccId(set<String> setName, set<String> setZSubId, set<Id> setAccId) {
    	system.debug('##MNE SM_Subscription getActiveSubscriptionBySetNameORSetZSubIdORSetAccId setName >> '+setName);
    	system.debug('##MNE SM_Subscription getActiveSubscriptionBySetNameORSetZSubIdORSetAccId setZSubId >> '+setZSubId);
    	system.debug('##MNE SM_Subscription getActiveSubscriptionBySetNameORSetZSubIdORSetAccId setAccId >> '+setAccId);
        Date d1 = Date.today();
        list<Zuora__Subscription__c> listSub = new list<Zuora__Subscription__c>([
                SELECT  Id,Name,TypeContrat__c,CodeFinContrat__c,Tech_AvecRembouesement__c,DateFinContrat__c,Marche__c,Tech_DetteFraisGestion__c,
						Tech_DetteNonEchue__c,Tech_DetteTargetDate__c,Zuora__SubscriptionNumber__c,Zuora__Status__c,Zuora__CancelledDate__c,
						Zuora__TermEndDate__c,Zuora__SubscriptionEndDate__c,Zuora__TermStartDate__c,Zuora__SubscriptionStartDate__c,Zuora__ContractEffectiveDate__c,
						Zuora__NextChargeDate__c,Zuora__NextRenewalDate__c,Zuora__PreviousSubscriptionId__c,Zuora__External_Id__c,Zuora__CurrentTermPeriodType__c,
						Zuora__CurrentTerm__c,Zuora__TermSettingType__c,Zuora__Zuora_Id__c,Zuora__Account__r.Id,Zuora__Account__r.CodePays__c,Zuora__Account__r.PersonContactId,
						Zuora__CustomerAccount__r.Zuora__Balance__c,Zuora__CustomerAccount__r.Zuora__Zuora_Id__c
                FROM Zuora__Subscription__c
                WHERE Zuora__SubscriptionNumber__c IN :setName
				OR Zuora__External_Id__c IN :setZSubId
				OR (Zuora__Account__r.Id = :setAccId AND (Zuora__SubscriptionEndDate__c > :d1 OR Zuora__SubscriptionEndDate__c = NULL))
                ORDER BY CreatedDate DESC
        ]);
		system.debug('##MNE SM_Subscription getActiveSubscriptionBySetNameORSetZSubIdORSetAccId listSub >> '+listSub);
        return listSub;
    }*/
    
	//Non Utiliser
    // method : recupere le contrat actif du client
    // TODO Cette methode peut evoluer pour filtrer le dernier contrat parmis plusieurs ou se baser sur subscription end date
    /*public static Id getLastActiveSubscriptionId(Id accId) {
        Date d1 = Date.today();
        List<Zuora__Subscription__c> subscriptions = [
                SELECT  Id,Name,TypeContrat__c,CodeFinContrat__c,Tech_AvecRembouesement__c,DateFinContrat__c,Marche__c,Tech_DetteFraisGestion__c,
						Tech_DetteNonEchue__c,Tech_DetteTargetDate__c,Zuora__SubscriptionNumber__c,Zuora__Status__c,Zuora__CancelledDate__c,
						Zuora__TermEndDate__c,Zuora__SubscriptionEndDate__c,Zuora__TermStartDate__c,Zuora__SubscriptionStartDate__c,Zuora__ContractEffectiveDate__c,
						Zuora__NextChargeDate__c,Zuora__NextRenewalDate__c,Zuora__PreviousSubscriptionId__c,Zuora__External_Id__c,Zuora__CurrentTermPeriodType__c,
						Zuora__CurrentTerm__c,Zuora__TermSettingType__c,Zuora__Zuora_Id__c,Zuora__Account__r.Id,Zuora__Account__r.CodePays__c,Zuora__Account__r.PersonContactId,
						Zuora__CustomerAccount__r.Zuora__Balance__c,Zuora__CustomerAccount__r.Zuora__Zuora_Id__c
                FROM Zuora__Subscription__c
                WHERE Zuora__Account__r.Id = :accId
                //AND Zuora__Status__c = 'Active' AND Zuora__SubscriptionEndDate__c > :d1 ORDER BY CreatedDate DESC LIMIT 1];
                AND Zuora__SubscriptionEndDate__c > :d1
                ORDER BY CreatedDate DESC
                LIMIT 1
        ];
        if (subscriptions.isEmpty()) {
            return null;
        } else {
            return subscriptions[0].Id;
        }
    }*/

	/*//non utliser
	public static Date getLastChargedDate(String subZID) {
	    List<AggregateResult> gResult= [SELECT  MAX(Zuora__ChargedThroughDate__c) maxDate  FROM Zuora__SubscriptionProductCharge__c
	                WHERE Zuora__Subscription__r.Zuora__External_Id__c=:subZID AND Zuora__IsLastSegment__c='true'];
	    return (Date)gResult[0].get('maxDate');
    }*/
    
    //##MNE 24/09/2018 dev after 'note de Mouadh'
    //##MNE commenter a la suite refonte synchro, on ne met plus a jour l'id de la sub sur les case apres un amend
    /*public static void SubscriptionAfterInsert (List<Zuora__Subscription__c> listSubscriptions)  {   
        system.debug('##MNE SM_Subscription SubscriptionAfterInsert listSubscriptions >> '+listSubscriptions);
        map<String, Zuora__Subscription__c> mapSubscriptionByZuoraPreviousSubscriptionId = new map<String, Zuora__Subscription__c>();
        for(Zuora__Subscription__c sub : listSubscriptions){
            if(String.isNotBlank(sub.Name)){
                mapSubscriptionByZuoraPreviousSubscriptionId.put(sub.Name, sub);
            }
        }
        list<Case> listCasesToProcess = new list<Case>([Select Id, SubscriptionZName__c, Subscription__c FROM Case WHERE SubscriptionZName__c IN :mapSubscriptionByZuoraPreviousSubscriptionId.keySet()]);
        list<Case> listCasesToUpdated = new list<Case>();
        //list<File_Impression__c> listFIToProcess = new list<File_Impression__c>([Select Id, SubscriptionZName__c, Subscription__c FROM File_Impression__c WHERE SubscriptionZName__c IN :mapSubscriptionByZuoraPreviousSubscriptionId.keySet()]);
        //list<File_Impression__c> listFIToUpdated = new list<File_Impression__c>();
        for(Case c : listCasesToProcess){
            if(String.isNotBlank(c.SubscriptionZName__c) && mapSubscriptionByZuoraPreviousSubscriptionId.containsKey(c.SubscriptionZName__c)){
                c.Subscription__c    = mapSubscriptionByZuoraPreviousSubscriptionId.get(c.SubscriptionZName__c).Id;
                c.SubscriptionZName__c = mapSubscriptionByZuoraPreviousSubscriptionId.get(c.SubscriptionZName__c).Name; 
                listCasesToUpdated.add(c);
            }   
        }
        if(listCasesToUpdated.size() > 0){
            update listCasesToUpdated;
        }
        //for(File_Impression__c fi : listFIToProcess){
        //    if(String.isNotBlank(fi.SubscriptionZName__c) && mapSubscriptionByZuoraPreviousSubscriptionId.containsKey(fi.SubscriptionZName__c)){
        //        fi.Subscription__c    = mapSubscriptionByZuoraPreviousSubscriptionId.get(fi.SubscriptionZName__c).Id;
        //        fi.SubscriptionZName__c = mapSubscriptionByZuoraPreviousSubscriptionId.get(fi.SubscriptionZName__c).Name; 
        //        listFIToUpdated.add(fi);
        //    }   
        //}
        //if(listFIToUpdated.size() > 0){
        //    update listFIToUpdated;
        //}
    }*/

    /*public static Zuora__Subscription__c getSubByPaymentId(String paymentId){
        String invoiceId = SM_Payment.getPaymentPart(paymentId).paymentParts[0].invoiceId;
        String subName = SM_Invoice.getInvoiceItems(invoiceId).invoiceItems[0].subscriptionName;
        return getSubscriptionByName(subName);
    }*/
    
	/*//non utiliser
    public static void syncCancelCaseId (map<Id, Zuora__Subscription__c> mapOldSubscriptions, List<Zuora__Subscription__c> listSubscriptions)  {
            //TODO   Sync du CancelCaseID et CancelCase__c
    }*/
}