force-app/main/default/objects/Account/fields/CodeFinContrat__c.field-meta.xml
<CustomField>
    <fullName>CodeFinContrat__c</fullName>
    <label>Code Fin Contrat</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>L</fullName>
            </value>
            <value>
                <fullName>E</fullName>
            </value>
            <value>
                <fullName>X</fullName>
            </value>
            <value>
                <fullName>M</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/CodePays__c.field-meta.xml
<CustomField>
    <fullName>CodePays__c</fullName>
    <label>Code Pays</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/IdMonCompte__c.field-meta.xml
<CustomField>
    <fullName>IdMonCompte__c</fullName>
    <label>Id MonCompte</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/lien_porteur_payeur__c.field-meta.xml
<CustomField>
    <fullName>lien_porteur_payeur__c</fullName>
    <formula>IF(Payeur__c =&#39;&#39; , &quot;Porteur = Payeur&quot;,  &#39;Porteur ≠ Payeur&#39;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>lien porteur / payeur</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Note_Client__c.field-meta.xml
<CustomField>
    <fullName>Note_Client__c</fullName>
    <label>Note Client</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/ProduitUGC__c.field-meta.xml
<CustomField>
    <fullName>ProduitUGC__c</fullName>
    <defaultValue>&quot;français&quot;</defaultValue>
    <label>Pays de résidence</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>français</fullName>
                <default>true</default>
                <label>français</label>
            </value>
            <value>
                <fullName>belge</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/ScoreAntichurn__c.field-meta.xml
<CustomField>
    <fullName>ScoreAntichurn__c</fullName>
    <label>Score antichurn</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Tech_IdMonCompte__c.field-meta.xml
<CustomField>
    <fullName>Tech_IdMonCompte__c</fullName>
    <externalId>true</externalId>
    <label>Tech Id MonCompte</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Carte__c/Carte__c.object-meta.xml
<CustomObject>
    <description>Carte abonné, UI/UU</description>
    <label>Carte</label>
    <nameField>
        <label>Numéro de carte</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cartes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Carte__c/fields/Abonn__c.field-meta.xml
<CustomField>
    <fullName>Abonn__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Abonné</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cartes</relationshipLabel>
    <relationshipName>Cartes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Carte__c/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Carte__c.field-meta.xml
<CustomField>
    <fullName>Carte__c</fullName>
    <description>Champ pour la création d&#39;un ticket par la salle</description>
    <label>Carte</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>N/A</fullName>
            </value>
            <value>
                <fullName>En possession de l&#39;abonné</fullName>
            </value>
            <value>
                <fullName>Récupéré par la salle</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/DateFinContrat__c.field-meta.xml
<CustomField>
    <fullName>DateFinContrat__c</fullName>
    <label>TECH_Date de fin de contrat</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/Subscription__c.field-meta.xml
<CustomField>
    <fullName>Subscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Abonnement</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>$Source.AccountId</field>
            <operation>equals</operation>
            <valueField>Zuora__Subscription__c.Zuora__Account__r.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Zuora__Subscription__c</referenceTo>
    <relationshipLabel>Demandes</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/SubscriptionZName__c.field-meta.xml
<CustomField>
    <fullName>SubscriptionZName__c</fullName>
    <description>Stock le name Zuora de la souscription</description>
    <label>Zuora Subscription Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/TECH_IdMonCompte__c.field-meta.xml
<CustomField>
    <fullName>TECH_IdMonCompte__c</fullName>
    <description>Champ technique utilisé par le flux pour alimenter Vertica.</description>
    <formula>Account.IdMonCompte__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>TECH_IdMonCompte</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Zuora__Subscription__c/Zuora__Subscription__c.object-meta.xml
<CustomObject>
    <description>A subscription is a product or service that has recurring charges, such as a monthly flat fee or charges based on usage. Subscriptions can also include one-time charges, such as activation fees.</description>
    <label>Subscription</label>
    <nameField>
        <label>Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Zuora__Subscription__c/fields/CodeFinContrat__c.field-meta.xml
<CustomField>
    <fullName>CodeFinContrat__c</fullName>
    <label>Code Fin Contrat</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>L</fullName>
            </value>
            <value>
                <fullName>E</fullName>
            </value>
            <value>
                <fullName>M</fullName>
            </value>
            <value>
                <fullName>X</fullName>
            </value>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>V</fullName>
            </value>
            <value>
                <fullName>S</fullName>
            </value>
            <value>
                <fullName>R</fullName>
            </value>
            <value>
                <fullName>P</fullName>
            </value>
            <value>
                <fullName>D</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Zuora__Subscription__c/fields/CodeOffrePrincipale__c.field-meta.xml
<CustomField>
    <fullName>CodeOffrePrincipale__c</fullName>
    <label>Code Offre Principale</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>UI1CDD</fullName>
            </value>
            <value>
                <fullName>UI2CDD</fullName>
            </value>
            <value>
                <fullName>UI3CDD</fullName>
            </value>
            <value>
                <fullName>UUCDD</fullName>
            </value>
            <value>
                <fullName>UI1CDI</fullName>
            </value>
            <value>
                <fullName>UI2CDI</fullName>
            </value>
            <value>
                <fullName>UI3CDI</fullName>
            </value>
            <value>
                <fullName>UUCDI</fullName>
            </value>
            <value>
                <fullName>UU</fullName>
            </value>
            <value>
                <fullName>UI1</fullName>
            </value>
            <value>
                <fullName>UI2</fullName>
            </value>
            <value>
                <fullName>UI3</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Zuora__Subscription__c/fields/Date_de_debut_de_contrat__c.field-meta.xml
<CustomField>
    <fullName>Date_de_debut_de_contrat__c</fullName>
    <formula>Zuora__ContractEffectiveDate__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Date de début de contrat</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Zuora__Subscription__c/fields/DateFinContrat__c.field-meta.xml
<CustomField>
    <fullName>DateFinContrat__c</fullName>
    <description>custom field for Date Fin Contrat pour les cancel sub a term</description>
    <label>Date Fin Contrat</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Zuora__Subscription__c/fields/lien_porteur_payeur__c.field-meta.xml
<CustomField>
    <fullName>lien_porteur_payeur__c</fullName>
    <formula>IF(Payeur__c =&#39;&#39; , &quot;Porteur = Payeur&quot;, &#39;Porteur ≠ Payeur&#39;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>lien porteur / payeur</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Zuora__Subscription__c/fields/Lieu__c.field-meta.xml
<CustomField>
    <fullName>Lieu__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lieu</label>
    <referenceTo>Complexe__c</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Zuora__Subscription__c/fields/Marche__c.field-meta.xml
<CustomField>
    <fullName>Marche__c</fullName>
    <description>BTOB, BTOC</description>
    <label>Marche</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Zuora__Subscription__c/fields/TypeContrat__c.field-meta.xml
<CustomField>
    <fullName>TypeContrat__c</fullName>
    <description>CDI ou CDD</description>
    <label>Type Contrat</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Zuora__Subscription__c/fields/Zuora__Account__c.field-meta.xml
<CustomField>
    <fullName>Zuora__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Zuora__Subscription__c/fields/Zuora__ContractAcceptanceDate__c.field-meta.xml
<CustomField>
    <fullName>Zuora__ContractAcceptanceDate__c</fullName>
    <description>This is the date on which the contract was accepted by the customer, and will trigger charges that have their trigger event set to Upon Customer Acceptance.</description>
    <label>Contract Acceptance Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Zuora__Subscription__c/fields/Zuora__ContractEffectiveDate__c.field-meta.xml
<CustomField>
    <fullName>Zuora__ContractEffectiveDate__c</fullName>
    <description>This is the date on which the contract becomes effective, and will trigger charges that have their trigger event set to Upon Contract Effective.</description>
    <label>Contract Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Zuora__Subscription__c/fields/Zuora__OriginalCreated_Date__c.field-meta.xml
<CustomField>
    <fullName>Zuora__OriginalCreated_Date__c</fullName>
    <description>The date when the subscription was originally created. This value is the same as the CreatedDate value until the subscription is amended.</description>
    <inlineHelpText>The date when the subscription was originally created. This value is the same as the CreatedDate value until the subscription is amended.</inlineHelpText>
    <label>Original Created Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Zuora__Subscription__c/fields/Zuora__Status__c.field-meta.xml
<CustomField>
    <fullName>Zuora__Status__c</fullName>
    <label>Status</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/LCC002_BandeauField.cls
public without sharing class LCC002_BandeauField {
    
    public static final List<String> fieldsForQuerryAccount = new List<String> {
        'Note_Client__c',
        'ScoreAntichurn__c'
    };
    
    public static final List<String> fieldsForQuerrySubscription = new List<String> {
        'lien_porteur_payeur__c',//
        'CodeOffrePrincipale__c',//
        'Zuora__Status__c',//
        'Date_de_debut_de_contrat__c',//
        'Zuora__ContractEffectiveDate__c',//
        'DateFinContrat__c',//
        'CodeFinContrat__c',//
        'Marche__c',//
        'Lieu__c',//
        'TypeContrat__c',
        'Zuora__ContractAcceptanceDate__c'
    };
    
    public static final List<String> fieldsForQuerryCarte = new List<String> {
        'Name',
        'Statut__c'
    };
    
        
    /*public static final List<String> fieldsForQuerryCase = new List<String> {
        'AccountId',
        'Subscription__c',
        'SubscriptionZName__c'
    };*/
    
    
    @AuraEnabled 
    public static List<WRPFieldValues> getFieldValuesInAccout(Id accId){
        system.debug('##MNE getFieldValuesInAccout accId >> '+accId);
     
        String query = 'SELECT Id, '+String.join(fieldsForQuerryAccount, ', ')+ ' FROM Account WHERE Id = \'' + accId+ '\'';
        system.debug('##MNE getFieldValuesInAccout query >> '+query);
        
        list<Account> listAcc = (list<Account>) Database.query(query); 
        
        if(listAcc == null || listAcc.size() == 0){
            system.debug('##MNE getFieldValuesInAccout no data found');
            return null;
        }
        
        Account acc = listAcc.get(0); 
        
        list<WRPFieldValues> rep = new list<WRPFieldValues>();
        
        Map<String, Schema.SObjectType> schemaMap = Schema.getGlobalDescribe();
        Schema.SObjectType accSchema = schemaMap.get('Account');
        Map<String, Schema.SObjectField> fieldMap = accSchema.getDescribe().fields.getMap();

        for(String field : fieldsForQuerryAccount){
            String label = fieldMap.get(field).getDescribe().getLabel();
            String value = String.valueof(acc.get(field));
            rep.add(new WRPFieldValues(label, value));
        }
        system.debug('##MNE getFieldValuesInAccout rep >> '+rep);
        return rep;

    }
    
    @AuraEnabled 
    public static List<WRPFieldValues> getFieldValuesInSubscription(Id accId){
        system.debug('##MNE getFieldValuesInSubscription accId >> '+accId);
     
        String query = 'SELECT Id, LastModifiedDate, '+String.join(fieldsForQuerrySubscription, ', ')+ ' FROM Zuora__Subscription__c WHERE Zuora__Account__c = \'' + accId + '\'  ORDER BY Zuora__OriginalCreated_Date__c DESC NULLS LAST LIMIT 1';
        system.debug('##MNE getFieldValuesInSubscription query >> '+query);
        
        list<Zuora__Subscription__c> listSub = (list<Zuora__Subscription__c>) Database.query(query); 
        
        if(listSub == null || listSub.size() == 0){
            system.debug('##MNE getFieldValuesInSubscription no data found');
            return null;
        }
        
        Zuora__Subscription__c sub = listSub.get(0); 
        
        list<WRPFieldValues> rep = new list<WRPFieldValues>();
        
        Map<String, Schema.SObjectType> schemaMap = Schema.getGlobalDescribe();
        Schema.SObjectType accSchema = schemaMap.get('Zuora__Subscription__c');
        Map<String, Schema.SObjectField> fieldMap = accSchema.getDescribe().fields.getMap();

        for(String field : fieldsForQuerrySubscription){
            Schema.DisplayType typeTMP =  fieldMap.get(field).getDescribe().getType();
            String label = fieldMap.get(field).getDescribe().getLabel();
            String value = String.valueof(sub.get(field));
            if(typeTMP == Schema.DisplayType.DATE){
                Date d = Date.valueOf(sub.get(field));
                system.debug('##MNE getFieldValuesInSubscription date d >> '+d); 
                if(d == null){
                  value = null; 
                }else {
                  value = DateTime.newInstance(d.year(), d.month(), d.day()).format('dd-MM-yyyy');
                }
            }
            rep.add(new WRPFieldValues(label, value));
        }
        system.debug('##MNE getFieldValuesInSubscription rep >> '+rep);
        return rep;

    }
    
    @AuraEnabled 
    public static List<WRPFieldValues> getFieldValuesInCarte(Id accId){
        system.debug('##MNE getFieldValuesInCarte accId >> '+accId);
     
        String query = 'SELECT Id, LastModifiedDate, '+String.join(fieldsForQuerryCarte, ', ')+ ' FROM Carte__c WHERE Abonn__c = \'' + accId + '\' ORDER BY LastModifiedDate DESC NULLS LAST LIMIT 1';
        system.debug('##MNE getFieldValuesInCarte query >> '+query);
        
        list<Carte__c> listCarte = (list<Carte__c>) Database.query(query); 
        
        if(listCarte == null || listCarte.size() == 0){
            system.debug('##MNE getFieldValuesInCarte no data found');
            return null;
        }
        
        Carte__c carte = listCarte.get(0);
        
        list<WRPFieldValues> rep = new list<WRPFieldValues>();
        
        Map<String, Schema.SObjectType> schemaMap = Schema.getGlobalDescribe();
        Schema.SObjectType accSchema = schemaMap.get('Carte__c');
        Map<String, Schema.SObjectField> fieldMap = accSchema.getDescribe().fields.getMap();

        for(String field : fieldsForQuerryCarte){
            String label = fieldMap.get(field).getDescribe().getLabel();
            String value = String.valueof(carte.get(field));
            rep.add(new WRPFieldValues(label, value));
        }
        system.debug('##MNE getFieldValuesInCarte rep >> '+rep);
        return rep;

    }
    
    
    
    
    @AuraEnabled 
    public static list<ListWRPFieldValues> initGetFieldValues(Id recordId){
        system.debug('##MNE initGetFieldValues recordId >> '+recordId);
        
        Id accId = recordId;
     
        if(recordId.getSObjectType() == Schema.Case.SObjectType) {
            String query = 'SELECT Id, AccountId, Account.Tech_IdMonCompte__c FROM Case WHERE Id = \'' + recordId + '\' LIMIT 1';
            system.debug('##MNE initGetFieldValues query Case >> '+query);
            Case c = (Case) Database.query(query)[0]; 
            accId = c.AccountId;
        }
        
        list<ListWRPFieldValues> repFinal = new list<ListWRPFieldValues>();
        
        list<WRPFieldValues> rep = new list<WRPFieldValues>();
           
        List<WRPFieldValues> repAcc = getFieldValuesInAccout(accId);
        List<WRPFieldValues> repSub = getFieldValuesInSubscription(accId);
        List<WRPFieldValues> repCarte = getFieldValuesInCarte(accId);
        
        if(repAcc != null){
            rep.addAll(repAcc);
        }
        if(repSub != null){
            rep.addAll(repSub);
        }
        if(repCarte != null){
            rep.addAll(repCarte);
        }
        
        list<WRPFieldValues> repTMP = new list<WRPFieldValues>();
        for(WRPFieldValues tmp : rep){
            Integer currentIndex = rep.indexOf(tmp);
            if(currentIndex != 0 && Math.mod(currentIndex,10) == 0){
                repFinal.add(new ListWRPFieldValues(repTMP));
                repTMP = new list<WRPFieldValues>();
            }
            repTMP.add(tmp);
        }
        if(repTMP.size() > 0){
            repFinal.add(new ListWRPFieldValues(repTMP));
        }
        system.debug('##MNE repFinal >> '+repFinal);
        return repFinal;
    }
    
    @AuraEnabled 
    public static String getPhotoSFDC (Id recordId){
        try{
            system.debug('##MNE LCC002_BandeauField getPhotoSFDC recordId >> '+recordId);
            
            String RCUId = null;
            String paysTMP = null;
            String pays = null;
         
            if(recordId.getSObjectType() == Schema.Case.SObjectType) {
                String query = 'SELECT Account.IdMonCompte__c, Account.ProduitUGC__c, Account.CodePays__c FROM Case WHERE Id = \'' + recordId + '\' LIMIT 1';
                system.debug('##MNE getPhotoSFDC query Case >> '+query);
                Case c = (Case) Database.query(query)[0]; 
                RCUId = c.Account.IdMonCompte__c;
                paysTMP = c.Account.CodePays__c;
            } else {
                String query = 'SELECT IdMonCompte__c, ProduitUGC__c, CodePays__c FROM Account WHERE Id = \'' + recordId + '\' LIMIT 1';
                system.debug('##MNE getPhotoSFDC query Account >> '+query);
                Account acc = (Account) Database.query(query)[0]; 
                RCUId = acc.IdMonCompte__c;
                paysTMP = acc.CodePays__c;
            }
            system.debug('##MNE LCC002_BandeauField getPhotoSFDC RCUId >> '+RCUId);
            system.debug('##MNE LCC002_BandeauField getPhotoSFDC paysTMP >> '+paysTMP);
            
            if (Util.FRANCE.contains(paysTMP)) {
              pays = '033';
          } else {
              pays = '032';
          }
          
          system.debug('##MNE LCC002_BandeauField getPhotoSFDC pays >> '+pays);
            
            String endpoint = '/Photos/GetPhoto/'+pays+'/'+RCUId;
            //String endpoint = '/Photos/GetPhoto/033/14538';
    
            Http h = new Http();
            HttpRequest req = new HttpRequest();
            req.setEndpoint('callout:HerculeAPI'+endpoint);
            //req.setEndpoint('https://moteur.ugc.fr/moncompte.api.preprod/api/Photos/GetPhoto/033/14538');
            req.setMethod('GET');
            req.setHeader('Content-Type', 'image/jpg');
            req.setCompressed(true);
            req.setTimeout(60000);
            
            HttpResponse res = h.send(req);
            blob image = res.getBodyAsBlob();
            String imageUrl = 'data:'+res.getHeader('Content-Type')+';base64,'+EncodingUtil.base64Encode(image);
            system.debug('##MNE LCC002_BandeauField getPhotoSFDC imageUrl >> '+imageUrl);
            return imageUrl;
        }catch(Exception e){
            return '';
        }
    }
    
    
    
    public without sharing class WRPFieldValues {
        @AuraEnabled public String  label    { get; set; }
        @AuraEnabled public String  value    { get; set; }

        public WRPFieldValues(String label, String value) {
            this.label      = label;
            this.value      = value;
        } 
    }
    
    public without sharing class ListWRPFieldValues {
        @AuraEnabled public list<WRPFieldValues>  listWRPFieldValues    { get; set; }

        public ListWRPFieldValues(list<WRPFieldValues> listWRPFieldValues) {
            this.listWRPFieldValues   = listWRPFieldValues;
        } 
    }

}