force-app/main/default/objects/Account/fields/CodePays__c.field-meta.xml
<CustomField>
    <fullName>CodePays__c</fullName>
    <label>Code Pays</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/MauvaisComportement__c.field-meta.xml
<CustomField>
    <fullName>MauvaisComportement__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Mauvais Comportement</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/ProduitUGC__c.field-meta.xml
<CustomField>
    <fullName>ProduitUGC__c</fullName>
    <defaultValue>&quot;français&quot;</defaultValue>
    <label>Pays de résidence</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>français</fullName>
                <default>true</default>
                <label>français</label>
            </value>
            <value>
                <fullName>belge</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SM_Account.cls
/**
 * Created by mouad on 03/09/2018.
 */

public with sharing class SM_Account {

    public static Account getAccount(Id accId){

        Account account = [
                SELECT Id, Name, MauvaisComportement__c, ProduitUGC__c, CodePays__c
                FROM Account
                WHERE Id = :accId
        ];
        return account; //TODO 5 voir si c une passage en reference ou en valeur ?

    }
    
    

}