force-app/main/default/objects/Account/fields/CodeFinContrat__c.field-meta.xml
<CustomField>
    <fullName>CodeFinContrat__c</fullName>
    <label>Code Fin Contrat</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>L</fullName>
            </value>
            <value>
                <fullName>E</fullName>
            </value>
            <value>
                <fullName>X</fullName>
            </value>
            <value>
                <fullName>M</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/MauvaisComportement__c.field-meta.xml
<CustomField>
    <fullName>MauvaisComportement__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Mauvais Comportement</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/ProduitUGC__c.field-meta.xml
<CustomField>
    <fullName>ProduitUGC__c</fullName>
    <defaultValue>&quot;français&quot;</defaultValue>
    <label>Pays de résidence</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>français</fullName>
                <default>true</default>
                <label>français</label>
            </value>
            <value>
                <fullName>belge</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Date_de_R_siliation__c.field-meta.xml
<CustomField>
    <fullName>Date_de_R_siliation__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <label>Date de résiliation</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case/fields/DateDemande__c.field-meta.xml
<CustomField>
    <fullName>DateDemande__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Date de la demande</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/DateFinContrat__c.field-meta.xml
<CustomField>
    <fullName>DateFinContrat__c</fullName>
    <label>TECH_Date de fin de contrat</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/DemandeRemboursement2__c.field-meta.xml
<CustomField>
    <fullName>DemandeRemboursement2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Demande de remboursement 2</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Demandes d&#39;origine</relationshipLabel>
    <relationshipName>OrigineDemandes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/MontantRembourser__c.field-meta.xml
<CustomField>
    <fullName>MontantRembourser__c</fullName>
    <inlineHelpText>Merci de remplir le montant avec une virgule et non un point</inlineHelpText>
    <label>Montant à rembourser</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Case/fields/Motif_de_R_siliation__c.field-meta.xml
<CustomField>
    <fullName>Motif_de_R_siliation__c</fullName>
    <label>Motif de Résiliation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Code X</fullName>
            </value>
            <value>
                <fullName>M3</fullName>
            </value>
            <value>
                <fullName>M6</fullName>
            </value>
            <value>
                <fullName>M10</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/RemboursementFaire__c.field-meta.xml
<CustomField>
    <fullName>RemboursementFaire__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Quand c est coché une demande de remboursement est automatiquement crée</description>
    <label>Remboursement à faire</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/SousMotif__c.field-meta.xml
<CustomField>
    <fullName>SousMotif__c</fullName>
    <label>Sous-motif</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Motif__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>I- Info</fullName>
            </value>
            <value>
                <fullName>R- Récla</fullName>
            </value>
            <value>
                <fullName>A- Action</fullName>
            </value>
            <value>
                <fullName>Click to Call Info</fullName>
            </value>
            <value>
                <fullName>Click to Call Recla</fullName>
            </value>
            <value>
                <fullName>AD- Action DRC</fullName>
            </value>
            <value>
                <fullName>AS- Action Stand</fullName>
            </value>
            <value>
                <fullName>AH- Action Selfcare</fullName>
            </value>
            <value>
                <fullName>R1- 1er rejet</fullName>
            </value>
            <value>
                <fullName>R2- 2nd rejet</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Subscription__c.field-meta.xml
<CustomField>
    <fullName>Subscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Abonnement</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>$Source.AccountId</field>
            <operation>equals</operation>
            <valueField>Zuora__Subscription__c.Zuora__Account__r.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Zuora__Subscription__c</referenceTo>
    <relationshipLabel>Demandes</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Remboursement.recordType-meta.xml
<RecordType>
    <fullName>Remboursement</fullName>
    <active>true</active>
    <businessProcess>Remboursement</businessProcess>
    <label>Remboursement</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/Souscription.recordType-meta.xml
<RecordType>
    <fullName>Souscription</fullName>
    <active>true</active>
    <businessProcess>Demandes clients</businessProcess>
    <label>Souscription</label>
</RecordType>

force-app/main/default/objects/Zuora__Subscription__c/Zuora__Subscription__c.object-meta.xml
<CustomObject>
    <description>A subscription is a product or service that has recurring charges, such as a monthly flat fee or charges based on usage. Subscriptions can also include one-time charges, such as activation fees.</description>
    <label>Subscription</label>
    <nameField>
        <label>Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Zuora__Subscription__c/fields/CodeFinContrat__c.field-meta.xml
<CustomField>
    <fullName>CodeFinContrat__c</fullName>
    <label>Code Fin Contrat</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>L</fullName>
            </value>
            <value>
                <fullName>E</fullName>
            </value>
            <value>
                <fullName>M</fullName>
            </value>
            <value>
                <fullName>X</fullName>
            </value>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>V</fullName>
            </value>
            <value>
                <fullName>S</fullName>
            </value>
            <value>
                <fullName>R</fullName>
            </value>
            <value>
                <fullName>P</fullName>
            </value>
            <value>
                <fullName>D</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Zuora__Subscription__c/fields/DateFinContrat__c.field-meta.xml
<CustomField>
    <fullName>DateFinContrat__c</fullName>
    <description>custom field for Date Fin Contrat pour les cancel sub a term</description>
    <label>Date Fin Contrat</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Zuora__Subscription__c/fields/Zuora__Status__c.field-meta.xml
<CustomField>
    <fullName>Zuora__Status__c</fullName>
    <label>Status</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Zuora__Subscription__c/fields/Zuora__Zuora_Id__c.field-meta.xml
<CustomField>
    <fullName>Zuora__Zuora_Id__c</fullName>
    <description>The Zuora Id (external primary key) of this Subscription.</description>
    <inlineHelpText>The Zuora Id (external primary key) of this Subscription.</inlineHelpText>
    <label>Zuora Id (Deprecated)</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SM_Resiliation.cls
/**
 * Created by mouad on 03/09/2018.
 */

public with sharing class SM_Resiliation {


    //Constructor
    //public SM_Desabonnement(){}
    public static Case dem = new Case();
    public static Zuora__Subscription__c sub = new Zuora__Subscription__c();
    public static Account acc = new Account();
    
    
    
    public static void resiliation(Id ddeId) {
        if(ddeId == null){
            throw new MyException('No Id Case found for Retractation');
        }
        Case c = [SELECT Id, Motif_de_R_siliation__c, Date_de_R_siliation__c FROM Case WHERE Id =:ddeId].get(0);
        
        if(String.isBlank(c.Motif_de_R_siliation__c)   || c.Date_de_R_siliation__c == null){
            throw new MyException('Veuillez renseigner les champs : "Motif de Résiliation" et "Date de Résiliation"');
        }
        SM_Desabonnement.desabonner(ddeId);
    }


/*    public static void resilier(Id ddeId) {
        //TODO gestion de la reprise sur erreur: savepoint.
        //TODO SFDC: on save: Date fin contrat = date du jour (pour ce sous Fam,motif,sous-motif)

        String policy = 'SpecificDate';
        String codeDesaCarte = null;
        String operation = 'resiliation';
        Id remboursementId = null;
        Case dem2 = new Case(); // objects to update
        Account acc2 = new Account();

        // Initialisation du contexte: dem: (demande)
        dem = SM_Demande.getDemande(ddeId);

        // Initialisation du contexte: sub: (souscription)
        if (dem.Subscription__c == null) {
            throw new MyException('Abonnement absent de la demande: pas dabo, plusieurs ou inactif');
        } else {
            Id subId = dem.Subscription__c;
        }
        sub = SM_Subscription.getSubscription(dem.Subscription__c);

        //Verifications
        preVerification();

        //Call WS Zuora: Cancel subscription
        WSZ.SubCancelOut rCancel = SM_Subscription.cancelSub(Util.zDate(dem.DateFinContrat__c), policy, sub.Zuora__Zuora_Id__c,false,''); //TODO a corriger les input params
        Id newSubId = rCancel.subscriptionId;

        System.debug((String) JSON.serialize(rCancel));

        // Mise a jour de la souscription dans Zuora
        //TODO: Mettre a jour le CodeFinContrat en fonction du SousMotif__c
        Zuora__Subscription__c newSub = new Zuora__Subscription__c();
        //TODO :  voir une fois la matrice etablit si besoin d utiliser le sous motif ou Fam/Mot suffit
        //if (dem.SousMotif__c == 'Mauvais comportement') {
        //    newSub.CodeFinContrat__c='E';}
        newSub.CodeFinContrat__c='M';
        WSZ.SubOut rUpdate =  SM_Subscription.updateSub(newSubId,newSub);

        //Desactivation de la carte
        codeDesaCarte = 'M';
        //SM_Carte.carteDesactivation(codeDesaCarte);
        SM_Carte.desactivation(codeDesaCarte);


        //Creation demande de remboursement
        if (dem.RemboursementFaire__c) {
            //Calculer le montant du remboursement: optionnelle

            Case demandeRemb = new Case(SousMotif__c = 'EF-Automatique', Origin = 'Courrier', AccountId = dem.AccountId,
                    ContactId = dem.ContactId, MontantRembourser__c = 999, //TODO MontantRembourser__c a calculer si possible
                    DateDemande__c = date.today());

            //SM_Remboursement remboursement = new SM_Remboursement();
            remboursementId = SM_Demande.creerRemboursement(demandeRemb);
        }

        //Mise a jour de la demande
        dem2.DemandeRemboursement2__c = remboursementId; // maj lookup remboursement
        dem2.Status = SM_Demande.getStatus('Fermee'); // close ticket
        update dem2;

        //Mise à jour du Client
        acc2.MauvaisComportement__c = true; //TODO voir si on met à jour depuis Trigger sur souscription
        acc2.CodeFinContrat__c = 'M'; //TODO voir si on met à jour depuis Trigger sur souscription
        update acc2;

        //ClientNotification
        clientNotification();
    }


    private static void preVerification() {

        Integer preavis = Util.PREAVIS(acc.ProduitUGC__c);

        //Check demande
        if (dem.Status == SM_Demande.getStatus('Fermee')) {
            throw new MyException('Cette demande a deja ete traite');
        }

        if (dem.SousMotif__c == null) { //TODO peut etre a mettre au niveau parametrage AVOIR
            throw new MyException('Sous-Motif obligatoire');
        }

        //Check Souscription Status
        if (sub.Zuora__Status__c != 'Active') {
            throw new MyException('L abonnement n est pas actif');
        }

        //Check Date Fin contrat
        if (dem.DateFinContrat__c != date.today()) {
            throw new MyException('Date fin contrat doit etre = date du jour');
        }

        if (dem.DateFinContrat__c < dem.DateDemande__c) {
            throw new MyException('Date fin contrat doit etre >= date demande');
        }



    }
*/

    private static void clientNotification(){

    }


    private class MyException extends Exception {
    }

}