force-app/main/default/objects/Account/fields/CodeFinContrat__c.field-meta.xml
<CustomField>
    <fullName>CodeFinContrat__c</fullName>
    <label>Code Fin Contrat</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>L</fullName>
            </value>
            <value>
                <fullName>E</fullName>
            </value>
            <value>
                <fullName>X</fullName>
            </value>
            <value>
                <fullName>M</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/CodePays__c.field-meta.xml
<CustomField>
    <fullName>CodePays__c</fullName>
    <label>Code Pays</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/DateFinContrat__c.field-meta.xml
<CustomField>
    <fullName>DateFinContrat__c</fullName>
    <label>TECH_Date de fin de contrat</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/SousMotif__c.field-meta.xml
<CustomField>
    <fullName>SousMotif__c</fullName>
    <label>Sous-motif</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Motif__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>I- Info</fullName>
            </value>
            <value>
                <fullName>R- Récla</fullName>
            </value>
            <value>
                <fullName>A- Action</fullName>
            </value>
            <value>
                <fullName>Click to Call Info</fullName>
            </value>
            <value>
                <fullName>Click to Call Recla</fullName>
            </value>
            <value>
                <fullName>AD- Action DRC</fullName>
            </value>
            <value>
                <fullName>AS- Action Stand</fullName>
            </value>
            <value>
                <fullName>AH- Action Selfcare</fullName>
            </value>
            <value>
                <fullName>R1- 1er rejet</fullName>
            </value>
            <value>
                <fullName>R2- 2nd rejet</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Remboursement.recordType-meta.xml
<RecordType>
    <fullName>Remboursement</fullName>
    <active>true</active>
    <businessProcess>Remboursement</businessProcess>
    <label>Remboursement</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/Souscription.recordType-meta.xml
<RecordType>
    <fullName>Souscription</fullName>
    <active>true</active>
    <businessProcess>Demandes clients</businessProcess>
    <label>Souscription</label>
</RecordType>

force-app/main/default/objects/Zuora__CustomerAccount__c/Zuora__CustomerAccount__c.object-meta.xml
<CustomObject>
    <description>Zuora Billing Account object.  An account is a customer account that collects all of the critical information about the customer, such as contact information, payment terms, and payment methods. You can use a customer account to track subscriptions, amendments, and transactions, such as invoices and payments.</description>
    <label>Billing Account</label>
    <nameField>
        <label>Billing Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Zuora__Subscription__c/Zuora__Subscription__c.object-meta.xml
<CustomObject>
    <description>A subscription is a product or service that has recurring charges, such as a monthly flat fee or charges based on usage. Subscriptions can also include one-time charges, such as activation fees.</description>
    <label>Subscription</label>
    <nameField>
        <label>Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Zuora__Subscription__c/fields/CancelCaseID__c.field-meta.xml
<CustomField>
    <fullName>CancelCaseID__c</fullName>
    <description>id synchronise de Zuora</description>
    <label>ID Demande de desabo</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Zuora__Subscription__c/fields/CodeFinContrat__c.field-meta.xml
<CustomField>
    <fullName>CodeFinContrat__c</fullName>
    <label>Code Fin Contrat</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>L</fullName>
            </value>
            <value>
                <fullName>E</fullName>
            </value>
            <value>
                <fullName>M</fullName>
            </value>
            <value>
                <fullName>X</fullName>
            </value>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>V</fullName>
            </value>
            <value>
                <fullName>S</fullName>
            </value>
            <value>
                <fullName>R</fullName>
            </value>
            <value>
                <fullName>P</fullName>
            </value>
            <value>
                <fullName>D</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Zuora__Subscription__c/fields/DateFinContrat__c.field-meta.xml
<CustomField>
    <fullName>DateFinContrat__c</fullName>
    <description>custom field for Date Fin Contrat pour les cancel sub a term</description>
    <label>Date Fin Contrat</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Zuora__Subscription__c/fields/Tech_AvecRembouesement__c.field-meta.xml
<CustomField>
    <fullName>Tech_AvecRembouesement__c</fullName>
    <label>Tech_AvecRembouesement</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Zuora__Subscription__c/fields/TypeContrat__c.field-meta.xml
<CustomField>
    <fullName>TypeContrat__c</fullName>
    <description>CDI ou CDD</description>
    <label>Type Contrat</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Zuora__Subscription__c/fields/Zuora__Account__c.field-meta.xml
<CustomField>
    <fullName>Zuora__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Zuora__Subscription__c/fields/Zuora__CancelledDate__c.field-meta.xml
<CustomField>
    <fullName>Zuora__CancelledDate__c</fullName>
    <description>The date of the Amendment object that canceled the subscription.</description>
    <label>Cancelled Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Zuora__Subscription__c/fields/Zuora__CustomerAccount__c.field-meta.xml
<CustomField>
    <fullName>Zuora__CustomerAccount__c</fullName>
    <deleteConstraint>Cascade</deleteConstraint>
    <label>Billing Account</label>
    <referenceTo>Zuora__CustomerAccount__c</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Zuora__Subscription__c/fields/Zuora__OriginalCreated_Date__c.field-meta.xml
<CustomField>
    <fullName>Zuora__OriginalCreated_Date__c</fullName>
    <description>The date when the subscription was originally created. This value is the same as the CreatedDate value until the subscription is amended.</description>
    <inlineHelpText>The date when the subscription was originally created. This value is the same as the CreatedDate value until the subscription is amended.</inlineHelpText>
    <label>Original Created Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Zuora__Subscription__c/fields/Zuora__PreviousSubscriptionId__c.field-meta.xml
<CustomField>
    <fullName>Zuora__PreviousSubscriptionId__c</fullName>
    <description>The subscription ID immediately prior to the current subscription.</description>
    <label>Previous Subscription Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Zuora__Subscription__c/fields/Zuora__Status__c.field-meta.xml
<CustomField>
    <fullName>Zuora__Status__c</fullName>
    <label>Status</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Zuora__Subscription__c/fields/Zuora__SubscriptionEndDate__c.field-meta.xml
<CustomField>
    <fullName>Zuora__SubscriptionEndDate__c</fullName>
    <description>This is when the subscription ends. This is always equal to term end date, unless the subscription has been cancelled. If the subscription has been cancelled, this is set to the cancellation date.</description>
    <label>Subscription End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Zuora__Subscription__c/fields/Zuora__Zuora_Id__c.field-meta.xml
<CustomField>
    <fullName>Zuora__Zuora_Id__c</fullName>
    <description>The Zuora Id (external primary key) of this Subscription.</description>
    <inlineHelpText>The Zuora Id (external primary key) of this Subscription.</inlineHelpText>
    <label>Zuora Id (Deprecated)</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SM005_AnnulationDesabo.cls
/**
 * Created by EasyFront on 20/05/2019.
 */

public without sharing class SM005_AnnulationDesabo {

    public static Case dem = new Case();
    public static Account acc = new Account();
    public static Zuora__Subscription__c sub = new Zuora__Subscription__c();

	public static void AnnulerDesabo(Id ddeId) {    	

        WSZ.GenericEmptyFields subEmpty = new WSZ.GenericEmptyFields();
        subEmpty.fieldsToNull = new List<String>{'DateFinContrat__c','CodeFinContrat__c','CancelCaseID__c'};

        /** Initialisation du contexte: dem: (demande), Account */
        //setDem(ddeId);
        dem = SM_Demande.getDemande(ddeId);
        acc = SM_Account.getAccount(dem.AccountId);

        //recuperer la derniere souscription du compte        
        List<Zuora__Subscription__c> lastSubscription = [Select Id, CancelCaseID__c from Zuora__Subscription__c where Zuora__Account__c =:acc.Id ORDER BY Zuora__OriginalCreated_Date__c DESC NULLS LAST LIMIT 1];
        if (lastSubscription.size() == 0 ){
            throw new RTException(RTExceptionCode.ERREUR_ANNUL_DESABO_AUCUN_CONTRAT_TROUVE);
        }
        sub = SM_Subscription.getSubscription(lastSubscription[0].Id);
        
        verifAnnulerDesabo();
        

        /** Annuler desabonnement */
        String zEntityId = WS001_CallZuora.getZuoraEntityId(acc.CodePays__c);

        if (sub.Zuora__Status__c == 'Active') { //contrat en desabo futur            
            WSZ.SubOut subOut = SM_Subscription.updateSub(sub.Zuora__Zuora_Id__c, subEmpty, zEntityId);  
        }else {   // contract cancelled                 

            //suppression de l'amend cancel
            WSZ.AmendOut rep = SM_Amendment.getAmendment(sub.Zuora__Zuora_Id__c, zEntityId);
            if (rep.typeX != 'Cancellation') {
                throw new MyException('Le dernier Amend n\'est pas un Amend de type Cancellation');
            }
            if (rep.status != 'Completed') {
                throw new MyException('Le dernier Amend n\'est pas Completed');
            }

            list<String> listAmendId = new list<String>();
            listAmendId.add(rep.id);
            list<WSZ.DeleteOut> deleteRep =  SM_Subscription.deleteZObject(listAmendId, 'Amendment', zEntityId);

            WSZ.SubOut subOut = SM_Subscription.updateSub(sub.Zuora__PreviousSubscriptionId__c, subEmpty, zEntityId);            

        }

        SM_Carte.activation(dem.AccountId);

        /** cloture de la demande */        
		dem.Status = 'Fermee';       
        update dem;

// ------
       		
    	
    }
    
    private static void verifAnnulerDesabo() {

        Date dateLatence;

        // if(sub.CancelCaseID__c == null)

        if (dem.Status == SM_Demande.getStatus('Fermee')) {
            throw new MyException('Cette demande a deja ete traite');
        }

        if (dem.SousMotif__c == null) {
            throw new MyException('Sous-Motif obligatoire');
        }
        
        // if(sub.Zuora__PreviousSubscriptionId__c == sub.Zuora__Zuora_Id__c){
        // 	throw new MyException('La souscription est l\'original, elle ne possède aucun desabonnement.');
        // }
        
        if(sub.Zuora__CustomerAccount__r.Zuora__Balance__c != 0){
        	throw new MyException('La balance du compte zuora n\'est pas à 0');
        }
        
        if(sub.Tech_AvecRembouesement__c == 'true'){
        	throw new MyException('Cet amend est suivie par un besoins de remboursement ou de payment');
        }


        if (sub.DateFinContrat__c == null) {
            throw new RTException(RTExceptionCode.ERREUR_ANNUL_DESABO_DATEFINCONTRAT_VIDE);
        }

        //Verifier si on a depasse le mois de latence et le statut du contrat
        Integer periodeLatence = Integer.valueOf(Utils.getUgcGenericParam('Periode de latence',acc.CodePays__c).ParamValue__c);

        // calcul dateLatence
        if (sub.Zuora__Status__c == 'Active' && sub.DateFinContrat__c != null){ //contrat en futur Cancel
            dateLatence = sub.DateFinContrat__c.addMonths(periodeLatence);
        }else if (sub.Zuora__Status__c == 'Cancelled') { // contrat deja cancelled
            dateLatence = sub.Zuora__CancelledDate__c.addMonths(periodeLatence);            
        }
        System.debug('MBEN dateLatence: ' + dateLatence);



        if (sub.Zuora__Status__c == 'Active') {
            if (sub.TypeContrat__c == 'CDI') {
            // continue
            }else if (sub.TypeContrat__c == 'CDD'){                
                // if (sub.DateFinContrat__c.addDays(1) == sub.Zuora__SubscriptionEndDate__c){ //aucun desabo n existe sur ce contrat 
                if (sub.CodeFinContrat__c == null){
                    throw new RTException(RTExceptionCode.ERREUR_ANNUL_DESABO_CONTRAT_DEJA_ACTIF);
                }else {
                // continue
                }
            }                                                     
        }else if (sub.Zuora__Status__c == 'Cancelled') {
            if (sub.TypeContrat__c == 'CDI'){
                if (Date.today() >= dateLatence){
                    throw new RTException(RTExceptionCode.ERREUR_ANNUL_DESABO_PERIODLATENCE_DEPASSE);
                }
            }else if (sub.TypeContrat__c == 'CDD'){
                // en premier annes: NON
                // CDD aterme: NON
                throw new RTException(RTExceptionCode.ERREUR_ANNUL_DESABO_CDD_DEJA_INACTIF);
            }                
        }else {
            throw new RTException(RTExceptionCode.ERREUR_ANNUL_DESABO_STATUT_CONTRAT_NON_VALIDE);
        }        
    }
    
	

    
    private class MyException extends Exception {
    }
    
    
}