force-app/main/default/objects/Account/fields/CodePays__c.field-meta.xml
<CustomField>
    <fullName>CodePays__c</fullName>
    <label>Code Pays</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/ProduitUGC__c.field-meta.xml
<CustomField>
    <fullName>ProduitUGC__c</fullName>
    <defaultValue>&quot;français&quot;</defaultValue>
    <label>Pays de résidence</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>français</fullName>
                <default>true</default>
                <label>français</label>
            </value>
            <value>
                <fullName>belge</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/DateDemande__c.field-meta.xml
<CustomField>
    <fullName>DateDemande__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Date de la demande</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/Mois_de_d_but_remise__c.field-meta.xml
<CustomField>
    <fullName>Mois_de_d_but_remise__c</fullName>
    <label>Mois de début remise</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Janvier</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Février</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Mars</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Avril</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Mai</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>Juin</label>
            </value>
            <value>
                <fullName>7</fullName>
                <label>Juillet</label>
            </value>
            <value>
                <fullName>8</fullName>
                <label>Août</label>
            </value>
            <value>
                <fullName>9</fullName>
                <label>Septembre</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>Octobre</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>Novembre</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>Décembre</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/MontantRemise__c.field-meta.xml
<CustomField>
    <fullName>MontantRemise__c</fullName>
    <label>Montant remise</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case/fields/Motif__c.field-meta.xml
<CustomField>
    <fullName>Motif__c</fullName>
    <label>Motif</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Famille__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>01- Info process abo</fullName>
            </value>
            <value>
                <fullName>02- Erreur prise abo</fullName>
            </value>
            <value>
                <fullName>03- Click and collect</fullName>
            </value>
            <value>
                <fullName>05- B2B</fullName>
            </value>
            <value>
                <fullName>06- VPC</fullName>
            </value>
            <value>
                <fullName>07- Creation Abonnement</fullName>
            </value>
            <value>
                <fullName>01- Reception carte</fullName>
                <label>01- Réception carte</label>
            </value>
            <value>
                <fullName>02- Reedition payante</fullName>
            </value>
            <value>
                <fullName>03- Reedition gratuite</fullName>
            </value>
            <value>
                <fullName>04- Desabonnement</fullName>
            </value>
            <value>
                <fullName>05- Resiliation</fullName>
            </value>
            <value>
                <fullName>06- Migration UI 1/2/3</fullName>
            </value>
            <value>
                <fullName>07- Reabonnement</fullName>
            </value>
            <value>
                <fullName>08- Retention</fullName>
            </value>
            <value>
                <fullName>09- Retour Carte</fullName>
            </value>
            <value>
                <fullName>10- Retractation</fullName>
            </value>
            <value>
                <fullName>11- Avertissement</fullName>
            </value>
            <value>
                <fullName>12- Annulation Migration</fullName>
            </value>
            <value>
                <fullName>13- Annulation Contrat</fullName>
            </value>
            <value>
                <fullName>04- Dematerialise</fullName>
                <label>04- Dématérialisé</label>
            </value>
            <value>
                <fullName>01- Inscription</fullName>
            </value>
            <value>
                <fullName>02- Solde de points</fullName>
            </value>
            <value>
                <fullName>03- Echange de points</fullName>
            </value>
            <value>
                <fullName>04- Fonctionnement Club</fullName>
            </value>
            <value>
                <fullName>01- Offres UGC</fullName>
            </value>
            <value>
                <fullName>02- Formules UGC+</fullName>
            </value>
            <value>
                <fullName>03- Solo</fullName>
            </value>
            <value>
                <fullName>04- Blue</fullName>
            </value>
            <value>
                <fullName>05- VLO</fullName>
            </value>
            <value>
                <fullName>01- Modalites de reservation</fullName>
                <label>01- Modalités de réservation</label>
            </value>
            <value>
                <fullName>06- Gestes commerciaux</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/NombreDeMoisRemise__c.field-meta.xml
<CustomField>
    <fullName>NombreDeMoisRemise__c</fullName>
    <label>Nombre de mois remise</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case/fields/Pallier__c.field-meta.xml
<CustomField>
    <fullName>Pallier__c</fullName>
    <label>Pallier</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>20</fullName>
            </value>
            <value>
                <fullName>25</fullName>
            </value>
            <value>
                <fullName>100</fullName>
                <isActive>false</isActive>
                <label>100</label>
            </value>
            <value>
                <fullName>200</fullName>
                <isActive>false</isActive>
                <label>200</label>
            </value>
            <value>
                <fullName>50</fullName>
                <isActive>false</isActive>
                <label>50</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/SousMotif__c.field-meta.xml
<CustomField>
    <fullName>SousMotif__c</fullName>
    <label>Sous-motif</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Motif__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>I- Info</fullName>
            </value>
            <value>
                <fullName>R- Récla</fullName>
            </value>
            <value>
                <fullName>A- Action</fullName>
            </value>
            <value>
                <fullName>Click to Call Info</fullName>
            </value>
            <value>
                <fullName>Click to Call Recla</fullName>
            </value>
            <value>
                <fullName>AD- Action DRC</fullName>
            </value>
            <value>
                <fullName>AS- Action Stand</fullName>
            </value>
            <value>
                <fullName>AH- Action Selfcare</fullName>
            </value>
            <value>
                <fullName>R1- 1er rejet</fullName>
            </value>
            <value>
                <fullName>R2- 2nd rejet</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Subscription__c.field-meta.xml
<CustomField>
    <fullName>Subscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Abonnement</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>$Source.AccountId</field>
            <operation>equals</operation>
            <valueField>Zuora__Subscription__c.Zuora__Account__r.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Zuora__Subscription__c</referenceTo>
    <relationshipLabel>Demandes</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Souscription.recordType-meta.xml
<RecordType>
    <fullName>Souscription</fullName>
    <active>true</active>
    <businessProcess>Demandes clients</businessProcess>
    <label>Souscription</label>
</RecordType>

force-app/main/default/objects/ProdRatePlan__c/ProdRatePlan__c.object-meta.xml
<CustomObject>
    <description>Objet qui contient les objets zuora, ne fait pas partie de Z360</description>
    <label>Prod Rate Plan</label>
    <nameField>
        <label>Nom Produit</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prod Rate Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ProdRatePlan__c/fields/Reference__c.field-meta.xml
<CustomField>
    <fullName>Reference__c</fullName>
    <externalId>true</externalId>
    <label>Reference</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProdRatePlanCharge__c/ProdRatePlanCharge__c.object-meta.xml
<CustomObject>
    <label>Prod Charges</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prod Charges</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ProdRatePlanCharge__c/fields/ProdRatePlan__c.field-meta.xml
<CustomField>
    <fullName>ProdRatePlan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ProdRatePlan</label>
    <referenceTo>ProdRatePlan__c</referenceTo>
    <relationshipName>RatePlanCharges</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProdRatePlanCharge__c/fields/zid__c.field-meta.xml
<CustomField>
    <fullName>zid__c</fullName>
    <label>zid</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Zuora__Subscription__c/Zuora__Subscription__c.object-meta.xml
<CustomObject>
    <description>A subscription is a product or service that has recurring charges, such as a monthly flat fee or charges based on usage. Subscriptions can also include one-time charges, such as activation fees.</description>
    <label>Subscription</label>
    <nameField>
        <label>Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Zuora__Subscription__c/fields/TypeContrat__c.field-meta.xml
<CustomField>
    <fullName>TypeContrat__c</fullName>
    <description>CDI ou CDD</description>
    <label>Type Contrat</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Zuora__Subscription__c/fields/Zuora__Account__c.field-meta.xml
<CustomField>
    <fullName>Zuora__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Zuora__Subscription__c/fields/Zuora__CurrentTerm__c.field-meta.xml
<CustomField>
    <fullName>Zuora__CurrentTerm__c</fullName>
    <label>Current Term</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Zuora__Subscription__c/fields/Zuora__CurrentTermPeriodType__c.field-meta.xml
<CustomField>
    <fullName>Zuora__CurrentTermPeriodType__c</fullName>
    <description>The period type for the current subscription term.</description>
    <inlineHelpText>The period type of the current subscription term.</inlineHelpText>
    <label>Current Term Period Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Month</fullName>
            </value>
            <value>
                <fullName>Year</fullName>
            </value>
            <value>
                <fullName>Day</fullName>
            </value>
            <value>
                <fullName>Week</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Zuora__Subscription__c/fields/Zuora__External_Id__c.field-meta.xml
<CustomField>
    <fullName>Zuora__External_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>This field holds the Zuora object ID, and is used as external ID for data synchronization between Salesforce and Zuora.</description>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Zuora__Subscription__c/fields/Zuora__Status__c.field-meta.xml
<CustomField>
    <fullName>Zuora__Status__c</fullName>
    <label>Status</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Zuora__Subscription__c/fields/Zuora__SubscriptionStartDate__c.field-meta.xml
<CustomField>
    <fullName>Zuora__SubscriptionStartDate__c</fullName>
    <description>The date when the subscription term starts. This is equal to the term start date if the subscription is on its initial term. Otherwise, it is the original term start date if the subscription has renewed.</description>
    <label>Subscription Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Zuora__Subscription__c/fields/Zuora__TermEndDate__c.field-meta.xml
<CustomField>
    <fullName>Zuora__TermEndDate__c</fullName>
    <label>Term End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Zuora__Subscription__c/fields/Zuora__TermStartDate__c.field-meta.xml
<CustomField>
    <fullName>Zuora__TermStartDate__c</fullName>
    <label>Term Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/LCC006_GesteCommercial.cls
public without sharing class LCC006_GesteCommercial {
	
	public static Case dem;
    public static Zuora__Subscription__c sub;
    public static Account acc;
    
    public static void executeGesteCommercial(Id ddeId) {
    	system.debug('##MNE LCC006_GesteCommercial executeGesteCommercial ddeId >> '+ddeId);
    	dem = SM_Demande.getDemande(ddeId);

        if (dem.Subscription__c == null) {
            throw new MyException('Abonnement absent de la demande: pas dabo, plusieurs ou inactif');
        } 
        
        sub = SM_Subscription.getSubscription(dem.Subscription__c);

        acc = SM_Account.getAccount(dem.AccountId);

        verif();
        
        if (sub.TypeContrat__c == 'CDI') {
        	executeGesteCommercialCDI(ddeId);
        }
        else {
        	executeGesteCommercialCDD(ddeId);
        }
    }
    
    
    public static void executeGesteCommercialCDD(Id ddeId) {
        system.debug('##MNE LCC006_GesteCommercial executeGesteCommercialCDD BEGIN');
        String zuoraSubId = sub.Zuora__External_Id__c;
		String zEntityId = WS001_CallZuora.getZuoraEntityId(acc.CodePays__c);
		String ProductRatePlanId;
		String ProductRatePlanChargeId;
			
		String prefixe = '';
		if(acc.CodePays__c == '033'){
			prefixe = 'FR';
		}else if(acc.CodePays__c == '032'){
			prefixe = 'BE';
		}
		String productRatePlanReference = prefixe + SM001_GesteCommercial.prodRatePlanChargeReferenceGesteCommercialCDD;
		list<ProdRatePlanCharge__c> listProdRatePlanCharge = new list<ProdRatePlanCharge__c>([SELECT Reference__c, zid__c, ProdRatePlan__r.zid__c FROM ProdRatePlanCharge__c WHERE Reference__c = :productRatePlanReference]);
		if(listProdRatePlanCharge.size() == 0){
			system.debug('##MNE LCC006_GesteCommercial executeGesteCommercial Pas de Product Rate Plan Charge trouvée pour le geste commercial');
            throw new MyException('Pas de Product Rate Plan Charge trouvée pour le geste commercial.');
		}

        
        ProdRatePlanCharge__c prodRatePlanCharge = listProdRatePlanCharge.get(0);
		ProductRatePlanId = prodRatePlanCharge.ProdRatePlan__r.zid__c;
		ProductRatePlanChargeId = prodRatePlanCharge.zid__c;
		list<SM001_GesteCommercial.Amendment> listAmendment = new list<SM001_GesteCommercial.Amendment>();
        
        //Redmine MNE 18/09/2019 ticket n°699
        //Date dateDebutRemise = sub.Zuora__SubscriptionStartDate__c;
        Date dateDebutRemise = sub.Zuora__TermEndDate__c;
        system.debug('##MNE LCC006_GesteCommercial executeGesteCommercialCDD dateDebutRemise >> '+dateDebutRemise);
        
        //add product mois gratuit
        SM001_GesteCommercial.Amendment addPr = new SM001_GesteCommercial.Amendment(zuoraSubId, ProductRatePlanId, ProductRatePlanChargeId, dateDebutRemise);
        addPr.Name = 'Geste Commercial CDD mois offert';
        addPr.Description = 'Geste Commercial CDD mois offert';
        listAmendment.add(addPr);
        
        //Renew
        Integer nbDeMoisRemise = Integer.valueOf(dem.NombreDeMoisRemise__c);
        Date contractEffectiveDate = Date.today();
        Integer currentTerm = Integer.valueOf(sub.Zuora__CurrentTerm__c.split(' ').get(0));
        String currentTermPeriodType = sub.Zuora__CurrentTermPeriodType__c;
        Integer newCurrentTerm;
        
        if(CurrentTermPeriodType == 'Day'){
        	Date startDate  = Date.valueOf(sub.Zuora__TermStartDate__c);
			Date endDate    = startDate.addDays(currentTerm);
			Date newEndDate = endDate.addMonths(nbDeMoisRemise);
			newCurrentTerm = startDate.daysBetween(newEndDate);
        }
        else {
        	newCurrentTerm = currentTerm + nbDeMoisRemise;
        }
        SM001_GesteCommercial.Amendment renew = new SM001_GesteCommercial.Amendment(zuoraSubId, contractEffectiveDate, newCurrentTerm);
        listAmendment.add(0,renew);
        
        SM001_GesteCommercial.Body res = new SM001_GesteCommercial.Body();
    	res.requests.get(0).Amendments = listAmendment;
    	String inBody = JSON.serialize(res);
        inBody = inBody.replace('null','""');
        System.debug('##MNE LCC006_GesteCommercial executeGesteCommercialCDD inBody >> '+inBody);
        
        String repWS = SM001_GesteCommercial.sendAmendRequest(inBody, zEntityId);
        System.debug('##MNE LCC006_GesteCommercial executeGesteCommercialCDD repWS >> '+repWS);
        
        SM001_GesteCommercial.Resultat resApex =   (SM001_GesteCommercial.Resultat)System.JSON.deserialize(repWS, SM001_GesteCommercial.Resultat.class);
        System.debug('##MNE LCC006_GesteCommercial executeGesteCommercialCDD resApex >> '+resApex);
        
        Boolean success = true;
        String messageError = '';
        if(resApex != null && resApex.results != null  && resApex.results.size() > 0){
            for(SM001_GesteCommercial.Result r : resApex.results){
                if(!r.Success){
                    if(r.Errors != null && r.Errors.size() > 0){
                        throw new MyException(r.Errors.get(0).Message);
                    }
                }
            }
        }
        
        

        /*for(SM001_GesteCommercial.Amendment amend : listAmendment){
        	SM001_GesteCommercial.Body res = new SM001_GesteCommercial.Body();
        	res.requests.get(0).Amendments.add(amend);
        	String inBody = JSON.serialize(res);
	        inBody = inBody.replace('null','""');
	        System.debug('##MNE LCC006_GesteCommercial executeGesteCommercialCDD inBody >> '+inBody);
	        
	        String repWS = SM001_GesteCommercial.sendAmendRequest(inBody, zEntityId);
	        System.debug('##MNE LCC006_GesteCommercial executeGesteCommercialCDD repWS >> '+repWS);
	        
	        SM001_GesteCommercial.Resultat resApex =   (SM001_GesteCommercial.Resultat)System.JSON.deserialize(repWS, SM001_GesteCommercial.Resultat.class);
	        System.debug('##MNE LCC006_GesteCommercial executeGesteCommercialCDD resApex >> '+resApex);
	        
	        Boolean success = true;
	        String messageError = '';
	        if(resApex != null && resApex.results != null  && resApex.results.size() > 0){
	            for(SM001_GesteCommercial.Result r : resApex.results){
	                if(!r.Success){
	                    if(r.Errors != null && r.Errors.size() > 0){
	                        throw new MyException(r.Errors.get(0).Message);
	                    }
	                }
	            }
	        }
        }*/
    }
	
	
	public static void executeGesteCommercialCDI(Id ddeId) {
		system.debug('##MNE LCC006_GesteCommercial executeGesteCommercialCDI BEGIN');
        
        String zuoraSubId = sub.Zuora__External_Id__c;
		String zEntityId = WS001_CallZuora.getZuoraEntityId(acc.CodePays__c);
		String ProductRatePlanId;
		String ProductRatePlanChargeId;
			
		//MNE TODO => 
		//modifier le call zuora pour prendre en compte le pallier (c a d soit montant sur plusieur mois sois pallier sur moi apres la date de la demande)
		//dinamiser ZUora entity Id, aujourd'hui que sur France (en dure)
		String prefixe = '';
		if(acc.CodePays__c == '033'){
			prefixe = 'FR';
		}else if(acc.CodePays__c == '032'){
			prefixe = 'BE';
		}
		String productRatePlanReference = prefixe + SM001_GesteCommercial.prodRatePlanChargeReferenceGesteCommercialCDI;
		list<ProdRatePlanCharge__c> listProdRatePlanCharge = new list<ProdRatePlanCharge__c>([SELECT Reference__c, zid__c, ProdRatePlan__r.zid__c FROM ProdRatePlanCharge__c WHERE Reference__c = :productRatePlanReference]);
		if(listProdRatePlanCharge.size() == 0){
			system.debug('##MNE LCC006_GesteCommercial executeGesteCommercialCDI Pas de Product Rate Plan Charge trouvée pour le geste commercial');
            throw new MyException('Pas de Product Rate Plan Charge trouvée pour le geste commercial.');
		}
		
		ProdRatePlanCharge__c prodRatePlanCharge = listProdRatePlanCharge.get(0);
		ProductRatePlanId = prodRatePlanCharge.ProdRatePlan__r.zid__c;
		ProductRatePlanChargeId = prodRatePlanCharge.zid__c;
		
		String moisDebutRemise = dem.Mois_de_d_but_remise__c;
        Double montantRemise = dem.MontantRemise__c;
        Integer nbDeMoisRemise = Integer.valueOf(dem.NombreDeMoisRemise__c);
        String pallier = dem.Pallier__c;
		
		String inBody = SM001_GesteCommercial.getBodyGC (zuoraSubId, ProductRatePlanId, ProductRatePlanChargeId, montantRemise, nbDeMoisRemise, dem.DateDemande__c, moisDebutRemise);
		
        //String repWS = SM001_GesteCommercial.sendRequest(zuoraSubId, ProductRatePlanId, ProductRatePlanChargeId, montantRemise, nbDeMoisRemise, dateDemande, moisDebutRemise);
        String repWS = SM001_GesteCommercial.sendAmendRequest(inBody, zEntityId);
        
        
        SM001_GesteCommercial.Resultat resApex =   (SM001_GesteCommercial.Resultat)System.JSON.deserialize(repWS, SM001_GesteCommercial.Resultat.class);
        System.debug('##MNE LCC006_GesteCommercial executeGesteCommercialCDI resJsonOriginal >> '+repWS);
        System.debug('##MNE LCC006_GesteCommercial executeGesteCommercialCDI resApex >> '+resApex);
        
        Boolean success = true;
        String messageError = '';
        if(resApex != null && resApex.results != null  && resApex.results.size() > 0){
        	for(SM001_GesteCommercial.Result r : resApex.results){
        		if(!r.Success){
        			if(r.Errors != null && r.Errors.size() > 0){
        				throw new MyException(r.Errors.get(0).Message);
        			}
        		}
        	}
        }
	}
	
	private static void verif() {

        if (dem.Status == SM_Demande.getStatus('Fermee')) {
            throw new MyException('Cette demande a deja ete traite'); 
        }

        if (dem.SousMotif__c == null) {
            throw new MyException('Sous-Motif obligatoire');
        }

        //Check Souscription Status
        if (sub.Zuora__Status__c != 'Active') {
            throw new MyException('L abonnement n est pas actif');
        }
        
        String moisDebutRemise = dem.Mois_de_d_but_remise__c;
        Double montantRemise = dem.MontantRemise__c;
        Integer nbDeMoisRemise = Integer.valueOf(dem.NombreDeMoisRemise__c);
        String pallier = dem.Pallier__c;
        
        if (sub.TypeContrat__c == 'CDI') {
	        if((String.isBlank(moisDebutRemise) && montantRemise == null && nbDeMoisRemise == null && String.isBlank(pallier))
	        || (String.isNotBlank(moisDebutRemise) && montantRemise != null && nbDeMoisRemise != null && String.isNotBlank(pallier))
	        || ((String.isBlank(moisDebutRemise) || montantRemise == null || nbDeMoisRemise == null) && String.isBlank(pallier))
	        || ((String.isNotBlank(moisDebutRemise) || montantRemise != null || nbDeMoisRemise != null) && String.isNotBlank(pallier)) ){
	            throw new MyException('Merci de renseigner les champ : \n -Montant remise\n -Mois de début remise\n -Nombre de mois remise\n\nOU\n\n-Pallier');
	        }
        }
        else {
        	if(nbDeMoisRemise == null){
        		throw new MyException('Merci de renseigner le champ : Nombre de mois remise');
        	}
        }
    }
    
    
    
    
    
	
	
	
	
	
	
	
	
	
	
	
	
	
    
    @AuraEnabled 
    public static WRPInt executeGesteCommercial(Id caseId, Id accId, String moisDebutRemise, Double montantRemise, Integer nbDeMoisRemise, String pallier, String dateDemandeTMP){
        Date dateDemande = Date.valueOf(dateDemandeTMP);
        system.debug('##MNE LCC006_GesteCommercial executeGesteCommercial caseId >> '+caseId);
        system.debug('##MNE LCC006_GesteCommercial executeGesteCommercial accId >> '+accId);
        system.debug('##MNE LCC006_GesteCommercial executeGesteCommercial moisDebutRemise >> '+moisDebutRemise);
        system.debug('##MNE LCC006_GesteCommercial executeGesteCommercial montantRemise >> '+montantRemise);
        system.debug('##MNE LCC006_GesteCommercial executeGesteCommercial nbDeMoisRemise >> '+nbDeMoisRemise);
        system.debug('##MNE LCC006_GesteCommercial executeGesteCommercial pallier >> '+pallier);
        system.debug('##MNE LCC006_GesteCommercial executeGesteCommercial dateDemande >> '+dateDemande);
        
        WRPInt rep = new WRPInt();  
        
             
        
        if((String.isBlank(moisDebutRemise) && montantRemise == null && nbDeMoisRemise == null && String.isBlank(pallier))
        || (String.isNotBlank(moisDebutRemise) && montantRemise != null && nbDeMoisRemise != null && String.isNotBlank(pallier))
        || ((String.isBlank(moisDebutRemise) || montantRemise == null || nbDeMoisRemise == null) && String.isBlank(pallier))
        || ((String.isNotBlank(moisDebutRemise) || montantRemise != null || nbDeMoisRemise != null) && String.isNotBlank(pallier)) ){
            rep.showMessage = true;
            rep.messageToDisplay = 'Merci de renseigner les champ : \n -Montant remise\n -Mois de début remise\n -Nombre de mois remise\n\nOU\n\n-Pallier';
            return rep;
        }
        
        list<Zuora__Subscription__c> listSub = new list<Zuora__Subscription__c>([SELECT Zuora__External_Id__c, Zuora__Account__r.ProduitUGC__c, Zuora__Account__r.CodePays__c, TypeContrat__c FROM Zuora__Subscription__c WHERE Zuora__Account__c =:accId AND Zuora__Status__c = 'Active' ORDER BY CreatedDate DESC NULLS FIRST LIMIT 1]);
		
		if(listSub.size() == 0){
			rep.showMessage = true;
            rep.messageToDisplay = 'Pas de souscription trouvée.';
            return rep;
		}
		
		String zuoraSubId = listSub.get(0).Zuora__External_Id__c;
		String zEntityId = WS001_CallZuora.getZuoraEntityId(listSub.get(0).Zuora__Account__r.CodePays__c);
		String ProductRatePlanId;
		String ProductRatePlanChargeId;
		
        try{
			
			//MNE TODO => 
			//modifier le call zuora pour prendre en compte le pallier (c a d soit montant sur plusieur mois sois pallier sur moi apres la date de la demande)
			//dinamiser ZUora entity Id, aujourd'hui que sur France (en dure)
			String prefixe = '';
			if(listSub.get(0).Zuora__Account__r.CodePays__c == '033'){
				prefixe = 'FR';
			}else if(listSub.get(0).Zuora__Account__r.CodePays__c == '032'){
				prefixe = 'BE';
			}
			String productRatePlanReference = prefixe + SM001_GesteCommercial.prodRatePlanChargeReferenceGesteCommercialCDI;
			list<ProdRatePlanCharge__c> listProdRatePlanCharge = new list<ProdRatePlanCharge__c>([SELECT Reference__c, zid__c, ProdRatePlan__r.zid__c FROM ProdRatePlanCharge__c WHERE Reference__c = :productRatePlanReference]);
			if(listProdRatePlanCharge.size() == 0){
				system.debug('##MNE LCC006_GesteCommercial executeGesteCommercial Pas de Product Rate Plan Charge trouvée pour le geste commercial');
				rep.showMessage = true;
	            rep.messageToDisplay = 'Pas de Product Rate Plan Charge trouvée pour le geste commercial.';
	            return rep;
			}
			
			ProdRatePlanCharge__c prodRatePlanCharge = listProdRatePlanCharge.get(0);
			ProductRatePlanId = prodRatePlanCharge.ProdRatePlan__r.zid__c;
			ProductRatePlanChargeId = prodRatePlanCharge.zid__c;
			
			String inBody = SM001_GesteCommercial.getBodyGC (zuoraSubId, ProductRatePlanId, ProductRatePlanChargeId, montantRemise, nbDeMoisRemise, dateDemande, moisDebutRemise);
			
            //String repWS = SM001_GesteCommercial.sendRequest(zuoraSubId, ProductRatePlanId, ProductRatePlanChargeId, montantRemise, nbDeMoisRemise, dateDemande, moisDebutRemise);
            String repWS = SM001_GesteCommercial.sendAmendRequest(inBody, zEntityId);
            
            
            SM001_GesteCommercial.Resultat resApex =   (SM001_GesteCommercial.Resultat)System.JSON.deserialize(repWS, SM001_GesteCommercial.Resultat.class);
	        System.debug('##MNE LCC006_GesteCommercial executeGesteCommercial resJsonOriginal >> '+repWS);
	        System.debug('##MNE LCC006_GesteCommercial executeGesteCommercial resApex >> '+resApex);
	        
	        Boolean success = true;
	        String messageError = '';
	        if(resApex != null && resApex.results != null  && resApex.results.size() > 0){
	        	for(SM001_GesteCommercial.Result r : resApex.results){
	        		if(!r.Success){
	        			rep.showMessage = true;
	        			if(r.Errors != null && r.Errors.size() > 0){
	        				rep.messageToDisplay = r.Errors.get(0).Message;
	        				break;
	        			}
	        		}
	        	}
	        }

        } catch(Exception e){
            rep.showMessage = true;
            rep.messageToDisplay = e.getMessage();
            system.debug('##MNE inser KO');
            return rep;
        }
        system.debug('##MNE LCC006_GesteCommercial executeGesteCommercial rep >> '+rep);
        return rep;
        
    }
    
    @AuraEnabled
    public static WRPInt ongletExecuteGesteCommercial(Case caseRecord, Id caseId) {
        System.debug('##MNE LCC006_GesteCommercial ongletExecuteGesteCommercial caseRecord >> '+caseRecord);
        System.debug('##MNE LCC006_GesteCommercial ongletExecuteGesteCommercial caseId >> '+caseId);
        
        Case c = [SELECT Id, AccountId, DateDemande__c FROM Case WHERE Id = :caseId LIMIT 1];
        Id accId = c.AccountId;
        
        String moisDebutRemise = caseRecord.Mois_de_d_but_remise__c;
        Double montantRemise = caseRecord.MontantRemise__c;
        Integer nbDeMoisRemise = Integer.valueOf(caseRecord.NombreDeMoisRemise__c);
        String pallier = caseRecord.Pallier__c; 
        String dateDemandeTMP = String.valueOf(c.DateDemande__c);
        
        WRPInt rep = executeGesteCommercial(caseId, accId, moisDebutRemise, montantRemise, nbDeMoisRemise, pallier, dateDemandeTMP);
        if(!rep.showMessage){
            //creataion du nouveau case
            Id gesteCoRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Gestes commerciaux').getRecordTypeId();
            Case cTMP = new Case();
            cTMP.Mois_de_d_but_remise__c = moisDebutRemise;
            cTMP.MontantRemise__c = montantRemise;
            cTMP.NombreDeMoisRemise__c = nbDeMoisRemise;
            cTMP.Pallier__c = pallier;
            cTMP.AccountId = accId;
            cTMP.RecordTypeId = gesteCoRecordTypeId;
            cTMP.Famille__c = '7- Finance';
 			cTMP.Motif__c = '06- Gestes commerciaux';
            insert cTMP;     
            rep.caseIdToRedirect = cTMP.Id;
            rep.accountIdToRedirect = accId;
        }
        return rep;
    }
    
    public without sharing class WRPInt {
        @AuraEnabled public Boolean showMessage                         { get; set; }
        @AuraEnabled public String  messageToDisplay                    { get; set; }
        @AuraEnabled public Id  caseIdToRedirect                    	{ get; set; }
        @AuraEnabled public Id  accountIdToRedirect                    	{ get; set; }
        
        public WRPInt() {
            this.showMessage            = false;
            this.messageToDisplay       = '';
            this.caseIdToRedirect       = null;
            this.accountIdToRedirect    = null;
        }
    }
    
    private class MyException extends Exception {
    }

}