force-app/main/default/objects/Account/fields/CodeFinContrat__c.field-meta.xml
<CustomField>
    <fullName>CodeFinContrat__c</fullName>
    <label>Code Fin Contrat</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>L</fullName>
            </value>
            <value>
                <fullName>E</fullName>
            </value>
            <value>
                <fullName>X</fullName>
            </value>
            <value>
                <fullName>M</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Famille__c.field-meta.xml
<CustomField>
    <fullName>Famille__c</fullName>
    <label>Famille</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0- Souscription</fullName>
            </value>
            <value>
                <fullName>1- Vie de l&#39;abonnement</fullName>
            </value>
            <value>
                <fullName>2- Club UGC / fidelite</fullName>
            </value>
            <value>
                <fullName>3- Autres Produits</fullName>
            </value>
            <value>
                <fullName>4- Reservation</fullName>
                <label>4- Réservation</label>
            </value>
            <value>
                <fullName>5- Compte client</fullName>
            </value>
            <value>
                <fullName>6- Prospection</fullName>
            </value>
            <value>
                <fullName>7- Finance</fullName>
            </value>
            <value>
                <fullName>8- Cinema</fullName>
                <label>8- Cinéma</label>
            </value>
            <value>
                <fullName>9- Divers</fullName>
            </value>
            <value>
                <fullName>0- Commentaires</fullName>
                <isActive>false</isActive>
                <label>0- Commentaires</label>
            </value>
            <value>
                <fullName>1- Demandes d info UI</fullName>
                <isActive>false</isActive>
                <label>1- Demandes d info UI</label>
            </value>
            <value>
                <fullName>1- Demandes d&#39;info UI</fullName>
                <isActive>false</isActive>
                <label>1- Demandes d&#39;info UI</label>
            </value>
            <value>
                <fullName>2- Demande d infos generales</fullName>
                <isActive>false</isActive>
                <label>2- Demande d infos generales</label>
            </value>
            <value>
                <fullName>2- Demande d&#39;infos générales</fullName>
                <isActive>false</isActive>
                <label>2- Demande d&#39;infos générales</label>
            </value>
            <value>
                <fullName>3- Autres demandes d&#39;informations</fullName>
                <isActive>false</isActive>
                <label>3- Autres demandes d&#39;informations</label>
            </value>
            <value>
                <fullName>4- Abonnement Carte UGC</fullName>
                <isActive>false</isActive>
                <label>4- Abonnement Carte UGC</label>
            </value>
            <value>
                <fullName>5- Abonnement en attente</fullName>
                <isActive>false</isActive>
                <label>5- Abonnement en attente</label>
            </value>
            <value>
                <fullName>6- GestionCompteUI</fullName>
                <isActive>false</isActive>
                <label>6- GestionCompteUI</label>
            </value>
            <value>
                <fullName>7- Réclamations UI</fullName>
                <isActive>false</isActive>
                <label>7- Réclamations UI</label>
            </value>
            <value>
                <fullName>8- Autres types de reclamations</fullName>
                <isActive>false</isActive>
                <label>8- Autres types de reclamations</label>
            </value>
            <value>
                <fullName>8- Autres types de réclamations</fullName>
                <isActive>false</isActive>
                <label>8- Autres types de réclamations</label>
            </value>
            <value>
                <fullName>9- Supports Digitaux</fullName>
                <isActive>false</isActive>
                <label>9- Supports Digitaux</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Motif__c.field-meta.xml
<CustomField>
    <fullName>Motif__c</fullName>
    <label>Motif</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Famille__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>01- Info process abo</fullName>
            </value>
            <value>
                <fullName>02- Erreur prise abo</fullName>
            </value>
            <value>
                <fullName>03- Click and collect</fullName>
            </value>
            <value>
                <fullName>05- B2B</fullName>
            </value>
            <value>
                <fullName>06- VPC</fullName>
            </value>
            <value>
                <fullName>07- Creation Abonnement</fullName>
            </value>
            <value>
                <fullName>01- Reception carte</fullName>
                <label>01- Réception carte</label>
            </value>
            <value>
                <fullName>02- Reedition payante</fullName>
            </value>
            <value>
                <fullName>03- Reedition gratuite</fullName>
            </value>
            <value>
                <fullName>04- Desabonnement</fullName>
            </value>
            <value>
                <fullName>05- Resiliation</fullName>
            </value>
            <value>
                <fullName>06- Migration UI 1/2/3</fullName>
            </value>
            <value>
                <fullName>07- Reabonnement</fullName>
            </value>
            <value>
                <fullName>08- Retention</fullName>
            </value>
            <value>
                <fullName>09- Retour Carte</fullName>
            </value>
            <value>
                <fullName>10- Retractation</fullName>
            </value>
            <value>
                <fullName>11- Avertissement</fullName>
            </value>
            <value>
                <fullName>12- Annulation Migration</fullName>
            </value>
            <value>
                <fullName>13- Annulation Contrat</fullName>
            </value>
            <value>
                <fullName>04- Dematerialise</fullName>
                <label>04- Dématérialisé</label>
            </value>
            <value>
                <fullName>01- Inscription</fullName>
            </value>
            <value>
                <fullName>02- Solde de points</fullName>
            </value>
            <value>
                <fullName>03- Echange de points</fullName>
            </value>
            <value>
                <fullName>04- Fonctionnement Club</fullName>
            </value>
            <value>
                <fullName>01- Offres UGC</fullName>
            </value>
            <value>
                <fullName>02- Formules UGC+</fullName>
            </value>
            <value>
                <fullName>03- Solo</fullName>
            </value>
            <value>
                <fullName>04- Blue</fullName>
            </value>
            <value>
                <fullName>05- VLO</fullName>
            </value>
            <value>
                <fullName>01- Modalites de reservation</fullName>
                <label>01- Modalités de réservation</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/SousMotif__c.field-meta.xml
<CustomField>
    <fullName>SousMotif__c</fullName>
    <label>Sous-motif</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Motif__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>I- Info</fullName>
            </value>
            <value>
                <fullName>R- Récla</fullName>
            </value>
            <value>
                <fullName>A- Action</fullName>
            </value>
            <value>
                <fullName>Click to Call Info</fullName>
            </value>
            <value>
                <fullName>Click to Call Recla</fullName>
            </value>
            <value>
                <fullName>AD- Action DRC</fullName>
            </value>
            <value>
                <fullName>AS- Action Stand</fullName>
            </value>
            <value>
                <fullName>AH- Action Selfcare</fullName>
            </value>
            <value>
                <fullName>R1- 1er rejet</fullName>
            </value>
            <value>
                <fullName>R2- 2nd rejet</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Subscription__c.field-meta.xml
<CustomField>
    <fullName>Subscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Abonnement</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>$Source.AccountId</field>
            <operation>equals</operation>
            <valueField>Zuora__Subscription__c.Zuora__Account__r.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Zuora__Subscription__c</referenceTo>
    <relationshipLabel>Demandes</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Zuora__Subscription__c/Zuora__Subscription__c.object-meta.xml
<CustomObject>
    <description>A subscription is a product or service that has recurring charges, such as a monthly flat fee or charges based on usage. Subscriptions can also include one-time charges, such as activation fees.</description>
    <label>Subscription</label>
    <nameField>
        <label>Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Zuora__Subscription__c/fields/CodeFinContrat__c.field-meta.xml
<CustomField>
    <fullName>CodeFinContrat__c</fullName>
    <label>Code Fin Contrat</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>L</fullName>
            </value>
            <value>
                <fullName>E</fullName>
            </value>
            <value>
                <fullName>M</fullName>
            </value>
            <value>
                <fullName>X</fullName>
            </value>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>V</fullName>
            </value>
            <value>
                <fullName>S</fullName>
            </value>
            <value>
                <fullName>R</fullName>
            </value>
            <value>
                <fullName>P</fullName>
            </value>
            <value>
                <fullName>D</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Zuora__Subscription__c/fields/Date_de_fin_de_contrat__c.field-meta.xml
<CustomField>
    <fullName>Date_de_fin_de_contrat__c</fullName>
    <formula>IF((TypeContrat__c = &#39;CDD&#39; &amp;&amp; (ISPICKVAL(CodeFinContrat__c,&#39;&#39;))),Zuora__TermEndDate__c-1,IF((TypeContrat__c =&#39;CDI&#39;&amp;&amp; (ISPICKVAL(CodeFinContrat__c,&#39;&#39;))),NULL,IF(ISPICKVAL(CodeFinContrat__c, &#39;L&#39;),Zuora__SubscriptionEndDate__c-1,IF(ISPICKVAL(CodeFinContrat__c, &#39;E&#39;),Zuora__SubscriptionEndDate__c- 1, IF(ISPICKVAL(CodeFinContrat__c, &#39;A&#39;),Zuora__SubscriptionEndDate__c-1, IF(ISPICKVAL(CodeFinContrat__c, &#39;M&#39;),Zuora__SubscriptionEndDate__c-1  ,IF(ISPICKVAL(CodeFinContrat__c, &#39;X&#39;),Zuora__SubscriptionEndDate__c-1  , NULL)))))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Date de fin de contrat</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Zuora__Subscription__c/fields/TypeContrat__c.field-meta.xml
<CustomField>
    <fullName>TypeContrat__c</fullName>
    <description>CDI ou CDD</description>
    <label>Type Contrat</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Zuora__Subscription__c/fields/Zuora__Account__c.field-meta.xml
<CustomField>
    <fullName>Zuora__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Batch_SubscriptionRenewEmail.cls
global class Batch_SubscriptionRenewEmail implements Database.Batchable<sObject>, Database.Stateful, Database.AllowsCallouts{
	

    global Database.QueryLocator start(Database.BatchableContext BC) {
        
        System.debug('##ECH Start of SubscriptionRenewEmail batch' );
        
		Integer renewDays = Integer.valueOf(Utils.getUgcGenericParam('Subscription Renewal Days','FR').ParamValue__c);
        
        Date renewDate = Date.today().addDays(renewDays);

        System.debug('##ECH Batch_SubscriptionRenewEmail renewDate:'+renewDate );

        return Database.getQueryLocator(
            'SELECT ID,Name, Zuora__Account__c,Zuora__Account__r.PersonContactId ' +
            'FROM Zuora__Subscription__c ' + 
            'Where Date_de_fin_de_contrat__c = :renewDate ' +
            'AND CodeFinContrat__c = null ' +
            'AND TypeContrat__c = \'CDD\' ');
        
        
    }
    
    global void execute(Database.BatchableContext BC, List<Zuora__Subscription__c> scope) {
        System.debug('##ECH Batch_SubscriptionRenewEmail scope size: '+ scope.size());
        Id remboursementRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Réabonnement').getRecordTypeId();
        List<Case> CaseToAdd = new List<Case>();
        
        for (Zuora__Subscription__c sub: scope){
            try {
            	System.debug('##ECH Batch_SubscriptionRenewEmail New Case: '+ sub.Name);
                Case c = new Case();
                c.RecordTypeId = remboursementRecordTypeId;
                c.AccountId = sub.Zuora__Account__c;
                c.ContactId = sub.Zuora__Account__r.PersonContactId;
                c.Subscription__c = sub.Id;
                c.Famille__c = '1- Vie de l\'abonnement';
        		c.Motif__c = '07- Reabonnement';
                c.SousMotif__c = 'C - Communication';
            	c.Origin = 'Interne';             
                CaseToAdd.add(c);
            }
            catch(Exception e) {      
        		System.debug('##ECH Batch_SubscriptionRenewEmail Exception: '+ String.valueOf(e));
        	}
			finally{
                                
            } 

        }
        
        if(CaseToAdd.size()>0)
            insert CaseToAdd;
        
    }
    
    global void finish(Database.BatchableContext BC) {
        System.debug('##ECH End of SubscriptionRenewEmail batch' );
    }
}