force-app/main/default/objects/Account/fields/CodePays__c.field-meta.xml
<CustomField>
    <fullName>CodePays__c</fullName>
    <label>Code Pays</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/MauvaisComportement__c.field-meta.xml
<CustomField>
    <fullName>MauvaisComportement__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Mauvais Comportement</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/ProduitUGC__c.field-meta.xml
<CustomField>
    <fullName>ProduitUGC__c</fullName>
    <defaultValue>&quot;français&quot;</defaultValue>
    <label>Pays de résidence</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>français</fullName>
                <default>true</default>
                <label>français</label>
            </value>
            <value>
                <fullName>belge</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Coupon__c/Coupon__c.object-meta.xml
<CustomObject>
    <label>Coupon</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Coupons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Offre__c/Offre__c.object-meta.xml
<CustomObject>
    <label>Offre</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Offres</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Offre__c/fields/Coupon__c.field-meta.xml
<CustomField>
    <fullName>Coupon__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>test git</description>
    <label>Coupon</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Coupon__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>BtoC generique, BtoC multiples, BtoB, BtoC Nominatif Client, BtoC Nominatif Agent</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Coupon__c</referenceTo>
    <relationshipLabel>Offres</relationshipLabel>
    <relationshipName>Offres</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Offre__c/fields/Reference__c.field-meta.xml
<CustomField>
    <fullName>Reference__c</fullName>
    <externalId>true</externalId>
    <label>Reference</label>
    <length>15</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProcessLog__c/ProcessLog__c.object-meta.xml
<CustomObject>
    <label>ProcessLog</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ProcessLogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProcessLog__c/fields/Process__c.field-meta.xml
<CustomField>
    <fullName>Process__c</fullName>
    <label>Process</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Zuora__Subscription__c/Zuora__Subscription__c.object-meta.xml
<CustomObject>
    <description>A subscription is a product or service that has recurring charges, such as a monthly flat fee or charges based on usage. Subscriptions can also include one-time charges, such as activation fees.</description>
    <label>Subscription</label>
    <nameField>
        <label>Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Zuora__Subscription__c/fields/Lieu__c.field-meta.xml
<CustomField>
    <fullName>Lieu__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lieu</label>
    <referenceTo>Complexe__c</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Zuora__Subscription__c/fields/Offre__c.field-meta.xml
<CustomField>
    <fullName>Offre__c</fullName>
    <formula>IF(ISPICKVAL(CodeOffrePrincipale__c, &#39;UI1CDD&#39;),&#39;UI1&#39;, IF(ISPICKVAL(CodeOffrePrincipale__c, &#39;UI1CDI&#39;),&#39;UI1&#39;,IF(ISPICKVAL(CodeOffrePrincipale__c, &#39;UI2CDD&#39;),&#39;UI2&#39;,IF(ISPICKVAL(CodeOffrePrincipale__c, &#39;UI2CDI&#39;),&#39;UI2&#39;,IF(ISPICKVAL(CodeOffrePrincipale__c, &#39;UI3CDD&#39;), &#39;UI3&#39;,IF(ISPICKVAL(CodeOffrePrincipale__c, &#39;UI3CDI&#39;),&#39;UI3&#39;,IF(ISPICKVAL(CodeOffrePrincipale__c, &#39;UUCDI&#39;),&#39;UU&#39;,IF(ISPICKVAL(CodeOffrePrincipale__c, &#39;UUCDD&#39;), &#39;UU&#39;,&#39;null&#39;))))))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Offre</label>
    <type>Text</type>
</CustomField>

liv/apex/Evo_synchro.cls
String accessToken = WS001_CallZuora.access_token;
String zEntityId = WS001_CallZuora.getZuoraEntityId('033');
zc_GETSubscriptionTypeWithSuccess respObj = zc_Api.subscriptionGET(accessToken, zEntityId, '8adc9a416e16dc1c016e1c70821733ed', RTExceptionCode.ERREUR_IMPAYE_REGLER_UPDATE_ACCOUNT);
System.debug('MBEN: '+JSON.serialize(respObj,true));

// acquisition
WSZ.SubHermesIn hermesIn = new WSZ.SubHermesIn();
hermesIn.accountId = '0010E00000bzVUFQA2';
hermesIn.subscriptionZID = '8adcba9c6df77503016df824b81e5880';
hermesIn.subscriptionName = 'F-S00009596';
hermesIn.accountZID = '8adcfb506df787f2016df8249e560b97';
hermesIn.motif = '07- Création abonnement';
hermesIn.lieu = 'WEB';
hermesIn.origin='Selfcare';
hermesIn.numeroCarte = '17100188300';
WSZ.SubHermesOut acquOut = SM_Hermes.acquisition(hermesIn);

// migration
WSZ.SubHermesIn hermesIn = new WSZ.SubHermesIn();
hermesIn.accountId = '0010E00000bzVUFQA2';
hermesIn.subscriptionZID = '8adcba9c6df77503016df824b81e5880';
hermesIn.subscriptionName = 'F-S00009596';
hermesIn.accountZID = '8adcfb506df787f2016df8249e560b97';
hermesIn.motif = '06- Migration UI 1/2/3';
hermesIn.lieu = 'WEB';
hermesIn.origin='Selfcare';
hermesIn.numeroCarte = '17100188300';
hermesIn.typeDeMigration = 'UI 1 > UI 2';
//hermesIn.dateFinContrat = String.valueOf(Date.today());
WSZ.SubHermesOut acquOut = SM_Hermes.migration(hermesIn);



Account acc = SM_Account.getAccount('0010E00000bzVUFQA2');

// get Account
String accessToken = WS001_CallZuora.access_token;
String zEntityId = WS001_CallZuora.getZuoraEntityId('033');
 
//zc_ProxyGetAccount acc = zc_Api.objectAccountGET(accessToken, zEntityId, '8adcc59c6684e41e0166a648e4af6c6d', RTExceptionCode.ERREUR_IMPAYE_REGLER_UPDATE_ACCOUNT);
zc_ProxyGetPaymentMethod pm = zc_Api.objectPaymentMethodGET(accessToken, zEntityId, '8adce4216684e4260166a64ca12d3ae4', RTExceptionCode.ERREUR_IMPAYE_REGLER_UPDATE_ACCOUNT);
System.debug(JSON.serialize(pm,true));





SELECT Id, Name, MauvaisComportement__c, ProduitUGC__c, CodePays__c, PersonContactId 
                FROM Account
                WHERE Id = '0010E00000bzVUFQA2'


Date dateFinContrat = null;
// String subNumber = 'SUF00054036'; desabonnement impossible pour CDD (bilendi)
String subNumber = null;
Batch_SubscriptionCancel batch = new Batch_SubscriptionCancel(dateFinContrat,subNumber);
Database.executeBatch(batch,50);


select Id, EventType, LogDate, LogFileLength from EventLogFile where EventType not in ('Login','Logout') //= 'API' limit 10 //and LogDate = 2019-11-04T00:00:00.000Z

Select Lieu__c from Zuora__Subscription__c

Map<String,Zuora__Subscription__c> mp = new Map<String,Zuora__Subscription__c>();
mp.put('AAA',new Zuora__Subscription__c());
mp.put('BBB',new Zuora__Subscription__c());
System.debug(mp.size());
mp.put('AAA',new Zuora__Subscription__c());
System.debug(mp.size());

Set<String> st = new Set<String>();
st.add('AAA');
st.add('BBB');
System.debug(st.size());
st.add('AAAA');
System.debug(st.size());

List<Offre__c> offs = [Select Reference__c from Offre__c];
System.debug(offs.contains(new Offre__c(Reference__c='OFRHIVER2019')));
//System.assertEquals(true,offs.contains(new Offre__c(Reference__c='OFRHIVER2019')));

String str = 'ABO-ITA';
List<String> codeOffreCo = str.split('-');
System.debug(codeOffreCo);
System.debug(codeOffreCo[0]);
System.debug(codeOffreCo.size());
//System.debug(codeOffreCo.get(1));




String offreAboTier = Utils.getUgcGenericParam('Abo Tier Offre Name','032').ParamValue__c;
Integer validiteCoupon_AT = Integer.valueOf(Utils.getUgcGenericParam('Abo Tier Coupon Validite','032').ParamValue__c);
Id parentCouponID_AT = [Select Coupon__c from Offre__c where Name = :offreAboTier Limit 1].Coupon__c;
if (parentCouponID_AT == null) {throw new RTException(RTExceptionCode.ERREUR_DESABO_COUPON_ABOTIER,new ProcessLog__c());}
String coupon_AT = SM_Coupon.generateCouponItem(parentCouponID_AT,null,Date.today(),Date.today().addMonths(validiteCoupon_AT));

System.debug('MBEN:coupon_AT:'+coupon_AT);

Date dt = null;

//If(Date.today() < dt){
    System.debug('MBEN:'+ (Date.today() != dt));
//}


String accessToken = WS001_CallZuora.access_token;
String zEntityId = WS001_CallZuora.getZuoraEntityId('033');
zc_GETInvoiceItemsResponse resp = zc_Api.invoicesItemsGET(accessToken, zEntityId, '8adcfb506c7497ee016c76ac8d8e710b', RTExceptionCode.ERREUR_DESABO_COUPON_ABOTIER, new ProcessLog__c());
System.debug(JSON.serialize(resp));

Boolean hasDetteTech = SM_Impaye.hasDetteTechnique(new List<String>{'8adcfb506c7497ee016c76ac8d8e710b','8adcfb506c7497ee016c76ac8d8e710b'});
System.debug('MBEN:'+hasDetteTech);

Date dd = Date.newInstance(2016, 01, 03).adddays(1490);  // 01/02/2020 --> 
System.debug(dd);


Datetime d1 = System.now()
System.debug('MBEN:'+System.now().getTime());

Boolean enableResponseTime = Boolean.valueOf(Utils.getUgcGenericParam('Enable Response Time Log',null).ParamValue__c);
System.debug('MBEN:'+!enableResponseTime);


select StartTime__c, EndTime__c from ProcessLog__c where Process__c = 'ResponseTime_acquisition'