force-app/main/default/objects/Account/fields/NoCarteUI__c.field-meta.xml
<CustomField>
    <fullName>NoCarteUI__c</fullName>
    <label>N° Carte UI</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Courriel__c.field-meta.xml
<CustomField>
    <fullName>Courriel__c</fullName>
    <description>Champ pour la création d&#39;un ticket par la salle</description>
    <label>Courriel</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Case/fields/NoCarteUI__c.field-meta.xml
<CustomField>
    <fullName>NoCarteUI__c</fullName>
    <description>Champ qui copie le numéro de carte UI de la fiche client</description>
    <formula>Account.NoCarteUI__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>N° Carte UI</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Nom__c.field-meta.xml
<CustomField>
    <fullName>Nom__c</fullName>
    <description>Champ pour la création d&#39;un ticket par la salle</description>
    <label>Nom</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Prenom__c.field-meta.xml
<CustomField>
    <fullName>Prenom__c</fullName>
    <description>Champ pour la création d&#39;un ticket par la salle</description>
    <label>Prénom</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/QuestionConcerne__c.field-meta.xml
<CustomField>
    <fullName>QuestionConcerne__c</fullName>
    <description>Champ alimenté par le formulaire de contact depuis le site internet avec la valeur renseignée dans &quot;et qui concerne&quot;</description>
    <label>Question concerne</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/TECH_CodePaysFormulaire__c.field-meta.xml
<CustomField>
    <fullName>TECH_CodePaysFormulaire__c</fullName>
    <description>Ce champ est alimenté lors de la création de tickets issus du formulaire de contact : 
BE si formulaire belge
FR si formulaire français</description>
    <label>TECH_CodePaysFormulaire</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/TECH_NoCarteFideliteFormulaire__c.field-meta.xml
<CustomField>
    <fullName>TECH_NoCarteFideliteFormulaire__c</fullName>
    <description>Ce champ sera alimenté par le numéro de carte Fidélité renseigné par le client dans le formulaire de contact 
(numéro de carte contient 16 chiffres et commence par 831-)</description>
    <label>N° Carte fidélité issu du formulaire</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/DemandesCliensencours.recordType-meta.xml
<RecordType>
    <fullName>DemandesCliensencours</fullName>
    <active>true</active>
    <businessProcess>Demandes clients</businessProcess>
    <description>Présentation de page des demandes clients en cours (statut nouveau, en attente)</description>
    <label>Demandes Clients en cours</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/Standard.recordType-meta.xml
<RecordType>
    <fullName>Standard</fullName>
    <active>true</active>
    <businessProcess>Demandes clients</businessProcess>
    <label>Standard</label>
</RecordType>

force-app/main/default/objects/Global_Parameters__mdt/Global_Parameters__mdt.object-meta.xml
<CustomObject>
    <description>Paramètres globaux de l&#39;application</description>
    <label>Global Parameters</label>
    <pluralLabel>Global Parameters</pluralLabel>
</CustomObject>

force-app/main/default/objects/Global_Parameters__mdt/fields/Deployment_Level__c.field-meta.xml
<CustomField>
    <fullName>Deployment_Level__c</fullName>
    <label>Deployment Level</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SATGE-PILOTE</fullName>
                <default>true</default>
                <label>SATGE-PILOTE</label>
            </value>
            <value>
                <fullName>SATGE-LOT1</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Suivi_Demandes_Fidelite__c/Suivi_Demandes_Fidelite__c.object-meta.xml
<CustomObject>
    <description>Cet Objet trace toutes les demandes de fidélité renvoyé à Bilendi ou en erreur</description>
    <label>Suivi Demandes Fidelite</label>
    <nameField>
        <label>Suivi Demandes Fidelite Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Suivi Demandes Fidelite</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Suivi_Demandes_Fidelite__c/fields/Carte_Number__c.field-meta.xml
<CustomField>
    <fullName>Carte_Number__c</fullName>
    <label>Carte Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Suivi_Demandes_Fidelite__c/fields/Message_Erreur__c.field-meta.xml
<CustomField>
    <fullName>Message_Erreur__c</fullName>
    <label>Message Erreur</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Suivi_Demandes_Fidelite__c/fields/Question_Concerne__c.field-meta.xml
<CustomField>
    <fullName>Question_Concerne__c</fullName>
    <label>Question Concerne</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/WS01_WebToCaseWithPJ.cls
@RestResource(urlMapping='/WebToCase')
global with sharing class WS01_WebToCaseWithPJ {
    
    @HttpPost
    global static ReturnClass HandleCases() {
        
        Case caseWebToCase = new Case();
        RestRequest req = RestContext.request;
        Blob jsonBlob = req.requestBody;
        
        String jsonString = jsonBlob.toString();
        System.debug('--#### jsonString brute = ' + jsonString);
        
        Global_Parameters__mdt gParam = Utils.getGlobalParameters('UGC_One_Parameters');
        System.debug('--#### Deployment Level = '+gParam.Deployment_Level__c); // Deployment_Level__c = SATGE-LOT1
        
        WrpWebToCase webToCaseIn = (WrpWebToCase)JSON.deserialize(jsonString, WrpWebToCase.class);
        System.debug('--#### Jason Data in = ' + webToCaseIn);
        
        String typeCarte = getTypeCarte(webToCaseIn.carteNumber, gParam.Deployment_Level__c); //typeCarte = 'N/A' ou 'CarteFID' ou ''
        System.debug('--#### Type carte formulaire = ' + typeCarte);
        
        Case caseToCreate = new Case();
        Suivi_Demandes_Fidelite__c suiviDemande = new Suivi_Demandes_Fidelite__c();
        suiviDemande.Carte_Number__c = webToCaseIn.carteNumber;
        suiviDemande.Description__c = webToCaseIn.description;
        suiviDemande.Email__c = webToCaseIn.email;
        suiviDemande.First_Name__c = webToCaseIn.firstName;
        suiviDemande.Last_Name__c = webToCaseIn.lastName;
        suiviDemande.Question_Concerne__c = webToCaseIn.questionConcerne;
        suiviDemande.Subject__c = webToCaseIn.subject;  
        
        //pas de case si num catre renseigner et pas de type FID ('831[0-9]{13}')   
        //if('CarteFID'.equalsIgnoreCase(typeCarte)  || (''.equalsIgnoreCase(typeCarte)) && (webToCaseIn.subject.startsWithIgnoreCase('Un autre produit'))){
            
            // Recherche du recorde type du case à créer
            //Id rtId = [SELECT Id FROM RecordType where DeveloperName = 'DemandesCliensencours'].get(0).Id;
            Id rtId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Standard').getRecordTypeId();
            
            Contact[] contacts = [SELECT Id, Account.Id, Account.NoCarteUI__c FROM Contact WHERE Account.PersonEmail = :webToCaseIn.email Limit 1] ;
            
            if (contacts.size() == 1) {
                caseToCreate.AccountId = contacts.get(0).Account.Id;
                caseToCreate.ContactId = contacts.get(0).Id;
            } 
            
            System.debug('--#### Client non UI ==> Création Case ...');
            caseToCreate.Subject = webToCaseIn.subject;
            caseToCreate.Description = webToCaseIn.description;
            caseToCreate.Origin = 'Formulairedecontact';
            String s1 = webToCaseIn.questionConcerne;
        	String s2  = s1.split('\\-').get(0);
            caseToCreate.QuestionConcerne__c = s2;
            System.debug( webToCaseIn.questionConcerne);
            caseToCreate.nom__c = webToCaseIn.lastName;
            caseToCreate.prenom__c = webToCaseIn.firstName;
            caseToCreate.Courriel__c = webToCaseIn.email;
            caseToCreate.TECH_NoCarteFideliteFormulaire__c = webToCaseIn.carteNumber;
            caseToCreate.RecordTypeId = rtId;
            caseToCreate.TECH_CodePaysFormulaire__c = ('FR'.equalsIgnoreCase(webToCaseIn.Pays)?'033':('BE'.equalsIgnoreCase(webToCaseIn.Pays)?'032':''));
            
            try {
                Insert caseToCreate;
                return new ReturnClass('success', 'Cases treatment worked as expected with email client', caseToCreate.Id);
                
            } catch (Exception e) {
                suiviDemande.Message_Erreur__c = 'Erreur Insertion Case : ' + e.getMessage();
                Insert suiviDemande;
                return new ReturnClass('failed', e.getMessage(), null);
            }

        /*}
        
        else{
            suiviDemande.Message_Erreur__c = 'Le numéro de carte n\'est pas reconnue comme carte de Fidélité';
            Insert suiviDemande;
            System.debug('--#### Client UI (Numéro de carte transmise) ==> Pas de création Case, demande de transmission à Bilendi.');
            return new ReturnClass('delayed', 'Ticket à transmettre à Bilendi car numéro de NON Fidélité.', null);
        }*/
        
    }
    
    public static String getTypeCarte(String carteNumber, String deploymentStage){
        String strRetour = 'NA';
        if(carteNumber != ''){
            Pattern patternCarteUI = Pattern.compile('000[0-9]{8}|01[0-9]{9}');
			Pattern patternCarteFID = Pattern.compile('831[0-9]{13}');
        
	        Matcher matchCarteUI = patternCarteUI.matcher(carteNumber);
	        Matcher matchcarteFID = patternCarteFID.matcher(carteNumber);
        
        	if(carteNumber!=null && matchcarteFID.matches()){
            	strRetour = 'CarteFID';
        	}
        	return strRetour;
        }
       return '';
    }
    
    
    global class ReturnClass {
        
        global String status;
        global String message;
        global Id caseId;
        
        global ReturnClass(String status, String message, Id caseId) {
            this.status = status;
            this.message = message;
            this.caseId = caseId;
        }
        
    }
    
}