force-app/main/default/objects/Account/fields/Tech_IdMonCompte__c.field-meta.xml
<CustomField>
    <fullName>Tech_IdMonCompte__c</fullName>
    <externalId>true</externalId>
    <label>Tech Id MonCompte</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Zuora__Subscription__c/Zuora__Subscription__c.object-meta.xml
<CustomObject>
    <description>A subscription is a product or service that has recurring charges, such as a monthly flat fee or charges based on usage. Subscriptions can also include one-time charges, such as activation fees.</description>
    <label>Subscription</label>
    <nameField>
        <label>Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Zuora__Subscription__c/fields/Zuora__Account__c.field-meta.xml
<CustomField>
    <fullName>Zuora__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Zuora__Subscription__c/fields/Zuora__SubscriptionEndDate__c.field-meta.xml
<CustomField>
    <fullName>Zuora__SubscriptionEndDate__c</fullName>
    <description>This is when the subscription ends. This is always equal to term end date, unless the subscription has been cancelled. If the subscription has been cancelled, this is set to the cancellation date.</description>
    <label>Subscription End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/Batch002_AnonymisationAfterThreeYears.cls
global class Batch002_AnonymisationAfterThreeYears implements Database.Batchable<sObject>, Database.Stateful, Database.AllowsCallouts{

    Double failedUpdates{get; set;}
    
    global Batch002_AnonymisationAfterThreeYears (){
        failedUpdates = 0;
    } 

    global Database.QueryLocator start(Database.BatchableContext BC){
        Date now = Date.today();
        Date trhee = now.addYears(-3);
        String trheeStr = String.valueOf(trhee);
        system.debug('##MNE trheeStr >> '+trheeStr);
        
        String query = ' SELECT Id, Tech_IdMonCompte__c FROM Account WHERE Id IN (SELECT Zuora__Account__c FROM Zuora__Subscription__c WHERE Zuora__SubscriptionEndDate__c <= '+trheeStr+') AND Id NOT IN (SELECT Zuora__Account__c FROM Zuora__Subscription__c WHERE Zuora__SubscriptionEndDate__c >= '+trheeStr+')';  
        system.debug('##MNE Batch002_AnonymisationAfterThreeYears start query >> '+query);
        return Database.getQueryLocator(query); 
    }

    global void execute(Database.BatchableContext BC, List<sObject> scope){  
        system.debug('##MNE Batch002_AnonymisationAfterThreeYears execute scope >> '+scope);   
        List<Account> accounts = (List<Account>)scope;
        system.debug('##MNE Batch002_AnonymisationAfterThreeYears execute scope size >> '+accounts.size()); 
        
        SM002_Anonymisation.accountAnonymisation(accounts, SM002_Anonymisation.AnonymisationType.ONLY_ZUORA);
        
        
    }

    global void finish(Database.BatchableContext BC){
        system.debug('##MNE Batch002_AnonymisationAfterThreeYears finish NumberOfFails [deprecated] >> '+failedUpdates);
    }


}