force-app/main/default/objects/BillingOperation__c/BillingOperation__c.object-meta.xml
<CustomObject>
    <label>Billing Operation</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Operation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billing Operations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BillingOperation__c/fields/Action__c.field-meta.xml
<CustomField>
    <fullName>Action__c</fullName>
    <label>Action</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AJOUT</fullName>
            </value>
            <value>
                <fullName>SUPPRESSION</fullName>
            </value>
            <value>
                <fullName>MODIFICATION</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BillingOperation__c/fields/AmendZID__c.field-meta.xml
<CustomField>
    <fullName>AmendZID__c</fullName>
    <label>AmendZID</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BillingOperation__c/fields/DateOperation__c.field-meta.xml
<CustomField>
    <fullName>DateOperation__c</fullName>
    <label>Date Operation</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/BillingOperation__c/fields/Operation__c.field-meta.xml
<CustomField>
    <fullName>Operation__c</fullName>
    <label>Operation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Souscription</fullName>
            </value>
            <value>
                <fullName>Migration</fullName>
            </value>
            <value>
                <fullName>Renouvellement</fullName>
            </value>
            <value>
                <fullName>Desabonnement</fullName>
            </value>
            <value>
                <fullName>Resiliation</fullName>
            </value>
            <value>
                <fullName>Retractation</fullName>
            </value>
            <value>
                <fullName>FinContrat</fullName>
            </value>
            <value>
                <fullName>PassageU26</fullName>
            </value>
            <value>
                <fullName>Reactivation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BillingOperation__c/fields/Pays__c.field-meta.xml
<CustomField>
    <fullName>Pays__c</fullName>
    <label>Pays</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>France</fullName>
            </value>
            <value>
                <fullName>Belgique</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BillingOperation__c/fields/SubscriptionName__c.field-meta.xml
<CustomField>
    <fullName>SubscriptionName__c</fullName>
    <label>SubscriptionName</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BillingOperation__c/fields/Zoperation__c.field-meta.xml
<CustomField>
    <fullName>Zoperation__c</fullName>
    <description>zuora operation</description>
    <label>Zoperation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Subscribe</fullName>
            </value>
            <value>
                <fullName>Cancel</fullName>
            </value>
            <value>
                <fullName>Amend</fullName>
            </value>
            <value>
                <fullName>DeleteCancel</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SMQ_TrackOperation.cls
public without sharing class SMQ_TrackOperation implements Queueable {
    
    private BillingOperation__c ope;

    public SMQ_TrackOperation(String action, Datetime dateOperation, String operation, String zOperation, String amendId, String subId, String subName, String codePays) {
        
        String pays;

        if (Util.BELGIQUE.contains(codePays)) {
            pays = 'Belgique';
        } else if (Util.FRANCE.contains(codePays)){
            pays = 'France';
        } else {
            //TODO : throw new MyException('Attribut Code Pays obligatoire sur le Compte');
        }

        this.ope = new BillingOperation__c(Action__c = action, DateOperation__c = dateOperation, Operation__c=operation, Zoperation__c = zOperation, 
        AmendZID__c= amendId, SubscriptionZID__c = subId, SubscriptionName__c = subName, Pays__c=pays);
    }

    public void execute(QueueableContext ctx){
        
        insert ope;

    }
}