force-app/main/default/objects/Carte__c/Carte__c.object-meta.xml
<CustomObject>
    <description>Carte abonné, UI/UU</description>
    <label>Carte</label>
    <nameField>
        <label>Numéro de carte</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cartes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Carte__c/fields/Contrat__c.field-meta.xml
<CustomField>
    <fullName>Contrat__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Voir si on maintient ce champs, ca va demander un trigger pour maj l&#39;id suite aux synchro z360.</description>
    <label>Contrat</label>
    <referenceTo>Zuora__Subscription__c</referenceTo>
    <relationshipLabel>Cartes</relationshipLabel>
    <relationshipName>Cartes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Carte__c/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/File_Impression__c/File_Impression__c.object-meta.xml
<CustomObject>
    <label>File d&#39;impression</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Files d&#39;impression</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/File_Impression__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Files d&#39;impression</relationshipLabel>
    <relationshipName>Files_d_impression</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/File_Impression__c/fields/Carte__c.field-meta.xml
<CustomField>
    <fullName>Carte__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Carte</label>
    <referenceTo>Carte__c</referenceTo>
    <relationshipLabel>Files d&#39;impression</relationshipLabel>
    <relationshipName>Files_d_impression</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/File_Impression__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Demande</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Files d&#39;impression</relationshipLabel>
    <relationshipName>Files_d_impression</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/File_Impression__c/fields/CodeOffrePrincipale__c.field-meta.xml
<CustomField>
    <fullName>CodeOffrePrincipale__c</fullName>
    <label>Code Offre Principale</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/File_Impression__c/fields/IsCarte__c.field-meta.xml
<CustomField>
    <fullName>IsCarte__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Carte</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/File_Impression__c/fields/PayeurFirstName__c.field-meta.xml
<CustomField>
    <fullName>PayeurFirstName__c</fullName>
    <label>PayeurFirstName</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/File_Impression__c/fields/PayeurLastName__c.field-meta.xml
<CustomField>
    <fullName>PayeurLastName__c</fullName>
    <label>PayeurLastName</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/File_Impression__c/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Imprime</fullName>
                <label>Imprimé</label>
            </value>
            <value>
                <fullName>En cours d_impression</fullName>
                <label>En cours d&#39;impression</label>
            </value>
            <value>
                <fullName>A Imprimer</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/File_Impression__c/fields/Subscription__c.field-meta.xml
<CustomField>
    <fullName>Subscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Abonnement</label>
    <referenceTo>Zuora__Subscription__c</referenceTo>
    <relationshipLabel>Files d&#39;impression</relationshipLabel>
    <relationshipName>Files_d_impression</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/File_Impression__c/fields/SubscriptionZName__c.field-meta.xml
<CustomField>
    <fullName>SubscriptionZName__c</fullName>
    <externalId>true</externalId>
    <label>Zuora Subscription Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SM_FileImpression.cls
public with sharing class SM_FileImpression {
    public SM_FileImpression() {

    }

    public static String createFileImpressionCarte 
    (String numeroCarte, Id accountId, Id carteId, Id caseId, String subscriptionName, String codeOffrePrincipale, String payeurFirst, String payeurLast)  
    { 

        File_Impression__c fi   = new File_Impression__c();
        //fi.Subscription__c      = c.Contrat__c;
        if (numeroCarte != null) {fi.Name = numeroCarte;}
        fi.Account__c           = accountId;
        fi.IsCarte__c           = true;
        fi.Carte__c             = carteId;
        fi.Case__c              = caseId;
        fi.Statut__c            = 'A Imprimer';
        fi.SubscriptionZName__c    = subscriptionName;
        fi.CodeOffrePrincipale__c   = codeOffrePrincipale;
        fi.PayeurFirstName__c   =  payeurFirst; 
        fi.PayeurLastName__c    = payeurLast;

        insert fi;
        return fi.Id;

    }

}