force-app/main/default/objects/ProdRatePlanCharge__c/ProdRatePlanCharge__c.object-meta.xml
<CustomObject>
    <label>Prod Charges</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prod Charges</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Promo__c/Promo__c.object-meta.xml
<CustomObject>
    <label>Promo</label>
    <nameField>
        <label>Nom</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Promos</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/PromoRemise__c/PromoRemise__c.object-meta.xml
<CustomObject>
    <label>Remise de promo</label>
    <nameField>
        <displayFormat>rem-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Remises de promo</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PromoRemise__c/fields/Promo__c.field-meta.xml
<CustomField>
    <fullName>Promo__c</fullName>
    <label>Promo</label>
    <referenceTo>Promo__c</referenceTo>
    <relationshipLabel>Remises de promo</relationshipLabel>
    <relationshipName>PromoRemises</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/LCC023_PromoRemise_NewEditForm.cls
/**
 * Created by mouad on 12/01/2019.
 */

public with sharing class LCC023_PromoRemise_NewEditForm {

    @AuraEnabled
    public static ProdRatePlanCharge__c getCharge (String chargeId){
        // no return
        return [SELECT Id,Name,Reference__c FROM ProdRatePlanCharge__c WHERE Id=:chargeId LIMIT 1];
    }


    @AuraEnabled
    public static String getPromoRemiseRTid(Id promoId){
        // no return
        String promoRT = [SELECT RecordType.Name FROM Promo__c WHERE Id = :promoId LIMIT 1].RecordType.Name;
        return [SELECT Id FROM RecordType WHERE SobjectType='PromoRemise__c'
        AND Name = :promoRT LIMIT 1].Id;
    }

}