force-app/main/default/objects/ProdRatePlanCharge__c/ProdRatePlanCharge__c.object-meta.xml
<CustomObject>
    <label>Prod Charges</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prod Charges</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ProdRatePlanCharge__c/fields/EligibleOffre__c.field-meta.xml
<CustomField>
    <fullName>EligibleOffre__c</fullName>
    <defaultValue>false</defaultValue>
    <label>EligibleOffre</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ProdRatePlanCharge__c/fields/FamilleRPC__c.field-meta.xml
<CustomField>
    <fullName>FamilleRPC__c</fullName>
    <label>FamilleRPC</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PromoRemise__c/PromoRemise__c.object-meta.xml
<CustomObject>
    <label>Remise de promo</label>
    <nameField>
        <displayFormat>rem-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Remises de promo</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/LCC020_PromoRemise_NewForm.cls
public with sharing class LCC020_PromoRemise_NewForm {

    @AuraEnabled
    public static String initApexMethod(String promoRT){
        // no return
        return [SELECT Id FROM RecordType WHERE SobjectType='PromoRemise__c' AND Name = :promoRT LIMIT 1].Id;
    }

    @AuraEnabled
    public static ProdRatePlanCharge__c getCharge(String chargeId){

        // return [SELECT Id, Name, Reference__c, FamilleRPC__c FROM ProdRatePlanCharge__c where Id = :chargeId LIMIT 1];


        Return [SELECT Id, Name, Reference__c, FamilleRPC__c, EligibleOffre__c FROM ProdRatePlanCharge__c where Id = :chargeId LIMIT 1];
        // myId = [SELECT Id FROM ProdRatePlanCharge__c where Id = :chargeId LIMIT 1].Id;


    }

}