force-app/main/default/objects/MC_Campaign__c/MC_Campaign__c.object-meta.xml
<CustomObject>
    <label>Campagne</label>
    <nameField>
        <label>Message Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campagnes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/MC_Campaign__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Campagnes</relationshipLabel>
    <relationshipName>MC_Campagnes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MC_Campaign__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>MC_Campagnes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/DataExtension_Account.cls
Public class DataExtension_Account implements Database.Batchable<sObject>,Database.AllowsCallouts,Database.Stateful
{

    
    public DataExtension_Account()
    {
    }
    
    public Iterable<SObject> start(Database.BatchableContext BC)
    {
        return [SELECT Contact__r.AccountId, Id FROM MC_Campaign__c WHERE Account__c = null];
    }
    
    public void execute(Database.BatchableContext BC, List<SObject> scope)
    {
        List<MC_Campaign__c> mcCampaignList = new list<MC_Campaign__c>();
        for(Integer i=0;i < scope.size(); i++)
        {
            MC_Campaign__c scopeCampaign = (MC_Campaign__c)scope.get(i);
            MC_Campaign__c campaign = new MC_Campaign__c();
            campaign.Id = scopeCampaign.Id;
            campaign.Account__c = scopeCampaign.Contact__r.AccountId;
            mcCampaignList.add(campaign);
        }
        update mcCampaignList;
    } 
    
    public void finish(Database.BatchableContext BC)
    {
    }
}