force-app/main/default/objects/Agent__c/Agent__c.object-meta.xml
<CustomObject>
    <label>Agent</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Coupon__c/Coupon__c.object-meta.xml
<CustomObject>
    <label>Coupon</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Coupons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Coupon__c/fields/DateFin__c.field-meta.xml
<CustomField>
    <fullName>DateFin__c</fullName>
    <label>Date Fin</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Coupon__c/fields/InclureChiffres__c.field-meta.xml
<CustomField>
    <fullName>InclureChiffres__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Inclure des chiffres</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Coupon__c/fields/NombreCaracteres__c.field-meta.xml
<CustomField>
    <fullName>NombreCaracteres__c</fullName>
    <label>Nombre de caracteres</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Coupon__c/fields/Prefixe__c.field-meta.xml
<CustomField>
    <fullName>Prefixe__c</fullName>
    <label>Prefixe</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Coupon__c/fields/PrixVente__c.field-meta.xml
<CustomField>
    <fullName>PrixVente__c</fullName>
    <label>Prix de vente</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Coupon__c/fields/Quantite__c.field-meta.xml
<CustomField>
    <fullName>Quantite__c</fullName>
    <label>Quantite</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Coupon__c/fields/QuantiteDisponible__c.field-meta.xml
<CustomField>
    <fullName>QuantiteDisponible__c</fullName>
    <formula>Quantite__c -  QuantiteUtilise__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Quantite Disponible</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Coupon__c/fields/QuantiteUtilise__c.field-meta.xml
<CustomField>
    <fullName>QuantiteUtilise__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Quantite Utilisée</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Coupon__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Usage unique
Usage multiple
Plusieurs usages uniques</description>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Usage unique</fullName>
            </value>
            <value>
                <fullName>Generique</fullName>
            </value>
            <value>
                <fullName>Multiples</fullName>
            </value>
            <value>
                <fullName>BtoB</fullName>
            </value>
            <value>
                <fullName>NominatifClient</fullName>
                <label>Nominatif Client</label>
            </value>
            <value>
                <fullName>Nominatif Agent</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Coupon__c/recordTypes/BtoB.recordType-meta.xml
<RecordType>
    <fullName>BtoB</fullName>
    <active>true</active>
    <label>BtoB</label>
</RecordType>

force-app/main/default/objects/CouponItem__c/CouponItem__c.object-meta.xml
<CustomObject>
    <label>Coupon Item</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Coupon Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CouponItem__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Coupon Items</relationshipLabel>
    <relationshipName>CouponItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CouponItem__c/fields/Agent__c.field-meta.xml
<CustomField>
    <fullName>Agent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Agent</label>
    <referenceTo>Agent__c</referenceTo>
    <relationshipLabel>Coupon Items</relationshipLabel>
    <relationshipName>CouponItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CouponItem__c/fields/Coupon__c.field-meta.xml
<CustomField>
    <fullName>Coupon__c</fullName>
    <label>Coupon</label>
    <referenceTo>Coupon__c</referenceTo>
    <relationshipLabel>Coupon Items</relationshipLabel>
    <relationshipName>CouponItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CouponItem__c/fields/Utilise__c.field-meta.xml
<CustomField>
    <fullName>Utilise__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Utilise</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CouponItem__c/recordTypes/BtoB.recordType-meta.xml
<RecordType>
    <fullName>BtoB</fullName>
    <active>true</active>
    <label>BtoB</label>
</RecordType>

force-app/main/default/classes/SM_Coupon.cls
/**
 * Created by mouad on 02/11/2018.
 */

public with sharing class SM_Coupon {

    public static void generateCouponItems(Id coupId){
        List<CouponItem__c> couponItems = new List<CouponItem__c>();
        Coupon__c coupon = [SELECT Id, NombreCaracteres__c, Prefixe__c, Quantite__c, InclureChiffres__c, RecordType.Name
                FROM Coupon__c WHERE Id = :coupId LIMIT 1];
        String mCode = '';
        String recTypeId = '';
        Integer qte = coupon.Quantite__c.intValue();
        for (Integer i = 0; i < qte; i++){
            mCode = Util.generateRandomString(coupon.NombreCaracteres__c.intValue(), coupon.InclureChiffres__c);
            mCode = coupon.Prefixe__c + mCode;
            System.debug('MBEN: Code: ' + mCode);
            recTypeId = [SELECT Id FROM RecordType WHERE SobjectType='CouponItem__c' AND Name = :coupon.RecordType.Name LIMIT 1].Id;
            System.debug('MBEN+ recTypeId: ' + recTypeId);
            if (recTypeId != null) {couponItems.add(new CouponItem__c(Name=mCode, Coupon__c=coupId, RecordTypeId=recTypeId));}
        }
        if (!couponItems.isEmpty()) {insert couponItems;}
    }

    public static void consommer(String coup, Date dateSub) {

        WSZ.CouponGeneric couponG = new WSZ.CouponGeneric();
        getCouponGbyRef(coup, couponG);

        switch on couponG.RecordType {
            when 'BtoB' {
                if (!couponG.isAvailable) {
                    throw new RTException(RTExceptionCode.ERREUR_COUPON_DEJA_UTILISE);
                } else if (!(couponG.DateDebut <= dateSub && couponG.DateFin >= dateSub)) {
                    throw new RTException(RTExceptionCode.ERREUR_COUPON_EXPIRE);
                } else {
                    CouponItem__c couponItem = [SELECT Id FROM CouponItem__c WHERE Name = :coup LIMIT 1];
                    couponItem.Utilise__c = true;
                    update couponItem;
                }
            }
            when 'BtoC generique' {
                if (!couponG.isAvailable) {
                    throw new RTException(RTExceptionCode.ERREUR_COUPON_DEJA_UTILISE);
                } else {
                    Coupon__c coupon = [SELECT Id,QuantiteUtilise__c FROM Coupon__c WHERE Name = :coup LIMIT 1];
                    coupon.QuantiteUtilise__c = coupon.QuantiteUtilise__c + 1;
                    update coupon;
                }
            }
            when 'BtoC multiples' {
                if (!couponG.isAvailable) {
                    throw new RTException(RTExceptionCode.ERREUR_COUPON_DEJA_UTILISE);
                } else {
                    CouponItem__c couponItem = [SELECT Id FROM CouponItem__c WHERE Name = :coup LIMIT 1];
                    couponItem.Utilise__c = true;
                    update couponItem;
                }
            }
            when else {
                throw new RTException(RTExceptionCode.ERREUR_COUPON);
            }
        }
    }

    public static WSZ.CouponGeneric getCouponGbyRef(String coup, WSZ.CouponGeneric couponG) {
        //couponG = getCouponG(coup);
        //WSZ.CouponGeneric couponG = new WSZ.CouponGeneric();

        // A-Verifier Coupon present dans : Dans BtoC generique / BTOC usage unique
        List<Coupon__c> coupons1 = [
                SELECT Id, Name, RecordTypeId, DateDebut__c, DateFin__c, QuantiteDisponible__c, PrixVente__c, QuantiteUtilise__c,Type__c,
                        RecordType.Name
                FROM Coupon__c
                WHERE Name = :coup AND Type__c IN ('Generique')
                LIMIT 1
        ];

        // B-Verifier Coupon present : Dans BtoC plusieurs Usage unique + validite
        List<CouponItem__c> coupons2 = [
                SELECT Id, Name, Coupon__r.Id, Coupon__r.RecordTypeId, Coupon__r.DateDebut__c, Coupon__r.DateFin__c, Utilise__c, Coupon__r.Type__c,
                        Coupon__r.RecordType.Name, PrixVente__c, Agent__r.Code__c, Account__c, DateDebut__c, DateFin__c
                FROM CouponItem__c
                WHERE Name = :coup AND Coupon__r.Type__c IN ('Multiples')
        ];


        if (coupons1.isEmpty() && coupons2.isEmpty()) {
            //throw new RTException('erreur coupon non trouve','ERREUR_COUPON_NON_TROUVE');
            throw new RTException(RTExceptionCode.ERREUR_COUPON_NON_TROUVE);
            //return null;
        } else {
            if (!coupons1.isEmpty()) {
                if (coupons1.get(0).RecordType.Name == 'BtoC generique') {
                    couponG.Id = coupons1.get(0).Id;
                    couponG.Name = coupons1.get(0).Name;
                    //couponG.RecordType = [SELECT Name FROM RecordType WHERE Id = :coupons1.get(0).RecordTypeId LIMIT 1].Name;
                    couponG.RecordType = coupons1.get(0).RecordType.Name;
                    couponG.DateDebut = coupons1.get(0).DateDebut__c;
                    couponG.DateFin = coupons1.get(0).DateFin__c;
                    couponG.QuantiteDisponible = coupons1.get(0).QuantiteDisponible__c;
                    couponG.QuantiteUtilise = coupons1.get(0).QuantiteUtilise__c;
                    //couponG.PrixVente = coupons1.get(0).PrixVente__c;
                    couponG.isAvailable = (couponG.QuantiteDisponible > 0);
                    System.debug('MBEN: couponG1: ' + couponG);
                    return couponG;
                }
            }
            if (!coupons2.isEmpty()) {
                couponG.Id = coupons2.get(0).Coupon__c;
                couponG.ItemId = coupons2.get(0).Id;
                couponG.Name = coupons2.get(0).Name;
                couponG.RecordType = coupons2.get(0).Coupon__r.RecordType.Name;
                //[SELECT Name FROM RecordType WHERE Id = :coupons2.get(0).Coupon__r.RecordTypeId LIMIT 1].Name;
                couponG.Utilise = coupons2.get(0).Utilise__c;
                couponG.isAvailable = (couponG.Utilise == false);

                if (couponG.RecordType == 'BtoC multiples') {
                    couponG.DateDebut = coupons2.get(0).Coupon__r.DateDebut__c; // date du parent
                    couponG.DateFin = coupons2.get(0).Coupon__r.DateFin__c;  // date du parent
                }
                if (couponG.RecordType == 'BtoC Nominatif Agent') {
                    couponG.DateDebut = coupons2.get(0).DateDebut__c;
                    couponG.DateFin = coupons2.get(0).DateFin__c;
                    couponG.Agent = coupons2.get(0).Agent__r.Code__c;
                }
                if (couponG.RecordType == 'BtoC Nominatif Client') {
                    couponG.DateDebut = coupons2.get(0).DateDebut__c;
                    couponG.DateFin = coupons2.get(0).DateFin__c;
                    couponG.Account = coupons2.get(0).Account__c;
                }
                if (couponG.RecordType == 'BtoB') {
                    couponG.DateDebut = coupons2.get(0).DateDebut__c;
                    couponG.DateFin = coupons2.get(0).DateFin__c;
                    couponG.PrixVente = coupons2.get(0).PrixVente__c; // prix vente
                }
                return couponG;
            }
        }
        return couponG;
    }



/*    public static WSZ.CouponGeneric getCouponG(String coup){

            WSZ.CouponGeneric couponG = new WSZ.CouponGeneric();

            // A-Verifier Coupon present dans : Dans BtoC generique / BTOC usage unique
            List<Coupon__c> coupons1 = [
                    SELECT Id, Name, RecordTypeId, DateDebut__c, DateFin__c, QuantiteDisponible__c, PrixVente__c, QuantiteUtilise__c,Type__c
                    FROM Coupon__c
                    WHERE Name = :coup AND Type__c IN ('Usage unique', 'Usage multiple')
                    LIMIT 1
            ];

            // B-Verifier Coupon present : Dans BtoC plusieurs Usage unique + validite
            List<CouponItem__c> coupons2 = [
                    SELECT Id, Name, Coupon__r.Id, Coupon__r.RecordTypeId, Coupon__r.DateDebut__c, Coupon__r.DateFin__c, Utilise__c, Coupon__r.Type__c
                    FROM CouponItem__c
                    WHERE Name = :coup AND Coupon__r.Type__c IN ('Plusieurs usages uniques')
            ];

            // B-bis-Verifier Coupon present : Dans BTBO plusieurs Usage unique + validite
            List<CouponItem__c> coupons3 = [
                    SELECT Id, Name, Coupon__r.Id, Coupon__r.RecordTypeId, DateDebut__c, DateFin__c, Utilise__c, Coupon__r.Type__c, PrixVente__c
                    FROM CouponItem__c
                    WHERE Name = :coup AND Coupon__r.Type__c IN ('Plusieurs usages uniques - BtoB')
            ];


            if (coupons1.isEmpty() && coupons2.isEmpty() && coupons3.isEmpty()) {
                //throw new RTException('erreur coupon non trouve','ERREUR_COUPON_NON_TROUVE');
                throw new RTException(RTExceptionCode.ERREUR_COUPON_NON_TROUVE);
                //return null;
            } else {
                if (!coupons1.isEmpty()) {
                    couponG.Id = coupons1.get(0).Id;
                    couponG.Name = coupons1.get(0).Name;
                    couponG.RecordType = [SELECT Name FROM RecordType WHERE Id = :coupons1.get(0).RecordTypeId LIMIT 1].Name;
                    couponG.DateDebut = coupons1.get(0).DateDebut__c;
                    couponG.DateFin = coupons1.get(0).DateFin__c;
                    couponG.QuantiteDisponible = coupons1.get(0).QuantiteDisponible__c;
                    couponG.QuantiteUtilise = coupons1.get(0).QuantiteUtilise__c;
                    //couponG.PrixVente = coupons1.get(0).PrixVente__c;
                    couponG.isAvailable = (couponG.QuantiteDisponible > 0);
                    System.debug('MBEN: couponG1: ' + couponG);
                    return couponG;
                } else if (!coupons2.isEmpty()) {
                    couponG.Id = coupons2.get(0).Coupon__c;
                    couponG.ItemId = coupons2.get(0).Id;
                    couponG.Name = coupons2.get(0).Name;
                    couponG.RecordType = [SELECT Name FROM RecordType WHERE Id = :coupons2.get(0).Coupon__r.RecordTypeId LIMIT 1].Name;
                    couponG.DateDebut = coupons2.get(0).Coupon__r.DateDebut__c;
                    couponG.DateFin = coupons2.get(0).Coupon__r.DateFin__c;
                    couponG.Utilise = coupons2.get(0).Utilise__c;
                    couponG.PrixVente = coupons2.get(0).PrixVente__c;
                    //coupon.isAvailable = (coupon.Utilise == true) ? false : true;
                    couponG.isAvailable = (couponG.Utilise == false);
                    //coupon.isAvailable = (coupon.Utilise == false) ? true:false;
                    System.debug('MBEN: couponG2: ' + couponG);
                    return couponG;
                }else if (!coupons3.isEmpty()) {
                    couponG.Id = coupons3.get(0).Coupon__c;
                    couponG.ItemId = coupons3.get(0).Id;
                    couponG.Name = coupons3.get(0).Name;
                    couponG.RecordType = [SELECT Name FROM RecordType WHERE Id = :coupons3.get(0).Coupon__r.RecordTypeId LIMIT 1].Name;
                    couponG.DateDebut = coupons3.get(0).DateDebut__c;
                    couponG.DateFin = coupons3.get(0).DateFin__c;
                    couponG.Utilise = coupons3.get(0).Utilise__c;
                    couponG.PrixVente = coupons3.get(0).PrixVente__c;
                    //coupon.isAvailable = (coupon.Utilise == true) ? false : true;
                    couponG.isAvailable = (couponG.Utilise == false);
                    //coupon.isAvailable = (coupon.Utilise == false) ? true:false;
                    System.debug('MBEN: couponG3: ' + couponG);
                    return couponG;
                }else {
                    System.debug('MBEN: couponG: inconnu' + couponG);
                    return couponG;
                }
            }
    }*/

}