force-app/main/default/objects/Zuora__Subscription__c/Zuora__Subscription__c.object-meta.xml
<CustomObject>
    <description>A subscription is a product or service that has recurring charges, such as a monthly flat fee or charges based on usage. Subscriptions can also include one-time charges, such as activation fees.</description>
    <label>Subscription</label>
    <nameField>
        <label>Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Zuora__Subscription__c/fields/CodeOffrePrincipale__c.field-meta.xml
<CustomField>
    <fullName>CodeOffrePrincipale__c</fullName>
    <label>Code Offre Principale</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>UI1CDD</fullName>
            </value>
            <value>
                <fullName>UI2CDD</fullName>
            </value>
            <value>
                <fullName>UI3CDD</fullName>
            </value>
            <value>
                <fullName>UUCDD</fullName>
            </value>
            <value>
                <fullName>UI1CDI</fullName>
            </value>
            <value>
                <fullName>UI2CDI</fullName>
            </value>
            <value>
                <fullName>UI3CDI</fullName>
            </value>
            <value>
                <fullName>UUCDI</fullName>
            </value>
            <value>
                <fullName>UU</fullName>
            </value>
            <value>
                <fullName>UI1</fullName>
            </value>
            <value>
                <fullName>UI2</fullName>
            </value>
            <value>
                <fullName>UI3</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Zuora__Subscription__c/fields/PayeurCRMID__c.field-meta.xml
<CustomField>
    <fullName>PayeurCRMID__c</fullName>
    <label>PayeurCRMID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Zuora__Subscription__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <description>Bilendi</description>
    <label>Source</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Zuora__Subscription__c/fields/TypeContrat__c.field-meta.xml
<CustomField>
    <fullName>TypeContrat__c</fullName>
    <description>CDI ou CDD</description>
    <label>Type Contrat</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Zuora__Subscription__c/fields/Zuora__Account__c.field-meta.xml
<CustomField>
    <fullName>Zuora__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Zuora__Subscription__c/fields/Zuora__Status__c.field-meta.xml
<CustomField>
    <fullName>Zuora__Status__c</fullName>
    <label>Status</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Zuora__Subscription__c/fields/Zuora__SubscriptionEndDate__c.field-meta.xml
<CustomField>
    <fullName>Zuora__SubscriptionEndDate__c</fullName>
    <description>This is when the subscription ends. This is always equal to term end date, unless the subscription has been cancelled. If the subscription has been cancelled, this is set to the cancellation date.</description>
    <label>Subscription End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Zuora__Subscription__c/fields/Zuora__SubscriptionNumber__c.field-meta.xml
<CustomField>
    <fullName>Zuora__SubscriptionNumber__c</fullName>
    <externalId>true</externalId>
    <label>Subscription Number</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/SM_TestHelper.cls
public with sharing class SM_TestHelper {
    public SM_TestHelper() {

    }


    public static Blob genRenewDataSample(RenewSampleIn objIn){

        Integer nbr = objIn.nbr;

        List<Zuora__Subscription__c> subDatas = new List<Zuora__Subscription__c>();
        blob file;

        Date mTodayP40 = Date.today().addDays(40);
        Date mTodayP30 = Date.today().addDays(30);
        String ts = DateTime.now().format('MM_dd_HHmmss');

        // List<Zuora__Subscription__c> sub1 = [Select Id, Zuora__SubscriptionNumber__c, Zuora__SubscriptionEndDate__c, Zuora__Status__c, Zuora__Account__c, 
        // PayeurCRMID__c, CodeOffrePrincipale__c, Source__c, TypeContrat__c
        // from Zuora__Subscription__c where Zuora__Status__c =  'Active' AND Zuora__SubscriptionEndDate__c < :mTodayP40 AND Zuora__SubscriptionEndDate__c > TODAY AND TypeContrat__c = 'CDD' limit :nbr];

        // //latence
        // List<Zuora__Subscription__c> sub2 = [Select Id, Zuora__SubscriptionNumber__c, Zuora__SubscriptionEndDate__c, Zuora__Status__c, Zuora__Account__c, 
        // PayeurCRMID__c, CodeOffrePrincipale__c, Source__c, TypeContrat__c
        // from Zuora__Subscription__c where Zuora__Status__c =  'Cancelled' AND Zuora__SubscriptionEndDate__c > TODAY AND Zuora__SubscriptionEndDate__c < :mTodayP30 AND TypeContrat__c = 'CDD' limit :nbr];


        //exemple
        List<Zuora__Subscription__c> sub = [Select Id, Zuora__SubscriptionNumber__c, Zuora__SubscriptionEndDate__c, Zuora__Status__c, Zuora__Account__c, 
        PayeurCRMID__c, CodeOffrePrincipale__c, Source__c, TypeContrat__c
        from Zuora__Subscription__c where Zuora__Status__c =  'Active' AND TypeContrat__c = 'CDD' limit :nbr];


        //if (sub1.size() > 0) subDatas.addAll(sub1);
        //if (sub2.size() > 0)  subDatas.addAll(sub2);
        if (sub.size() > 0) subDatas.addAll(sub);      

        //Map<String,Object> mp = new Map<String,Object>();
        String jsonStr = JSON.serialize(subDatas);

        //mp = (Map<String,Object>)JSON.deserializeUntyped(jsonStr);

        //String toto = String.valueOf(mp);
        Integer i = 0;
        String sBody='',sHeader='',sText='';
        for (Object obj:subDatas){
            i++;

            Map<String,Object> mp = new Map<String,Object>();
            String sLine = '';
            mp = (Map<String,Object>)JSON.deserializeUntyped(JSON.serialize(obj));                
            //System.debug('MBEN: ' + JSON.serialize(mp));
            for (String key:mp.keySet()){
                if (i == 1 && key != 'attributes') sHeader += key + ',';
                if(key != 'attributes') sLine += mp.get(key) + ',';
            }
            
            sBody += '\n' + sLine;
        }
        // System.debug('MBEN: ' + sHeader);
        // System.debug('MBEN: ' + sBody);
        sText = sHeader + sBody;
        System.debug('MBEN: ' + sText);
        


        if (subDatas.size() > 0) {
            //String sBody = JSON.serialize(subDatas);
            
            file = Blob.valueOf(sText);
            ContentVersion cv = new ContentVersion();
            cv.ContentLocation = 'S';
            //cv.ContentDocumentId = contentDocumentId;
            // cv.VersionData = EncodingUtil.base64Decode('bW91YWQgYmVuYnJhaGlt');
            cv.VersionData = file;
            cv.Title = 'renewTestData_'+ts;
            cv.PathOnClient = 'renewTestData_' + ts +  '.csv';
            //cv.FileExtension = 'csv'; //Field is not writeable
            //cv.FileType = 'CSV'; //Field is not writeable

            insert cv;
            //System.debug('MBEN: ContentDocumentId: '+ JSON.serialize(cv));
            //System.debug('MBEN: ContentDocumentId: '+ cv.VersionData);
        }
        //System.debug('MBEN: ContentDocumentId: '+ cv.ContentDocumentId);

        return file;
        
    }

    public class RenewSampleIn{
        Integer nbr; // limit dans le SOQL sample data
    }
}