force-app/main/default/objects/Credentials__c/Credentials__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Credentials to log in to Viatelecom</description>
    <label>Credentials</label>
</CustomObject>

force-app/main/default/objects/Credentials__c/fields/banerUrl__c.field-meta.xml
<CustomField>
    <fullName>banerUrl__c</fullName>
    <label>banerUrl</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Credentials__c/fields/Viadialog_Url__c.field-meta.xml
<CustomField>
    <fullName>Viadialog_Url__c</fullName>
    <label>Viadialog Url</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PostInstallClass.cls
/**
 * Created by Alona Riabchenko on 20.10.2017.
 */

global class PostInstallClass implements InstallHandler{
	global void onInstall(InstallContext context) {
		if(context.previousVersion() == null) {
			initCredentialCustomSetting();
		}
		if(context.isUpgrade()) {
			initCredentialCustomSetting();
		}
	}

	global void initCredentialCustomSetting(){
		Credentials__c orgCredentials = Credentials__c.getOrgDefaults();
		orgCredentials.Access_Token__c = 'Basic N3lZNVJFS3M6RjY4QnJzNXdUTWFYQ1BTekdIN3lYVk5IQ2VZa3gyZng=N3lZNVJFS3M6RjY4QnJzNXdUTWFYQ1BTekdIN3lYVk5IQ2VZa3gyZng=';
		orgCredentials.Scope__c = 'salesforce-api';
		orgCredentials.Grant_Type__c = 'client_credentials';
		orgCredentials.Viadialog_Url__c = 'http://salesforce.viadialog.com/';
		orgCredentials.banerUrl__c = 'http://ccv.viatelecom.com/services/?';
		upsert orgCredentials;
	}

}