force-app/main/default/objects/Credentials__c/Credentials__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Credentials to log in to Viatelecom</description>
    <label>Credentials</label>
</CustomObject>

force-app/main/default/objects/Credentials__c/fields/banerUrl__c.field-meta.xml
<CustomField>
    <fullName>banerUrl__c</fullName>
    <label>banerUrl</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Credentials__c/fields/Viadialog_Url__c.field-meta.xml
<CustomField>
    <fullName>Viadialog_Url__c</fullName>
    <label>Viadialog Url</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PostInstallClassTest.cls
/**
 * Created by Alona Riabchenko on 20.10.2017.
 */
@isTest
private with sharing class PostInstallClassTest {
	@isTest
	static void testInstallScript() {
		PostInstallClass postinstall = new PostInstallClass();
		Test.testInstall(postinstall, null);
		Credentials__c orgCredentials = Credentials__c.getOrgDefaults();
		System.assertNotEquals(null,orgCredentials.Access_Token__c);
		System.assertNotEquals(null,orgCredentials.Scope__c);
		System.assertNotEquals(null,orgCredentials.Grant_Type__c);
		System.assertNotEquals(null,orgCredentials.Viadialog_Url__c);
		System.assertNotEquals(null,orgCredentials.banerUrl__c);
	}
}