force-app/main/default/objects/ProcessLog__c/ProcessLog__c.object-meta.xml
<CustomObject>
    <label>ProcessLog</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ProcessLogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProcessLog__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <label>Code</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ProcessLog__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <label>Message</label>
    <length>65536</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/RTException.cls
/**
 * Created by mouad on 11/11/2018.
 */

public without sharing class RTException extends Exception {

    public Integer Code;
    // public WSZ.ProcessLog pLog;

    public RTException(RTExceptionCode e){
        this.setMessage(e.libelle + ' - ErrorCode: ' + e.code) ;
        //this.setMessage(e.libelle);
        this.Code = e.code;
    }

    public RTException(RTExceptionCode e, ProcessLog__c pLog){
        String msg = e.libelle + ' - ErrorCode: ' + e.code;
        this.setMessage(msg) ;
        //this.setMessage(e.libelle);
        this.Code = e.code;
        
        // Insert processLog
        if(e.code<5000 && e.code>=6000)
        {
            pLog.Code__c = e.code;
            pLog.Message__c = msg + pLog.Message__c;
            insert pLog;
        }
    }


}